Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
Import-Module (Join-Path $PSScriptRoot 'MorphospaceProtocolCommon.psm1')
Import-Module (Join-Path $PSScriptRoot 'MorphospaceTransitionLedger.psm1')
Import-Module (Join-Path $PSScriptRoot 'MorphospaceDevelopmentEnvelopeSemantics.psm1')
Import-Module (Join-Path $PSScriptRoot 'MorphospaceRepreparationHistory.psm1')
Import-Module (Join-Path $PSScriptRoot '../AdmissionCompletionTimestampRecovery.psm1')

$script:LegacyProducerCommit = 'f45a7500d0a68b5cea0d910b26010c10ba42705c'
$script:LegacyStrengtheningCommit = '70a6129633d38913cfc8907c7937b3b18ad9df54'
$script:LegacyConsumerCommit = 'fb91fb4a574109912f44f4c1f371662e291e7528'
$script:LegacyConsumerBindingSha256 = '1effbae2e90fa45e5b4804b19305ffe5eeed633dcb885a38606ceddf8d117c80'
$script:LegacyProducerBlobs = [ordered]@{
    'scripts/lib/MorphospaceTransitionLedger.psm1' = '74c30a3c8638ac1725dc191b21d26cbe3f9258af'
    'scripts/lib/MorphospaceProtocolCommon.psm1' = '6bc370195aeb15851e78b2be102a10298164ea31'
    'schemas/workspace-state-v2.schema.json' = 'd89298ca5a9a3a1a2b983e572781f16610b4e394'
    'schemas/iteration-unit.schema.json' = '992aea13de894d7f25536933bf229155e5f06044'
    'schemas/iteration-event.schema.json' = 'cebda92ae9c503fa0cdff107ea392e5f2642e98d'
    'schemas/validation-receipt.schema.json' = '71f7fcf2ea0e9185d9f6a29ebdbf409fd33c8b5e'
}

function Get-CurrentWorkRepositoryRoot { Split-Path (Split-Path $PSScriptRoot -Parent) -Parent }
function Copy-CurrentWorkDocument { param([object]$Value) $Value | ConvertTo-Json -Depth 100 | ConvertFrom-Json -Depth 100 -DateKind String }
function Get-CurrentWorkEventLineBytes { param([object]$Event) [Text.UTF8Encoding]::new($false).GetBytes((ConvertTo-MorphospaceCanonicalJson $Event) + "`n") }
function Test-CurrentWorkByteRange { param([byte[]]$Value,[int64]$Offset,[byte[]]$Expected) if($Offset-lt0-or$Offset+$Expected.LongLength-gt$Value.LongLength){return $false};for($i=0;$i-lt$Expected.Length;$i++){if($Value[$Offset+$i]-ne$Expected[$i]){return $false}};$true }
function Assert-CurrentWorkSchemaFile { param([string]$Path,[string]$Schema,[string]$Message) if(-not(Test-Json -Json (Get-Content -LiteralPath $Path -Raw) -SchemaFile (Join-Path (Get-CurrentWorkRepositoryRoot) "schemas/$Schema"))){throw $Message} }
function Get-CurrentWorkSnapshot {
    param([string]$Workspace,[object]$Binding,[string]$ExpectedPath,[string]$Context)
    if([string]$Binding.path-cne$ExpectedPath){throw "$Context path differs from its canonical identity."}
    $path=Resolve-MorphospaceWorkspacePath $Workspace $ExpectedPath -RequireLeaf
    $bytes=[IO.File]::ReadAllBytes($path);$document=ConvertFrom-MorphospaceProtocolJsonBytes $bytes $Context
    if([string]$Binding.raw_sha256-cne(Get-MorphospaceSha256Bytes $bytes)-or[string]$Binding.canonical_sha256-cne(Get-MorphospaceCanonicalJsonSha256 $document)){throw "$Context bytes differ from their recovery binding."}
    [pscustomobject]@{path=$path;bytes=$bytes;raw_sha256=(Get-MorphospaceSha256Bytes $bytes);canonical_sha256=(Get-MorphospaceCanonicalJsonSha256 $document);document=$document}
}
function Assert-CurrentWorkExactProperties { param([object]$Value,[string[]]$Names,[string]$Context) Assert-MorphospaceExactPropertySet $Value $Names @() $Context }

function Assert-LegacyProducerProvenance {
    $root=Get-CurrentWorkRepositoryRoot
    foreach($pair in $script:LegacyProducerBlobs.GetEnumerator()){
        $actual=@(& git -C $root rev-parse "$($script:LegacyProducerCommit):$($pair.Key)" 2>$null)
        if($LASTEXITCODE-ne0-or$actual.Count-ne1-or[string]$actual[0]-cne[string]$pair.Value){throw 'Historical transition v1 producer provenance is unavailable or differs from the pinned source.'}
    }
    & git -C $root merge-base --is-ancestor $script:LegacyProducerCommit $script:LegacyStrengtheningCommit 2>$null
    if($LASTEXITCODE-ne0){throw 'Historical transition v1 producer lineage is detached from its pinned strengthening boundary.'}
}
function Get-LegacyProducerSchemaText {
    param([string]$Path)
    $root=Get-CurrentWorkRepositoryRoot
    $text=@(& git -C $root cat-file blob "$($script:LegacyProducerCommit):$Path" 2>$null) -join "`n"
    if($LASTEXITCODE-ne0-or-not$text){throw "Historical transition v1 producer schema '$Path' is unavailable."}
    $text
}
function Assert-GitHeadBytes {
    param([string]$Workspace,[string]$RelativePath,[byte[]]$Expected,[string]$Context)
    $repo=@(& git -C $Workspace rev-parse --show-toplevel 2>$null)
    if($LASTEXITCODE-ne0-or$repo.Count-ne1){throw "$Context is not contained in an owner Git repository."}
    $repoRoot=[IO.Path]::GetFullPath([string]$repo[0]);$full=Resolve-MorphospaceWorkspacePath $Workspace $RelativePath -RequireLeaf
    $gitPath=[IO.Path]::GetRelativePath($repoRoot,$full).Replace('\','/')
    if($gitPath.StartsWith('../',[StringComparison]::Ordinal)-or$gitPath-eq'..'){throw "$Context escapes its owner Git repository."}
    if((Get-MorphospaceFileSha256 $full)-cne(Get-MorphospaceSha256Bytes $Expected)){throw "$Context changed while its historical snapshot was being authenticated."}
    $headBlob=@(& git -C $repoRoot rev-parse "HEAD:$gitPath" 2>$null);$liveBlob=@(& git -C $repoRoot hash-object -- $full 2>$null)
    if($LASTEXITCODE-ne0-or$headBlob.Count-ne1-or$liveBlob.Count-ne1-or[string]$headBlob[0]-cne[string]$liveBlob[0]){throw "$Context differs from its Git-contained owner bytes."}
}

function Assert-LegacyConsumerBinding {
    param([string]$Workspace,[object]$Event,[string]$IntentRelative,[byte[]]$IntentBytes,[string]$CompletionRelative,[byte[]]$CompletionBytes,[string]$UnitRelative,[byte[]]$UnitBytes,[string]$ReceiptRelative,[byte[]]$ReceiptBytes)
    $repo=@(& git -C $Workspace rev-parse --show-toplevel 2>$null);if($LASTEXITCODE-ne0-or$repo.Count-ne1){throw 'Historical transition v1 lacks its owner Git repository.'};$repoRoot=[IO.Path]::GetFullPath([string]$repo[0])
    & git -C $repoRoot cat-file -e "$($script:LegacyConsumerCommit)^{commit}" 2>$null;if($LASTEXITCODE-ne0){throw 'Historical transition v1 pinned owner commit is unavailable.'}; & git -C $repoRoot merge-base --is-ancestor $script:LegacyConsumerCommit HEAD 2>$null;if($LASTEXITCODE-ne0){throw 'Historical transition v1 pinned owner commit is not retained by the current owner head.'}
    $workspacePrefix=[IO.Path]::GetRelativePath($repoRoot,$Workspace).Replace('\','/');if($workspacePrefix-eq'.'){$workspacePrefix=''}elseif($workspacePrefix.StartsWith('../',[StringComparison]::Ordinal)) { throw 'Historical transition v1 workspace escapes its owner repository.' } else {$workspacePrefix+='/' }
    $records=[ordered]@{}
    foreach($entry in @(@('intent',$IntentRelative,$IntentBytes),@('completion',$CompletionRelative,$CompletionBytes),@('unit',$UnitRelative,$UnitBytes),@('receipt',$ReceiptRelative,$ReceiptBytes))){
        $gitPath=$workspacePrefix+[string]$entry[1];$rawHash=Get-MorphospaceSha256Bytes ([byte[]]$entry[2]);$records[[string]$entry[0]]=[ordered]@{path=$gitPath;sha256=$rawHash}
        $pinnedBlob=@(& git -C $repoRoot rev-parse "$($script:LegacyConsumerCommit):$gitPath" 2>$null);$liveBlob=@(& git -C $repoRoot hash-object -- (Resolve-MorphospaceWorkspacePath $Workspace ([string]$entry[1]) -RequireLeaf) 2>$null)
        if($LASTEXITCODE-ne0-or$pinnedBlob.Count-ne1-or$liveBlob.Count-ne1-or[string]$pinnedBlob[0]-cne[string]$liveBlob[0]){throw 'Historical transition v1 retained record differs from its exact pinned owner commit.'}
    }
    $ledgerPath=Resolve-MorphospaceWorkspacePath $Workspace 'iteration-events.jsonl' -RequireLeaf;$ledger=[IO.File]::ReadAllBytes($ledgerPath);$lineCount=0;$offset=0;while($offset-lt$ledger.Length-and$lineCount-lt[int]$Event.sequence){if($ledger[$offset]-eq10){$lineCount++};$offset++};if($lineCount-ne[int]$Event.sequence){throw 'Historical transition v1 ledger prefix is incomplete.'};$prefix=[byte[]]::new($offset);[Array]::Copy($ledger,0,$prefix,0,$offset)
    $binding=[ordered]@{consumer_commit=$script:LegacyConsumerCommit;records=$records;event=[ordered]@{canonical_sha256=(Get-MorphospaceCanonicalJsonSha256 $Event);prefix_path=$workspacePrefix+'iteration-events.jsonl';prefix_length=$offset;prefix_sha256=(Get-MorphospaceSha256Bytes $prefix)}}
    if((Get-MorphospaceCanonicalJsonSha256 $binding)-cne$script:LegacyConsumerBindingSha256){throw 'Historical transition v1 does not match the one finite owner checkpoint binding.'}
}

function Test-MorphospaceHistoricalCommittedTransitionV1 {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][string]$TransactionId,[Parameter(Mandatory)][object]$ExpectedEvent)
    Assert-LegacyProducerProvenance
    $workspace=[IO.Path]::GetFullPath($WorkspaceRoot);$intentRelative="receipts/transactions/$TransactionId.intent.json";$completionRelative="receipts/transactions/$TransactionId.completion.json"
    $intentPath=Resolve-MorphospaceWorkspacePath $workspace $intentRelative -RequireLeaf;$completionPath=Resolve-MorphospaceWorkspacePath $workspace $completionRelative -RequireLeaf
    $intentBytes=[IO.File]::ReadAllBytes($intentPath);$completionBytes=[IO.File]::ReadAllBytes($completionPath);$intent=ConvertFrom-MorphospaceProtocolJsonBytes $intentBytes 'historical transition v1 intent';$completion=ConvertFrom-MorphospaceProtocolJsonBytes $completionBytes 'historical transition v1 completion'
    Assert-CurrentWorkExactProperties $intent @('schema','transaction_id','created_at','state','unit','events','pre','target','event','status') 'Historical transition v1 intent'
    Assert-CurrentWorkExactProperties $intent.pre @('state','unit') 'Historical transition v1 preimage'
    Assert-CurrentWorkExactProperties $intent.target @('state','unit') 'Historical transition v1 target'
    foreach($name in @('state','unit')){Assert-CurrentWorkExactProperties $intent.pre.$name @('sha256') "Historical transition v1 pre-$name";Assert-CurrentWorkExactProperties $intent.target.$name @('sha256','document') "Historical transition v1 target-$name"}
    if([string]$intent.schema-cne'rusty.morphospace.workflow.transition_ledger_intent.v1'-or[string]$intent.transaction_id-cne$TransactionId-or[string]$intent.status-cne'prepared'-or[string]$intent.state.path-cne'workspace.state.json'-or[string]$intent.events.path-cne'iteration-events.jsonl'-or[string]$intent.unit.path-cne"iteration-units/$([string]$ExpectedEvent.unit_id).json"-or[string]$TransactionId-cne"$([string]$ExpectedEvent.event_id)-transition"){throw 'Historical transition v1 identity or paths differ from the producer shape.'}
    [void](Test-MorphospaceStrictUtcTimestamp ([string]$intent.created_at));[void](Test-MorphospaceStrictUtcTimestamp ([string]$intent.event.timestamp))
    if((Get-MorphospaceCanonicalJsonSha256 $intent.event)-cne(Get-MorphospaceCanonicalJsonSha256 $ExpectedEvent)){throw 'Historical transition v1 event differs from the retained ledger event.'}
    foreach($name in @('state','unit')){if([string]$intent.pre.$name.sha256-cnotmatch'^[0-9a-f]{64}$'-or[string]$intent.target.$name.sha256-cnotmatch'^[0-9a-f]{64}$'-or[string]$intent.target.$name.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $intent.target.$name.document)){throw "Historical transition v1 $name hashes are invalid."}}
    $pin="https://raw.githubusercontent.com/MesmerPrism/rusty-morphospace-work-environment/$($script:LegacyProducerCommit)/schemas/"
    if([string]$intent.target.state.document.'$schema'-cne"${pin}workspace-state-v2.schema.json"-or[string]$intent.target.unit.document.'$schema'-cne"${pin}iteration-unit.schema.json"){throw 'Historical transition v1 target documents do not pin the producer schemas.'}
    foreach($check in @(@($intent.target.state.document,'schemas/workspace-state-v2.schema.json'),@($intent.target.unit.document,'schemas/iteration-unit.schema.json'),@($intent.event,'schemas/iteration-event.schema.json'))){if(-not(Test-Json -Json ($check[0]|ConvertTo-Json -Depth 100) -Schema (Get-LegacyProducerSchemaText $check[1]))){throw "Historical transition v1 document fails producer schema '$($check[1])'."}}
    Assert-CurrentWorkExactProperties $completion @('schema','transaction_id','completed_at','intent','state_sha256','unit_sha256','event_id','status') 'Historical transition v1 completion';Assert-CurrentWorkExactProperties $completion.intent @('role','path','schema','sha256') 'Historical transition v1 completion intent binding'
    if([string]$completion.schema-cne'rusty.morphospace.workflow.transition_ledger_completion.v1'-or[string]$completion.transaction_id-cne$TransactionId-or[string]$completion.status-cne'committed'-or[string]$completion.event_id-cne[string]$ExpectedEvent.event_id-or[string]$completion.intent.role-cne'transition-ledger-intent'-or[string]$completion.intent.path-cne$intentRelative-or[string]$completion.intent.schema-cne[string]$intent.schema-or[string]$completion.intent.sha256-cne(Get-MorphospaceSha256Bytes $intentBytes)-or[string]$completion.state_sha256-cne[string]$intent.target.state.sha256-or[string]$completion.unit_sha256-cne[string]$intent.target.unit.sha256-or(Test-MorphospaceStrictUtcTimestamp ([string]$completion.completed_at))-lt(Test-MorphospaceStrictUtcTimestamp ([string]$intent.created_at))){throw 'Historical transition v1 completion is detached or inconsistent.'}
    $unitPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$intent.unit.path) -RequireLeaf;$unitBytes=[IO.File]::ReadAllBytes($unitPath);$unit=ConvertFrom-MorphospaceProtocolJsonBytes $unitBytes 'historical accepted unit'
    if((Get-MorphospaceCanonicalJsonSha256 $unit)-cne[string]$intent.target.unit.sha256-or[string]$unit.status-cne'accepted'){throw 'Historical transition v1 retained unit differs from its accepted target.'}
    $receipts=@($ExpectedEvent.receipts);if($receipts.Count-ne1-or[string]$receipts[0]-cne[string]$intent.target.state.document.last_accepted_receipt){throw 'Historical transition v1 accepted event does not name its exact validation receipt.'}
    $receiptPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$receipts[0]) -RequireLeaf;$receiptBytes=[IO.File]::ReadAllBytes($receiptPath);$receipt=ConvertFrom-MorphospaceProtocolJsonBytes $receiptBytes 'historical validation receipt'
    if(-not(Test-Json -Json ([Text.UTF8Encoding]::new($false,$true).GetString($receiptBytes)) -Schema (Get-LegacyProducerSchemaText 'schemas/validation-receipt.schema.json'))-or[string]$receipt.schema-cne'rusty.morphospace.workflow.validation_receipt.v1'-or[string]$receipt.project_id-cne[string]$ExpectedEvent.project_id-or[string]$receipt.unit_id-cne[string]$ExpectedEvent.unit_id-or[string]$receipt.result-cne'pass'-or[string]$receipts[0]-cne"receipts/$([string]$receipt.receipt_id).json"){throw 'Historical transition v1 validation receipt is detached or invalid.'}
    Assert-LegacyConsumerBinding $workspace $ExpectedEvent $intentRelative $intentBytes $completionRelative $completionBytes ([string]$intent.unit.path) $unitBytes ([string]$receipts[0]) $receiptBytes
    foreach($owned in @(@($intentRelative,$intentBytes,'intent'),@($completionRelative,$completionBytes,'completion'),@([string]$intent.unit.path,$unitBytes,'unit'),@([string]$receipts[0],$receiptBytes,'validation receipt'))){Assert-GitHeadBytes $workspace $owned[0] $owned[1] "Historical transition v1 $($owned[2])"}
    [pscustomobject]@{intent=$intent;completion=$completion;historical_only=$true;producer_commit=$script:LegacyProducerCommit;grants_validation_credit=$false}
}

function Test-MorphospaceAcceptedCheckpointProof {
    [CmdletBinding()]param(
        [Parameter(Mandatory)][string]$WorkspaceRoot,
        [Parameter(Mandatory)][object]$ExpectedEvent,
        [switch]$AllowFiniteHistoricalV1
    )
    $workspace=[IO.Path]::GetFullPath($WorkspaceRoot);$unitId=[string]$ExpectedEvent.unit_id;$eventId=[string]$ExpectedEvent.event_id
    if([string]$ExpectedEvent.event_type-cne'state-transition'-or[string]::IsNullOrWhiteSpace($unitId)-or$eventId-cnotmatch('^'+[regex]::Escape($unitId)+'-accepted-[0-9]{4,}$')){
        throw 'Accepted-checkpoint proof requires an accepted state-transition event.'
    }
    $transactionId="$eventId-transition";$intentPath=Resolve-MorphospaceWorkspacePath $workspace "receipts/transactions/$transactionId.intent.json" -RequireLeaf
    $intent=Read-MorphospaceProtocolJson $intentPath
    $finiteHistoricalV1=[string]$intent.schema-ceq'rusty.morphospace.workflow.transition_ledger_intent.v1'-and
        $intent.PSObject.Properties.Name-notcontains'expected'-and$intent.PSObject.Properties.Name-notcontains'artifacts'
    $proof=if($finiteHistoricalV1-and$AllowFiniteHistoricalV1){
        Test-MorphospaceHistoricalCommittedTransitionV1 -WorkspaceRoot $workspace -TransactionId $transactionId -ExpectedEvent $ExpectedEvent
    }else{
        Test-MorphospaceCommittedTransitionLedger -WorkspaceRoot $workspace -TransactionId $transactionId -ExpectedStatePath 'workspace.state.json' -ExpectedUnitPath "iteration-units/$unitId.json" -ExpectedEventsPath 'iteration-events.jsonl'
    }
    if((Get-MorphospaceCanonicalJsonSha256 $proof.intent.event)-cne(Get-MorphospaceCanonicalJsonSha256 $ExpectedEvent)-or
        [string]$proof.intent.target.unit.document.unit_id-cne$unitId-or
        [string]$proof.intent.target.unit.document.status-cne'accepted'){
        throw 'Accepted-checkpoint proof does not authenticate the expected accepted event and target.'
    }
    $proof
}

function Test-MorphospaceCommittedDevelopmentEnvelopeRepreparation {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][object]$ExpectedEvent)
    $workspace=[IO.Path]::GetFullPath($WorkspaceRoot);$refs=@($ExpectedEvent.receipts)
    if($refs.Count-ne2){throw 'Current-work repreparation event must name exactly its recovery and preparation receipts.'}
    $repreparationPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$refs[0]) -RequireLeaf;$preparationPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$refs[1]) -RequireLeaf
    Assert-CurrentWorkSchemaFile $repreparationPath 'development-envelope-repreparation-receipt-v1.schema.json' 'Current-work repreparation receipt schema is invalid.';Assert-CurrentWorkSchemaFile $preparationPath 'development-envelope-preparation-receipt-v1.schema.json' 'Current-work repreparation preparation receipt schema is invalid.'
    $repreparation=Read-MorphospaceProtocolJson $repreparationPath;$preparation=Read-MorphospaceProtocolJson $preparationPath
    $transactionId="$([string]$repreparation.repreparation_id)-transition";$intentRelative="receipts/transactions/$transactionId.intent.json";$completionRelative="receipts/transactions/$transactionId.completion.json";$intentPath=Resolve-MorphospaceWorkspacePath $workspace $intentRelative -RequireLeaf;$completionPath=Resolve-MorphospaceWorkspacePath $workspace $completionRelative -RequireLeaf
    Assert-CurrentWorkSchemaFile $intentPath 'development-envelope-repreparation-intent-v1.schema.json' 'Current-work repreparation intent schema is invalid.';Assert-CurrentWorkSchemaFile $completionPath 'development-envelope-repreparation-completion-v1.schema.json' 'Current-work repreparation completion schema is invalid.'
    $intent=Read-MorphospaceProtocolJson $intentPath;$completion=Read-MorphospaceProtocolJson $completionPath
    if([string]$intent.created_at-cne[string]$ExpectedEvent.timestamp-or
        [string]$intent.pre.events.path-cne'iteration-events.jsonl'-or
        [string]$intent.pre.events.tail_id-cne[string]$repreparation.retirement.event_id){
        throw 'Current-work repreparation timestamp or predecessor identity is detached.'
    }
    $eventId="$([string]$repreparation.preparation_id)-prepared";$expectedSummary='Reprepared a corrected development envelope after exact proposed-unit retirement; separate ordinary admission remains required.'
    if([string]$refs[0]-cne"receipts/$([string]$repreparation.repreparation_id)-repreparation.json"-or[string]$refs[1]-cne"receipts/$([string]$repreparation.preparation_id).json"-or[string]$preparation.preparation_id-cne[string]$repreparation.preparation_id-or[string]$preparation.predecessor_unit_id-cne[string]$repreparation.retired_unit_id-or[string]$repreparation.project_id-cne[string]$ExpectedEvent.project_id-or[string]$ExpectedEvent.event_id-cne$eventId-or[string]$ExpectedEvent.unit_id-cne[string]$repreparation.retired_unit_id-or[string]$ExpectedEvent.event_type-cne'decision'-or[string]$ExpectedEvent.summary-cne$expectedSummary-or[string]$intent.transaction_id-cne$transactionId-or(Get-MorphospaceCanonicalJsonSha256 $intent.event)-cne(Get-MorphospaceCanonicalJsonSha256 $ExpectedEvent)){throw 'Current-work repreparation identities are detached.'}
    if([string]$completion.transaction_id-cne$transactionId-or[string]$completion.event_id-cne[string]$ExpectedEvent.event_id-or[string]$completion.intent_sha256-cne(Get-MorphospaceFileSha256 $intentPath)-or[string]$completion.target_project_sha256-cne[string]$intent.target.project.sha256-or[string]$completion.target_state_sha256-cne[string]$intent.target.state.sha256-or[string]$completion.target_feature_lock_sha256-cne[string]$intent.target.feature_lock.sha256-or(Test-MorphospaceStrictUtcTimestamp ([string]$completion.completed_at))-lt(Test-MorphospaceStrictUtcTimestamp ([string]$intent.created_at))){throw 'Current-work repreparation completion is detached.'}
    $projectionPaths=@{project='project.spec.json';state='workspace.state.json';feature_lock='feature.lock.json'}
    foreach($name in @('project','state','feature_lock')){
        if([string]$intent.pre.$name.path-cne$projectionPaths[$name]-or
            [string]$intent.target.$name.path-cne$projectionPaths[$name]-or
            [string]$intent.pre.$name.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $intent.pre.$name.document)-or
            [string]$intent.target.$name.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $intent.target.$name.document)){
            throw "Current-work repreparation $name projection is damaged."
        }
    }
    $artifacts=@($intent.artifacts);if($artifacts.Count-ne3){throw 'Current-work repreparation does not own its exact three producer artifacts.'}
    foreach($artifact in $artifacts){$path=Resolve-MorphospaceWorkspacePath $workspace ([string]$artifact.path) -RequireLeaf;$bytes=[IO.File]::ReadAllBytes($path);if([string]$artifact.sha256-cne(Get-MorphospaceSha256Bytes $bytes)-or[string]$artifact.bytes_base64-cne[Convert]::ToBase64String($bytes)){throw "Current-work repreparation artifact '$([string]$artifact.path)' is damaged."}}
    $receiptArtifact=@($artifacts|Where-Object{[string]$_.path-ceq[string]$refs[0]});if($receiptArtifact.Count-ne1-or[string]$completion.repreparation_receipt_sha256-cne[string]$receiptArtifact[0].sha256){throw 'Current-work repreparation receipt is not owned by its intent and completion.'}
    $sourcePath=[string]$repreparation.source_composition.path;$sourceArtifact=@($artifacts|Where-Object{[string]$_.path-ceq$sourcePath});$preparationArtifact=@($artifacts|Where-Object{[string]$_.path-ceq[string]$refs[1]});if($sourceArtifact.Count-ne1-or$preparationArtifact.Count-ne1){throw 'Current-work repreparation source or preparation artifact is absent.'};$sourceAbsolute=Resolve-MorphospaceWorkspacePath $workspace $sourcePath -RequireLeaf;Assert-CurrentWorkSchemaFile $sourceAbsolute 'development-envelope-source-composition-v2.schema.json' 'Current-work repreparation source composition schema is invalid.';$source=Read-MorphospaceProtocolJson $sourceAbsolute
    $mapRelative=[string]$intent.pre.repository_map.path;$mapPath=Resolve-MorphospaceWorkspacePath $workspace $mapRelative -RequireLeaf;if([string]$intent.pre.repository_map.sha256-cne(Get-MorphospaceFileSha256 $mapPath)){throw 'Current-work repreparation repository map binding is detached.'};Assert-CurrentWorkSchemaFile $mapPath 'repository-map.schema.json' 'Current-work repreparation repository map schema is invalid.';$mapDocument=Read-MorphospaceProtocolJson $mapPath
    $history=[ordered]@{retirement=$repreparation.retirement;original_preparation=$repreparation.original_preparation;preserved_evidence=@($repreparation.preserved_evidence)}
    $retiredPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$intent.pre.retired_unit.path) -RequireLeaf
    $retiredUnit=Read-MorphospaceProtocolJson $retiredPath
    $producerHistoryInput=[pscustomobject]@{project_id=[string]$repreparation.project_id;retired_unit_id=[string]$repreparation.retired_unit_id;replacement_unit_id=[string]$repreparation.replacement_unit_id;retirement=$repreparation.retirement;original_preparation=$repreparation.original_preparation}
    $events=@(Get-Content -LiteralPath (Resolve-MorphospaceWorkspacePath $workspace 'iteration-events.jsonl' -RequireLeaf)|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$retirementEvent=@($events|Where-Object{[string]$_.event_id-ceq[string]$repreparation.retirement.event_id})
    if($retirementEvent.Count-ne1-or[int]$retirementEvent[0].sequence+1-ne[int]$ExpectedEvent.sequence){throw 'Current-work repreparation retirement is not its exact contiguous predecessor.'}
    $producerHistory=Assert-RepreparationHistoricalSuffix $workspace (Get-CurrentWorkRepositoryRoot) $producerHistoryInput @($events|Where-Object{[int]$_.sequence-le[int]$retirementEvent[0].sequence}) $retiredUnit
    $retirementTransaction="$([string]$retirementEvent[0].event_id)-transition";$retirementStep=Test-MorphospaceCommittedTransitionLedger -WorkspaceRoot $workspace -TransactionId $retirementTransaction -ExpectedStatePath 'workspace.state.json' -ExpectedUnitPath "iteration-units/$([string]$repreparation.retired_unit_id).json" -ExpectedEventsPath 'iteration-events.jsonl';Test-MorphospaceHistoricalProposedRetirement -WorkspaceRoot $workspace -ExpectedEvent $retirementEvent[0] -CommittedStep $retirementStep|Out-Null
    $expectedPreserved=@($producerHistory.preserved)+@([pscustomobject][ordered]@{path=[string]$intent.pre.retired_unit.path;sha256=(Get-MorphospaceFileSha256 $retiredPath)})
    if((Get-MorphospaceCanonicalJsonSha256 $expectedPreserved)-cne(Get-MorphospaceCanonicalJsonSha256 @($repreparation.preserved_evidence))-or(Get-MorphospaceCanonicalJsonSha256 $expectedPreserved)-cne(Get-MorphospaceCanonicalJsonSha256 @($intent.preserved_evidence))){throw 'Current-work repreparation preserved evidence is not the exact historical closure.'}
    if([string]$producerHistory.live.project_sha256-cne[string]$intent.pre.project.sha256-or[string]$producerHistory.live.feature_lock_sha256-cne[string]$intent.pre.feature_lock.sha256-or[string]$producerHistory.live.state_sha256-cne[string]$intent.pre.state.sha256-or[string]$producerHistory.live.repository_map_path-cne[string]$intent.pre.repository_map.path-or[string]$producerHistory.live.repository_map_sha256-cne[string]$intent.pre.repository_map.sha256){throw 'Current-work repreparation preimage differs from the exact producer-authenticated historical suffix.'}
    Assert-MorphospaceDevelopmentEnvelopeRepreparationDefect $intent.pre.project.document $intent.pre.feature_lock.document $intent.pre.state.document
    $sourceIdentity=[pscustomobject][ordered]@{project_id=[string]$source.project_id;preparation_id=[string]$source.preparation_id;repositories=@($source.repositories)}
    if([string]$repreparation.input_sha256-cne[string]$intent.input_sha256-or[string]$preparation.input_sha256-cne[string]$intent.input_sha256-or[string]$repreparation.retired_unit_id-ceq[string]$repreparation.replacement_unit_id-or(Get-MorphospaceCanonicalJsonSha256 $intent.source_composition)-cne(Get-MorphospaceCanonicalJsonSha256 $source)-or[string]$intent.source_composition.preparation_id-cne[string]$repreparation.preparation_id-or[string]$intent.source_composition.project_id-cne[string]$repreparation.project_id-or[string]$source.project_id-cne[string]$repreparation.project_id-or[string]$source.preparation_id-cne[string]$repreparation.preparation_id-or[string]$source.fingerprint-cne(Get-MorphospaceCanonicalJsonSha256 $sourceIdentity)-or[string]$source.lock_id-cne"$([string]$source.preparation_id)-source-$(([string]$source.fingerprint).Substring(0,12))"-or[string]$repreparation.source_composition.sha256-cne[string]$sourceArtifact[0].sha256-or[string]$preparation.source_composition.path-cne$sourcePath-or[string]$preparation.source_composition.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $source)-or[string]$repreparation.history_sha256-cne(Get-MorphospaceCanonicalJsonSha256 $history)-or(Get-MorphospaceCanonicalJsonSha256 @($repreparation.preserved_evidence))-cne(Get-MorphospaceCanonicalJsonSha256 @($intent.preserved_evidence))-or[string]$preparation.project_sha256-cne(Get-MorphospaceCanonicalJsonSha256 $preparation.envelope.project)-or[string]$preparation.feature_lock_sha256-cne(Get-MorphospaceCanonicalJsonSha256 $preparation.envelope.feature_lock)-or[string]$preparation.project_sha256-cNe[string]$intent.target.project.sha256-or[string]$preparation.feature_lock_sha256-cne[string]$intent.target.feature_lock.sha256-or(Get-MorphospaceCanonicalJsonSha256 $preparation.envelope.project)-cne[string]$intent.target.project.sha256-or(Get-MorphospaceCanonicalJsonSha256 $preparation.envelope.feature_lock)-cne[string]$intent.target.feature_lock.sha256-or[string]$intent.pre.retired_unit.path-cne"iteration-units/$([string]$repreparation.retired_unit_id).json"-or[string]$intent.pre.retired_unit.sha256-cne(Get-MorphospaceCanonicalJsonSha256 (Read-MorphospaceProtocolJson $retiredPath))-or[string]$intent.pre.retired_unit.raw_sha256-cne(Get-MorphospaceFileSha256 $retiredPath)-or$null-ne$intent.pre.state.document.current_unit-or$null-ne$intent.pre.state.document.next_ready_unit){throw 'Current-work repreparation project, unit, source, or preserved-history bindings are detached.'}
    if([string]$preparation.envelope.source_composition.path-cne$sourcePath){
        throw 'Current-work repreparation envelope source path differs from its owned artifact.'
    }
    $declaredSourceIds=@($preparation.envelope.source_composition.repository_ids|ForEach-Object{[string]$_}|Sort-Object -Unique)
    $ownerIds=@($preparation.envelope.owner_repositories|ForEach-Object{[string]$_.repo_id}|Sort-Object -Unique);$sourceIds=@($source.repositories|ForEach-Object{[string]$_.repo_id}|Sort-Object -Unique);$mapIds=@($mapDocument.repositories|ForEach-Object{[string]$_.repo_id}|Sort-Object -Unique);$targetProjectIds=@($intent.target.project.document.repositories|ForEach-Object{[string]$_.repo_id}|Sort-Object -Unique)
    if($ownerIds.Count-ne$declaredSourceIds.Count-or$ownerIds.Count-ne$sourceIds.Count-or$ownerIds.Count-ne$mapIds.Count-or$ownerIds.Count-ne$targetProjectIds.Count-or@($ownerIds|Where-Object{$declaredSourceIds-cnotcontains$_-or$sourceIds-cnotcontains$_-or$mapIds-cnotcontains$_-or$targetProjectIds-cnotcontains$_}).Count-ne0){throw 'Current-work repreparation owner, source, map, and target project repository sets differ.'}
    foreach($sourceRepository in @($source.repositories)){$mapRepository=@($mapDocument.repositories|Where-Object{[string]$_.repo_id-ceq[string]$sourceRepository.repo_id});if($mapRepository.Count-ne1-or[string]$sourceRepository.role-cne[string]$mapRepository[0].role){throw 'Current-work repreparation source role differs from its repository map.'}}
    $ownerRootMap=@{};foreach($entry in @($mapDocument.repositories)){$ownerRootMap[[string]$entry.repo_id]=$true}
    Assert-MorphospaceDevelopmentEnvelopeOwnerRoots @($preparation.envelope.owner_repositories) $intent.target.project.document $ownerRootMap
    Assert-MorphospaceDevelopmentEnvelopeRepositoryRoots @($intent.pre.project.document.repositories) @($intent.target.project.document.repositories) @($preparation.envelope.owner_repositories)
    foreach($binding in @($intent.preserved_evidence)){if((Get-MorphospaceFileSha256 (Resolve-MorphospaceWorkspacePath $workspace ([string]$binding.path) -RequireLeaf))-cne[string]$binding.sha256){throw "Current-work repreparation preserved evidence '$([string]$binding.path)' is damaged."}}
    $preparationRequest=[pscustomobject]@{project_id=[string]$repreparation.project_id;envelope=$preparation.envelope}
    Assert-MorphospaceDevelopmentEnvelopeAdditiveProject $intent.pre.project.document $intent.target.project.document $true
    Assert-MorphospaceDevelopmentEnvelope $preparationRequest $intent.pre.project.document $intent.pre.feature_lock.document
    $derivedState=Get-MorphospaceDevelopmentEnvelopeTargetState $preparationRequest $intent.pre.project.document $intent.pre.feature_lock.document $intent.pre.state.document
    $derivedState.last_event_id=[string]$ExpectedEvent.event_id
    if((Get-MorphospaceCanonicalJsonSha256 $derivedState)-cne[string]$intent.target.state.sha256){throw 'Current-work repreparation target state is not the exact owner-derived projection.'}
    Assert-MorphospaceDevelopmentEnvelopeLockAndRegistry $intent.target.project.document $intent.target.feature_lock.document $intent.target.state.document 'historical target'
    $ledger=[IO.File]::ReadAllBytes((Resolve-MorphospaceWorkspacePath $workspace 'iteration-events.jsonl' -RequireLeaf));$length=[int64]$intent.pre.events.length;if($length-lt0-or$length-ge$ledger.LongLength){throw 'Current-work repreparation ledger predecessor length is invalid.'};$prefix=[byte[]]::new([int]$length);if($prefix.Length){[Array]::Copy($ledger,0,$prefix,0,$prefix.Length)};$line=Get-CurrentWorkEventLineBytes $ExpectedEvent
    if((Get-MorphospaceSha256Bytes $prefix)-cne[string]$intent.pre.events.sha256-or-not(Test-CurrentWorkByteRange $ledger $length $line)){throw 'Current-work repreparation is detached from its exact ledger predecessor.'}
    [pscustomobject]@{intent=$intent;completion=$completion;transaction_id=$transactionId}
}

function Test-MorphospaceHistoricalProposedRetirement {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][object]$ExpectedEvent,[Parameter(Mandatory)][object]$CommittedStep)
    $workspace=[IO.Path]::GetFullPath($WorkspaceRoot);$intent=$CommittedStep.intent;$unitId=[string]$ExpectedEvent.unit_id;$eventId=[string]$ExpectedEvent.event_id;$artifacts=@($intent.artifacts)
    if([string]$intent.schema-cne'rusty.morphospace.workflow.transition_ledger_intent.v1'-or$eventId-cnotmatch('^'+[regex]::Escape("$unitId-proposal-retired-")+'[0-9]{4}$')-or[string]$ExpectedEvent.event_type-cne'state-transition'-or$artifacts.Count-ne1-or@($ExpectedEvent.receipts).Count-ne1-or[string]$ExpectedEvent.receipts[0]-cne[string]$artifacts[0].path){throw 'Current-work proposed retirement transaction shape is not exact.'}
    $receiptPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$artifacts[0].path) -RequireLeaf;Assert-CurrentWorkSchemaFile $receiptPath 'work-unit-automation-receipt.schema.json' 'Current-work proposed retirement receipt schema is invalid.';$receiptBytes=[IO.File]::ReadAllBytes($receiptPath);$receipt=ConvertFrom-MorphospaceProtocolJsonBytes $receiptBytes 'current-work proposed retirement receipt';$binding=$receipt.proposed_retirement;$pre=$binding.authenticated_preimage;$replacement=[string]$binding.replacement_unit_id
    $summary="Retired the exact admitted proposed unit because its contract is invalid; preserved its admission chain and recorded intended replacement identity '$replacement' for separate admission."
    if([string]$artifacts[0].path-cnotmatch'^receipts/[a-z0-9][a-z0-9-]{1,127}\.json$'-or[string]$receipt.action-cne'RetireProposed'-or-not[bool]$receipt.executed-or[string]$receipt.transition-cne'proposed-to-superseded-retired'-or[string]$receipt.project_id-cne[string]$ExpectedEvent.project_id-or[string]$receipt.unit_id-cne$unitId-or[string]$receipt.event_id-cne$eventId-or[string]$receipt.status_before-cne'proposed'-or[string]$receipt.status_after-cne'superseded'-or$null-ne$receipt.current_unit_before-or$null-ne$receipt.current_unit_after-or[string]$binding.reason-cne'contract-invalid'-or$replacement-ceq$unitId-or-not[bool]$binding.replacement_identity_absent-or-not[bool]$binding.current_unit_absent-or-not[bool]$binding.next_ready_unit_absent-or-not[bool]$binding.original_admission_preserved-or[string]$ExpectedEvent.summary-cne$summary-or[string]$artifacts[0].sha256-cne(Get-MorphospaceSha256Bytes $receiptBytes)-or[string]$artifacts[0].bytes_base64-cne[Convert]::ToBase64String($receiptBytes)){throw 'Current-work proposed retirement receipt or event semantics are detached.'}
    $preUnit=Copy-CurrentWorkDocument $intent.target.unit.document;$preUnit.status='proposed';$preState=Copy-CurrentWorkDocument $intent.target.state.document;$preState.last_event_id=[string]$intent.expected.event_tail_id
    if([string]$intent.target.unit.document.status-cne'superseded'-or[string]$intent.target.unit.document.unit_id-cne$unitId-or[string]$intent.target.state.document.last_event_id-cne$eventId-or$null-ne$intent.target.state.document.current_unit-or$null-ne$intent.target.state.document.next_ready_unit-or[string]$intent.pre.unit.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $preUnit)-or[string]$intent.pre.state.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $preState)-or[string]$pre.state_sha256-cne[string]$intent.pre.state.sha256-or[string]$pre.unit_sha256-cne[string]$intent.pre.unit.sha256-or[string]$pre.events_sha256-cne[string]$intent.expected.events_sha256-or[int64]$pre.events_length-ne[int64]$intent.expected.events_length-or[string]$pre.event_tail_id-cne[string]$intent.expected.event_tail_id){throw 'Current-work proposed retirement projections are not the exact idle proposed-to-superseded change.'}
    $admission=$binding.authenticated_admission;$admissionReceipt=Resolve-MorphospaceWorkspacePath $workspace ([string]$admission.receipt.path) -RequireLeaf;$admissionIntent=Resolve-MorphospaceWorkspacePath $workspace ([string]$admission.transaction.intent.path) -RequireLeaf;$admissionCompletion=Resolve-MorphospaceWorkspacePath $workspace ([string]$admission.transaction.completion.path) -RequireLeaf;Assert-CurrentWorkSchemaFile $admissionReceipt 'development-unit-admission-v1.schema.json' 'Current-work proposed retirement admission receipt schema is invalid.';$events=@(Get-Content -LiteralPath (Resolve-MorphospaceWorkspacePath $workspace 'iteration-events.jsonl' -RequireLeaf)|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$admissionEvent=@($events|Where-Object{[string]$_.event_id-ceq[string]$admission.event.event_id});$admissionDocument=Read-MorphospaceProtocolJson $admissionReceipt
    $base=[ordered]@{replacement_unit_id=$replacement;reason=[string]$binding.reason;authenticated_admission=$admission;authenticated_preimage=$pre;replacement_identity_absent=$true;current_unit_absent=$true;next_ready_unit_absent=$true;original_admission_preserved=$true}
    $admissionId=[string]$admission.admission_id;$admissionTransaction="$admissionId-admitted-transition";$admissionSummary='Admitted a bounded proposed development unit; normal Ready, Inspect, and Claim remain required.'
    if($admissionEvent.Count-ne1-or[string]$admission.event.event_id-cne"$admissionId-admitted"-or[string]$admissionEvent[0].project_id-cne[string]$ExpectedEvent.project_id-or[string]$admissionEvent[0].unit_id-cne$unitId-or[string]$admissionEvent[0].event_type-cne'state-transition'-or[string]$admissionEvent[0].summary-cne$admissionSummary-or@($admissionEvent[0].receipts).Count-ne1-or[string]$admissionEvent[0].receipts[0]-cne"receipts/$admissionId.json"-or[string]$admission.receipt.path-cne"receipts/$admissionId.json"){throw "Current-work proposed retirement '$unitId' admission event identity is detached."}
    if((Get-MorphospaceCanonicalJsonSha256 $admissionEvent[0])-cne[string]$admission.event.sha256-or[string]$admission.transaction.transaction_id-cne$admissionTransaction-or[string]$admission.transaction.intent.path-cne"receipts/transactions/$admissionTransaction.intent.json"-or[string]$admission.transaction.completion.path-cne"receipts/transactions/$admissionTransaction.completion.json"-or(Get-MorphospaceFileSha256 $admissionReceipt)-cne[string]$admission.receipt.sha256-or(Get-MorphospaceFileSha256 $admissionIntent)-cne[string]$admission.transaction.intent.sha256-or(Get-MorphospaceFileSha256 $admissionCompletion)-cne[string]$admission.transaction.completion.sha256-or[string]$admission.transaction.target_unit_sha256-cne[string]$pre.unit_sha256){throw "Current-work proposed retirement '$unitId' admission evidence binding is detached."}
    if([string]$admissionDocument.admission_id-cne$admissionId-or[string]$admissionDocument.project_id-cne[string]$ExpectedEvent.project_id-or[string]$admissionDocument.unit_id-cne$unitId-or[string]$admissionDocument.unit.project_id-cne[string]$ExpectedEvent.project_id-or[string]$admissionDocument.unit.unit_id-cne$unitId-or[string]$admissionDocument.unit.status-cne'proposed'){throw "Current-work proposed retirement '$unitId' admitted unit identity is detached."}
    if((Get-MorphospaceCanonicalJsonSha256 $admissionDocument.unit)-cne[string]$pre.unit_sha256){throw "Current-work proposed retirement '$unitId' admitted unit canonical identity is detached."}
    if([string]$pre.unit_raw_sha256-cne(Get-MorphospaceSha256Bytes (ConvertTo-MorphospaceProtocolJsonBytes $admissionDocument.unit))){throw "Current-work proposed retirement '$unitId' admitted unit raw identity is detached."}
    $bindingDigest=Get-MorphospaceCanonicalJsonSha256 $base
    if([string]$binding.binding_sha256-cne$bindingDigest){throw "Current-work proposed retirement '$unitId' binding digest is detached (expected '$([string]$binding.binding_sha256)', derived '$bindingDigest')."}
    if([string]$pre.event_tail_id-cmatch'^admission-completion-timestamp-recovered-[0-9]{4,}$'){
        $recoveryEvent=@($events|Where-Object{[string]$_.event_id-ceq[string]$pre.event_tail_id});if($recoveryEvent.Count-ne1-or@($recoveryEvent[0].receipts).Count-ne1){throw 'Current-work proposed retirement recovered admission event is absent or ambiguous.'};$recovery=Test-MorphospaceHistoricalAdmissionCompletionTimestampRecovery $workspace (Resolve-MorphospaceWorkspacePath $workspace ([string]$recoveryEvent[0].receipts[0]) -RequireLeaf) $recoveryEvent[0]
        if([string]$recovery.receipt.admission_id-cne[string]$admission.admission_id-or(Get-MorphospaceCanonicalJsonSha256 $recovery.target_state)-cne[string]$pre.state_sha256-or(Get-MorphospaceCanonicalJsonSha256 $recovery.target_unit)-cne[string]$pre.unit_sha256-or(Get-MorphospaceCanonicalJsonSha256 $recovery.pre_event_state)-cne[string]$admission.transaction.target_state_sha256){throw 'Current-work proposed retirement recovery does not derive its authenticated preimage.'}
    }else{
        $admissionStep=Test-MorphospaceCommittedTransitionLedger -WorkspaceRoot $workspace -TransactionId ([string]$admission.transaction.transaction_id) -ExpectedStatePath 'workspace.state.json' -ExpectedUnitPath "iteration-units/$unitId.json" -ExpectedEventsPath 'iteration-events.jsonl';$admissionArtifacts=@($admissionStep.intent.artifacts)
        if([string]$admission.transaction.target_state_sha256-cne[string]$pre.state_sha256-or(Get-MorphospaceCanonicalJsonSha256 $admissionStep.intent.event)-cne(Get-MorphospaceCanonicalJsonSha256 $admissionEvent[0])-or[string]$admissionStep.intent.target.state.sha256-cne[string]$pre.state_sha256-or[string]$admissionStep.intent.target.unit.sha256-cne[string]$pre.unit_sha256-or$admissionArtifacts.Count-ne1-or[string]$admissionArtifacts[0].path-cne[string]$admission.receipt.path-or[string]$admissionArtifacts[0].sha256-cne(Get-MorphospaceFileSha256 $admissionReceipt)-or[string]$admissionArtifacts[0].bytes_base64-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes($admissionReceipt))){throw 'Current-work proposed retirement admission target differs from its exact committed preimage.'}
    }
    if(@($events|Where-Object{[int]$_.sequence-lt[int]$ExpectedEvent.sequence-and[string]$_.unit_id-ceq$replacement}).Count){throw 'Current-work proposed retirement replacement identity was not absent at retirement.'}
    [pscustomobject]@{unit_id=$unitId;replacement_unit_id=$replacement;receipt=$receipt;grants_validation_credit=$false}
}

function Test-MorphospaceHistoricalAdmissionCompletionTimestampRecovery {
    [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][string]$RecoveryPath,[Parameter(Mandatory)][object]$ExpectedEvent)
    $workspace=[IO.Path]::GetFullPath($WorkspaceRoot);$full=[IO.Path]::GetFullPath($RecoveryPath);Assert-CurrentWorkSchemaFile $full 'admission-completion-timestamp-recovery-v1.schema.json' 'Current-work admission recovery receipt schema is invalid.'
    $receiptBytes=[IO.File]::ReadAllBytes($full);$receipt=ConvertFrom-MorphospaceProtocolJsonBytes $receiptBytes 'current-work admission recovery receipt';$recoveryId=[string]$receipt.recovery_id;$canonical="receipts/$recoveryId.json"
    if($full-cne(Resolve-MorphospaceWorkspacePath $workspace $canonical -RequireLeaf)-or[string]$ExpectedEvent.event_id-cne$recoveryId-or[string]$receipt.correction_event.event_id-cne$recoveryId-or[string]$receipt.correction_event.receipt_path-cne$canonical-or(Get-MorphospaceCanonicalJsonSha256 $ExpectedEvent)-cne(Get-MorphospaceCanonicalJsonSha256 ([pscustomobject][ordered]@{schema='rusty.morphospace.workflow.iteration_event.v1';event_id=$recoveryId;sequence=[int]$receipt.correction_event.sequence;timestamp=[string]$receipt.correction_event.timestamp;project_id=[string]$receipt.project_id;unit_id=[string]$receipt.unit_id;event_type='state-transition';summary="Authenticated the exact admission completion timestamp defect for '$([string]$receipt.admission_id)' while preserving the malformed completion bytes.";receipts=@($canonical)}))){throw 'Current-work admission recovery event is not fully derived from its receipt.'}
    $admissionId=[string]$receipt.admission_id;$unitId=[string]$receipt.unit_id;$originalEventId="$admissionId-admitted";$originalTransaction="$originalEventId-transition"
    $request=Get-CurrentWorkSnapshot $workspace $receipt.evidence.admission_request "local/$admissionId.json" 'Admission recovery request';$admission=Get-CurrentWorkSnapshot $workspace $receipt.evidence.admission_receipt "receipts/$admissionId.json" 'Admission recovery installed receipt';$intent=Get-CurrentWorkSnapshot $workspace $receipt.evidence.admission_intent "receipts/transactions/$originalTransaction.intent.json" 'Admission recovery original intent';$malformed=Get-CurrentWorkSnapshot $workspace $receipt.evidence.malformed_completion "receipts/transactions/$originalTransaction.completion.json" 'Admission recovery malformed completion';$repreparation=Get-CurrentWorkSnapshot $workspace $receipt.evidence.repreparation_receipt ([string]$request.document.preparation.recovery_receipt_path) 'Admission recovery repreparation receipt';$preparation=Get-CurrentWorkSnapshot $workspace $receipt.evidence.preparation_receipt ([string]$request.document.preparation.receipt_path) 'Admission recovery preparation receipt';$source=Get-CurrentWorkSnapshot $workspace $receipt.evidence.source_composition ([string]$request.document.expected.source_composition_path) 'Admission recovery source composition';$map=Get-CurrentWorkSnapshot $workspace $receipt.evidence.repository_map ([string]$request.document.expected.repository_map_path) 'Admission recovery repository map'
    if($request.raw_sha256-cne$admission.raw_sha256-or[string]$request.document.schema-cne'rusty.morphospace.workflow.development_unit_admission.v1'-or[string]$request.document.admission_kind-cne'ordinary'-or[string]$request.document.project_id-cne[string]$receipt.project_id-or[string]$request.document.unit_id-cne$unitId){throw 'Admission recovery request and installed receipt are detached.'}
    $originalIntent=$intent.document;$completion=$malformed.document;Assert-CurrentWorkExactProperties $originalIntent @('schema','transaction_id','created_at','state','unit','events','pre','target','expected','artifacts','event','status') 'Admission recovery original intent';Assert-CurrentWorkExactProperties $completion @('schema','transaction_id','completed_at','intent','state_sha256','unit_sha256','event_id','status') 'Admission recovery malformed completion'
    if([string]$originalIntent.transaction_id-cne$originalTransaction-or[string]$originalIntent.event.event_id-cne$originalEventId-or[string]$originalIntent.unit.path-cne"iteration-units/$unitId.json"-or[string]$completion.transaction_id-cne$originalTransaction-or[string]$completion.intent.sha256-cne$intent.raw_sha256-or[string]$completion.state_sha256-cne[string]$originalIntent.target.state.sha256-or[string]$completion.unit_sha256-cne[string]$originalIntent.target.unit.sha256){throw 'Admission recovery original transaction is detached.'}
    $unitDocument=$request.document.unit;$unitBytes=ConvertTo-MorphospaceProtocolJsonBytes $unitDocument;$projectDocument=$null;$lockDocument=$null
    $reprepEvent=@((Get-Content -LiteralPath (Resolve-MorphospaceWorkspacePath $workspace 'iteration-events.jsonl' -RequireLeaf)|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String})|Where-Object{[string]$_.event_id-ceq"$([string]$repreparation.document.preparation_id)-prepared"})
    if($reprepEvent.Count-ne1){throw 'Admission recovery cannot resolve its unique repreparation event.'}
    $reprepStep=Test-MorphospaceCommittedDevelopmentEnvelopeRepreparation $workspace $reprepEvent[0];$projectDocument=$reprepStep.intent.target.project.document;$lockDocument=$reprepStep.intent.target.feature_lock.document
    foreach($derived in @(@($receipt.evidence.unit,$unitDocument,$unitBytes,'unit'),@($receipt.evidence.project,$projectDocument,(ConvertTo-MorphospaceProtocolJsonBytes $projectDocument),'project'),@($receipt.evidence.feature_lock,$lockDocument,(ConvertTo-MorphospaceProtocolJsonBytes $lockDocument),'feature lock'),@($receipt.evidence.state,$originalIntent.target.state.document,(ConvertTo-MorphospaceProtocolJsonBytes $originalIntent.target.state.document),'state'))){if([string]$derived[0].canonical_sha256-cne(Get-MorphospaceCanonicalJsonSha256 $derived[1])-or[string]$derived[0].raw_sha256-cne(Get-MorphospaceSha256Bytes ([byte[]]$derived[2]))){throw "Admission recovery $($derived[3]) historical projection differs from its bound producer bytes."}}
    if((Get-MorphospaceCanonicalJsonSha256 $unitDocument)-cne[string]$originalIntent.target.unit.sha256-or[string]$unitDocument.status-cne'proposed'-or[string]$request.document.expected.project_sha256-cne(Get-MorphospaceCanonicalJsonSha256 $projectDocument)-or[string]$request.document.expected.feature_lock_sha256-cne(Get-MorphospaceCanonicalJsonSha256 $lockDocument)-or[string]$request.document.expected.repository_map_sha256-cne$map.raw_sha256-or[string]$request.document.expected.source_composition_sha256-cne$source.raw_sha256-or[string]$request.document.preparation.receipt_sha256-cne$preparation.raw_sha256-or[string]$request.document.preparation.recovery_receipt_sha256-cne$repreparation.raw_sha256){throw 'Admission recovery admission/preparation/source projection chain is detached.'}
    $ledger=[IO.File]::ReadAllBytes((Resolve-MorphospaceWorkspacePath $workspace 'iteration-events.jsonl' -RequireLeaf));$boundLength=[int64]$receipt.evidence.event_ledger.length;if($boundLength-lt1-or$ledger.LongLength-le$boundLength){throw 'Admission recovery ledger prefix is incomplete.'};$bound=[byte[]]::new([int]$boundLength);[Array]::Copy($ledger,0,$bound,0,$bound.Length)
    if((Get-MorphospaceSha256Bytes $bound)-cne[string]$receipt.evidence.event_ledger.raw_sha256){throw 'Admission recovery bound admission ledger bytes differ.'};$recoveryLine=Get-CurrentWorkEventLineBytes $ExpectedEvent;if(-not(Test-CurrentWorkByteRange $ledger $boundLength $recoveryLine)){throw 'Admission recovery correction is not the exact next ledger row.'}
    $targetState=Copy-CurrentWorkDocument $originalIntent.target.state.document;$targetState.last_event_id=$recoveryId
    $ownerContext=Test-MorphospaceAdmissionCompletionTimestampRecoveryHistoricalProjection -WorkspaceRoot $workspace -RecoveryPath $full -CorrectionEvent $ExpectedEvent -Project $projectDocument -FeatureLock $lockDocument -State $targetState -Unit $unitDocument
    $transaction="$recoveryId-transition";$committedRecovery=Test-MorphospaceCommittedTransitionLedger -WorkspaceRoot $workspace -TransactionId $transaction -ExpectedStatePath 'workspace.state.json' -ExpectedUnitPath "iteration-units/$unitId.json" -ExpectedEventsPath 'iteration-events.jsonl';$recoveryIntent=$committedRecovery.intent;$recoveryCompletion=$committedRecovery.completion
    if([string]$recoveryIntent.schema-cne'rusty.morphospace.workflow.transition_ledger_intent.v6'-or[string]$recoveryIntent.transaction_id-cne$transaction-or(Get-MorphospaceCanonicalJsonSha256 $recoveryIntent.event)-cne(Get-MorphospaceCanonicalJsonSha256 $ExpectedEvent)-or[string]$recoveryIntent.expected.events_sha256-cne[string]$receipt.evidence.event_ledger.raw_sha256-or[int64]$recoveryIntent.expected.events_length-ne$boundLength-or[string]$recoveryIntent.target.state.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $targetState)-or[string]$recoveryIntent.target.unit.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $unitDocument)-or[string]$recoveryIntent.pre_state_raw.sha256-cne[string]$receipt.evidence.state.raw_sha256-or[string]$recoveryIntent.pre_unit_raw.sha256-cne[string]$receipt.evidence.unit.raw_sha256-or@($recoveryIntent.artifacts).Count-ne1-or[string]$recoveryIntent.artifacts[0].path-cne$canonical-or[string]$recoveryIntent.artifacts[0].sha256-cne(Get-MorphospaceSha256Bytes $receiptBytes)-or[string]$recoveryIntent.artifacts[0].bytes_base64-cne[Convert]::ToBase64String($receiptBytes)){throw 'Admission recovery committed intent is detached.'}
    $projections=@($recoveryIntent.additional_projections);if($projections.Count-ne2-or[string]$projections[0].path-cne'feature.lock.json'-or[string]$projections[1].path-cne'project.spec.json'-or[string]$projections[0].pre_raw_sha256-cne[string]$receipt.evidence.feature_lock.raw_sha256-or[string]$projections[1].pre_raw_sha256-cne[string]$receipt.evidence.project.raw_sha256-or[string]$projections[0].pre_sha256-cne[string]$projections[0].target_sha256-or[string]$projections[1].pre_sha256-cne[string]$projections[1].target_sha256){throw 'Admission recovery preservation projections are detached.'}
    if([string]$recoveryCompletion.transaction_id-cne$transaction-or[string]$recoveryCompletion.event_id-cne$recoveryId-or[string]$recoveryCompletion.state_sha256-cne[string]$recoveryIntent.target.state.sha256-or[string]$recoveryCompletion.unit_sha256-cne[string]$recoveryIntent.target.unit.sha256){throw 'Admission recovery committed completion is detached.'}
    $intentAt=Test-MorphospaceStrictUtcTimestamp ([string]$originalIntent.created_at);$completedAt=Test-MorphospaceStrictUtcTimestamp ([string]$completion.completed_at);$eventAt=Test-MorphospaceStrictUtcTimestamp ([string]$originalIntent.event.timestamp);$recoveryAt=Test-MorphospaceStrictUtcTimestamp ([string]$ExpectedEvent.timestamp)
    if($eventAt-ne$intentAt-or$completedAt-ge$intentAt-or$recoveryAt-lt$intentAt-or[string]$receipt.chronology.intent_created_at-cne[string]$originalIntent.created_at-or[string]$receipt.chronology.malformed_completed_at-cne[string]$completion.completed_at){throw 'Admission recovery chronology is not the exact supported defect.'}
    [pscustomobject]@{intent=$recoveryIntent;completion=$recoveryCompletion;receipt=$receipt;receipt_sha256=(Get-MorphospaceSha256Bytes $receiptBytes);original_intent=$originalIntent;malformed_completion=$completion;pre_event_state=$originalIntent.target.state.document;target_state=$targetState;target_unit=$unitDocument;recovery_event=$ExpectedEvent;bound_ledger_length=$boundLength;recovery_ledger_length=($boundLength+$recoveryLine.LongLength);project=$projectDocument;feature_lock=$lockDocument;grants_validation_credit=$false}
}

Export-ModuleMember -Function Test-MorphospaceHistoricalCommittedTransitionV1,Test-MorphospaceAcceptedCheckpointProof,Test-MorphospaceCommittedDevelopmentEnvelopeRepreparation,Test-MorphospaceHistoricalProposedRetirement,Test-MorphospaceHistoricalAdmissionCompletionTimestampRecovery
