Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$script:RepreparationProtocolModule=Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceProtocolCommon.psm1') -PassThru
$script:RepreparationTransitionLedgerModule=Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceTransitionLedger.psm1') -PassThru
$script:RepreparationPreparationModule=Import-Module (Join-Path $PSScriptRoot 'DevelopmentEnvelopePreparation.psm1') -PassThru
$script:RepreparationGitInvoker={param([string]$Root,[string[]]$Arguments)$output=@(& git -C $Root @Arguments 2>&1);[pscustomobject]@{exit_code=$LASTEXITCODE;output=$output}}

function Get-RepreparationHash { param([object]$Value) Get-MorphospaceCanonicalJsonSha256 $Value }
function Get-RepreparationFileHash { param([string]$Path) Get-MorphospaceFileSha256 $Path }
function Copy-RepreparationValue { param([object]$Value) $Value|ConvertTo-Json -Depth 64|ConvertFrom-Json -DateKind String }
function Get-RepreparationPath { param([string]$Root,[string]$Relative) Resolve-MorphospaceWorkspacePath $Root $Relative }
function Get-RepreparationLocalSchema {
    param([string]$Root,[string]$Name)
    $path=[IO.Path]::GetFullPath((Join-Path $Root "schemas\$Name"));$schema=Get-Content -Raw -LiteralPath $path|ConvertFrom-Json -Depth 100
    if($schema.PSObject.Properties.Name-contains'$id'){$schema.'$id'=([Uri]$path).AbsoluteUri}
    $schema|ConvertTo-Json -Depth 100
}
function Assert-RepreparationSchema { param([string]$Root,[string]$Path,[string]$Name,[string]$Message) if(-not(Test-Json -Json (Get-Content -Raw -LiteralPath $Path) -Schema (Get-RepreparationLocalSchema $Root $Name))){throw $Message} }
function Assert-RepreparationObjectSchema { param([string]$Root,[object]$Value,[string]$Name,[string]$Message) if(-not(Test-Json -Json ($Value|ConvertTo-Json -Depth 64) -Schema (Get-RepreparationLocalSchema $Root $Name))){throw $Message} }
function Assert-RepreparationTransitionLedgerEvidence {
    param([string]$Workspace,[string]$IntentRelative,[string]$IntentAbsolute,[string]$CompletionRelative,[string]$CompletionAbsolute)
    $intent=Read-MorphospaceProtocolJson $IntentAbsolute;$transactionId=[string]$intent.transaction_id
    &$script:RepreparationTransitionLedgerModule {param($workspaceValue,$transactionValue,$intentRelativeValue,$intentAbsoluteValue,$intentValue,$completionAbsoluteValue)Assert-MorphospaceLedgerIntent $intentValue $transactionValue;Assert-MorphospaceLedgerCommittedCompletion $workspaceValue $transactionValue $intentRelativeValue $intentAbsoluteValue $intentValue $completionAbsoluteValue} $Workspace $transactionId $IntentRelative $IntentAbsolute $intent $CompletionAbsolute
}
function Get-RepreparationArtifact { param([string]$Path,[object]$Value) [pscustomobject][ordered]@{path=$Path;sha256=(Get-RepreparationHash $Value);bytes_base64=[Convert]::ToBase64String([Text.UTF8Encoding]::new($false).GetBytes(($Value|ConvertTo-Json -Depth 64)))} }
function Assert-RepreparationFileBinding { param([string]$Workspace,[object]$Binding,[string]$Name) $path=Get-RepreparationPath $Workspace ([string]$Binding.path);if(-not[IO.File]::Exists($path)-or(Get-RepreparationFileHash $path)-cne[string]$Binding.sha256){throw "Repreparation $Name bytes do not match the supplied evidence."};$path }
function Get-RepreparationEventProjection {
    param([object]$Event)
    [pscustomobject][ordered]@{schema=[string]$Event.schema;event_id=[string]$Event.event_id;sequence=[int]$Event.sequence;timestamp=[string]$Event.timestamp;project_id=[string]$Event.project_id;unit_id=$(if($null-eq$Event.unit_id){$null}else{[string]$Event.unit_id});event_type=[string]$Event.event_type;summary=[string]$Event.summary;receipts=@($Event.receipts|ForEach-Object{[string]$_})}
}
function Test-RepreparationOwnedDirtPath {
    param([string]$Path)
    $p=$Path.Replace('\','/')
    return $p-cmatch '^(project\.spec\.json|feature\.lock\.json|workspace\.state\.json|iteration-events\.jsonl|repository-map\.json)$' -or
        $p-cmatch '^iteration-units/[a-z0-9][a-z0-9-]{1,127}\.json$' -or
        $p-cmatch '^receipts/(?:transactions/)?[a-z0-9][a-z0-9.-]{1,191}\.json$' -or
        $p-cmatch '^source-composition/[A-Za-z0-9._-]+\.json$'
}
function Invoke-RepreparationGitRead {
    param([string]$Root,[string[]]$Arguments,[string]$Name)
    $result=&$script:RepreparationGitInvoker $Root $Arguments
    if($null-eq$result-or[int]$result.exit_code-ne0){throw "Repreparation repository Git $Name readback failed."}
    @($result.output|ForEach-Object{[string]$_})
}
function Get-RepreparationGitScalar {
    param([string]$Root,[string[]]$Arguments,[string]$Name,[string]$Pattern)
    $rows=@(Invoke-RepreparationGitRead $Root $Arguments $Name)
    if($rows.Count-ne1){throw "Repreparation repository Git $Name readback has an invalid stdout shape."}
    $value=$rows[0].Trim();if(-not$value-or($Pattern-and$value-cnotmatch$Pattern)){throw "Repreparation repository Git $Name readback has an invalid value."};$value
}
function Get-RepreparationSourceComposition {
    param([object]$Recovery,[hashtable]$Map,[AllowNull()][object]$OriginalSource)
    $allowed=@{};foreach($row in @($Recovery.allowed_workflow_dirt)){$key=([string]$row.repo_id)+'|'+([string]$row.path);if($allowed.ContainsKey($key)){throw 'Repreparation repeats an allowed workflow-dirt identity.'};if(-not(Test-RepreparationOwnedDirtPath ([string]$row.path))){throw "Repreparation workflow dirt '$([string]$row.path)' is outside the closed workflow-owned surface."};$allowed[$key]=$row}
    $observed=@{};$records=[Collections.Generic.List[object]]::new();$leaves=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    foreach($id in @($Recovery.envelope.source_composition.repository_ids|Sort-Object -Unique)){
        if(-not$Map.ContainsKey([string]$id)){throw "Repreparation source repository '$id' is unmapped."};$entry=$Map[[string]$id];$root=[IO.Path]::GetFullPath([string]$entry.path);if(-not[IO.Directory]::Exists($root)){throw "Repreparation mapped repository '$id' is unavailable."}
        $commit=(Get-RepreparationGitScalar $root @('rev-parse','HEAD') 'commit' '^[0-9a-fA-F]{40}$').ToLowerInvariant();$tree=(Get-RepreparationGitScalar $root @('rev-parse','HEAD^{tree}') 'tree' '^[0-9a-fA-F]{40}$').ToLowerInvariant();$branch=Get-RepreparationGitScalar $root @('rev-parse','--abbrev-ref','HEAD') 'branch' '^(?!HEAD$)[^\x00-\x20~^:?*\\]+(?:/[^\x00-\x20~^:?*\\]+)*$'
        $dirt=[Collections.Generic.List[object]]::new();$statusRows=@(Invoke-RepreparationGitRead $root @('status','--porcelain=v1','--untracked-files=all') 'status');foreach($lineValue in $statusRows){$line=[string]$lineValue;if($line.Length-lt4-or$line.Contains(' -> ') -or $line.Substring(3).StartsWith('"')){throw "Repreparation repository '$id' has unsupported dirt."};$status=$line.Substring(0,2);$path=$line.Substring(3).Replace('\','/');$key="$id|$path";if([string]$entry.role-cne'planning'-or-not$allowed.ContainsKey($key)){throw "Repreparation repository '$id' has unenumerated dirt '$path'."};$full=[IO.Path]::GetFullPath((Join-Path $root $path));if(-not[IO.File]::Exists($full)){throw "Repreparation workflow dirt '$id/$path' is not a present regular file."};$hash=Get-RepreparationFileHash $full;$expected=$allowed[$key];if([string]$expected.status-cne$status-or[string]$expected.sha256-cne$hash){throw "Repreparation workflow dirt '$id/$path' differs from its exact status/hash allowance."};$observed[$key]=$true;$dirt.Add([pscustomobject][ordered]@{path=$path;status=$status;sha256=$hash})|Out-Null}
        $leaf=Split-Path -Leaf $root;if(-not$leaves.Add($leaf)){throw 'Repreparation source composition repeats a materialization leaf.'};$records.Add([pscustomobject][ordered]@{repo_id=[string]$id;role=[string]$entry.role;commit=$commit;tree=$tree;branch=$branch;materialization_path=$leaf;worktree_state=$(if($dirt.Count){'workflow-owned-dirt'}else{'clean'});workflow_owned_dirt=@($dirt.ToArray())})|Out-Null
    }
    foreach($key in $allowed.Keys){if(-not$observed.ContainsKey($key)){throw "Repreparation allowed workflow dirt '$key' is not present exactly."}}
    if($null-ne$OriginalSource){$old=@{};foreach($row in @($OriginalSource.repositories)){$id=[string]$row.repo_id;if($old.ContainsKey($id)){throw "Repreparation original source lock repeats '$id'."};$old[$id]=$row};if($old.Count-ne$records.Count){throw 'Repreparation repository set drifted from the original source lock.'};foreach($row in @($records.ToArray())){$id=[string]$row.repo_id;if(-not$old.ContainsKey($id)){throw "Repreparation repository '$id' is absent from the original source lock."};$prior=$old[$id];foreach($field in @('role','commit','tree','branch','materialization_path')){if([string]$row.$field-cne[string]$prior.$field){throw "Repreparation repository '$id' $field drifted from the original source lock."}}}}
    $identity=[pscustomobject][ordered]@{project_id=$Recovery.project_id;preparation_id=$Recovery.preparation_id;repositories=@($records.ToArray())};$fingerprint=Get-RepreparationHash $identity
    [pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_source_composition.v2';lock_id="$($Recovery.preparation_id)-source-$($fingerprint.Substring(0,12))";preparation_id=$Recovery.preparation_id;project_id=$Recovery.project_id;fingerprint=$fingerprint;repositories=@($records.ToArray());status='locked';does_not_prove=@('Does not grant Ready, Claim, source mutation, device, remote, or publication authority.')}
}
function Assert-RepreparationHistoricalSuffix {
    param([string]$Workspace,[string]$RepoRoot,[object]$Recovery,[object[]]$Events,[object]$RetiredUnit)
    if($Events.Count-lt3-or[string]$Events[-1].event_id-cne[string]$Recovery.retirement.event_id){throw 'Repreparation requires the exact completed retirement at the ledger tail.'}
    foreach($event in @($Events[-3],$Events[-2],$Events[-1])){Assert-RepreparationObjectSchema $RepoRoot $event 'iteration-event.schema.json' 'Repreparation historical ledger suffix contains an invalid event.'}
    $retirementReceiptPath=Assert-RepreparationFileBinding $Workspace $Recovery.retirement.receipt 'retirement receipt';$retirementIntentPath=Assert-RepreparationFileBinding $Workspace $Recovery.retirement.intent 'retirement intent';$retirementCompletionPath=Assert-RepreparationFileBinding $Workspace $Recovery.retirement.completion 'retirement completion'
    Assert-RepreparationSchema $RepoRoot $retirementReceiptPath 'work-unit-automation-receipt.schema.json' 'Repreparation retirement receipt is invalid.';Assert-RepreparationTransitionLedgerEvidence $Workspace ([string]$Recovery.retirement.intent.path) $retirementIntentPath ([string]$Recovery.retirement.completion.path) $retirementCompletionPath
    $retirementReceipt=Read-MorphospaceProtocolJson $retirementReceiptPath;$retirementIntent=Read-MorphospaceProtocolJson $retirementIntentPath;$retirementCompletion=Read-MorphospaceProtocolJson $retirementCompletionPath;$retirementEvent=$Events[-1]
    if([string]$retirementReceipt.action-cne'RetireProposed'-or$retirementReceipt.executed-ne$true-or[string]$retirementReceipt.event_id-cne[string]$retirementEvent.event_id-or[string]$retirementReceipt.unit_id-cne[string]$Recovery.retired_unit_id-or[string]$retirementReceipt.proposed_retirement.replacement_unit_id-cne[string]$Recovery.replacement_unit_id-or[string]$retirementReceipt.proposed_retirement.reason-cne'contract-invalid'){throw 'Repreparation retirement receipt does not name the exact retired/replacement pair.'}
    $retirementCompletionIntentHash=if($retirementCompletion.PSObject.Properties.Name-contains'intent_sha256'){[string]$retirementCompletion.intent_sha256}else{[string]$retirementCompletion.intent.sha256}
    $retirementArtifact=@($retirementIntent.artifacts|Where-Object{[string]$_.path-ceq[string]$Recovery.retirement.receipt.path})
    $retirementEventHash=Get-RepreparationHash (Get-RepreparationEventProjection $retirementEvent)
    if([string]$retirementIntent.event.event_id-cne[string]$retirementEvent.event_id-or(Get-RepreparationHash (Get-RepreparationEventProjection $retirementIntent.event))-cne$retirementEventHash){throw 'Repreparation retirement event differs between its intent and ledger.'}
    if([string]$retirementCompletion.event_id-cne[string]$retirementEvent.event_id-or[string]$retirementCompletion.status-cne'committed'-or$retirementCompletionIntentHash-cne(Get-RepreparationFileHash $retirementIntentPath)){throw 'Repreparation retirement completion does not bind its committed intent and event.'}
    if($retirementArtifact.Count-ne1-or[string]$retirementArtifact[0].sha256-cne(Get-RepreparationFileHash $retirementReceiptPath)-or[string]$retirementArtifact[0].bytes_base64-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes($retirementReceiptPath))){throw 'Repreparation retirement intent does not preserve the exact receipt bytes.'}
    $admission=$retirementReceipt.proposed_retirement.authenticated_admission;$admissionReceiptPath=Assert-RepreparationFileBinding $Workspace $admission.receipt 'admission receipt';$admissionIntentPath=Assert-RepreparationFileBinding $Workspace $admission.transaction.intent 'admission intent';$admissionCompletionPath=Assert-RepreparationFileBinding $Workspace $admission.transaction.completion 'admission completion';$admissionReceipt=Read-MorphospaceProtocolJson $admissionReceiptPath;$admissionIntent=Read-MorphospaceProtocolJson $admissionIntentPath;$admissionCompletion=Read-MorphospaceProtocolJson $admissionCompletionPath;$admissionEvent=$Events[-2]
    Assert-RepreparationSchema $RepoRoot $admissionReceiptPath 'development-unit-admission-v1.schema.json' 'Repreparation admission receipt is invalid.';Assert-RepreparationTransitionLedgerEvidence $Workspace ([string]$admission.transaction.intent.path) $admissionIntentPath ([string]$admission.transaction.completion.path) $admissionCompletionPath
    $admittedUnitHash=Get-RepreparationHash $admissionReceipt.unit
    $admissionArtifact=@($admissionIntent.artifacts|Where-Object{[string]$_.path-ceq[string]$admission.receipt.path});$admissionCompletionIntentHash=if($admissionCompletion.PSObject.Properties.Name-contains'intent_sha256'){[string]$admissionCompletion.intent_sha256}else{[string]$admissionCompletion.intent.sha256}
    $admissionEventHash=Get-RepreparationHash (Get-RepreparationEventProjection $admissionEvent)
    if([string]$admission.event.event_id-cne[string]$admissionEvent.event_id-or[string]$admission.event.sha256-cne$admissionEventHash-or[string]$admissionIntent.event.event_id-cne[string]$admissionEvent.event_id-or(Get-RepreparationHash (Get-RepreparationEventProjection $admissionIntent.event))-cne$admissionEventHash-or[string]$admissionCompletion.event_id-cne[string]$admissionEvent.event_id-or$admissionCompletionIntentHash-cne(Get-RepreparationFileHash $admissionIntentPath)-or$admissionArtifact.Count-ne1-or[string]$admissionArtifact[0].sha256-cne(Get-RepreparationFileHash $admissionReceiptPath)-or[string]$admissionArtifact[0].bytes_base64-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes($admissionReceiptPath))-or[string]$admissionReceipt.unit_id-cne[string]$Recovery.retired_unit_id-or$admittedUnitHash-cne[string]$admission.transaction.target_unit_sha256-or$admittedUnitHash-cne[string]$retirementIntent.pre.unit.sha256-or(Get-RepreparationHash $RetiredUnit)-cne[string]$retirementIntent.target.unit.sha256){throw 'Repreparation admission is not the exact contiguous predecessor of retirement.'}
    $original=$Recovery.original_preparation;if([string]$admissionReceipt.preparation.preparation_id-cne[string]$original.preparation_id-or[string]$original.preparation_id-cne[string]$Recovery.original_preparation.preparation_id){throw 'Repreparation admission does not bind the supplied original preparation.'}
    $prepReceiptPath=Assert-RepreparationFileBinding $Workspace $original.receipt 'original preparation receipt';$sourcePath=Assert-RepreparationFileBinding $Workspace $original.source_composition 'original source lock';$prepIntentPath=Assert-RepreparationFileBinding $Workspace $original.intent 'original preparation intent';$prepCompletionPath=Assert-RepreparationFileBinding $Workspace $original.completion 'original preparation completion';$prepReceipt=Read-MorphospaceProtocolJson $prepReceiptPath;$source=Read-MorphospaceProtocolJson $sourcePath;$prepIntent=Read-MorphospaceProtocolJson $prepIntentPath;$prepCompletion=Read-MorphospaceProtocolJson $prepCompletionPath;$prepEvent=$Events[-3]
    Assert-RepreparationSchema $RepoRoot $prepReceiptPath 'development-envelope-preparation-receipt-v1.schema.json' 'Repreparation original preparation receipt is invalid.';Assert-RepreparationSchema $RepoRoot $sourcePath 'development-envelope-source-composition-v1.schema.json' 'Repreparation original source lock is invalid.';Assert-RepreparationSchema $RepoRoot $prepIntentPath 'development-envelope-preparation-intent-v1.schema.json' 'Repreparation original preparation intent is invalid.';Assert-RepreparationSchema $RepoRoot $prepCompletionPath 'development-envelope-preparation-completion-v1.schema.json' 'Repreparation original preparation completion is invalid.'
    $prepReceiptArtifact=@($prepIntent.artifacts|Where-Object{[string]$_.path-ceq[string]$original.receipt.path});$prepSourceArtifact=@($prepIntent.artifacts|Where-Object{[string]$_.path-ceq[string]$original.source_composition.path})
    if((Get-RepreparationHash $source)-cne[string]$original.source_composition.canonical_sha256-or[string]$prepEvent.event_id-cne[string]$original.event_id-or[string]$prepIntent.event.event_id-cne[string]$prepEvent.event_id-or(Get-RepreparationHash (Get-RepreparationEventProjection $prepIntent.event))-cne(Get-RepreparationHash (Get-RepreparationEventProjection $prepEvent))-or[string]$prepCompletion.event_id-cne[string]$prepEvent.event_id-or[string]$prepCompletion.status-cne'committed'-or[string]$prepCompletion.intent_sha256-cne(Get-RepreparationFileHash $prepIntentPath)-or[string]$prepReceipt.preparation_id-cne[string]$original.preparation_id-or[string]$prepReceipt.source_composition.path-cne[string]$original.source_composition.path-or[string]$prepReceipt.source_composition.sha256-cne[string]$original.source_composition.canonical_sha256-or$prepReceiptArtifact.Count-ne1-or$prepSourceArtifact.Count-ne1-or[string]$prepReceiptArtifact[0].bytes_base64-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes($prepReceiptPath))-or[string]$prepSourceArtifact[0].bytes_base64-cne[Convert]::ToBase64String([IO.File]::ReadAllBytes($sourcePath))){throw 'Repreparation original preparation/source chain is not exact and contiguous.'}
    $preserved=@($Recovery.retirement.receipt,$Recovery.retirement.intent,$Recovery.retirement.completion,$admission.receipt,$admission.transaction.intent,$admission.transaction.completion,$original.receipt,$original.source_composition,$original.intent,$original.completion)|ForEach-Object{[pscustomobject][ordered]@{path=[string]$_.path;sha256=(Get-RepreparationFileHash (Get-RepreparationPath $Workspace ([string]$_.path)))}}
    [pscustomobject]@{preserved=@($preserved);source=$source}
}
function Complete-MorphospaceDevelopmentEnvelopeRepreparation {
    param([string]$Workspace,[string]$RepoRoot,[string]$IntentRelative,[string]$CompletionRelative,[string]$InputSha256,[ValidateSet('none','after-artifacts','after-project','after-lock','after-state','after-event')][string]$FaultAfter='none')
    $intentPath=Get-RepreparationPath $Workspace $IntentRelative;Assert-RepreparationSchema $RepoRoot $intentPath 'development-envelope-repreparation-intent-v1.schema.json' 'Repreparation intent is invalid.';$intent=Read-MorphospaceProtocolJson $intentPath
    if([string]$intent.input_sha256-cne$InputSha256){throw 'Repreparation input bytes do not match the published intent.'}
    foreach($e in @($intent.preserved_evidence)){if((Get-RepreparationFileHash (Get-RepreparationPath $Workspace ([string]$e.path)))-cne[string]$e.sha256){throw "Repreparation preserved evidence '$([string]$e.path)' changed after intent publication."}}
    foreach($name in @('project','state','feature_lock')){$binding=$intent.pre.$name;$target=$intent.target.$name;$current=Read-MorphospaceProtocolJson (Get-RepreparationPath $Workspace ([string]$binding.path));if(@([string]$binding.sha256,[string]$target.sha256)-cnotcontains(Get-RepreparationHash $current)){throw "Repreparation $name CAS is stale or conflicting."}}
    $unitPath=Get-RepreparationPath $Workspace ([string]$intent.pre.retired_unit.path);if((Get-RepreparationHash (Read-MorphospaceProtocolJson $unitPath))-cne[string]$intent.pre.retired_unit.sha256-or(Get-RepreparationFileHash $unitPath)-cne[string]$intent.pre.retired_unit.raw_sha256){throw 'Repreparation retired unit bytes changed.'};$mapPath=Get-RepreparationPath $Workspace ([string]$intent.pre.repository_map.path);if((Get-RepreparationFileHash $mapPath)-cne[string]$intent.pre.repository_map.sha256){throw 'Repreparation repository map changed.'};Assert-RepreparationSchema $RepoRoot $mapPath 'repository-map.schema.json' 'Repreparation repository map is invalid on resume.';$mapDocument=Read-MorphospaceProtocolJson $mapPath;$map=@{};foreach($entry in @($mapDocument.repositories)){$id=[string]$entry.repo_id;if($map.ContainsKey($id)){throw "Repreparation repository map repeats '$id' on resume."};$map[$id]=$entry};$sourceRequest=[pscustomobject]@{project_id=[string]$intent.source_composition.project_id;preparation_id=[string]$intent.source_composition.preparation_id;allowed_workflow_dirt=@($intent.allowed_workflow_dirt);envelope=[pscustomobject]@{source_composition=[pscustomobject]@{repository_ids=@($intent.source_composition.repositories|ForEach-Object{[string]$_.repo_id})}}};$liveSource=Get-RepreparationSourceComposition $sourceRequest $map $null;if((Get-RepreparationHash $liveSource)-cne(Get-RepreparationHash $intent.source_composition)){throw 'Repreparation repository identity or workflow dirt changed after intent publication.'}
    foreach($artifact in @($intent.artifacts)){$path=Get-RepreparationPath $Workspace ([string]$artifact.path);if([IO.File]::Exists($path)){if((Get-RepreparationHash (Read-MorphospaceProtocolJson $path))-cne[string]$artifact.sha256){throw "Repreparation artifact '$([string]$artifact.path)' conflicts."}}else{[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($path))|Out-Null;[IO.File]::WriteAllBytes($path,[Convert]::FromBase64String([string]$artifact.bytes_base64))}}
    if($FaultAfter-eq'after-artifacts'){throw 'Injected repreparation interruption after artifacts.'};foreach($name in @('project','feature_lock','state')){$target=$intent.target.$name;$path=Get-RepreparationPath $Workspace ([string]$target.path);if((Get-RepreparationHash (Read-MorphospaceProtocolJson $path))-cne[string]$target.sha256){Write-MorphospaceManagedProtocolJsonAtomic $Workspace ([string]$target.path) $target.document};if($FaultAfter-eq("after-"+$name.Replace('feature_lock','lock'))){throw "Injected repreparation interruption after $name."}}
    $eventsPath=Get-RepreparationPath $Workspace 'iteration-events.jsonl';$events=@(Get-Content $eventsPath|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$same=@($events|Where-Object{[string]$_.event_id-ceq[string]$intent.event.event_id});if($same.Count-eq0){if((Get-RepreparationFileHash $eventsPath)-cne[string]$intent.pre.events.sha256-or[string]$events[-1].event_id-cne[string]$intent.pre.events.tail_id){throw 'Repreparation event predecessor changed.'};[IO.File]::AppendAllText($eventsPath,(($intent.event|ConvertTo-Json -Compress)+"`n"),[Text.UTF8Encoding]::new($false))}elseif($same.Count-ne1-or[string]$events[-1].event_id-cne[string]$intent.event.event_id){throw 'Repreparation event placement conflicts.'};if($FaultAfter-eq'after-event'){throw 'Injected repreparation interruption after event.'}
    $completionPath=Get-RepreparationPath $Workspace $CompletionRelative;if([IO.File]::Exists($completionPath)){$completion=Read-MorphospaceProtocolJson $completionPath;if([string]$completion.intent_sha256-cne(Get-RepreparationFileHash $intentPath)-or[string]$completion.event_id-cne[string]$intent.event.event_id){throw 'Repreparation completion conflicts with its intent.'};return 'already-committed'}
    $recoveryArtifact=@($intent.artifacts|Where-Object{[string]$_.path-cmatch'-repreparation\.json$'});$completion=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_repreparation_completion.v1';transaction_id=$intent.transaction_id;completed_at=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ');intent_sha256=(Get-RepreparationFileHash $intentPath);target_project_sha256=$intent.target.project.sha256;target_state_sha256=$intent.target.state.sha256;target_feature_lock_sha256=$intent.target.feature_lock.sha256;repreparation_receipt_sha256=[string]$recoveryArtifact[0].sha256;event_id=$intent.event.event_id;status='committed'};Write-MorphospaceManagedProtocolJsonAtomic $Workspace $CompletionRelative $completion -NoOverwrite;'committed'
}
function Invoke-MorphospaceReprepareRetiredDevelopmentEnvelope {
 [CmdletBinding()]param([string]$WorkspaceRoot,[string]$DevelopmentEnvelopeRepreparation,[string]$OutPath,[string]$ExpectedDevelopmentEnvelopeRepreparationSha256='',[string]$Timestamp='',[switch]$Execute,[ValidateSet('none','after-intent','after-artifacts','after-project','after-lock','after-state','after-event')][string]$FaultAfter='none')
 $repoRoot=Split-Path $PSScriptRoot -Parent;$workspace=(Resolve-Path $WorkspaceRoot).Path;$input=(Resolve-Path $DevelopmentEnvelopeRepreparation).Path;Assert-RepreparationSchema $repoRoot $input 'development-envelope-repreparation-v1.schema.json' 'Development envelope repreparation does not satisfy its closed schema.';$r=Read-MorphospaceProtocolJson $input;$inputHash=Get-RepreparationFileHash $input;if($Execute-and-not$ExpectedDevelopmentEnvelopeRepreparationSha256){throw 'Executed repreparation requires the dry-run input SHA-256.'};if($ExpectedDevelopmentEnvelopeRepreparationSha256-and$ExpectedDevelopmentEnvelopeRepreparationSha256-cne$inputHash){throw 'Expected repreparation hash does not match input.'};if(-not$Timestamp){$Timestamp=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ')};if(-not(Test-MorphospaceStrictUtcTimestamp $Timestamp)){throw 'Repreparation timestamp must be strict UTC.'}
 if([string]$r.retired_unit_id-ceq[string]$r.replacement_unit_id-or[string]$r.preparation_id-ceq[string]$r.original_preparation.preparation_id){throw 'Repreparation requires distinct retired/replacement and fresh preparation identities.'};if(Test-Path (Get-RepreparationPath $workspace "iteration-units/$($r.replacement_unit_id).json")){throw 'Repreparation replacement unit identity must remain absent for later ordinary admission.'}
 $receiptRelative="receipts/$($r.repreparation_id)-repreparation.json";$prepRelative="receipts/$($r.preparation_id).json";$sourceRelative=[string]$r.envelope.source_composition.path;$transactionId="$($r.repreparation_id)-transition";$intentRelative="receipts/transactions/$transactionId.intent.json";$completionRelative="receipts/transactions/$transactionId.completion.json";$eventId="$($r.preparation_id)-prepared";if([IO.Path]::GetFullPath($OutPath)-cne(Get-RepreparationPath $workspace $receiptRelative)){throw "Repreparation output must be '$receiptRelative'."}
 $earlyIntent=Get-RepreparationPath $workspace $intentRelative;if(Test-Path $earlyIntent){Assert-RepreparationSchema $repoRoot $earlyIntent 'development-envelope-repreparation-intent-v1.schema.json' 'Existing repreparation intent is invalid.';$intent=Read-MorphospaceProtocolJson $earlyIntent;if([string]$intent.input_sha256-cne$inputHash){throw 'Repreparation input bytes differ from the existing intent.'};if($Execute){$mutex=Enter-MorphospaceWorkspaceMutex $workspace;try{[void](Complete-MorphospaceDevelopmentEnvelopeRepreparation $workspace $repoRoot $intentRelative $completionRelative $inputHash -FaultAfter $FaultAfter)}finally{Exit-MorphospaceWorkspaceMutex $mutex}};return [pscustomobject][ordered]@{schema='rusty.morphospace.workflow.work_unit_automation_receipt.v2';project_id=$r.project_id;unit_id=$r.retired_unit_id;action='ReprepareRetiredDevelopmentEnvelope';timestamp=$Timestamp;executed=$Execute.IsPresent;transition='retired-envelope-reprepared';status_before='superseded';status_after='superseded';current_unit_before=$null;current_unit_after=$null;preservation=[ordered]@{git_mutation_performed=$false;device_mutation_performed=$false;remote_mutation_performed=$false};audit_receipt=[ordered]@{path=$receiptRelative;sha256=[string]$intent.input_sha256};event_id=$(if($Execute){$eventId}else{$null})}}
 $projectPath=Get-RepreparationPath $workspace 'project.spec.json';$statePath=Get-RepreparationPath $workspace 'workspace.state.json';$lockPath=Get-RepreparationPath $workspace 'feature.lock.json';$unitPath=Get-RepreparationPath $workspace ([string]$r.expected.retired_unit_path);$mapPath=Get-RepreparationPath $workspace ([string]$r.expected.repository_map_path);Assert-RepreparationSchema $repoRoot $projectPath 'project-spec-v2.schema.json' 'Repreparation current project is invalid.';Assert-RepreparationSchema $repoRoot $statePath 'workspace-state-v2.schema.json' 'Repreparation current workspace state is invalid.';Assert-RepreparationSchema $repoRoot $lockPath 'feature-lock-v2.schema.json' 'Repreparation current feature lock is invalid.';Assert-RepreparationSchema $repoRoot $unitPath 'iteration-unit.schema.json' 'Repreparation retired unit is invalid.';Assert-RepreparationSchema $repoRoot $mapPath 'repository-map.schema.json' 'Repreparation repository map is invalid.';$project=Read-MorphospaceProtocolJson $projectPath;$state=Read-MorphospaceProtocolJson $statePath;$lock=Read-MorphospaceProtocolJson $lockPath;$unit=Read-MorphospaceProtocolJson $unitPath;$mapDoc=Read-MorphospaceProtocolJson $mapPath;$eventsPath=Get-RepreparationPath $workspace 'iteration-events.jsonl';$events=@(Get-Content $eventsPath|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});if([string]$project.project_id-cne[string]$r.project_id-or[string]$state.project_id-cne[string]$r.project_id-or[string]$unit.unit_id-cne[string]$r.retired_unit_id-or[string]$unit.status-cne'superseded'-or$null-ne$state.current_unit-or$null-ne$state.next_ready_unit){throw 'Repreparation requires the exact idle retired-unit boundary.'}
 foreach($check in @(@{n='project';e=$r.expected.project_sha256;a=Get-RepreparationHash $project},@{n='state';e=$r.expected.state_sha256;a=Get-RepreparationHash $state},@{n='feature lock';e=$r.expected.feature_lock_sha256;a=Get-RepreparationHash $lock},@{n='repository map';e=$r.expected.repository_map_sha256;a=Get-RepreparationFileHash $mapPath},@{n='retired unit';e=$r.expected.retired_unit_sha256;a=Get-RepreparationHash $unit},@{n='retired unit bytes';e=$r.expected.retired_unit_raw_sha256;a=Get-RepreparationFileHash $unitPath},@{n='ledger';e=$r.expected.events_sha256;a=Get-RepreparationFileHash $eventsPath})){if([string]$check.e-cne[string]$check.a){throw "Repreparation stale $($check.n) CAS."}};if([int64]$r.expected.events_length-ne[IO.FileInfo]::new($eventsPath).Length-or[string]$r.expected.event_tail_id-cne[string]$events[-1].event_id){throw 'Repreparation ledger tail CAS is stale.'}
 $history=Assert-RepreparationHistoricalSuffix $workspace $repoRoot $r $events $unit;$preserved=@($history.preserved);$preserved+=,[pscustomobject][ordered]@{path=[string]$r.expected.retired_unit_path;sha256=(Get-RepreparationFileHash $unitPath)}
 $map=@{};foreach($e in @($mapDoc.repositories)){$id=[string]$e.repo_id;if($map.ContainsKey($id)){throw "Repreparation repository map repeats '$id'."};$map[$id]=$e};$shim=[pscustomobject]@{project_id=$r.project_id;envelope=$r.envelope};$prepModule=$script:RepreparationPreparationModule
 $currentFingerprint=&$prepModule {param($value)Get-PreparationLockFingerprint $value} $lock;$currentRegistry=&$prepModule {param($project,$value)Get-PreparationModuleRegistry $project $value} $project $lock;if([string]$lock.lock_fingerprint-ceq[string]$currentFingerprint-and(Get-RepreparationHash $state.module_registry)-ceq(Get-RepreparationHash $currentRegistry)){throw 'Repreparation is reserved for an exact lock-fingerprint or module-registry defect after retirement.'}
 if($null-eq$r.envelope.PSObject.Properties['schema_pin_revision']){throw 'Repreparation requires the adopted Work Environment schema-pin revision.'};$targetState=&$prepModule {param($p,$project,$lock,$state)Get-PreparationTargetState $p $project $lock $state} $shim $project $lock $state;&$prepModule {param($current,$target,$advance)Assert-PreparationAdditiveProject $current $target $advance} $project $r.envelope.project $true;&$prepModule {param($rows,$project,$map)Assert-PreparationRoots $rows $project $map} @($r.envelope.owner_repositories) $r.envelope.project $map;&$prepModule {param($p,$project,$lock)Assert-PreparationEnvelope $p $project $lock} $shim $project $lock;&$prepModule {param($p,$l,$s)Assert-PreparationLockAndRegistry $p $l $s 'target'} $r.envelope.project $r.envelope.feature_lock $targetState
 $ownerIds=@($r.envelope.owner_repositories|ForEach-Object{[string]$_.repo_id}|Sort-Object -Unique);$sourceIds=@($r.envelope.source_composition.repository_ids|ForEach-Object{[string]$_}|Sort-Object -Unique);$mapIds=@($map.Keys|Sort-Object -Unique);$projectIds=@($r.envelope.project.repositories|ForEach-Object{[string]$_.repo_id}|Sort-Object -Unique);foreach($set in @($sourceIds,$mapIds,$projectIds)){if($set.Count-ne$ownerIds.Count-or@($ownerIds|Where-Object{$set-cnotcontains$_}).Count-ne0){throw 'Repreparation owner, source-lock, project, and repository-map identities must agree exactly.'}}
 if(-not(Test-Json -Json ($r.envelope.project|ConvertTo-Json -Depth 64) -SchemaFile (Join-Path $repoRoot 'schemas\project-spec-v2.schema.json'))-or-not(Test-Json -Json ($r.envelope.feature_lock|ConvertTo-Json -Depth 64) -SchemaFile (Join-Path $repoRoot 'schemas\feature-lock-v2.schema.json'))-or-not(Test-Json -Json ($targetState|ConvertTo-Json -Depth 64) -SchemaFile (Join-Path $repoRoot 'schemas\workspace-state-v2.schema.json'))){throw 'Repreparation corrected project/lock/state triple is invalid.'}
 $source=Get-RepreparationSourceComposition $r $map $history.source;if(-not(Test-Json -Json ($source|ConvertTo-Json -Depth 64) -SchemaFile (Join-Path $repoRoot 'schemas\development-envelope-source-composition-v2.schema.json'))){throw 'Repreparation source lock is invalid.'};if((Get-RepreparationFileHash $input)-cne$inputHash-or(Get-RepreparationFileHash $mapPath)-cne[string]$r.expected.repository_map_sha256){throw 'Repreparation input or repository map changed during fresh repository observation.'};$targetState.last_event_id=$eventId
 $recoveryReceipt=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_repreparation_receipt.v1';repreparation_id=$r.repreparation_id;preparation_id=$r.preparation_id;project_id=$r.project_id;retired_unit_id=$r.retired_unit_id;replacement_unit_id=$r.replacement_unit_id;input_sha256=$inputHash;retirement=$r.retirement;original_preparation=$r.original_preparation;preserved_evidence=$preserved;does_not_prove=@('Does not amend old evidence or grant Ready, Claim, source mutation, device, remote, or publication authority.')};$prepReceipt=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_preparation_receipt.v1';preparation_id=$r.preparation_id;project_id=$r.project_id;predecessor_unit_id=$r.retired_unit_id;input_sha256=$inputHash;envelope=$r.envelope;project_sha256=(Get-RepreparationHash $r.envelope.project);feature_lock_sha256=(Get-RepreparationHash $r.envelope.feature_lock);source_composition=[pscustomobject]@{path=$sourceRelative;sha256=(Get-RepreparationHash $source)};does_not_prove=@('Recovery preparation does not admit the distinct replacement unit or grant Ready, Claim, source mutation, device, remote, or publication authority.')};$event=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.iteration_event.v1';event_id=$eventId;sequence=[int]$events[-1].sequence+1;timestamp=$Timestamp;project_id=$r.project_id;unit_id=$r.retired_unit_id;event_type='decision';summary='Reprepared a corrected development envelope after exact proposed-unit retirement; separate ordinary admission remains required.';receipts=@($receiptRelative,$prepRelative)}
 $artifacts=@(Get-RepreparationArtifact $receiptRelative $recoveryReceipt;Get-RepreparationArtifact $prepRelative $prepReceipt;Get-RepreparationArtifact $sourceRelative $source);$intent=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_repreparation_intent.v1';transaction_id=$transactionId;created_at=$Timestamp;input_sha256=$inputHash;pre=[pscustomobject]@{project=[pscustomobject]@{path='project.spec.json';sha256=(Get-RepreparationHash $project);document=$project};state=[pscustomobject]@{path='workspace.state.json';sha256=(Get-RepreparationHash $state);document=$state};feature_lock=[pscustomobject]@{path='feature.lock.json';sha256=(Get-RepreparationHash $lock);document=$lock};retired_unit=[pscustomobject]@{path=$r.expected.retired_unit_path;sha256=(Get-RepreparationHash $unit);raw_sha256=(Get-RepreparationFileHash $unitPath)};repository_map=[pscustomobject]@{path=$r.expected.repository_map_path;sha256=(Get-RepreparationFileHash $mapPath)};events=[pscustomobject]@{path='iteration-events.jsonl';sha256=(Get-RepreparationFileHash $eventsPath);tail_id=[string]$events[-1].event_id}};target=[pscustomobject]@{project=[pscustomobject]@{path='project.spec.json';sha256=(Get-RepreparationHash $r.envelope.project);document=$r.envelope.project};state=[pscustomobject]@{path='workspace.state.json';sha256=(Get-RepreparationHash $targetState);document=$targetState};feature_lock=[pscustomobject]@{path='feature.lock.json';sha256=(Get-RepreparationHash $r.envelope.feature_lock);document=$r.envelope.feature_lock}};source_composition=$source;allowed_workflow_dirt=@($r.allowed_workflow_dirt);artifacts=$artifacts;event=$event;preserved_evidence=$preserved;status='prepared'}
 if(-not$Execute){return [pscustomobject][ordered]@{schema='rusty.morphospace.workflow.work_unit_automation_receipt.v2';project_id=$r.project_id;unit_id=$r.retired_unit_id;action='ReprepareRetiredDevelopmentEnvelope';timestamp=$Timestamp;executed=$false;transition='retired-envelope-reprepared';status_before='superseded';status_after='superseded';current_unit_before=$null;current_unit_after=$null;preservation=[ordered]@{git_mutation_performed=$false;device_mutation_performed=$false;remote_mutation_performed=$false};audit_receipt=[ordered]@{path=$receiptRelative;sha256=$inputHash};event_id=$null}}
 $mutex=Enter-MorphospaceWorkspaceMutex $workspace;try{if(Test-Path (Get-RepreparationPath $workspace $intentRelative)){throw 'Repreparation intent appeared during observation.'};Write-MorphospaceManagedProtocolJsonAtomic $workspace $intentRelative $intent -NoOverwrite;if($FaultAfter-eq'after-intent'){throw 'Injected repreparation interruption after intent.'};[void](Complete-MorphospaceDevelopmentEnvelopeRepreparation $workspace $repoRoot $intentRelative $completionRelative $inputHash -FaultAfter $FaultAfter)}finally{Exit-MorphospaceWorkspaceMutex $mutex}
 [pscustomobject][ordered]@{schema='rusty.morphospace.workflow.work_unit_automation_receipt.v2';project_id=$r.project_id;unit_id=$r.retired_unit_id;action='ReprepareRetiredDevelopmentEnvelope';timestamp=$Timestamp;executed=$true;transition='retired-envelope-reprepared';status_before='superseded';status_after='superseded';current_unit_before=$null;current_unit_after=$null;preservation=[ordered]@{git_mutation_performed=$false;device_mutation_performed=$false;remote_mutation_performed=$false};audit_receipt=[ordered]@{path=$receiptRelative;sha256=$inputHash};event_id=$eventId}
}
Export-ModuleMember -Function Invoke-MorphospaceReprepareRetiredDevelopmentEnvelope,Complete-MorphospaceDevelopmentEnvelopeRepreparation
