Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceProtocolCommon.psm1') -Force
function Assert-PreparationProvenanceJson { param([string]$Path,[string]$Schema,[string]$Message) if(-not(Test-Json -Json (Get-Content -Raw -LiteralPath $Path) -SchemaFile $Schema)){throw $Message} }
function Test-MorphospacePreparedDevelopmentEnvelope {
 [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][object]$Admission,[ValidateSet('Admission','Freeze')][string]$Phase='Admission')
 $workspace=(Resolve-Path $WorkspaceRoot).Path;$repoRoot=Split-Path $PSScriptRoot -Parent;$p=$Admission.preparation
 $admissionPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$p.receipt_path) -RequireLeaf
 if((Get-MorphospaceFileSha256 $admissionPath)-cne[string]$p.receipt_sha256){throw 'Prepared-envelope admission receipt bytes drifted.'}
 $receipt=Read-MorphospaceProtocolJson $admissionPath;Assert-PreparationProvenanceJson $admissionPath (Join-Path $repoRoot 'schemas\development-envelope-preparation-receipt-v1.schema.json') 'Prepared-envelope receipt schema is invalid.'
 $tx="$([string]$p.preparation_id)-prepared-transition";$intentPath=Resolve-MorphospaceWorkspacePath $workspace "receipts/transactions/$tx.intent.json" -RequireLeaf;$completionPath=Resolve-MorphospaceWorkspacePath $workspace "receipts/transactions/$tx.completion.json" -RequireLeaf
 Assert-PreparationProvenanceJson $intentPath (Join-Path $repoRoot 'schemas\development-envelope-preparation-intent-v1.schema.json') 'Prepared-envelope intent schema is invalid.';Assert-PreparationProvenanceJson $completionPath (Join-Path $repoRoot 'schemas\development-envelope-preparation-completion-v1.schema.json') 'Prepared-envelope completion schema is invalid.'
 $intent=Read-MorphospaceProtocolJson $intentPath;$completion=Read-MorphospaceProtocolJson $completionPath;$sourcePath=Resolve-MorphospaceWorkspacePath $workspace ([string]$p.source_composition_path) -RequireLeaf
 Assert-PreparationProvenanceJson $sourcePath (Join-Path $repoRoot 'schemas\development-envelope-source-composition-v1.schema.json') 'Prepared-envelope source lock schema is invalid.'
 $source=Read-MorphospaceProtocolJson $sourcePath;$project=Read-MorphospaceProtocolJson (Resolve-MorphospaceWorkspacePath $workspace 'project.spec.json' -RequireLeaf);$lock=Read-MorphospaceProtocolJson (Resolve-MorphospaceWorkspacePath $workspace 'feature.lock.json' -RequireLeaf);$state=Read-MorphospaceProtocolJson (Resolve-MorphospaceWorkspacePath $workspace 'workspace.state.json' -RequireLeaf)
 $scope=$Admission.agent_scope_assessment;$envelope=$receipt.envelope;foreach($name in @('allowed_change_categories','allowed_effect_categories','allowed_permission_categories')){if($null-eq$envelope.$name){throw "Prepared-envelope omits $name."};foreach($value in @($scope.$name)){if(@($envelope.$name)-cnotcontains$value){throw "Admission scope exceeds prepared $name."}}};if([string]$scope.public_private_boundary-cne[string]$envelope.public_private_boundary-or[string]$scope.build_envelope.class-cne[string]$envelope.build_envelope.class-or[string]$scope.device_envelope.requirement-cne[string]$envelope.device_envelope.requirement){throw 'Admission public/private, build, or device ceiling exceeds the prepared envelope.'}
 foreach($profile in @($scope.build_envelope.allowed_profiles)){if(@($envelope.build_envelope.allowed_profiles)-cnotcontains[string]$profile){throw 'Admission build profile exceeds the prepared envelope.'}}
 foreach($kind in @($scope.device_envelope.allowed_kinds)){if(@($envelope.device_envelope.allowed_kinds)-cnotcontains[string]$kind){throw 'Admission device kind exceeds the prepared envelope.'}}
 foreach($owner in @($scope.owner_repositories)){$prepared=@($envelope.owner_repositories|Where-Object{[string]$_.repo_id-ceq[string]$owner.repo_id});if($prepared.Count-ne1){throw 'Admission repository identity exceeds the prepared envelope.'};foreach($root in @($owner.source_roots)){if(@($prepared[0].source_roots)-cnotcontains[string]$root){throw 'Admission source root exceeds the prepared envelope.'}}}
 if([string]$Admission.unit.source_composition.lock_path-cne[string]$p.source_composition_path){throw 'Admission unit does not bind the canonical prepared source lock.'}
 $artifacts=@($intent.artifacts);$receiptArtifact=@($artifacts|Where-Object{[string]$_.path-ceq[string]$p.receipt_path});$sourceArtifact=@($artifacts|Where-Object{[string]$_.path-ceq[string]$p.source_composition_path})
 $sourceRawFileSha256=Get-MorphospaceFileSha256 $sourcePath;$sourceCanonicalJsonSha256=Get-MorphospaceCanonicalJsonSha256 $source;$receiptCanonicalJsonSha256=Get-MorphospaceCanonicalJsonSha256 $receipt
 $receiptBytesBase64=[Convert]::ToBase64String([IO.File]::ReadAllBytes($admissionPath));$sourceBytesBase64=[Convert]::ToBase64String([IO.File]::ReadAllBytes($sourcePath))
 if([string]$receipt.preparation_id-cne[string]$p.preparation_id-or[string]$source.preparation_id-cne[string]$p.preparation_id-or[string]$receipt.source_composition.path-cne[string]$p.source_composition_path-or[string]$receipt.source_composition.sha256-cne$sourceCanonicalJsonSha256-or[string]$p.source_composition_sha256-cne$sourceRawFileSha256-or[string]$intent.transaction_id-cne$tx-or[string]$completion.transaction_id-cne$tx-or[string]$completion.intent_sha256-cne(Get-MorphospaceFileSha256 $intentPath)-or$receiptArtifact.Count-ne1-or$sourceArtifact.Count-ne1-or[string]$receiptArtifact[0].sha256-cne$receiptCanonicalJsonSha256-or[string]$sourceArtifact[0].sha256-cne$sourceCanonicalJsonSha256-or[string]$receiptArtifact[0].bytes_base64-cne$receiptBytesBase64-or[string]$sourceArtifact[0].bytes_base64-cne$sourceBytesBase64){throw 'Prepared-envelope artifact provenance is not exact.'}
 if([string]$intent.target.project.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $project)-or[string]$intent.target.feature_lock.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $lock)-or[string]$completion.target_project_sha256-cne[string]$intent.target.project.sha256-or[string]$completion.target_feature_lock_sha256-cne[string]$intent.target.feature_lock.sha256-or[string]$completion.target_state_sha256-cne[string]$intent.target.state.sha256){throw 'Prepared-envelope completion target bytes drifted.'};if($Phase-ceq'Admission'-and[string]$intent.target.state.sha256-cne(Get-MorphospaceCanonicalJsonSha256 $state)){throw 'Prepared-envelope admission state drifted before unit admission.'}
 $events=@(Get-Content -LiteralPath (Resolve-MorphospaceWorkspacePath $workspace 'iteration-events.jsonl' -RequireLeaf)|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json});$event=@($events|Where-Object{[string]$_.event_id-ceq[string]$completion.event_id});if($event.Count-ne1-or[string]$event[0].project_id-cne[string]$Admission.project_id-or[string]$event[0].unit_id-cne[string]$receipt.predecessor_unit_id-or[string]$event[0].event_id-cne[string]$intent.event.event_id){throw 'Prepared-envelope event provenance is invalid.'}
 return [pscustomobject]@{receipt=$receipt;intent=$intent;completion=$completion;source_lock=$source;project=$project;feature_lock=$lock;state=$state}
}
Export-ModuleMember -Function Test-MorphospacePreparedDevelopmentEnvelope
