Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$script:RepreparationProtocolModule=Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceProtocolCommon.psm1') -PassThru
Import-Module (Join-Path $PSScriptRoot 'lib/MorphospaceRepreparationHistory.psm1')
$script:RepreparationPreparationModule=Import-Module (Join-Path $PSScriptRoot 'DevelopmentEnvelopePreparation.psm1') -PassThru
$script:RepreparationGitInvoker={param([string]$Root,[string[]]$Arguments)$output=@(& git -C $Root @Arguments 2>&1);[pscustomobject]@{exit_code=$LASTEXITCODE;output=$output}}


function Get-RepreparationFileHash { param([string]$Path) Get-MorphospaceFileSha256 $Path }

function Copy-RepreparationValue { param([object]$Value) $Value|ConvertTo-Json -Depth 64|ConvertFrom-Json -DateKind String }


function Assert-RepreparationSchema { param([string]$Root,[string]$Path,[string]$Name,[string]$Message) if(-not(Test-Json -Json (Get-Content -Raw -LiteralPath $Path) -Schema (Get-RepreparationLocalSchema $Root $Name))){throw $Message} }



function Get-RepreparationRepositoryMapIndex {
    param([object]$Document)
    $map=@{};foreach($entry in @($Document.repositories)){$id=[string]$entry.repo_id;if($map.ContainsKey($id)){throw "Repreparation repository map repeats '$id'."};$map[$id]=$entry};$map
}

function Get-RepreparationArtifact { param([string]$Path,[object]$Value) [byte[]]$bytes=ConvertTo-MorphospaceProtocolJsonBytes $Value;[pscustomobject][ordered]@{path=$Path;sha256=(Get-RepreparationBytesHash $bytes);bytes_base64=[Convert]::ToBase64String($bytes)} }

function Test-RepreparationOwnedDirtPath {
    param([string]$Path,[string]$RepositoryMapPath='repository-map.json')
    $p=$Path.Replace('\','/');$mapPath=$RepositoryMapPath.Replace('\','/')
    return $p-ceq$mapPath -or $p-cmatch '^(project\.spec\.json|feature\.lock\.json|workspace\.state\.json|iteration-events\.jsonl)$' -or
        $p-cmatch '^iteration-units/[a-z0-9][a-z0-9-]{1,127}\.json$' -or
        $p-cmatch '^receipts/(?:transactions/)?[a-z0-9][a-z0-9.-]{1,191}\.json$' -or
        $p-cmatch '^source-composition\.json$' -or
        $p-cmatch '^source-composition/[A-Za-z0-9._-]+\.json$' -or
        $p-cmatch '^source-composition-locks/[a-z0-9][a-z0-9-]{1,127}\.json$'
}
function Invoke-RepreparationGitRead {
    param([string]$Root,[string[]]$Arguments,[string]$Name)
    $result=&$script:RepreparationGitInvoker $Root $Arguments
    if($null-eq$result-or[int]$result.exit_code-ne0){throw "Repreparation repository Git $Name readback failed."}
    @($result.output|ForEach-Object{[string]$_})
}
function Get-RepreparationGitScalar {
    param([string]$Root,[string[]]$Arguments,[string]$Name,[string]$Pattern)
    $rows=@(Invoke-RepreparationGitRead $Root $Arguments $Name)
    if($rows.Count-ne1){throw "Repreparation repository Git $Name readback has an invalid stdout shape."}
    $value=$rows[0].Trim();if(-not$value-or($Pattern-and$value-cnotmatch$Pattern)){throw "Repreparation repository Git $Name readback has an invalid value."};$value
}
function Get-RepreparationWorkspacePrefix {
    param([string]$Workspace,[string]$RepositoryRoot)
    $workspacePath=[IO.Path]::GetFullPath($Workspace).TrimEnd('\','/');$repositoryPath=[IO.Path]::GetFullPath($RepositoryRoot).TrimEnd('\','/')
    if($workspacePath.Equals($repositoryPath,[StringComparison]::OrdinalIgnoreCase)){return ''}
    $prefix=$repositoryPath+[IO.Path]::DirectorySeparatorChar
    if(-not$workspacePath.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw 'Repreparation planning repository does not contain the exact workspace.'}
    $workspacePath.Substring($prefix.Length).Replace('\','/').TrimEnd('/')+'/'
}
function Add-RepreparationResumeDirtBinding {
    param([hashtable]$Bindings,[string]$Path,[string]$Status,[string]$Sha256)
    if($Bindings.ContainsKey($Path)){throw "Repreparation resume binding repeats transaction path '$Path'."}
    $Bindings[$Path]=[pscustomobject]@{status=$Status;sha256=$Sha256}
}
function Get-RepreparationResumeDirtBindings {
    param([string]$Workspace,[string]$RepoRoot,[object]$Intent,[object[]]$AllowedWorkflowDirt)
    $bindings=@{};if($null-eq$Intent){return $bindings}
    $intentCreatedAt=Test-MorphospaceStrictUtcTimestamp ([string]$Intent.created_at)
    $allowedByPath=@{};foreach($row in @($AllowedWorkflowDirt)){$path=[string]$row.path;if(-not$allowedByPath.ContainsKey($path)){$allowedByPath[$path]=$row}}
    $transactionId=[string]$Intent.transaction_id;$intentRelative="receipts/transactions/$transactionId.intent.json";$intentPath=Get-RepreparationPath $Workspace $intentRelative
    [byte[]]$canonicalIntent=ConvertTo-MorphospaceProtocolJsonBytes $Intent
    if((Get-RepreparationFileHash $intentPath)-cne(Get-RepreparationBytesHash $canonicalIntent)-or[IO.FileInfo]::new($intentPath).Length-ne$canonicalIntent.Length){throw 'Existing repreparation intent is not canonical byte-exact protocol JSON.'}
    Add-RepreparationResumeDirtBinding $bindings $intentRelative '??' (Get-RepreparationBytesHash $canonicalIntent)
    foreach($artifact in @($Intent.artifacts)){
        try{[byte[]]$bytes=[Convert]::FromBase64String([string]$artifact.bytes_base64)}catch{throw "Repreparation intent artifact '$([string]$artifact.path)' is not base64."}
        if([Convert]::ToBase64String($bytes)-cne[string]$artifact.bytes_base64-or(Get-RepreparationBytesHash $bytes)-cne[string]$artifact.sha256){throw "Repreparation intent artifact '$([string]$artifact.path)' is not byte/hash exact."}
        Add-RepreparationResumeDirtBinding $bindings ([string]$artifact.path) '??' ([string]$artifact.sha256)
    }
    foreach($name in @('project','feature_lock','state')){$target=$Intent.target.$name;[byte[]]$bytes=ConvertTo-MorphospaceProtocolJsonBytes $target.document;if((Get-RepreparationHash $target.document)-cne[string]$target.sha256){throw "Repreparation intent target $name hash is invalid."};$status=if($allowedByPath.ContainsKey([string]$target.path)){[string]$allowedByPath[[string]$target.path].status}else{' M'};Add-RepreparationResumeDirtBinding $bindings ([string]$target.path) $status (Get-RepreparationBytesHash $bytes)}
    [byte[]]$ledgerBytes=[IO.File]::ReadAllBytes((Get-RepreparationPath $Workspace 'iteration-events.jsonl'));$prefixLength=[int]$Intent.pre.events.length;if($ledgerBytes.Length-lt$prefixLength){throw 'Repreparation ledger truncated before resume binding.'};[byte[]]$prefix=[byte[]]::new($prefixLength);if($prefixLength){[Array]::Copy($ledgerBytes,0,$prefix,0,$prefixLength)};if((Get-RepreparationBytesHash $prefix)-cne[string]$Intent.pre.events.sha256){throw 'Repreparation ledger prefix differs before resume binding.'};[byte[]]$eventBytes=[Text.UTF8Encoding]::new($false,$true).GetBytes((ConvertTo-MorphospaceCanonicalJson $Intent.event)+"`n");[byte[]]$targetLedger=[byte[]]::new($prefix.Length+$eventBytes.Length);[Array]::Copy($prefix,0,$targetLedger,0,$prefix.Length);[Array]::Copy($eventBytes,0,$targetLedger,$prefix.Length,$eventBytes.Length);$ledgerStatus=if($allowedByPath.ContainsKey('iteration-events.jsonl')){[string]$allowedByPath['iteration-events.jsonl'].status}else{' M'};Add-RepreparationResumeDirtBinding $bindings 'iteration-events.jsonl' $ledgerStatus (Get-RepreparationBytesHash $targetLedger)
    $completionRelative="receipts/transactions/$transactionId.completion.json";$completionPath=Get-RepreparationPath $Workspace $completionRelative
    if([IO.File]::Exists($completionPath)){
        Assert-RepreparationSchema $RepoRoot $completionPath 'development-envelope-repreparation-completion-v1.schema.json' 'Existing repreparation completion is invalid.';$completion=Read-MorphospaceProtocolJson $completionPath
        $completionAt=Test-MorphospaceStrictUtcTimestamp ([string]$completion.completed_at);if($completionAt-lt$intentCreatedAt){throw 'Existing repreparation completion predates its intent.'}
        $recoveryArtifact=@($Intent.artifacts|Where-Object{[string]$_.path-ceq[string]$Intent.event.receipts[0]});if($recoveryArtifact.Count-ne1-or[string]$completion.transaction_id-cne$transactionId-or[string]$completion.status-cne'committed'-or[string]$completion.intent_sha256-cne(Get-RepreparationFileHash $intentPath)-or[string]$completion.target_project_sha256-cne[string]$Intent.target.project.sha256-or[string]$completion.target_state_sha256-cne[string]$Intent.target.state.sha256-or[string]$completion.target_feature_lock_sha256-cne[string]$Intent.target.feature_lock.sha256-or[string]$completion.repreparation_receipt_sha256-cne[string]$recoveryArtifact[0].sha256-or[string]$completion.event_id-cne[string]$Intent.event.event_id){throw 'Existing repreparation completion conflicts with the pending intent.'}
        [byte[]]$completionBytes=ConvertTo-MorphospaceProtocolJsonBytes $completion;if((Get-RepreparationFileHash $completionPath)-cne(Get-RepreparationBytesHash $completionBytes)-or[IO.FileInfo]::new($completionPath).Length-ne$completionBytes.Length){throw 'Existing repreparation completion is not canonical byte-exact protocol JSON.'};Add-RepreparationResumeDirtBinding $bindings $completionRelative '??' (Get-RepreparationBytesHash $completionBytes)
    }
    $bindings
}
function Get-RepreparationSourceComposition {
    param([string]$Workspace,[object]$Recovery,[hashtable]$Map,[AllowNull()][object]$OriginalSource,[hashtable]$TransactionBindings=@{},[switch]$Resume)
    $allowed=@{};foreach($row in @($Recovery.allowed_workflow_dirt)){$key=([string]$row.repo_id)+'|'+([string]$row.path);if($allowed.ContainsKey($key)){throw 'Repreparation repeats an allowed workflow-dirt identity.'};if(-not(Test-RepreparationOwnedDirtPath ([string]$row.path) ([string]$Recovery.expected.repository_map_path))){throw "Repreparation workflow dirt '$([string]$row.path)' is outside the closed workflow-owned surface."};$allowed[$key]=$row}
    $observed=@{};$records=[Collections.Generic.List[object]]::new();$leaves=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    foreach($id in @($Recovery.envelope.source_composition.repository_ids|Sort-Object -Unique)){
        if(-not$Map.ContainsKey([string]$id)){throw "Repreparation source repository '$id' is unmapped."};$entry=$Map[[string]$id];$root=[IO.Path]::GetFullPath([string]$entry.path);if(-not[IO.Directory]::Exists($root)){throw "Repreparation mapped repository '$id' is unavailable."}
        $workspacePrefix=if([string]$entry.role-ceq'planning'){Get-RepreparationWorkspacePrefix $Workspace $root}else{$null}
        $commit=(Get-RepreparationGitScalar $root @('rev-parse','HEAD') 'commit' '^[0-9a-fA-F]{40}$').ToLowerInvariant();$tree=(Get-RepreparationGitScalar $root @('rev-parse','HEAD^{tree}') 'tree' '^[0-9a-fA-F]{40}$').ToLowerInvariant();$branchValue=Get-RepreparationGitScalar $root @('rev-parse','--abbrev-ref','HEAD') 'branch' '^(?:HEAD|[^\x00-\x20~^:?*\\]+(?:/[^\x00-\x20~^:?*\\]+)*)$';$branch=if($branchValue-ceq'HEAD'){$null}else{$branchValue}
        $dirt=[Collections.Generic.List[object]]::new();$statusRows=@(Invoke-RepreparationGitRead $root @('status','--porcelain=v1','--untracked-files=all') 'status');foreach($lineValue in $statusRows){$line=[string]$lineValue;if($line.Length-lt4-or$line.Contains(' -> ') -or $line.Substring(3).StartsWith('"')){throw "Repreparation repository '$id' has unsupported dirt."};$status=$line.Substring(0,2);$gitPath=$line.Substring(3).Replace('\','/');if([string]$entry.role-cne'planning'){throw "Repreparation repository '$id' has unenumerated dirt '$gitPath'."};if($workspacePrefix-and-not$gitPath.StartsWith($workspacePrefix,[StringComparison]::Ordinal)){throw "Repreparation planning dirt '$gitPath' is outside exact workspace prefix '$workspacePrefix'."};$path=if($workspacePrefix){$gitPath.Substring($workspacePrefix.Length)}else{$gitPath};if(-not$path-or-not(Test-RepreparationOwnedDirtPath $path ([string]$Recovery.expected.repository_map_path))){throw "Repreparation planning dirt '$gitPath' is outside the closed workspace-owned surface."};$full=[IO.Path]::GetFullPath((Join-Path $root $gitPath));if(-not[IO.File]::Exists($full)){throw "Repreparation workflow dirt '$id/$gitPath' is not a present regular file."};$hash=Get-RepreparationFileHash $full;$key="$id|$path";if($allowed.ContainsKey($key)){ $expected=$allowed[$key];if([string]$expected.status-ceq$status-and[string]$expected.sha256-ceq$hash){$observed[$key]=$true;$dirt.Add([pscustomobject][ordered]@{path=$path;status=$status;sha256=$hash})|Out-Null;continue} };if($Resume-and$TransactionBindings.ContainsKey($path)){ $binding=$TransactionBindings[$path];if([string]$binding.status-ceq$status-and[string]$binding.sha256-ceq$hash){if($allowed.ContainsKey($key)){$expected=$allowed[$key];$observed[$key]=$true;$dirt.Add([pscustomobject][ordered]@{path=$path;status=[string]$expected.status;sha256=[string]$expected.sha256})|Out-Null};continue};throw "Repreparation transaction-owned dirt '$id/$gitPath' is not byte/status exact." };if($allowed.ContainsKey($key)){throw "Repreparation workflow dirt '$id/$gitPath' differs from its exact status/hash allowance."};throw "Repreparation repository '$id' has unenumerated dirt '$gitPath'."}
        $leaf=Split-Path -Leaf $root;if(-not$leaves.Add($leaf)){throw 'Repreparation source composition repeats a materialization leaf.'};$records.Add([pscustomobject][ordered]@{repo_id=[string]$id;role=[string]$entry.role;commit=$commit;tree=$tree;branch=$branch;materialization_path=$leaf;workspace_prefix=$workspacePrefix;worktree_state=$(if($dirt.Count){'workflow-owned-dirt'}else{'clean'});workflow_owned_dirt=@($dirt.ToArray())})|Out-Null
    }
    foreach($key in $allowed.Keys){if(-not$observed.ContainsKey($key)){throw "Repreparation allowed workflow dirt '$key' is not present exactly."}}
    if($null-ne$OriginalSource){$old=@{};foreach($row in @($OriginalSource.repositories)){$id=[string]$row.repo_id;if($old.ContainsKey($id)){throw "Repreparation original source lock repeats '$id'."};$old[$id]=$row};if($old.Count-ne$records.Count){throw 'Repreparation repository set drifted from the original source lock.'};foreach($row in @($records.ToArray())){$id=[string]$row.repo_id;if(-not$old.ContainsKey($id)){throw "Repreparation repository '$id' is absent from the original source lock."};$prior=$old[$id];foreach($field in @('role','commit','tree','branch','materialization_path')){if([string]$row.$field-cne[string]$prior.$field){throw "Repreparation repository '$id' $field drifted from the original source lock."}}}}
    $identity=[pscustomobject][ordered]@{project_id=$Recovery.project_id;preparation_id=$Recovery.preparation_id;repositories=@($records.ToArray())};$fingerprint=Get-RepreparationHash $identity
    [pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_source_composition.v2';lock_id="$($Recovery.preparation_id)-source-$($fingerprint.Substring(0,12))";preparation_id=$Recovery.preparation_id;project_id=$Recovery.project_id;fingerprint=$fingerprint;repositories=@($records.ToArray());status='locked';does_not_prove=@('Does not grant Ready, Claim, source mutation, device, remote, or publication authority.')}
}

function Get-RepreparationLedgerObservation {
    param([string]$Path,[object]$Expected)
    [byte[]]$all=[IO.File]::ReadAllBytes($Path);$length=[int64]$Expected.events_length
    if($all.LongLength-lt$length){throw 'Repreparation event ledger truncated its authenticated prefix.'}
    [byte[]]$prefix=[byte[]]::new([int]$length);if($length){[Array]::Copy($all,0,$prefix,0,[int]$length)}
    if((Get-RepreparationBytesHash $prefix)-cne[string]$Expected.events_sha256){throw 'Repreparation event ledger replaced its authenticated prefix.'}
    [byte[]]$suffix=[byte[]]::new([int]($all.LongLength-$length));if($suffix.Length){[Array]::Copy($all,[int]$length,$suffix,0,$suffix.Length)}
    try{$text=[Text.UTF8Encoding]::new($false,$true).GetString($prefix)}catch{throw 'Repreparation event ledger prefix is not strict UTF-8.'}
    if(-not$text.EndsWith("`n",[StringComparison]::Ordinal)){throw 'Repreparation event ledger prefix does not end at a record boundary.'}
    $events=@($text.Split("`n",[StringSplitOptions]::None)|Select-Object -SkipLast 1|ForEach-Object{if(-not$_){throw 'Repreparation event ledger prefix contains a blank record.'};ConvertFrom-MorphospaceProtocolJsonBytes ([Text.UTF8Encoding]::new($false,$true).GetBytes($_)) 'repreparation ledger prefix'})
    if($events.Count-lt1-or[string]$events[-1].event_id-cne[string]$Expected.event_tail_id){throw 'Repreparation event ledger prefix tail differs from its authenticated identity.'}
    [pscustomobject]@{all=$all;prefix=$prefix;suffix=$suffix;events=$events}
}
function Assert-RepreparationLedgerObservation {
    param([object]$Observation,[object]$Event)
    [byte[]]$eventBytes=[Text.UTF8Encoding]::new($false,$true).GetBytes((ConvertTo-MorphospaceCanonicalJson $Event)+"`n")
    if($Observation.suffix.Length-ne0-and((Get-RepreparationBytesHash $Observation.suffix)-cne(Get-RepreparationBytesHash $eventBytes)-or$Observation.suffix.Length-ne$eventBytes.Length)){throw 'Repreparation ledger suffix is not the exact intended event bytes.'}
    [pscustomobject]@{event_bytes=$eventBytes;appended=($Observation.suffix.Length-ne0)}
}
function Write-RepreparationBytesAtomicNoOverwrite {
    param([string]$Path,[byte[]]$Bytes)
    $parent=[IO.Path]::GetDirectoryName($Path);if(-not[IO.Directory]::Exists($parent)){[void][IO.Directory]::CreateDirectory($parent)}
    $pending="$Path.pending-$([Guid]::NewGuid().ToString('N'))";$stream=[IO.FileStream]::new($pending,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None,4096,[IO.FileOptions]::WriteThrough)
    try{$stream.Write($Bytes,0,$Bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}
    try{[IO.File]::Move($pending,$Path)}catch{throw "Repreparation atomic no-overwrite publication failed; pending bytes remain at '$pending'. $($_.Exception.Message)"}
    if((Get-RepreparationFileHash $Path)-cne(Get-RepreparationBytesHash $Bytes)){throw "Repreparation published artifact changed at '$Path'."}
}
function Assert-RepreparationFreshIdentities {
    param([string]$Workspace,[object]$Recovery,[object[]]$Events,[AllowNull()][object]$ExistingIntent)
    $eventId="$([string]$Recovery.preparation_id)-prepared";$transactionId="$([string]$Recovery.repreparation_id)-transition"
    if(@($Events|Where-Object{[string]$_.event_id-ceq$eventId}).Count){throw "Repreparation event identity '$eventId' already exists in authenticated history."}
    foreach($file in @(Get-ChildItem -LiteralPath (Get-RepreparationPath $Workspace 'iteration-units') -Filter '*.json' -File -ErrorAction Stop)){$document=Read-MorphospaceProtocolJson $file.FullName;if([string]$document.unit_id-ceq[string]$Recovery.replacement_unit_id){throw "Repreparation replacement unit identity '$([string]$Recovery.replacement_unit_id)' already exists."}}
    foreach($file in @(Get-ChildItem -LiteralPath (Get-RepreparationPath $Workspace 'receipts') -Filter '*.json' -File -ErrorAction Stop)){
        $document=Read-MorphospaceProtocolJson $file.FullName;$relative='receipts/'+$file.Name
        if($document.PSObject.Properties.Name-contains'repreparation_id'-and[string]$document.repreparation_id-ceq[string]$Recovery.repreparation_id-and-not($null-ne$ExistingIntent-and$relative-ceq"receipts/$([string]$Recovery.repreparation_id)-repreparation.json")){throw "Repreparation identity '$([string]$Recovery.repreparation_id)' already exists in another receipt."}
        if($document.PSObject.Properties.Name-contains'preparation_id'-and[string]$document.preparation_id-ceq[string]$Recovery.preparation_id-and-not($null-ne$ExistingIntent-and$relative-in@("receipts/$([string]$Recovery.preparation_id).json","receipts/$([string]$Recovery.repreparation_id)-repreparation.json"))){throw "Repreparation preparation identity '$([string]$Recovery.preparation_id)' already exists in another receipt."}
    }
    $transactions=Get-RepreparationPath $Workspace 'receipts/transactions';if([IO.Directory]::Exists($transactions)){foreach($file in @(Get-ChildItem -LiteralPath $transactions -Filter '*.json' -File)){$document=Read-MorphospaceProtocolJson $file.FullName;if($document.PSObject.Properties.Name-contains'transaction_id'-and[string]$document.transaction_id-ceq$transactionId-and-not($null-ne$ExistingIntent-and$file.Name-in@("$transactionId.intent.json","$transactionId.completion.json"))){throw "Repreparation transaction identity '$transactionId' already exists."}}}
}
function New-RepreparationPlan {
    param([string]$Workspace,[string]$RepoRoot,[string]$InputPath,[object]$Recovery,[string]$InputSha256,[string]$Timestamp,[AllowNull()][object]$ExistingIntent)
    if((Get-RepreparationFileHash $InputPath)-cne$InputSha256){throw 'Repreparation input bytes changed during planning.'}
    if([string]$Recovery.retired_unit_id-ceq[string]$Recovery.replacement_unit_id-or[string]$Recovery.preparation_id-ceq[string]$Recovery.original_preparation.preparation_id){throw 'Repreparation requires distinct retired/replacement and fresh preparation identities.'}
    $receiptRelative="receipts/$($Recovery.repreparation_id)-repreparation.json";$prepRelative="receipts/$($Recovery.preparation_id).json";$sourceRelative="source-composition-locks/$($Recovery.preparation_id).json";$transactionId="$($Recovery.repreparation_id)-transition";$intentRelative="receipts/transactions/$transactionId.intent.json";$completionRelative="receipts/transactions/$transactionId.completion.json";$eventId="$($Recovery.preparation_id)-prepared"
    if([string]$Recovery.expected.retired_unit_path-cne"iteration-units/$($Recovery.retired_unit_id).json"-or[string]$Recovery.envelope.source_composition.path-cne$sourceRelative){throw 'Repreparation current and target paths are not exact protocol-derived constants.'}
    $identitySet=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($identity in @([string]$Recovery.repreparation_id,[string]$Recovery.preparation_id,[string]$Recovery.replacement_unit_id,$transactionId,$eventId)){if(-not$identitySet.Add($identity)){throw 'Repreparation fresh identities are not pairwise distinct.'}}
    if(Test-Path (Get-RepreparationPath $Workspace "iteration-units/$($Recovery.replacement_unit_id).json")){throw 'Repreparation replacement unit identity must remain absent for later ordinary admission.'}
    $projectPath=Get-RepreparationPath $Workspace 'project.spec.json';$statePath=Get-RepreparationPath $Workspace 'workspace.state.json';$lockPath=Get-RepreparationPath $Workspace 'feature.lock.json';$unitPath=Get-RepreparationPath $Workspace ([string]$Recovery.expected.retired_unit_path);$eventsPath=Get-RepreparationPath $Workspace 'iteration-events.jsonl'
    $projectSnapshot=Read-RepreparationJsonSnapshot $projectPath 'Repreparation current project' $RepoRoot 'project-spec-v2.schema.json' 'Repreparation current project is invalid.'
    $stateSnapshot=Read-RepreparationJsonSnapshot $statePath 'Repreparation current workspace state' $RepoRoot 'workspace-state-v2.schema.json' 'Repreparation current workspace state is invalid.'
    $lockSnapshot=Read-RepreparationJsonSnapshot $lockPath 'Repreparation current feature lock' $RepoRoot 'feature-lock-v2.schema.json' 'Repreparation current feature lock is invalid.'
    $unitSnapshot=Read-RepreparationJsonSnapshot $unitPath 'Repreparation retired unit' $RepoRoot 'iteration-unit.schema.json' 'Repreparation retired unit is invalid.' ([string]$Recovery.expected.retired_unit_raw_sha256)
    $currentProject=$projectSnapshot.document;$currentState=$stateSnapshot.document;$currentLock=$lockSnapshot.document;$unit=$unitSnapshot.document
    if((Get-RepreparationHash $unit)-cne[string]$Recovery.expected.retired_unit_sha256){throw 'Repreparation retired-unit CAS is stale.'}
    $ledger=Get-RepreparationLedgerObservation $eventsPath $Recovery.expected
    Assert-RepreparationFreshIdentities $Workspace $Recovery @($ledger.events) $ExistingIntent
    foreach($identity in @([string]$Recovery.repreparation_id,[string]$Recovery.preparation_id,[string]$Recovery.replacement_unit_id,$transactionId,$eventId)){if($identity-ceq[string]$Recovery.original_preparation.preparation_id-or@($ledger.events|Where-Object{[string]$_.event_id-ceq$identity}).Count){throw "Repreparation fresh identity '$identity' reuses authenticated history."}}
    if($null-eq$ExistingIntent){foreach($path in @($receiptRelative,$prepRelative,$sourceRelative,$intentRelative,$completionRelative)){if([IO.File]::Exists((Get-RepreparationPath $Workspace $path))){throw "Repreparation fresh output '$path' already exists."}}}
    $preProject=if($null-ne$ExistingIntent){$ExistingIntent.pre.project.document}else{$currentProject};$preState=if($null-ne$ExistingIntent){$ExistingIntent.pre.state.document}else{$currentState};$preLock=if($null-ne$ExistingIntent){$ExistingIntent.pre.feature_lock.document}else{$currentLock}
    foreach($item in @(@{name='project';document=$preProject;expected=$Recovery.expected.project_sha256;schema='project-spec-v2.schema.json'},@{name='state';document=$preState;expected=$Recovery.expected.state_sha256;schema='workspace-state-v2.schema.json'},@{name='feature lock';document=$preLock;expected=$Recovery.expected.feature_lock_sha256;schema='feature-lock-v2.schema.json'})){if((Get-RepreparationHash $item.document)-cne[string]$item.expected){throw "Repreparation authenticated pre-$($item.name) differs from input CAS."};Assert-RepreparationObjectSchema $RepoRoot $item.document $item.schema "Repreparation authenticated pre-$($item.name) is invalid."}
    if([string]$preProject.project_id-cne[string]$Recovery.project_id-or[string]$preState.project_id-cne[string]$Recovery.project_id-or[string]$unit.unit_id-cne[string]$Recovery.retired_unit_id-or[string]$unit.status-cne'superseded'-or$null-ne$preState.current_unit-or$null-ne$preState.next_ready_unit){throw 'Repreparation requires the exact idle retired-unit preimage.'}
    $history=Assert-RepreparationHistoricalSuffix $Workspace $RepoRoot $Recovery @($ledger.events) $unit
    $repositoryMapRelative=[string]$history.live.repository_map_path;if([string]$Recovery.expected.repository_map_path-cne$repositoryMapRelative-or[string]$Recovery.expected.repository_map_sha256-cne[string]$history.live.repository_map_sha256){throw 'Repreparation repository-map path or SHA-256 does not match the authenticated original preparation.'}
    $mapPath=Get-RepreparationPath $Workspace $repositoryMapRelative;$mapSnapshot=Read-RepreparationJsonSnapshot $mapPath 'Repreparation repository map' $RepoRoot 'repository-map.schema.json' 'Repreparation repository map is invalid.' ([string]$Recovery.expected.repository_map_sha256);$mapDoc=$mapSnapshot.document
    $pathSet=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase);foreach($path in @('project.spec.json','feature.lock.json','workspace.state.json',$repositoryMapRelative,'iteration-events.jsonl',[string]$Recovery.expected.retired_unit_path,"iteration-units/$($Recovery.replacement_unit_id).json",$receiptRelative,$prepRelative,$sourceRelative,$intentRelative,$completionRelative)){if(-not$pathSet.Add($path)){throw 'Repreparation control, unit, transaction, and artifact paths are not pairwise distinct.'}}
    $historyMismatches=[Collections.Generic.List[string]]::new();if((Get-RepreparationHash $preProject)-cne[string]$history.live.project_sha256){$historyMismatches.Add('project')};if((Get-RepreparationHash $preLock)-cne[string]$history.live.feature_lock_sha256){$historyMismatches.Add('feature-lock')};if([string]$mapSnapshot.sha256-cne[string]$history.live.repository_map_sha256){$historyMismatches.Add('repository-map')};if((Get-RepreparationHash $preState)-cne[string]$history.live.state_sha256){$historyMismatches.Add('state')};if($historyMismatches.Count){throw "Repreparation live owner preimages do not match the authenticated preparation-to-retirement history: $($historyMismatches -join ', ')."}
    $preserved=@($history.preserved);$preserved+=,[pscustomobject][ordered]@{path=[string]$Recovery.expected.retired_unit_path;sha256=[string]$unitSnapshot.sha256}
    $map=Get-RepreparationRepositoryMapIndex $mapDoc
    $shim=[pscustomobject]@{project_id=$Recovery.project_id;envelope=$Recovery.envelope};$prepModule=$script:RepreparationPreparationModule;$currentRegistry=&$prepModule {param($project,$value)Get-PreparationModuleRegistry $project $value} $preProject $preLock
    if((Test-MorphospaceFeatureLockFingerprint $preLock)-and(Get-RepreparationHash $preState.module_registry)-ceq(Get-RepreparationHash $currentRegistry)){throw 'Repreparation is reserved for an exact lock-fingerprint or module-registry defect after retirement.'}
    if($null-eq$Recovery.envelope.PSObject.Properties['schema_pin_revision']){throw 'Repreparation requires the adopted Work Environment schema-pin revision.'};$targetState=&$prepModule {param($p,$project,$lock,$state)Get-PreparationTargetState $p $project $lock $state} $shim $preProject $preLock $preState;$targetState.last_event_id=$eventId
    &$prepModule {param($current,$target,$advance)Assert-PreparationAdditiveProject $current $target $advance} $preProject $Recovery.envelope.project $true;&$prepModule {param($rows,$project,$map)Assert-PreparationRoots $rows $project $map} @($Recovery.envelope.owner_repositories) $Recovery.envelope.project $map;&$prepModule {param($p,$project,$lock)Assert-PreparationEnvelope $p $project $lock} $shim $preProject $preLock;&$prepModule {param($p,$l,$s)Assert-PreparationLockAndRegistry $p $l $s 'target'} $Recovery.envelope.project $Recovery.envelope.feature_lock $targetState
    $ownerIds=@($Recovery.envelope.owner_repositories|ForEach-Object{[string]$_.repo_id}|Sort-Object -Unique);foreach($set in @(@($Recovery.envelope.source_composition.repository_ids|ForEach-Object{[string]$_}|Sort-Object -Unique),@($map.Keys|Sort-Object -Unique),@($Recovery.envelope.project.repositories|ForEach-Object{[string]$_.repo_id}|Sort-Object -Unique))){if($set.Count-ne$ownerIds.Count-or@($ownerIds|Where-Object{$set-cnotcontains$_}).Count){throw 'Repreparation owner, source-lock, project, and repository-map identities must agree exactly.'}}
    Assert-RepreparationObjectSchema $RepoRoot $Recovery.envelope.project 'project-spec-v2.schema.json' 'Repreparation target project is invalid.';Assert-RepreparationObjectSchema $RepoRoot $Recovery.envelope.feature_lock 'feature-lock-v2.schema.json' 'Repreparation target feature lock is invalid.';Assert-RepreparationObjectSchema $RepoRoot $targetState 'workspace-state-v2.schema.json' 'Repreparation target state is invalid.'
    $transactionPaths=@('project.spec.json','feature.lock.json','workspace.state.json','iteration-events.jsonl',$intentRelative,$completionRelative,$receiptRelative,$prepRelative,$sourceRelative)
    $resumeBindings=Get-RepreparationResumeDirtBindings $Workspace $RepoRoot $ExistingIntent @($Recovery.allowed_workflow_dirt)
    $source=Get-RepreparationSourceComposition $Workspace $Recovery $map $history.source $resumeBindings -Resume:($null-ne$ExistingIntent);Assert-RepreparationObjectSchema $RepoRoot $source 'development-envelope-source-composition-v2.schema.json' 'Repreparation source lock is invalid.'
    [byte[]]$sourceBytes=ConvertTo-MorphospaceProtocolJsonBytes $source;$sourceRawSha=Get-RepreparationBytesHash $sourceBytes;$historyIdentity=[pscustomobject][ordered]@{retirement=$Recovery.retirement;original_preparation=$Recovery.original_preparation;preserved_evidence=$preserved};$historySha=Get-RepreparationHash $historyIdentity
    $recoveryReceipt=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_repreparation_receipt.v1';repreparation_id=$Recovery.repreparation_id;preparation_id=$Recovery.preparation_id;project_id=$Recovery.project_id;retired_unit_id=$Recovery.retired_unit_id;replacement_unit_id=$Recovery.replacement_unit_id;input_sha256=$InputSha256;source_composition=[pscustomobject][ordered]@{path=$sourceRelative;sha256=$sourceRawSha};history_sha256=$historySha;retirement=$Recovery.retirement;original_preparation=$Recovery.original_preparation;preserved_evidence=$preserved;does_not_prove=@('Does not amend old evidence or grant Ready, Claim, source mutation, device, remote, or publication authority.')}
    $prepReceipt=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_preparation_receipt.v1';preparation_id=$Recovery.preparation_id;project_id=$Recovery.project_id;predecessor_unit_id=$Recovery.retired_unit_id;input_sha256=$InputSha256;envelope=$Recovery.envelope;project_sha256=(Get-RepreparationHash $Recovery.envelope.project);feature_lock_sha256=(Get-RepreparationHash $Recovery.envelope.feature_lock);source_composition=[pscustomobject]@{path=$sourceRelative;sha256=(Get-RepreparationHash $source)};does_not_prove=@('Recovery preparation does not admit the distinct replacement unit or grant Ready, Claim, source mutation, device, remote, or publication authority.')}
    $createdAt=if($null-ne$ExistingIntent){[string]$ExistingIntent.created_at}else{$Timestamp};$event=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.iteration_event.v1';event_id=$eventId;sequence=[int]$ledger.events[-1].sequence+1;timestamp=$createdAt;project_id=$Recovery.project_id;unit_id=$Recovery.retired_unit_id;event_type='decision';summary='Reprepared a corrected development envelope after exact proposed-unit retirement; separate ordinary admission remains required.';receipts=@($receiptRelative,$prepRelative)}
    Assert-RepreparationObjectSchema $RepoRoot $recoveryReceipt 'development-envelope-repreparation-receipt-v1.schema.json' 'Repreparation derived recovery receipt is invalid.';Assert-RepreparationObjectSchema $RepoRoot $prepReceipt 'development-envelope-preparation-receipt-v1.schema.json' 'Repreparation derived preparation receipt is invalid.';Assert-RepreparationObjectSchema $RepoRoot $event 'iteration-event.schema.json' 'Repreparation derived event is invalid.'
    $artifacts=@(Get-RepreparationArtifact $receiptRelative $recoveryReceipt;Get-RepreparationArtifact $prepRelative $prepReceipt;Get-RepreparationArtifact $sourceRelative $source)
    $intent=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_repreparation_intent.v1';transaction_id=$transactionId;created_at=$createdAt;input_sha256=$InputSha256;pre=[pscustomobject]@{project=[pscustomobject]@{path='project.spec.json';sha256=(Get-RepreparationHash $preProject);document=$preProject};state=[pscustomobject]@{path='workspace.state.json';sha256=(Get-RepreparationHash $preState);document=$preState};feature_lock=[pscustomobject]@{path='feature.lock.json';sha256=(Get-RepreparationHash $preLock);document=$preLock};retired_unit=[pscustomobject]@{path=[string]$Recovery.expected.retired_unit_path;sha256=(Get-RepreparationHash $unit);raw_sha256=[string]$unitSnapshot.sha256};repository_map=[pscustomobject]@{path=$repositoryMapRelative;sha256=[string]$mapSnapshot.sha256};events=[pscustomobject]@{path='iteration-events.jsonl';sha256=[string]$Recovery.expected.events_sha256;length=[int64]$Recovery.expected.events_length;tail_id=[string]$Recovery.expected.event_tail_id}};target=[pscustomobject]@{project=[pscustomobject]@{path='project.spec.json';sha256=(Get-RepreparationHash $Recovery.envelope.project);document=$Recovery.envelope.project};state=[pscustomobject]@{path='workspace.state.json';sha256=(Get-RepreparationHash $targetState);document=$targetState};feature_lock=[pscustomobject]@{path='feature.lock.json';sha256=(Get-RepreparationHash $Recovery.envelope.feature_lock);document=$Recovery.envelope.feature_lock}};source_composition=$source;allowed_workflow_dirt=@($Recovery.allowed_workflow_dirt);artifacts=$artifacts;event=$event;preserved_evidence=$preserved;status='prepared'}
    Assert-RepreparationObjectSchema $RepoRoot $intent 'development-envelope-repreparation-intent-v1.schema.json' 'Repreparation derived intent is invalid.';[byte[]]$intentBytes=ConvertTo-MorphospaceProtocolJsonBytes $intent;$eventObservation=Assert-RepreparationLedgerObservation $ledger $event
    if($null-ne$ExistingIntent-and((Get-RepreparationHash $ExistingIntent)-cne(Get-RepreparationHash $intent)-or(Get-RepreparationFileHash (Get-RepreparationPath $Workspace $intentRelative))-cne(Get-RepreparationBytesHash $intentBytes))){throw 'Existing repreparation intent differs from the fully recomputed deterministic plan.'}
    [pscustomobject]@{intent=$intent;intent_bytes=$intentBytes;input=$InputPath;input_sha256=$InputSha256;recovery=$Recovery;map=$map;original_source=$history.source;transaction_paths=$transactionPaths;paths=[pscustomobject]@{intent=$intentRelative;completion=$completionRelative;receipt=$receiptRelative;preparation=$prepRelative;source=$sourceRelative;events='iteration-events.jsonl'};ledger=$ledger;event_observation=$eventObservation}
}
function Assert-RepreparationCompletion {
    param([object]$Plan,[string]$RepoRoot,[string]$Workspace,[string]$Path)
    $completionSnapshot=Read-RepreparationJsonSnapshot $Path 'Repreparation completion' $RepoRoot 'development-envelope-repreparation-completion-v1.schema.json' 'Repreparation completion is invalid.';$completion=$completionSnapshot.document;$intent=$Plan.intent;$recoveryArtifact=@($intent.artifacts|Where-Object{[string]$_.path-ceq[string]$Plan.paths.receipt})
    if($recoveryArtifact.Count-ne1-or[string]$completion.transaction_id-cne[string]$intent.transaction_id-or[string]$completion.status-cne'committed'-or[string]$completion.intent_sha256-cne(Get-RepreparationFileHash (Get-RepreparationPath $Workspace $Plan.paths.intent))-or[string]$completion.target_project_sha256-cne[string]$intent.target.project.sha256-or[string]$completion.target_state_sha256-cne[string]$intent.target.state.sha256-or[string]$completion.target_feature_lock_sha256-cne[string]$intent.target.feature_lock.sha256-or[string]$completion.repreparation_receipt_sha256-cne[string]$recoveryArtifact[0].sha256-or[string]$completion.event_id-cne[string]$intent.event.event_id){throw 'Repreparation completion conflicts with its exact transaction, targets, receipt, or event.'}
}
function Assert-RepreparationPlanBeforeMutation {
    param([object]$Plan,[string]$RepoRoot,[string]$Workspace)
    $intent=$Plan.intent;if((Get-RepreparationFileHash $Plan.input)-cne[string]$Plan.input_sha256){throw 'Repreparation input changed after plan derivation.'}
    $intentPath=Get-RepreparationPath $Workspace $Plan.paths.intent;if(-not[IO.File]::Exists($intentPath)-or(Get-RepreparationFileHash $intentPath)-cne(Get-RepreparationBytesHash $Plan.intent_bytes)-or[IO.FileInfo]::new($intentPath).Length-ne$Plan.intent_bytes.Length){throw 'Published repreparation intent is not byte-exact with the deterministic plan.'}
    foreach($e in @($intent.preserved_evidence)){if((Get-RepreparationFileHash (Get-RepreparationPath $Workspace ([string]$e.path)))-cne[string]$e.sha256){throw "Repreparation preserved evidence '$([string]$e.path)' changed after intent publication."}}
    $unitPath=Get-RepreparationPath $Workspace ([string]$intent.pre.retired_unit.path);$unitSnapshot=Read-RepreparationJsonSnapshot $unitPath 'Repreparation retired unit at mutation boundary' $RepoRoot 'iteration-unit.schema.json' 'Repreparation retired unit is invalid.' ([string]$intent.pre.retired_unit.raw_sha256);if((Get-RepreparationHash $unitSnapshot.document)-cne[string]$intent.pre.retired_unit.sha256){throw 'Repreparation retired unit bytes changed.'}
    $mapPath=Get-RepreparationPath $Workspace ([string]$intent.pre.repository_map.path);$mapSnapshot=Read-RepreparationJsonSnapshot $mapPath 'Repreparation repository map at mutation boundary' $RepoRoot 'repository-map.schema.json' 'Repreparation repository map is invalid.' ([string]$intent.pre.repository_map.sha256);$map=Get-RepreparationRepositoryMapIndex $mapSnapshot.document
    $targetStatus=@{};foreach($name in @('project','state','feature_lock')){$pre=$intent.pre.$name;$target=$intent.target.$name;$path=Get-RepreparationPath $Workspace ([string]$pre.path);$snapshot=Read-RepreparationJsonSnapshot $path "Repreparation $name at mutation boundary";$hash=Get-RepreparationHash $snapshot.document;if($hash-cne[string]$pre.sha256-and$hash-cne[string]$target.sha256){throw "Repreparation $name CAS is stale or conflicting."};$targetStatus[$name]=$hash-ceq[string]$target.sha256}
    $resumeBindings=Get-RepreparationResumeDirtBindings $Workspace $RepoRoot $intent @($Plan.recovery.allowed_workflow_dirt);$source=Get-RepreparationSourceComposition $Workspace $Plan.recovery $map $Plan.original_source $resumeBindings -Resume;if((Get-RepreparationHash $source)-cne(Get-RepreparationHash $intent.source_composition)){throw 'Repreparation repository identity or workflow dirt changed after plan derivation.'}
    $ledgerExpected=[pscustomobject]@{events_sha256=[string]$intent.pre.events.sha256;events_length=[int64]$intent.pre.events.length;event_tail_id=[string]$intent.pre.events.tail_id}
    $ledger=Get-RepreparationLedgerObservation (Get-RepreparationPath $Workspace 'iteration-events.jsonl') $ledgerExpected;$eventObservation=Assert-RepreparationLedgerObservation $ledger $intent.event
    $staged=[Collections.Generic.List[object]]::new();foreach($artifact in @($intent.artifacts)){try{[byte[]]$bytes=[Convert]::FromBase64String([string]$artifact.bytes_base64)}catch{throw "Repreparation artifact '$([string]$artifact.path)' is not base64."};if([Convert]::ToBase64String($bytes)-cne[string]$artifact.bytes_base64-or(Get-RepreparationBytesHash $bytes)-cne[string]$artifact.sha256){throw "Repreparation artifact '$([string]$artifact.path)' bytes/hash binding is invalid."};$document=ConvertFrom-MorphospaceProtocolJsonBytes $bytes "repreparation artifact '$([string]$artifact.path)'";[byte[]]$canonicalBytes=ConvertTo-MorphospaceProtocolJsonBytes $document;if($canonicalBytes.Length-ne$bytes.Length-or(Get-RepreparationBytesHash $canonicalBytes)-cne[string]$artifact.sha256){throw "Repreparation artifact '$([string]$artifact.path)' is not canonical protocol JSON bytes."};$path=Get-RepreparationPath $Workspace ([string]$artifact.path);$exists=[IO.File]::Exists($path);if($exists-and((Get-RepreparationFileHash $path)-cne[string]$artifact.sha256-or[IO.FileInfo]::new($path).Length-ne$bytes.Length)){throw "Repreparation artifact '$([string]$artifact.path)' differs byte-for-byte from the intended artifact."};$staged.Add([pscustomobject]@{relative=[string]$artifact.path;path=$path;bytes=$bytes;exists=$exists})|Out-Null}
    $completionPath=Get-RepreparationPath $Workspace $Plan.paths.completion;$completed=[IO.File]::Exists($completionPath);if($completed){Assert-RepreparationCompletion $Plan $RepoRoot $Workspace $completionPath;if(@($targetStatus.Values|Where-Object{-not$_}).Count-or-not$eventObservation.appended-or@($staged|Where-Object{-not$_.exists}).Count){throw 'Repreparation completion exists without every exact committed target.'}}
    [pscustomobject]@{staged=@($staged);targets=$targetStatus;ledger=$ledger;event=$eventObservation;completed=$completed}
}
function Complete-MorphospaceDevelopmentEnvelopeRepreparation {
    param([object]$Plan,[string]$RepoRoot,[string]$Workspace,[ValidateSet('none','after-first-artifact','after-artifacts','after-project','after-lock','after-state','after-event')][string]$FaultAfter='none')
    $verified=Assert-RepreparationPlanBeforeMutation $Plan $RepoRoot $Workspace;if($verified.completed){return 'already-committed'};$intent=$Plan.intent
    $artifactIndex=0;foreach($artifact in @($verified.staged)){if(-not$artifact.exists){Write-RepreparationBytesAtomicNoOverwrite $artifact.path $artifact.bytes};$artifactIndex++;if($FaultAfter-eq'after-first-artifact'-and$artifactIndex-eq1){throw 'Injected repreparation interruption after first artifact.'}}
    if($FaultAfter-eq'after-artifacts'){throw 'Injected repreparation interruption after artifacts.'}
    foreach($name in @('project','feature_lock','state')){if(-not$verified.targets[$name]){$target=$intent.target.$name;Write-MorphospaceManagedProtocolJsonAtomic $Workspace ([string]$target.path) $target.document};if($FaultAfter-eq("after-"+$name.Replace('feature_lock','lock'))){throw "Injected repreparation interruption after $name."}}
    if(-not$verified.event.appended){$eventsPath=Get-RepreparationPath $Workspace 'iteration-events.jsonl';$stream=[IO.FileStream]::new($eventsPath,[IO.FileMode]::Append,[IO.FileAccess]::Write,[IO.FileShare]::Read,4096,[IO.FileOptions]::WriteThrough);try{$stream.Write($verified.event.event_bytes,0,$verified.event.event_bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}}
    $ledgerExpected=[pscustomobject]@{events_sha256=[string]$intent.pre.events.sha256;events_length=[int64]$intent.pre.events.length;event_tail_id=[string]$intent.pre.events.tail_id};$postLedger=Get-RepreparationLedgerObservation (Get-RepreparationPath $Workspace 'iteration-events.jsonl') $ledgerExpected;[void](Assert-RepreparationLedgerObservation $postLedger $intent.event);if($FaultAfter-eq'after-event'){throw 'Injected repreparation interruption after event.'}
    $recoveryArtifact=@($intent.artifacts|Where-Object{[string]$_.path-ceq[string]$Plan.paths.receipt});$intentAt=Test-MorphospaceStrictUtcTimestamp ([string]$intent.created_at);$completedAt=[DateTimeOffset]::UtcNow;if($completedAt-lt$intentAt){$completedAt=$intentAt};$completion=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.development_envelope_repreparation_completion.v1';transaction_id=$intent.transaction_id;completed_at=$completedAt.ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ');intent_sha256=(Get-RepreparationFileHash (Get-RepreparationPath $Workspace $Plan.paths.intent));target_project_sha256=$intent.target.project.sha256;target_state_sha256=$intent.target.state.sha256;target_feature_lock_sha256=$intent.target.feature_lock.sha256;repreparation_receipt_sha256=[string]$recoveryArtifact[0].sha256;event_id=$intent.event.event_id;status='committed'};Assert-RepreparationObjectSchema $RepoRoot $completion 'development-envelope-repreparation-completion-v1.schema.json' 'Repreparation derived completion is invalid.';Write-MorphospaceManagedProtocolJsonAtomic $Workspace $Plan.paths.completion $completion -NoOverwrite;'committed'
}
function New-RepreparationAutomationReceipt {
    param([object]$Plan,[bool]$Executed)
    [pscustomobject][ordered]@{schema='rusty.morphospace.workflow.work_unit_automation_receipt.v2';project_id=$Plan.recovery.project_id;unit_id=$Plan.recovery.retired_unit_id;action='ReprepareRetiredDevelopmentEnvelope';timestamp=[string]$Plan.intent.created_at;executed=$Executed;transition='retired-envelope-reprepared';status_before='superseded';status_after='superseded';current_unit_before=$null;current_unit_after=$null;preservation=[ordered]@{git_mutation_performed=$false;device_mutation_performed=$false;remote_mutation_performed=$false};audit_receipt=[ordered]@{path=[string]$Plan.paths.receipt;sha256=[string]$Plan.input_sha256};event_id=$(if($Executed){[string]$Plan.intent.event.event_id}else{$null})}
}
function Invoke-MorphospaceReprepareRetiredDevelopmentEnvelope {
    [CmdletBinding()]param([string]$WorkspaceRoot,[string]$DevelopmentEnvelopeRepreparation,[string]$OutPath,[string]$ExpectedDevelopmentEnvelopeRepreparationSha256='',[string]$Timestamp='',[switch]$Execute,[ValidateSet('none','after-intent','after-first-artifact','after-artifacts','after-project','after-lock','after-state','after-event')][string]$FaultAfter='none')
    $repoRoot=Split-Path $PSScriptRoot -Parent;$workspace=(Resolve-Path $WorkspaceRoot).Path;$inputPath=(Resolve-Path $DevelopmentEnvelopeRepreparation).Path;$inputSnapshot=Read-RepreparationJsonSnapshot $inputPath 'Development envelope repreparation' $repoRoot 'development-envelope-repreparation-v1.schema.json' 'Development envelope repreparation does not satisfy its closed schema.';$recovery=$inputSnapshot.document;$inputHash=[string]$inputSnapshot.sha256
    if($Execute-and-not$ExpectedDevelopmentEnvelopeRepreparationSha256){throw 'Executed repreparation requires the dry-run input SHA-256.'};if($ExpectedDevelopmentEnvelopeRepreparationSha256-and$ExpectedDevelopmentEnvelopeRepreparationSha256-cne$inputHash){throw 'Expected repreparation hash does not match input.'};if(-not$Timestamp){$Timestamp=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ')};if(-not(Test-MorphospaceStrictUtcTimestamp $Timestamp)){throw 'Repreparation timestamp must be strict UTC.'}
    $receiptRelative="receipts/$($recovery.repreparation_id)-repreparation.json";$intentRelative="receipts/transactions/$($recovery.repreparation_id)-transition.intent.json";if([IO.Path]::GetFullPath($OutPath)-cne(Get-RepreparationPath $workspace $receiptRelative)){throw "Repreparation output must be '$receiptRelative'."}
    if(-not$Execute){$existing=if(Test-Path (Get-RepreparationPath $workspace $intentRelative)){(Read-RepreparationJsonSnapshot (Get-RepreparationPath $workspace $intentRelative) 'Existing repreparation intent' $repoRoot 'development-envelope-repreparation-intent-v1.schema.json' 'Existing repreparation intent is invalid.').document}else{$null};$plan=New-RepreparationPlan $workspace $repoRoot $inputPath $recovery $inputHash $Timestamp $existing;return New-RepreparationAutomationReceipt $plan $false}
    $mutex=Enter-MorphospaceWorkspaceMutex $workspace;try{$intentPath=Get-RepreparationPath $workspace $intentRelative;$existing=if([IO.File]::Exists($intentPath)){(Read-RepreparationJsonSnapshot $intentPath 'Existing repreparation intent' $repoRoot 'development-envelope-repreparation-intent-v1.schema.json' 'Existing repreparation intent is invalid.').document}else{$null};$plan=New-RepreparationPlan $workspace $repoRoot $inputPath $recovery $inputHash $Timestamp $existing;if($null-eq$existing){if((Get-RepreparationFileHash $inputPath)-cne$inputHash){throw 'Repreparation input changed before intent publication.'};$freshMapSnapshot=Read-RepreparationJsonSnapshot (Get-RepreparationPath $workspace ([string]$plan.intent.pre.repository_map.path)) 'Repreparation repository map before intent publication' $repoRoot 'repository-map.schema.json' 'Repreparation repository map is invalid.' ([string]$plan.intent.pre.repository_map.sha256);$freshMap=Get-RepreparationRepositoryMapIndex $freshMapSnapshot.document;$freshSource=Get-RepreparationSourceComposition $workspace $recovery $freshMap $plan.original_source @{};if((Get-RepreparationHash $freshSource)-cne(Get-RepreparationHash $plan.intent.source_composition)){throw 'Repreparation source observation changed before intent publication.'};Write-MorphospaceManagedProtocolJsonAtomic $workspace $intentRelative $plan.intent -NoOverwrite;if((Get-RepreparationFileHash $intentPath)-cne(Get-RepreparationBytesHash $plan.intent_bytes)){throw 'Published repreparation intent bytes differ from the deterministic plan.'}};if($FaultAfter-eq'after-intent'){throw 'Injected repreparation interruption after intent.'};[void](Complete-MorphospaceDevelopmentEnvelopeRepreparation $plan $repoRoot $workspace -FaultAfter $FaultAfter);New-RepreparationAutomationReceipt $plan $true}finally{Exit-MorphospaceWorkspaceMutex $mutex}
}
Export-ModuleMember -Function Invoke-MorphospaceReprepareRetiredDevelopmentEnvelope
