param([switch]$SelfTest)
$ErrorActionPreference='Stop'
if(-not$SelfTest){throw 'Test-BlockedSuccessorPreparation.ps1 requires -SelfTest.'}
$repoRoot=Split-Path $PSScriptRoot -Parent
$script:blockedProtocolModule=Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceProtocolCommon.psm1') -Force -PassThru
$script:blockedTransitionModule=Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceTransitionLedger.psm1') -Force -PassThru
$script:blockedSuccessorModule=Import-Module (Join-Path $PSScriptRoot 'BlockedSuccessorPreparation.psm1') -Force -PassThru
$script:blockedAdmissionModule=Import-Module (Join-Path $PSScriptRoot 'DevelopmentUnitAdmission.psm1') -Force -PassThru
$automation=Import-Module (Join-Path $PSScriptRoot 'WorkUnitAutomation.psm1') -Force -PassThru
function Assert-Blocked([bool]$Condition,[string]$Message){if(-not$Condition){throw "Blocked-successor self-test failed: $Message"}}
function Write-BlockedJson([string]$Path,[object]$Value){[IO.Directory]::CreateDirectory((Split-Path $Path -Parent))|Out-Null;[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 100)+"`n"),[Text.UTF8Encoding]::new($false))}
function Copy-Blocked([object]$Value){$Value|ConvertTo-Json -Depth 100|ConvertFrom-Json -DateKind String}
function Get-BlockedProtocolModule{if($null-eq$script:blockedProtocolModule){throw 'MorphospaceProtocolCommon module is unavailable.'};$script:blockedProtocolModule}
function Get-MorphospaceCanonicalJsonSha256([object]$Value){$module=Get-BlockedProtocolModule;&$module {param($v)Get-MorphospaceCanonicalJsonSha256 -Value $v} $Value}
function Get-MorphospaceFileSha256([string]$Path){$module=Get-BlockedProtocolModule;&$module {param($p)Get-MorphospaceFileSha256 -Path $p} $Path}
function Read-MorphospaceProtocolJson([string]$Path){$module=Get-BlockedProtocolModule;&$module {param($p)Read-MorphospaceProtocolJson -Path $p} $Path}
function Get-BlockedTransitionModule{if($null-eq$script:blockedTransitionModule){throw 'MorphospaceTransitionLedger module is unavailable.'};$script:blockedTransitionModule}
function Start-MorphospaceTransitionLedger {
  param(
    [string]$WorkspaceRoot,[string]$TransactionId,[string]$StatePath,[string]$UnitPath,[string]$EventsPath,
    [object]$TargetState,[object]$TargetUnit,[object]$Event,
    [ValidateSet('none','after-intent','after-artifact','after-projection','after-event')][string]$FaultAfter='none',
    [string]$ExpectedPreStateSha256='',[string]$ExpectedPreUnitSha256='',[string]$ExpectedPreUnitRawSha256='',
    [string]$ExpectedStateSha256='',[string]$ExpectedUnitSha256='',[AllowNull()][string]$ExpectedEventTailId,
    [string]$ExpectedEventsSha256='',[int64]$ExpectedEventsLength=-1,[string]$ExpectedSupersededUnitSha256='',
    [object[]]$AdditionalProjections=@(),[object[]]$Artifacts=@()
  )
  $module=Get-BlockedTransitionModule
  &$module {param($arguments)Start-MorphospaceTransitionLedger @arguments} $PSBoundParameters
}
function Invoke-BlockedRetainedModuleScope {
  [CmdletBinding()]param([Parameter(Mandatory)][Management.Automation.PSModuleInfo]$Module,[Parameter(Mandatory)][scriptblock]$Script,[AllowNull()][object]$Argument)
  try{return &$Module $Script $Argument}catch{
    $record=$_;$message=[string]$record.Exception.Message;$value=$null
    if($message-match'^Cannot convert value "([^"]*)" to type'){$value=[string]$Matches[1]}
    $diagnostic=[ordered]@{
      schema='rusty.morphospace.workflow.test_module_scope_error_diagnostic.v1'
      fully_qualified_error_id=[string]$record.FullyQualifiedErrorId
      position_message=[string]$record.InvocationInfo.PositionMessage
      script_stack_trace=[string]$record.ScriptStackTrace
      exception_type=$record.Exception.GetType().FullName
      exception_message=$message
      inner_exception_type=$(if($null-ne$record.Exception.InnerException){$record.Exception.InnerException.GetType().FullName}else{$null})
      inner_exception_message=$(if($null-ne$record.Exception.InnerException){[string]$record.Exception.InnerException.Message}else{$null})
      value=$value
    }
    $diagnosticJson=$diagnostic|ConvertTo-Json -Depth 8 -Compress
    $record.Exception.Data['blocked_successor_test_module_scope_diagnostic']=$diagnosticJson
    [Console]::Error.WriteLine("BLOCKED_SUCCESSOR_TEST_MODULE_SCOPE_DIAGNOSTIC $diagnosticJson")
    throw
  }
}
function Invoke-MorphospacePrepareBlockedSuccessor {
  [CmdletBinding()]param([string]$WorkspaceRoot,[string]$BlockedSuccessorPreparation,[string]$OutPath,[string]$ExpectedBlockedSuccessorPreparationSha256='',[string]$Timestamp='',[switch]$Execute,[ValidateSet('none','after-intent','after-artifact','after-projection','after-event')][string]$FaultAfter='none')
  Invoke-BlockedRetainedModuleScope -Module $script:blockedSuccessorModule -Script {param($arguments)Invoke-MorphospacePrepareBlockedSuccessor @arguments} -Argument $PSBoundParameters
}
function Test-MorphospaceBlockedSuccessorPreparation {
  [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][object]$Admission,[ValidateSet('Admission','Freeze','Release')][string]$Phase='Admission')
  &$script:blockedSuccessorModule {param($arguments)Test-MorphospaceBlockedSuccessorPreparation @arguments} $PSBoundParameters
}
function Assert-BlockedSuccessorHistoricalCommittedTransaction {
  [CmdletBinding()]param([string]$Workspace,[object]$Request,[object]$HistoricalState)
  &$script:blockedSuccessorModule {param($arguments)Assert-BlockedSuccessorHistoricalCommittedTransaction @arguments} $PSBoundParameters
}
function Invoke-MorphospaceAdmitDevelopmentUnit {
  [CmdletBinding()]param([string]$WorkspaceRoot,[string]$DevelopmentUnitAdmission,[string]$OutPath,[string]$ExpectedDevelopmentUnitAdmissionSha256='',[string]$Timestamp='',[switch]$Execute,[ValidateSet('none','after-stage','after-intent','after-artifact','after-state','after-unit','after-event')][string]$FaultAfter='none')
  &$script:blockedAdmissionModule {param($arguments)Invoke-MorphospaceAdmitDevelopmentUnit @arguments} $PSBoundParameters
}
function Invoke-BlockedGit([string]$Path,[string[]]$Arguments){$output=@(& git -C $Path @Arguments 2>&1);if($LASTEXITCODE-ne0){throw "Blocked-successor Git fixture failed: git -C $Path $($Arguments-join' ') $($output-join' ')"};@($output|ForEach-Object{[string]$_})}
function Get-BlockedHash([object]$Value){Get-MorphospaceCanonicalJsonSha256 $Value}
$diagnosticSuccess=Invoke-BlockedRetainedModuleScope -Module $script:blockedSuccessorModule -Script {param($value)"transparent:$value"} -Argument 'success'
Assert-Blocked ([string]$diagnosticSuccess-ceq'transparent:success') 'test module-scope diagnostic wrapper changed a successful result'
$diagnosticDamage=$null;try{Invoke-BlockedRetainedModuleScope -Module $script:blockedSuccessorModule -Script {param($value)[int]$value} -Argument 'blocked-successor-diagnostic-value'|Out-Null}catch{$diagnosticDamage=$_}
Assert-Blocked ($null-ne$diagnosticDamage) 'test module-scope diagnostic wrapper did not rethrow the forced conversion error'
$diagnosticJson=[string]$diagnosticDamage.Exception.Data['blocked_successor_test_module_scope_diagnostic'];Assert-Blocked (-not[string]::IsNullOrEmpty($diagnosticJson)) 'test module-scope diagnostic wrapper omitted the preserved error record'
$diagnostic=$diagnosticJson|ConvertFrom-Json -DateKind String
Assert-Blocked ([string]$diagnosticDamage.FullyQualifiedErrorId-ceq[string]$diagnostic.fully_qualified_error_id-and[string]$diagnostic.fully_qualified_error_id-ceq'InvalidCastFromStringToInteger'-and[string]$diagnostic.exception_type-ceq'System.Management.Automation.RuntimeException'-and[string]$diagnostic.inner_exception_type-ceq'System.Management.Automation.PSInvalidCastException'-and[string]$diagnostic.value-ceq'blocked-successor-diagnostic-value'-and[string]$diagnostic.exception_message-like'*blocked-successor-diagnostic-value*'-and[string]$diagnostic.inner_exception_message-like'*blocked-successor-diagnostic-value*'-and[string]$diagnostic.position_message-like'*Test-BlockedSuccessorPreparation.ps1*'-and[string]$diagnostic.script_stack_trace-like'*Test-BlockedSuccessorPreparation.ps1*') 'test module-scope diagnostic wrapper did not preserve exact classification, owner, type, message, stack, and value'
$blockedSource=Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'BlockedSuccessorPreparation.psm1');$provenanceSource=Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'DevelopmentEnvelopeProvenance.psm1');$automationSource=Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'WorkUnitAutomation.psm1')
foreach($contract in @(
  [pscustomobject]@{source=$blockedSource;old='if(-[IO.File]::Exists($artifactPath)';new='if(-not[IO.File]::Exists($artifactPath)'},
  [pscustomobject]@{source=$blockedSource;old="if(-(`$evidence.PSObject.Properties.Name-contains'source_path')";new="if(-not(`$evidence.PSObject.Properties.Name-contains'source_path')"},
  [pscustomobject]@{source=$blockedSource;old='if(-[IO.Directory]::Exists($root))';new='if(-not[IO.Directory]::Exists($root))'},
  [pscustomobject]@{source=$blockedSource;old='if(-$leaves.Add($leaf))';new='if(-not$leaves.Add($leaf))'},
  [pscustomobject]@{source=$provenanceSource;old="if(-(`$Admission.PSObject.Properties.Name-contains'blocked_successor'))";new="if(-not(`$Admission.PSObject.Properties.Name-contains'blocked_successor'))"},
  [pscustomobject]@{source=$automationSource;old='if(-$admissionMatch.Success-or';new='if(-not$admissionMatch.Success-or'},
  [pscustomobject]@{source=$automationSource;old='if(-[bool]$observed.available-or';new='if(-not[bool]$observed.available-or'}
)){Assert-Blocked (-not$contract.source.Contains($contract.old,[StringComparison]::Ordinal)-and$contract.source.Contains($contract.new,[StringComparison]::Ordinal)) "candidate production guard did not retain its exact boolean-negation correction: $($contract.old)"}
$truthSet=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);$firstLeaf=$truthSet.Add('source');$duplicateLeaf=$truthSet.Add('source');$matchingAdmission=[regex]::Match('unit004-admission-admitted','^(?<admission>[a-z0-9][a-z0-9-]{1,127})-admitted$');$missingAdmission=[regex]::Match('not-an-admission','^(?<admission>[a-z0-9][a-z0-9-]{1,127})-admitted$')
Assert-Blocked ((-not$true)-eq$false-and(-not$false)-eq$true-and(-not$firstLeaf)-eq$false-and(-not$duplicateLeaf)-eq$true-and(-not$matchingAdmission.Success)-eq$false-and(-not$missingAdmission.Success)-eq$true) 'candidate production boolean-negation truth table is not exact'
function New-BlockedRequest([string]$Workspace,[object]$TerminalUnit,[object]$State,[string]$RepoMapPath,[string]$TerminalTransactionId,[string]$RepairPath){
  $eventsPath=Join-Path $Workspace 'iteration-events.jsonl';$events=@(Get-Content $eventsPath|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$event=$events[-1]
  $intentRelative="receipts/transactions/$TerminalTransactionId.intent.json";$completionRelative="receipts/transactions/$TerminalTransactionId.completion.json"
  [ordered]@{
    schema='rusty.morphospace.workflow.blocked_successor_preparation.v1';preparation_id='unit004-preparation';project_id='blocked-successor-test';successor_unit_id='unit004'
    terminal=[ordered]@{unit_id='unit003';unit_path='iteration-units/unit003.json';unit_raw_sha256=Get-MorphospaceFileSha256 (Join-Path $Workspace 'iteration-units\unit003.json');unit_canonical_sha256=Get-BlockedHash $TerminalUnit;candidate_freeze=$TerminalUnit.candidate_freeze;selector_binding_sha256=Get-BlockedHash $State.normal_validation_selection;checkpoint=[ordered]@{tier='standard';result='blocked';receipt_path='receipts/unit003-standard-blocked.json';receipt_sha256=Get-MorphospaceFileSha256 (Join-Path $Workspace 'receipts\unit003-standard-blocked.json')};blocker_sha256=Get-BlockedHash $State.blockers[0];event_id=[string]$event.event_id;event_sha256=Get-BlockedHash $event;transaction=[ordered]@{transaction_id=$TerminalTransactionId;intent_path=$intentRelative;intent_sha256=Get-MorphospaceFileSha256 (Join-Path $Workspace ($intentRelative-replace'/','\'));completion_path=$completionRelative;completion_sha256=Get-MorphospaceFileSha256 (Join-Path $Workspace ($completionRelative-replace'/','\'))}}
    repair=[ordered]@{repo_id='public-source';path=$RepairPath;evidence_artifact_id='compile-blocker'};source_repository_ids=@('public-source')
    expected=[ordered]@{project_sha256=Get-BlockedHash (Read-MorphospaceProtocolJson (Join-Path $Workspace 'project.spec.json'));state_sha256=Get-BlockedHash $State;feature_lock_sha256=Get-BlockedHash (Read-MorphospaceProtocolJson (Join-Path $Workspace 'feature.lock.json'));repository_map_path='repository-map.json';repository_map_sha256=Get-MorphospaceFileSha256 $RepoMapPath;events_sha256=Get-MorphospaceFileSha256 $eventsPath;events_length=([IO.FileInfo]$eventsPath).Length;event_tail_id=[string]$event.event_id}
    does_not_prove=@('Does not admit or execute the repair.')
  }
}
$temp=Join-Path ([IO.Path]::GetTempPath()) ('workenv-blocked-successor-'+[guid]::NewGuid().ToString('N'))
try{
  $workspace=Join-Path $temp 'morphospace';$source=Join-Path $temp 'public-source';[IO.Directory]::CreateDirectory((Join-Path $workspace 'iteration-units'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $workspace 'receipts'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $source 'morphospace'))|Out-Null
  [IO.File]::WriteAllText((Join-Path $source 'morphospace\old.ps1'),'old',[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $source 'morphospace\repair.ps1'),'repair',[Text.UTF8Encoding]::new($false));Invoke-BlockedGit $temp @('init',$source)|Out-Null;Invoke-BlockedGit $source @('config','user.name','Blocked Successor Test')|Out-Null;Invoke-BlockedGit $source @('config','user.email','blocked@example.invalid')|Out-Null;Invoke-BlockedGit $source @('add','.')|Out-Null;Invoke-BlockedGit $source @('commit','-m','fixture')|Out-Null;$commit=(@(Invoke-BlockedGit $source @('rev-parse','HEAD'))[0]).Trim().ToLowerInvariant();$tree=(@(Invoke-BlockedGit $source @('rev-parse','HEAD^{tree}'))[0]).Trim().ToLowerInvariant()
  $example=Join-Path $repoRoot 'examples\hello-morphospace-v2\morphospace';$project=Get-Content -Raw (Join-Path $example 'project.spec.json')|ConvertFrom-Json;$project.project_id='blocked-successor-test';$project.repositories=@([ordered]@{repo_id='public-source';role='application';path='.';allowed_paths=@('morphospace/')});$project.validation_profiles=@([ordered]@{profile_id='workflow';commands=@('fixture')})
  $featureLock=Get-Content -Raw (Join-Path $example 'feature.lock.json')|ConvertFrom-Json;$featureLock.project_id='blocked-successor-test'
  $accepted=Get-Content -Raw (Join-Path $example 'iteration-units\hello-001.json')|ConvertFrom-Json;$accepted.project_id='blocked-successor-test';$accepted.unit_id='unit001';$accepted.status='accepted';$accepted.allowed_repositories=@([ordered]@{repo_id='public-source';allowed_paths=@('morphospace/old.ps1')})
  $scope=[ordered]@{schema='rusty.morphospace.workflow.agent_scope_assessment.v1';objective='Repair one terminal compile blocker.';owner_repositories=@([ordered]@{repo_id='public-source';source_roots=@('morphospace/')});public_private_boundary='public';allowed_change_categories=@('implementation','validation');allowed_effect_categories=@('none');allowed_permission_categories=@('none');build_envelope=[ordered]@{class='product';allowed_profiles=@('workflow')};device_envelope=[ordered]@{requirement='forbidden';allowed_kinds=@()};non_scope=@('Unrelated paths.');prerequisites=@('unit001');validation_class='quick';evidence_expectations=@('Focused validation.');cleanup_expectations=@('No residue.')}
  $terminal=Copy-Blocked $accepted;$terminal.unit_id='unit003';$terminal.status='active';$terminal.prerequisites=@('unit001');$terminal.allowed_repositories=@([ordered]@{repo_id='public-source';allowed_paths=@('morphospace/old.ps1')});$terminal.change_categories=@('implementation','validation');$terminal.risk_tier='standard';$terminal.validation=@([ordered]@{profile_id='standard';command='fixture standard'});$terminal|Add-Member agent_scope_assessment ([pscustomobject]$scope)
  $freeze=[ordered]@{schema='rusty.morphospace.workflow.candidate_freeze.v1';freeze_id='unit003-freeze';project_id='blocked-successor-test';unit_id='unit003';expected=[ordered]@{project_sha256=('0'*64);state_sha256=('0'*64);unit_sha256=('0'*64);feature_lock_sha256=('0'*64);source_composition_path='source-composition/old.json';source_composition_sha256=('0'*64);repository_map_path='repository-map.json';repository_map_sha256=('0'*64);events_sha256=('0'*64);events_length=1;event_tail_id='unit003-freeze-recorded'};final_repositories=@([ordered]@{repo_id='public-source';commit=$commit;tree=$tree});changed_paths=@([ordered]@{repo_id='public-source';paths=@('morphospace/old.ps1')});cleanliness_policy='clean-only';instruction_surfaces=@([ordered]@{path='README.md';disposition='reviewed-no-change'});feature_lock=[ordered]@{revision=1;sha256=('0'*64)};effects=@('none');permissions=@('none');device_use=@('none');test_matrix=@([ordered]@{test_id='workflow';command='fixture'});cleanup_evidence=@('none');source_composition=[ordered]@{path='source-composition/old.json';sha256=('0'*64)};does_not_prove=@('Fixture freeze.')}
  Write-BlockedJson (Join-Path $workspace 'receipts\unit003-freeze.json') $freeze;$terminal|Add-Member candidate_freeze ([ordered]@{freeze_id='unit003-freeze';receipt_path='receipts/unit003-freeze.json';receipt_sha256=Get-MorphospaceFileSha256 (Join-Path $workspace 'receipts\unit003-freeze.json')})
  $selection=[ordered]@{selector_id='unit003-quick-selector';unit_id='unit003';unit_contract_sha256=('0'*64);selector_path='validation-authority/selectors/unit003.json';selector_sha256=('0'*64);tier='quick';evidence_path='evidence/unit003-quick.json';evidence_path_sha256=('0'*64)}
  $state=Get-Content -Raw (Join-Path $example 'workspace.state.json')|ConvertFrom-Json;$state.project_id='blocked-successor-test';$state.current_unit='unit003';$state.next_ready_unit=$null;$state.last_event_id='unit003-freeze-recorded';$state.last_accepted_receipt='receipts/unit001-accepted.json'
  if(-not($state.PSObject.Properties.Name-contains'normal_validation_selection')){$state|Add-Member -NotePropertyName normal_validation_selection -NotePropertyValue $null}
  if(-not($state.PSObject.Properties.Name-contains'validation_checkpoint')){$state|Add-Member -NotePropertyName validation_checkpoint -NotePropertyValue $null}
  $state.normal_validation_selection=[pscustomobject]$selection;$state.validation_checkpoint=$null;$state.blockers=@()
  Write-BlockedJson (Join-Path $workspace 'project.spec.json') $project;Write-BlockedJson (Join-Path $workspace 'feature.lock.json') $featureLock;Write-BlockedJson (Join-Path $workspace 'iteration-units\unit001.json') $accepted;Write-BlockedJson (Join-Path $workspace 'iteration-units\unit003.json') $terminal;Write-BlockedJson (Join-Path $workspace 'workspace.state.json') $state;Write-BlockedJson (Join-Path $workspace 'repository-map.json') ([ordered]@{schema='rusty.morphospace.workflow.repository_map.v1';repositories=@([ordered]@{repo_id='public-source';path=$source;role='source'})})
  $initialEvent=[ordered]@{schema='rusty.morphospace.workflow.iteration_event.v1';event_id='unit003-freeze-recorded';sequence=1;timestamp='2026-09-01T00:00:00.0000000Z';project_id='blocked-successor-test';unit_id='unit003';event_type='state-transition';summary='Fixture candidate frozen.';receipts=@('receipts/unit003-freeze.json')}
  [IO.File]::WriteAllText((Join-Path $workspace 'iteration-events.jsonl'),(($initialEvent|ConvertTo-Json -Compress)+"`n"),[Text.UTF8Encoding]::new($false))
  Write-BlockedJson (Join-Path $workspace 'receipts\terminal-compile.json') ([ordered]@{source_path='morphospace/repair.ps1';diagnostic='compile blocker'})
  $validation=[ordered]@{'$schema'='fixture';schema='rusty.morphospace.workflow.validation_receipt.v1';receipt_id='unit003-standard-blocked';project_id='blocked-successor-test';unit_id='unit003';created_at='2026-09-01T00:01:00Z';tier='standard';result='blocked';repository_revisions=@([ordered]@{repo_id='public-source';base_revision=$commit;head_revision=$commit;branch='main'});changed_paths=@([ordered]@{repo_id='public-source';path='morphospace/old.ps1'});artifacts=@([ordered]@{artifact_id='compile-blocker';kind='compile-blocker';path='terminal-compile.json';sha256=Get-MorphospaceFileSha256 (Join-Path $workspace 'receipts\terminal-compile.json')});criteria=@([ordered]@{acceptance_id='compile';status='blocked';command='fixture';evidence_refs=@('compile-blocker')});gates=@([ordered]@{gate_id='compile';status='blocked';command='fixture';evidence_refs=@('compile-blocker')});device_validation=$null};Write-BlockedJson (Join-Path $workspace 'receipts\unit003-standard-blocked.json') $validation
  $targetTerminal=Copy-Blocked $terminal;$targetTerminal.status='blocked';$targetState=Copy-Blocked $state;$targetState.current_unit=$null;$targetState.validation_checkpoint=[ordered]@{tier='standard';result='blocked';receipt='receipts/unit003-standard-blocked.json'};$targetState.blockers=@([ordered]@{blocker_id='unit003-validation-blocked';condition='Validation result is blocked in receipts/unit003-standard-blocked.json.';resume_when='Correct the failure and explicitly resume the unit.'});$targetState.last_event_id='unit003-validation-blocked-0002';$terminalEvent=[ordered]@{schema='rusty.morphospace.workflow.iteration_event.v1';event_id='unit003-validation-blocked-0002';sequence=2;timestamp='2026-09-01T00:02:00.0000000Z';project_id='blocked-successor-test';unit_id='unit003';event_type='blocker';summary='Fixture terminal blocker.';receipts=@('receipts/unit003-standard-blocked.json')};$preEvents=Join-Path $workspace 'iteration-events.jsonl';Start-MorphospaceTransitionLedger -WorkspaceRoot $workspace -TransactionId 'unit003-validation-blocked-0002-transition' -StatePath 'workspace.state.json' -UnitPath 'iteration-units/unit003.json' -EventsPath 'iteration-events.jsonl' -TargetState $targetState -TargetUnit $targetTerminal -Event ([pscustomobject]$terminalEvent) -ExpectedPreStateSha256 (Get-BlockedHash $state) -ExpectedPreUnitSha256 (Get-BlockedHash $terminal) -ExpectedEventTailId 'unit003-freeze-recorded' -ExpectedEventsSha256 (Get-MorphospaceFileSha256 $preEvents) -ExpectedEventsLength ([IO.FileInfo]$preEvents).Length|Out-Null
  $terminalState=Read-MorphospaceProtocolJson (Join-Path $workspace 'workspace.state.json');$terminalUnit=Read-MorphospaceProtocolJson (Join-Path $workspace 'iteration-units\unit003.json');$request=New-BlockedRequest $workspace $terminalUnit $terminalState (Join-Path $workspace 'repository-map.json') 'unit003-validation-blocked-0002-transition' 'morphospace/repair.ps1';$requestPath=Join-Path $temp 'prepare-blocked.json';Write-BlockedJson $requestPath $request;$out=Join-Path $workspace 'receipts\unit004-preparation.json'
  $terminalIntent=Read-MorphospaceProtocolJson (Join-Path $workspace 'receipts\transactions\unit003-validation-blocked-0002-transition.intent.json');$targetTerminalHash=Get-BlockedHash $targetTerminal;$terminalUnitHash=Get-BlockedHash $terminalUnit;$intentTerminalHash=Get-BlockedHash $terminalIntent.target.unit.document
  Assert-Blocked ($targetTerminal.PSObject.Properties.Name-contains'candidate_freeze'-and$terminalIntent.target.unit.document.PSObject.Properties.Name-contains'candidate_freeze'-and$terminalUnit.PSObject.Properties.Name-contains'candidate_freeze'-and$targetTerminalHash-ceq$intentTerminalHash-and$intentTerminalHash-ceq$terminalUnitHash-and$terminalUnitHash-ceq[string]$request.terminal.unit_canonical_sha256-and(Get-MorphospaceFileSha256 (Join-Path $workspace 'iteration-units\unit003.json'))-ceq[string]$request.terminal.unit_raw_sha256) 'terminal transition did not preserve candidate-freeze target, intent, canonical, and on-disk hash identity'
  $inputHash=Get-MorphospaceFileSha256 $requestPath
  [void](Assert-BlockedSuccessorHistoricalCommittedTransaction -Workspace $workspace -Request $request -HistoricalState $terminalState)
  foreach($historicalDamage in @('state-target','completion-binding','event-mismatch','event-position','artifact-drift')){
    $historicalWorkspace=Join-Path $temp "historical-$historicalDamage";Copy-Item $workspace $historicalWorkspace -Recurse;$historicalRequest=Copy-Blocked $request;$historicalTx=$historicalRequest.terminal.transaction;$historicalIntentPath=Join-Path $historicalWorkspace ($historicalTx.intent_path-replace'/','\');$historicalCompletionPath=Join-Path $historicalWorkspace ($historicalTx.completion_path-replace'/','\');$historicalIntent=Read-MorphospaceProtocolJson $historicalIntentPath;$historicalCompletion=Read-MorphospaceProtocolJson $historicalCompletionPath
    if($historicalDamage-ceq'state-target'){$historicalIntent.target.state.document.blockers[0].condition='Damaged historical target state.';$historicalIntent.target.state.sha256=Get-BlockedHash $historicalIntent.target.state.document;$historicalCompletion.state_sha256=$historicalIntent.target.state.sha256}
    elseif($historicalDamage-ceq'completion-binding'){$historicalCompletion.event_id='damaged-completion-event'}
    elseif($historicalDamage-ceq'event-mismatch'){$historicalIntent.event.summary='Damaged historical event summary.'}
    elseif($historicalDamage-ceq'event-position'){$historicalLedgerPath=Join-Path $historicalWorkspace 'iteration-events.jsonl';$historicalEvents=@(Get-Content $historicalLedgerPath|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$historicalEvents[-1].summary='Damaged ledger event summary.';$historicalLines=@($historicalEvents|ForEach-Object{$_|ConvertTo-Json -Depth 100 -Compress});[IO.File]::WriteAllText($historicalLedgerPath,(($historicalLines-join"`n")+"`n"),[Text.UTF8Encoding]::new($false))}
    else{$artifactBytes=[Text.UTF8Encoding]::new($false).GetBytes('historical-artifact');$artifactHash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($artifactBytes)).ToLowerInvariant();$historicalIntent.artifacts=@([pscustomobject][ordered]@{path='receipts/historical-artifact.bin';sha256=$artifactHash;bytes_base64=[Convert]::ToBase64String($artifactBytes)});[IO.File]::WriteAllText((Join-Path $historicalWorkspace 'receipts\historical-artifact.bin'),'drift',[Text.UTF8Encoding]::new($false))}
    if($historicalDamage-cne'event-position'){Write-BlockedJson $historicalIntentPath $historicalIntent;$historicalCompletion.intent.sha256=Get-MorphospaceFileSha256 $historicalIntentPath;Write-BlockedJson $historicalCompletionPath $historicalCompletion;$historicalRequest.terminal.transaction.intent_sha256=Get-MorphospaceFileSha256 $historicalIntentPath;$historicalRequest.terminal.transaction.completion_sha256=Get-MorphospaceFileSha256 $historicalCompletionPath}
    $historicalRejected=$false;try{Assert-BlockedSuccessorHistoricalCommittedTransaction -Workspace $historicalWorkspace -Request $historicalRequest -HistoricalState $terminalState|Out-Null}catch{$historicalRejected=$true};Assert-Blocked $historicalRejected "historical committed verifier accepted $historicalDamage damage"
  }
  foreach($fault in @('after-intent','after-artifact','after-projection','after-event')){
    $recoveryWorkspace=Join-Path $temp "recovery-$fault";Copy-Item $workspace $recoveryWorkspace -Recurse;$recoveryOut=Join-Path $recoveryWorkspace 'receipts\unit004-preparation.json';$faultObserved=$false
    try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $recoveryWorkspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath $recoveryOut -Timestamp '2026-09-01T00:03:00.0000000Z' -Execute -FaultAfter $fault|Out-Null}catch{$faultObserved=$_.Exception.Message-like'Injected interruption*'}
    Assert-Blocked $faultObserved "preparation did not stop at $fault"
    $recovered=Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $recoveryWorkspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath $recoveryOut -Timestamp '2026-09-01T00:03:09.0000000Z' -Execute
    $recoveryEvents=@(Get-Content (Join-Path $recoveryWorkspace 'iteration-events.jsonl')|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$ownedEvents=@($recoveryEvents|Where-Object{[string]$_.event_id-ceq'unit004-preparation-prepared'})
    $recoveryIntentPath=Join-Path $recoveryWorkspace 'receipts\transactions\unit004-preparation-prepared-transition.intent.json';$recoveryCompletionPath=Join-Path $recoveryWorkspace 'receipts\transactions\unit004-preparation-prepared-transition.completion.json';$recoverySourcePath=Join-Path $recoveryWorkspace 'source-composition\unit004-preparation.json'
    Assert-Blocked ($recovered.executed-and[string]$recovered.timestamp-ceq'2026-09-01T00:03:00.0000000Z'-and$ownedEvents.Count-eq1-and(Test-Path $recoveryOut)-and(Test-Path $recoverySourcePath)-and(Test-Path $recoveryIntentPath)-and(Test-Path $recoveryCompletionPath)-and(Get-MorphospaceFileSha256 (Join-Path $recoveryWorkspace 'iteration-units\unit003.json'))-ceq[string]$request.terminal.unit_raw_sha256) "preparation did not recover exact $fault intent"
    $stableHashes=@((Get-MorphospaceFileSha256 (Join-Path $recoveryWorkspace 'workspace.state.json'));(Get-MorphospaceFileSha256 (Join-Path $recoveryWorkspace 'iteration-events.jsonl'));(Get-MorphospaceFileSha256 $recoveryOut);(Get-MorphospaceFileSha256 $recoverySourcePath);(Get-MorphospaceFileSha256 $recoveryCompletionPath))
    $replay=Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $recoveryWorkspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath $recoveryOut -Timestamp '2026-09-01T00:03:10.0000000Z' -Execute
    $replayHashes=@((Get-MorphospaceFileSha256 (Join-Path $recoveryWorkspace 'workspace.state.json'));(Get-MorphospaceFileSha256 (Join-Path $recoveryWorkspace 'iteration-events.jsonl'));(Get-MorphospaceFileSha256 $recoveryOut);(Get-MorphospaceFileSha256 $recoverySourcePath);(Get-MorphospaceFileSha256 $recoveryCompletionPath))
    Assert-Blocked ((Get-BlockedHash $stableHashes)-ceq(Get-BlockedHash $replayHashes)-and(Get-BlockedHash $recovered)-ceq(Get-BlockedHash $replay)) "committed $fault replay was not byte-stable and idempotent"
  }
  foreach($recoveryDamage in @('request','artifact-order','target-state','terminal-bytes')){
    $damageWorkspace=Join-Path $temp "recovery-damage-$recoveryDamage";Copy-Item $workspace $damageWorkspace -Recurse;$damageOut=Join-Path $damageWorkspace 'receipts\unit004-preparation.json'
    try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $damageWorkspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath $damageOut -Timestamp '2026-09-01T00:03:00.0000000Z' -Execute -FaultAfter after-intent|Out-Null}catch{}
    $damageIntentPath=Join-Path $damageWorkspace 'receipts\transactions\unit004-preparation-prepared-transition.intent.json';$damageIntent=Read-MorphospaceProtocolJson $damageIntentPath;$damageRequestPath=$requestPath;$damageExpectedHash=$inputHash
    if($recoveryDamage-ceq'request'){$damageRequest=Copy-Blocked $request;$damageRequest.does_not_prove=@('Changed request bytes.');$damageRequestPath=Join-Path $temp 'prepare-blocked-recovery-request-drift.json';Write-BlockedJson $damageRequestPath $damageRequest;$damageExpectedHash=Get-MorphospaceFileSha256 $damageRequestPath}
    elseif($recoveryDamage-ceq'artifact-order'){$damageIntent.artifacts=@($damageIntent.artifacts[1],$damageIntent.artifacts[0]);Write-BlockedJson $damageIntentPath $damageIntent}
    elseif($recoveryDamage-ceq'target-state'){$damageIntent.target.state.document|Add-Member -NotePropertyName next_ready_unit -NotePropertyValue 'unit004' -Force;$damageIntent.target.state.sha256=Get-BlockedHash $damageIntent.target.state.document;Write-BlockedJson $damageIntentPath $damageIntent}
    else{$terminalDamagePath=Join-Path $damageWorkspace 'iteration-units\unit003.json';$terminalDamage=Read-MorphospaceProtocolJson $terminalDamagePath;$terminalDamage.status='active';Write-BlockedJson $terminalDamagePath $terminalDamage}
    $damageRejected=$false;try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $damageWorkspace -BlockedSuccessorPreparation $damageRequestPath -ExpectedBlockedSuccessorPreparationSha256 $damageExpectedHash -OutPath $damageOut -Timestamp '2026-09-01T00:03:09.0000000Z' -Execute|Out-Null}catch{$damageRejected=$true}
    Assert-Blocked ($damageRejected-and-not(Test-Path (Join-Path $damageWorkspace 'receipts\transactions\unit004-preparation-prepared-transition.completion.json'))) "recovery accepted $recoveryDamage damage or committed it"
  }
  $sourceDriftWorkspace=Join-Path $temp 'recovery-damage-source';Copy-Item $workspace $sourceDriftWorkspace -Recurse;$sourceDriftOut=Join-Path $sourceDriftWorkspace 'receipts\unit004-preparation.json';try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $sourceDriftWorkspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath $sourceDriftOut -Timestamp '2026-09-01T00:03:00.0000000Z' -Execute -FaultAfter after-intent|Out-Null}catch{};$repairSourcePath=Join-Path $source 'morphospace\repair.ps1';[IO.File]::WriteAllText($repairSourcePath,'drift',[Text.UTF8Encoding]::new($false));$sourceDriftRejected=$false;try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $sourceDriftWorkspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath $sourceDriftOut -Timestamp '2026-09-01T00:03:09.0000000Z' -Execute|Out-Null}catch{$sourceDriftRejected=$true}finally{[IO.File]::WriteAllText($repairSourcePath,'repair',[Text.UTF8Encoding]::new($false))};Assert-Blocked ($sourceDriftRejected-and-not(Test-Path (Join-Path $sourceDriftWorkspace 'receipts\transactions\unit004-preparation-prepared-transition.completion.json'))) 'pending recovery accepted source repository drift'
  $orphanWorkspace=Join-Path $temp 'recovery-orphan';Copy-Item $workspace $orphanWorkspace -Recurse;$orphanCompletion=Join-Path $orphanWorkspace 'receipts\transactions\unit004-preparation-prepared-transition.completion.json';Write-BlockedJson $orphanCompletion ([ordered]@{schema='orphan'});$orphanRejected=$false;try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $orphanWorkspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath (Join-Path $orphanWorkspace 'receipts\unit004-preparation.json') -Timestamp '2026-09-01T00:03:00.0000000Z' -Execute|Out-Null}catch{$orphanRejected=$_.Exception.Message-like'*orphaned transaction evidence*'};Assert-Blocked $orphanRejected 'preparation accepted an orphan completion without intent'
  $missingFreezeWorkspace=Join-Path $temp 'missing-candidate-freeze';Copy-Item $workspace $missingFreezeWorkspace -Recurse;$missingFreezeUnitPath=Join-Path $missingFreezeWorkspace 'iteration-units\unit003.json';$missingFreezeUnit=Read-MorphospaceProtocolJson $missingFreezeUnitPath;$missingFreezeUnit.PSObject.Properties.Remove('candidate_freeze');Write-BlockedJson $missingFreezeUnitPath $missingFreezeUnit;$missingFreezeRequest=Copy-Blocked $request;$missingFreezeRequest.terminal.unit_raw_sha256=Get-MorphospaceFileSha256 $missingFreezeUnitPath;$missingFreezeRequest.terminal.unit_canonical_sha256=Get-BlockedHash $missingFreezeUnit;$missingFreezeRequestPath=Join-Path $temp 'prepare-blocked-missing-freeze.json';Write-BlockedJson $missingFreezeRequestPath $missingFreezeRequest;$missingFreezeRejected=$false;try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $missingFreezeWorkspace -BlockedSuccessorPreparation $missingFreezeRequestPath -OutPath (Join-Path $missingFreezeWorkspace 'receipts\unit004-preparation.json') -Timestamp '2026-09-01T00:03:00.0000000Z'|Out-Null}catch{$missingFreezeRejected=$_.Exception.Message-like'*predecessor is not candidate-frozen*'};Assert-Blocked $missingFreezeRejected 'preparation accepted a terminal predecessor without candidate_freeze'
  foreach($artifactDamage in @('missing-artifact','hash-drift','missing-source-path','source-path-drift')){$damageWorkspace=Join-Path $temp "artifact-$artifactDamage";Copy-Item $workspace $damageWorkspace -Recurse;$damageEvidencePath=Join-Path $damageWorkspace 'receipts\terminal-compile.json';$damageValidationPath=Join-Path $damageWorkspace 'receipts\unit003-standard-blocked.json';$damageValidation=Read-MorphospaceProtocolJson $damageValidationPath;$damageRequest=Copy-Blocked $request;if($artifactDamage-ceq'missing-artifact'){Remove-Item -LiteralPath $damageEvidencePath -Force}elseif($artifactDamage-ceq'hash-drift'){Write-BlockedJson $damageEvidencePath ([ordered]@{source_path='morphospace/repair.ps1';diagnostic='drifted'})}else{$damageEvidence=Read-MorphospaceProtocolJson $damageEvidencePath;if($artifactDamage-ceq'missing-source-path'){$damageEvidence.PSObject.Properties.Remove('source_path')}else{$damageEvidence.source_path='morphospace/other.ps1'};Write-BlockedJson $damageEvidencePath $damageEvidence;$damageValidation.artifacts[0].sha256=Get-MorphospaceFileSha256 $damageEvidencePath;Write-BlockedJson $damageValidationPath $damageValidation;$damageRequest.terminal.checkpoint.receipt_sha256=Get-MorphospaceFileSha256 $damageValidationPath};$damageRequestPath=Join-Path $temp "prepare-$artifactDamage.json";Write-BlockedJson $damageRequestPath $damageRequest;$damageRejected=$false;try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $damageWorkspace -BlockedSuccessorPreparation $damageRequestPath -OutPath (Join-Path $damageWorkspace 'receipts\unit004-preparation.json') -Timestamp '2026-09-01T00:03:00.0000000Z'|Out-Null}catch{$damageRejected=$(if($artifactDamage-in@('missing-artifact','hash-drift')){$_.Exception.Message-like'*evidence artifact bytes drifted*'}else{$_.Exception.Message-like'*evidence does not identify the exact repair path*'})};Assert-Blocked $damageRejected "preparation accepted $artifactDamage damage"}
  $missingRepositoryWorkspace=Join-Path $temp 'missing-source-repository';Copy-Item $workspace $missingRepositoryWorkspace -Recurse;$missingRepositoryMapPath=Join-Path $missingRepositoryWorkspace 'repository-map.json';$missingRepositoryMap=Read-MorphospaceProtocolJson $missingRepositoryMapPath;$missingRepositoryMap.repositories[0].path=Join-Path $temp 'absent-source-repository';Write-BlockedJson $missingRepositoryMapPath $missingRepositoryMap;$missingRepositoryRequest=Copy-Blocked $request;$missingRepositoryRequest.expected.repository_map_sha256=Get-MorphospaceFileSha256 $missingRepositoryMapPath;$missingRepositoryRequestPath=Join-Path $temp 'prepare-missing-source-repository.json';Write-BlockedJson $missingRepositoryRequestPath $missingRepositoryRequest;$missingRepositoryRejected=$false;try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $missingRepositoryWorkspace -BlockedSuccessorPreparation $missingRepositoryRequestPath -OutPath (Join-Path $missingRepositoryWorkspace 'receipts\unit004-preparation.json') -Timestamp '2026-09-01T00:03:00.0000000Z'|Out-Null}catch{$missingRepositoryRejected=$_.Exception.Message-like'*source repository*is unavailable*'};Assert-Blocked $missingRepositoryRejected 'preparation accepted an unavailable source repository'
  $beforeProject=Get-MorphospaceFileSha256 (Join-Path $workspace 'project.spec.json');$beforeLock=Get-MorphospaceFileSha256 (Join-Path $workspace 'feature.lock.json');$beforeTerminal=Get-MorphospaceFileSha256 (Join-Path $workspace 'iteration-units\unit003.json')
  $dry=Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $workspace -BlockedSuccessorPreparation $requestPath -OutPath $out -Timestamp '2026-09-01T00:03:00.0000000Z';Assert-Blocked (-not$dry.executed-and-not(Test-Path $out)-and[string]$dry.timestamp-ceq'2026-09-01T00:03:00.0000000Z') 'dry-run mutated the workspace or changed the supplied strict timestamp'
  $generatedTimestamp=Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $workspace -BlockedSuccessorPreparation $requestPath -OutPath $out;Assert-Blocked ([string]$generatedTimestamp.timestamp-cmatch'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{7}Z$'-and-not$generatedTimestamp.executed-and-not(Test-Path $out)) 'omitted timestamp did not generate canonical strict UTC without mutation'
  $malformedTimestampRejected=$false;try{Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $workspace -BlockedSuccessorPreparation $requestPath -OutPath $out -Timestamp '2026-09-01T00:03:00Z'|Out-Null}catch{$malformedTimestampRejected=$_.Exception.Message-like'*timestamp must be strict UTC*'-or$_.Exception.Message-like'*seven-digit UTC ISO-8601*'};Assert-Blocked $malformedTimestampRejected 'malformed nonempty preparation timestamp was accepted'
  $inputHash=Get-MorphospaceFileSha256 $requestPath;$run=Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $workspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath $out -Timestamp '2026-09-01T00:03:00.0000000Z' -Execute
  Assert-Blocked ($run.executed-and(Test-Path $out)-and(Get-MorphospaceFileSha256 (Join-Path $workspace 'project.spec.json'))-ceq$beforeProject-and(Get-MorphospaceFileSha256 (Join-Path $workspace 'feature.lock.json'))-ceq$beforeLock-and(Get-MorphospaceFileSha256 (Join-Path $workspace 'iteration-units\unit003.json'))-ceq$beforeTerminal) 'preparation did not preserve project, lock, and immutable terminal bytes'
  $committedDryBefore=@((Get-MorphospaceFileSha256 (Join-Path $workspace 'workspace.state.json'));(Get-MorphospaceFileSha256 (Join-Path $workspace 'iteration-events.jsonl'));(Get-MorphospaceFileSha256 $out));$committedDryReplay=Invoke-MorphospacePrepareBlockedSuccessor -WorkspaceRoot $workspace -BlockedSuccessorPreparation $requestPath -ExpectedBlockedSuccessorPreparationSha256 $inputHash -OutPath $out -Timestamp '2026-09-01T00:03:10.0000000Z';$committedDryAfter=@((Get-MorphospaceFileSha256 (Join-Path $workspace 'workspace.state.json'));(Get-MorphospaceFileSha256 (Join-Path $workspace 'iteration-events.jsonl'));(Get-MorphospaceFileSha256 $out));$committedDryEvents=@(Get-Content (Join-Path $workspace 'iteration-events.jsonl')|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String}|Where-Object{[string]$_.event_id-ceq'unit004-preparation-prepared'})
  Assert-Blocked ($committedDryReplay.executed-and[string]$committedDryReplay.timestamp-ceq'2026-09-01T00:03:00.0000000Z'-and[string]$committedDryReplay.event_id-ceq'unit004-preparation-prepared'-and(Get-BlockedHash $committedDryReplay)-ceq(Get-BlockedHash $run)-and(Get-BlockedHash $committedDryBefore)-ceq(Get-BlockedHash $committedDryAfter)-and$committedDryEvents.Count-eq1) 'completed preparation dry replay did not return the original committed result idempotently'
  $receipt=Read-MorphospaceProtocolJson $out;$sourcePath=Join-Path $workspace ($receipt.source_composition.path-replace'/','\')
  $successor=Copy-Blocked $terminalUnit;$successor.unit_id='unit004';$successor.status='proposed';$successor.prerequisites=@('unit001');$successor.allowed_repositories=@([ordered]@{repo_id='public-source';allowed_paths=@('morphospace/repair.ps1')});if($successor.PSObject.Properties.Name-contains'candidate_freeze'){$successor.PSObject.Properties.Remove('candidate_freeze')};$successor.change_categories=@('implementation');$successor.instruction_impact='none';$successor.instruction_surfaces=@();$successor.instruction_none_justification='The bounded successor changes only the exact implementation repair path and no instruction surface.';$successorSourceComposition=[ordered]@{mode='exact-lock';lock_path=[string]$receipt.source_composition.path;materialization_receipt=$null};if($successor.PSObject.Properties.Name-contains'source_composition'){$successor.source_composition=$successorSourceComposition}else{$successor|Add-Member -NotePropertyName source_composition -NotePropertyValue $successorSourceComposition}
  $afterPrepState=Read-MorphospaceProtocolJson (Join-Path $workspace 'workspace.state.json');$afterPrepEvents=Join-Path $workspace 'iteration-events.jsonl'
  $admission=[ordered]@{
    schema='rusty.morphospace.workflow.development_unit_admission.v1';admission_kind='blocked-successor';admission_id='unit004-admission';project_id='blocked-successor-test';unit_id='unit004'
    preparation=[ordered]@{preparation_id='unit004-preparation';receipt_path='receipts/unit004-preparation.json';receipt_sha256=Get-MorphospaceFileSha256 $out;source_composition_path=[string]$receipt.source_composition.path;source_composition_sha256=Get-MorphospaceFileSha256 $sourcePath;terminal_binding_sha256=[string]$receipt.terminal_binding_sha256}
    blocked_successor=[ordered]@{terminal_unit_id='unit003';terminal_binding_sha256=[string]$receipt.terminal_binding_sha256};agent_scope_assessment=$successor.agent_scope_assessment;unit=$successor
    expected=[ordered]@{project_sha256=Get-BlockedHash $project;state_sha256=Get-BlockedHash $afterPrepState;feature_lock_sha256=Get-BlockedHash (Read-MorphospaceProtocolJson (Join-Path $workspace 'feature.lock.json'));source_composition_path=[string]$receipt.source_composition.path;source_composition_sha256=Get-MorphospaceFileSha256 $sourcePath;repository_map_path='repository-map.json';repository_map_sha256=Get-MorphospaceFileSha256 (Join-Path $workspace 'repository-map.json');events_sha256=Get-MorphospaceFileSha256 $afterPrepEvents;events_length=([IO.FileInfo]$afterPrepEvents).Length;event_tail_id=[string]$afterPrepState.last_event_id}
    does_not_prove=@('Does not Ready, claim, build, use a device, accept, or publish.')
  }
  $admissionPath=Join-Path $temp 'unit004-admission.json';Write-BlockedJson $admissionPath $admission;$admissionOut=Join-Path $workspace 'receipts\unit004-admission.json'
  $archivedWorkspace=Join-Path $temp 'archived-terminal-transaction';Copy-Item $workspace $archivedWorkspace -Recurse;$archivedIntentPath=Join-Path $archivedWorkspace 'receipts\transactions\unit003-validation-blocked-0002-transition.intent.json';$archivedCompletionPath=Join-Path $archivedWorkspace 'receipts\transactions\unit003-validation-blocked-0002-transition.completion.json';Remove-Item -LiteralPath $archivedIntentPath,$archivedCompletionPath -Force
  [void](Test-MorphospaceBlockedSuccessorPreparation -WorkspaceRoot $archivedWorkspace -Admission $admission -Phase Admission);[void](Test-MorphospaceBlockedSuccessorPreparation -WorkspaceRoot $archivedWorkspace -Admission $admission -Phase Freeze)
  $archivedAdmissionOut=Join-Path $archivedWorkspace 'receipts\unit004-admission.json';$archivedAdmissionDry=Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $archivedWorkspace -DevelopmentUnitAdmission $admissionPath -OutPath $archivedAdmissionOut -Timestamp '2026-09-01T00:04:00.0000000Z';Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $archivedWorkspace -DevelopmentUnitAdmission $admissionPath -ExpectedDevelopmentUnitAdmissionSha256 $archivedAdmissionDry.audit_receipt.sha256 -OutPath $archivedAdmissionOut -Timestamp '2026-09-01T00:04:00.0000000Z' -Execute|Out-Null
  foreach($archivedDamage in @('terminal-raw','freeze','checkpoint','event')){$archivedDamageRoot=Join-Path $temp "archived-terminal-damage-$archivedDamage";Copy-Item $archivedWorkspace $archivedDamageRoot -Recurse;if($archivedDamage-ceq'terminal-raw'){$p=Join-Path $archivedDamageRoot 'iteration-units\unit003.json';$d=Read-MorphospaceProtocolJson $p;$d.status='active';Write-BlockedJson $p $d}elseif($archivedDamage-ceq'freeze'){$p=Join-Path $archivedDamageRoot 'receipts\unit003-freeze.json';$d=Read-MorphospaceProtocolJson $p;$d.does_not_prove=@('Damaged retained freeze.');Write-BlockedJson $p $d}elseif($archivedDamage-ceq'checkpoint'){$p=Join-Path $archivedDamageRoot 'receipts\unit003-standard-blocked.json';$d=Read-MorphospaceProtocolJson $p;$d.created_at='2026-09-01T00:01:01Z';Write-BlockedJson $p $d}else{$p=Join-Path $archivedDamageRoot 'iteration-events.jsonl';$eventDamage=@(Get-Content $p|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$eventDamage[1].summary='Damaged retained historical terminal event.';$eventDamageLines=@($eventDamage|ForEach-Object{$_|ConvertTo-Json -Depth 100 -Compress});[IO.File]::WriteAllText($p,(($eventDamageLines-join"`n")+"`n"),[Text.UTF8Encoding]::new($false))};$archivedDamageState=Get-MorphospaceFileSha256 (Join-Path $archivedDamageRoot 'workspace.state.json');$archivedDamageUnit=Get-MorphospaceFileSha256 (Join-Path $archivedDamageRoot 'iteration-units\unit004.json');$archivedDamageEvents=Get-MorphospaceFileSha256 (Join-Path $archivedDamageRoot 'iteration-events.jsonl');$archivedDamageRejected=$false;try{&$automation {param($arguments)Invoke-MorphospaceWorkUnitAutomation @arguments} @{Action='Ready';WorkspaceRoot=$archivedDamageRoot;UnitId='unit004';RepoMapPath=(Join-Path $archivedDamageRoot 'repository-map.json');Timestamp='2026-09-01T00:05:00.0000000Z';Execute=$true}|Out-Null}catch{$archivedDamageRejected=$true};Assert-Blocked ($archivedDamageRejected-and-not(Test-Path (Join-Path $archivedDamageRoot 'receipts\unit004-terminal-validation-selection-release.json'))-and(Get-MorphospaceFileSha256 (Join-Path $archivedDamageRoot 'workspace.state.json'))-ceq$archivedDamageState-and(Get-MorphospaceFileSha256 (Join-Path $archivedDamageRoot 'iteration-units\unit004.json'))-ceq$archivedDamageUnit-and(Get-MorphospaceFileSha256 (Join-Path $archivedDamageRoot 'iteration-events.jsonl'))-ceq$archivedDamageEvents) "Ready accepted archived $archivedDamage retained-evidence drift or mutated before rejection"}
  $archivedReady=&$automation {param($arguments)Invoke-MorphospaceWorkUnitAutomation @arguments} @{Action='Ready';WorkspaceRoot=$archivedWorkspace;UnitId='unit004';RepoMapPath=(Join-Path $archivedWorkspace 'repository-map.json');Timestamp='2026-09-01T00:05:00.0000000Z';Execute=$true};Assert-Blocked ($archivedReady.executed-and-not(Test-Path $archivedIntentPath)-and-not(Test-Path $archivedCompletionPath)-and(Test-Path (Join-Path $archivedWorkspace 'receipts\unit004-terminal-validation-selection-release.json'))) 'Admission, Freeze, or Ready required archived predecessor terminal transaction files'
  $preparationReceiptSchema=Join-Path $repoRoot 'schemas\blocked-successor-preparation-receipt-v1.schema.json'
  foreach($receiptSchemaDamage in @('terminal-missing','terminal-extra','repair-type')){$schemaDamage=Copy-Blocked $receipt;if($receiptSchemaDamage-ceq'terminal-missing'){$schemaDamage.terminal.PSObject.Properties.Remove('unit_id')}elseif($receiptSchemaDamage-ceq'terminal-extra'){$schemaDamage.terminal|Add-Member -NotePropertyName extra -NotePropertyValue 'damage'}else{$schemaDamage.repair.path=7};$schemaRejected=$false;$schemaDiagnostic='';try{$schemaRejected=-not(Test-Json -Json ($schemaDamage|ConvertTo-Json -Depth 100 -Compress) -SchemaFile $preparationReceiptSchema -ErrorAction Stop)}catch{if([string]$_.FullyQualifiedErrorId-cne'InvalidJsonAgainstSchemaDetailed,Microsoft.PowerShell.Commands.TestJsonCommand'){throw};$schemaRejected=$true;$schemaDiagnostic=[string]$_.Exception.Message};$expectedSchemaDiagnostic=$(if($receiptSchemaDamage-ceq'terminal-missing'){'*unit_id*/terminal*'}elseif($receiptSchemaDamage-ceq'terminal-extra'){"*'/terminal/extra'*"}else{'*integer*/repair/path*'});Assert-Blocked ($schemaRejected-and($schemaDiagnostic-eq''-or$schemaDiagnostic-like$expectedSchemaDiagnostic)) "preparation receipt schema accepted or misclassified $receiptSchemaDamage damage: $schemaDiagnostic"}
  foreach($preparationDamage in @('target-state','target-unit','event','artifact')){
    $preparationRoot=Join-Path $temp "preparation-substitution-$preparationDamage";Copy-Item $workspace $preparationRoot -Recurse;$damagedAdmission=Copy-Blocked $admission;$prepTx='unit004-preparation-prepared-transition';$prepIntentPath=Join-Path $preparationRoot "receipts\transactions\$prepTx.intent.json";$prepCompletionPath=Join-Path $preparationRoot "receipts\transactions\$prepTx.completion.json";$prepIntent=Read-MorphospaceProtocolJson $prepIntentPath;$prepCompletion=Read-MorphospaceProtocolJson $prepCompletionPath
    if($preparationDamage-ceq'target-state'){$prepIntent.target.state.document.blockers[0].condition='Substituted preparation target state.';$prepIntent.target.state.sha256=Get-BlockedHash $prepIntent.target.state.document;$prepCompletion.state_sha256=$prepIntent.target.state.sha256}
    elseif($preparationDamage-ceq'target-unit'){$prepIntent.target.unit.document.status='active';$unitSubstitutionHash=Get-BlockedHash $prepIntent.target.unit.document;$prepIntent.target.unit.sha256=$unitSubstitutionHash;$prepIntent.pre.unit.sha256=$unitSubstitutionHash;$prepIntent.expected.unit_sha256=$unitSubstitutionHash;$prepCompletion.unit_sha256=$unitSubstitutionHash}
    elseif($preparationDamage-ceq'event'){$prepIntent.event.summary='Substituted preparation event.'}
    else{$sourceSubstitution=Read-MorphospaceProtocolJson (Join-Path $preparationRoot 'source-composition\unit004-preparation.json');$sourceSubstitution.does_not_prove=@('Substituted source artifact.');$sourceSubstitutionBytes=[Text.UTF8Encoding]::new($false).GetBytes(($sourceSubstitution|ConvertTo-Json -Depth 100));$sourceSubstitutionHash=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($sourceSubstitutionBytes)).ToLowerInvariant();$prepIntent.artifacts[1].bytes_base64=[Convert]::ToBase64String($sourceSubstitutionBytes);$prepIntent.artifacts[1].sha256=$sourceSubstitutionHash;[IO.File]::WriteAllBytes((Join-Path $preparationRoot 'source-composition\unit004-preparation.json'),$sourceSubstitutionBytes);$damagedAdmission.preparation.source_composition_sha256=$sourceSubstitutionHash}
    Write-BlockedJson $prepIntentPath $prepIntent;$prepCompletion.intent.sha256=Get-MorphospaceFileSha256 $prepIntentPath;Write-BlockedJson $prepCompletionPath $prepCompletion;$preparationRejected=$false;try{Test-MorphospaceBlockedSuccessorPreparation -WorkspaceRoot $preparationRoot -Admission $damagedAdmission -Phase Admission|Out-Null}catch{$preparationRejected=$true};Assert-Blocked $preparationRejected "completed preparation verifier accepted $preparationDamage substitution"
  }
  $receiptSubstitutionRoot=Join-Path $temp 'preparation-receipt-substitution';Copy-Item $workspace $receiptSubstitutionRoot -Recurse;$receiptSubstitutionPath=Join-Path $receiptSubstitutionRoot 'receipts\unit004-preparation.json';$receiptSubstitution=Read-MorphospaceProtocolJson $receiptSubstitutionPath;$receiptSubstitution.terminal.unit_id='unit005';$receiptSubstitution.terminal_binding_sha256=Get-BlockedHash ([pscustomobject][ordered]@{terminal=$receiptSubstitution.terminal;repair=$receiptSubstitution.repair});Write-BlockedJson $receiptSubstitutionPath $receiptSubstitution;Assert-Blocked (Test-Json -Json (Get-Content -Raw $receiptSubstitutionPath) -SchemaFile $preparationReceiptSchema) 'valid-shape receipt substitution did not satisfy the closed schema fixture';$receiptSubstitutionAdmission=Copy-Blocked $admission;$receiptSubstitutionAdmission.preparation.receipt_sha256=Get-MorphospaceFileSha256 $receiptSubstitutionPath;$receiptSubstitutionAdmission.preparation.terminal_binding_sha256=$receiptSubstitution.terminal_binding_sha256;$receiptSubstitutionAdmission.blocked_successor.terminal_unit_id='unit005';$receiptSubstitutionAdmission.blocked_successor.terminal_binding_sha256=$receiptSubstitution.terminal_binding_sha256;$receiptSubstitutionRejected=$false;try{Test-MorphospaceBlockedSuccessorPreparation -WorkspaceRoot $receiptSubstitutionRoot -Admission $receiptSubstitutionAdmission -Phase Admission|Out-Null}catch{$receiptSubstitutionRejected=$true};Assert-Blocked $receiptSubstitutionRejected 'completed preparation consumer accepted valid-shape terminal substitution'
  foreach($terminalBindingDamage in @('missing','drift')){
    $damagedAdmission=Copy-Blocked $admission
    if($terminalBindingDamage-ceq'missing'){$damagedAdmission.preparation.PSObject.Properties.Remove('terminal_binding_sha256')}else{$damagedAdmission.preparation.terminal_binding_sha256='0'*64}
    $damagedAdmissionPath=Join-Path $temp "unit004-admission-terminal-binding-$terminalBindingDamage.json";Write-BlockedJson $damagedAdmissionPath $damagedAdmission;$terminalBindingRejected=$false
    try{Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $workspace -DevelopmentUnitAdmission $damagedAdmissionPath -OutPath $admissionOut -Timestamp '2026-09-01T00:04:00.0000000Z'|Out-Null}catch{$terminalBindingRejected=$(if($terminalBindingDamage-ceq'missing'){[string]$_.FullyQualifiedErrorId-ceq'InvalidJsonAgainstSchemaDetailed,Microsoft.PowerShell.Commands.TestJsonCommand'-and[string]$_.Exception.Message-like'*terminal_binding_sha256*'-and[string]$_.Exception.Message-like'*/preparation*'}else{$_.Exception.Message-like'*does not bind the exact preparation*'})}
    Assert-Blocked $terminalBindingRejected "admission accepted $terminalBindingDamage preparation terminal-binding damage before release"
  }
  $admissionDry=Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $workspace -DevelopmentUnitAdmission $admissionPath -OutPath $admissionOut -Timestamp '2026-09-01T00:04:00.0000000Z';Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $workspace -DevelopmentUnitAdmission $admissionPath -ExpectedDevelopmentUnitAdmissionSha256 $admissionDry.audit_receipt.sha256 -OutPath $admissionOut -Timestamp '2026-09-01T00:04:00.0000000Z' -Execute|Out-Null
  $liveState=Read-MorphospaceProtocolJson (Join-Path $workspace 'workspace.state.json');$liveUnit=Read-MorphospaceProtocolJson (Join-Path $workspace 'iteration-units\unit004.json');$liveTerminal=Read-MorphospaceProtocolJson (Join-Path $workspace 'iteration-units\unit003.json');$events=@(Get-Content (Join-Path $workspace 'iteration-events.jsonl')|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$release=&$automation {param($arguments)Get-MorphospaceBlockedSuccessorTerminalRelease @arguments} @{WorkspaceRoot=$workspace;UnitId='unit004';Unit=$liveUnit;UnitRelativePath='iteration-units/unit004.json';SelectedUnitEntry=[pscustomobject]@{path=(Join-Path $workspace 'iteration-units\unit003.json');document=$liveTerminal};State=$liveState;Events=$events;Selection=$liveState.normal_validation_selection;RepositoryMap=@{'public-source'=[pscustomobject]@{repo_id='public-source';path=$source;role='source'}};Timestamp='2026-09-01T00:05:00.0000000Z'}
  Assert-Blocked ([string]$release.schema-ceq'rusty.morphospace.workflow.terminal_validation_selection_release.v2'-and-not$release.selector_evidence_verified-and-not$release.selector_evidence_reused) 'release-v2 did not preserve explicit no-evidence semantics'
  foreach($postAdmissionDamage in @('terminal-raw','freeze','checkpoint','terminal-transaction')){$postRoot=Join-Path $temp "post-admission-$postAdmissionDamage";Copy-Item $workspace $postRoot -Recurse;if($postAdmissionDamage-ceq'terminal-raw'){$p=Join-Path $postRoot 'iteration-units\unit003.json';$d=Read-MorphospaceProtocolJson $p;$d.status='active';Write-BlockedJson $p $d}elseif($postAdmissionDamage-ceq'freeze'){$p=Join-Path $postRoot 'receipts\unit003-freeze.json';$d=Read-MorphospaceProtocolJson $p;$d.does_not_prove=@('Damaged freeze.');Write-BlockedJson $p $d}elseif($postAdmissionDamage-ceq'checkpoint'){$p=Join-Path $postRoot 'receipts\unit003-standard-blocked.json';$d=Read-MorphospaceProtocolJson $p;$d.created_at='2026-09-01T00:01:01Z';Write-BlockedJson $p $d}else{$p=Join-Path $postRoot 'receipts\transactions\unit003-validation-blocked-0002-transition.completion.json';$d=Read-MorphospaceProtocolJson $p;$d.status='damaged';Write-BlockedJson $p $d};$beforeDamageState=Get-MorphospaceFileSha256 (Join-Path $postRoot 'workspace.state.json');$beforeDamageUnit=Get-MorphospaceFileSha256 (Join-Path $postRoot 'iteration-units\unit004.json');$beforeDamageEvents=Get-MorphospaceFileSha256 (Join-Path $postRoot 'iteration-events.jsonl');$readyRejected=$false;try{&$automation {param($arguments)Invoke-MorphospaceWorkUnitAutomation @arguments} @{Action='Ready';WorkspaceRoot=$postRoot;UnitId='unit004';RepoMapPath=(Join-Path $postRoot 'repository-map.json');Timestamp='2026-09-01T00:05:00.0000000Z';Execute=$true}|Out-Null}catch{$readyRejected=$true};Assert-Blocked ($readyRejected-and-not(Test-Path (Join-Path $postRoot 'receipts\unit004-terminal-validation-selection-release.json'))-and(Get-MorphospaceFileSha256 (Join-Path $postRoot 'workspace.state.json'))-ceq$beforeDamageState-and(Get-MorphospaceFileSha256 (Join-Path $postRoot 'iteration-units\unit004.json'))-ceq$beforeDamageUnit-and(Get-MorphospaceFileSha256 (Join-Path $postRoot 'iteration-events.jsonl'))-ceq$beforeDamageEvents) "Ready accepted $postAdmissionDamage drift or mutated before rejection"}
  $readyWorkspace=Join-Path $temp 'ready-owner-entrypoint';Copy-Item $workspace $readyWorkspace -Recurse;$readyResult=&$automation {param($arguments)Invoke-MorphospaceWorkUnitAutomation @arguments} @{Action='Ready';WorkspaceRoot=$readyWorkspace;UnitId='unit004';RepoMapPath=(Join-Path $readyWorkspace 'repository-map.json');Timestamp='2026-09-01T00:05:00.0000000Z';Execute=$true};$readyState=Read-MorphospaceProtocolJson (Join-Path $readyWorkspace 'workspace.state.json');$readyUnit=Read-MorphospaceProtocolJson (Join-Path $readyWorkspace 'iteration-units\unit004.json');$readyReleasePath=Join-Path $readyWorkspace 'receipts\unit004-terminal-validation-selection-release.json';$readyRelease=Read-MorphospaceProtocolJson $readyReleasePath
  Assert-Blocked ($readyResult.executed-and[string]$readyResult.transition-ceq'proposed-to-ready'-and[string]$readyResult.terminal_validation_selection_release.terminal_unit_id-ceq'unit003'-and[string]$readyUnit.status-ceq'ready'-and$null-eq$readyState.normal_validation_selection-and[string]$readyRelease.terminal.binding.unit_id-ceq'unit003'-and-not$readyRelease.selector_evidence_verified-and-not$readyRelease.selector_evidence_reused) 'owner Ready entrypoint did not transactionally consume the exact release-v2 proof'
  foreach($damage in @('terminal-binding','repair-path','ordinary-prerequisite','selector')){$root=Join-Path $temp "damage-$damage";Copy-Item $workspace $root -Recurse;$damagedAdmission=Copy-Blocked $admission;if($damage-ceq'terminal-binding'){$damagedAdmission.blocked_successor.terminal_binding_sha256='0'*64}elseif($damage-ceq'repair-path'){$damagedAdmission.unit.allowed_repositories[0].allowed_paths=@('morphospace/old.ps1')}elseif($damage-ceq'ordinary-prerequisite'){$damagedAdmission.unit.prerequisites+=,'unit003'}else{$damagedState=Read-MorphospaceProtocolJson (Join-Path $root 'workspace.state.json');$damagedState.normal_validation_selection.selector_id='drifted-selector';Write-BlockedJson (Join-Path $root 'workspace.state.json') $damagedState;continue};$rejected=$false;try{Test-MorphospaceBlockedSuccessorPreparation -WorkspaceRoot $root -Admission $damagedAdmission -Phase Release|Out-Null}catch{$rejected=$true};Assert-Blocked $rejected "accepted $damage damage"}
  $trueSelector=Copy-Blocked $liveState.normal_validation_selection;$trueSelector.selector_id='drifted-selector';$selectorRejected=$false;try{&$automation {param($arguments)Get-MorphospaceBlockedSuccessorTerminalRelease @arguments} @{WorkspaceRoot=$workspace;UnitId='unit004';Unit=$liveUnit;UnitRelativePath='iteration-units/unit004.json';SelectedUnitEntry=[pscustomobject]@{path=(Join-Path $workspace 'iteration-units\unit003.json');document=$liveTerminal};State=$liveState;Events=$events;Selection=$trueSelector;RepositoryMap=@{'public-source'=[pscustomobject]@{repo_id='public-source';path=$source;role='source'}};Timestamp='2026-09-01T00:05:00.0000000Z'}|Out-Null}catch{$selectorRejected=$true};Assert-Blocked $selectorRejected 'release-v2 accepted selector drift'
  Write-Host 'Blocked-successor preparation/admission/release-v2 self-test passed.'
}finally{if(Test-Path $temp){Remove-Item -LiteralPath $temp -Recurse -Force}}
