param([switch]$SelfTest)
$ErrorActionPreference='Stop'
$repoRoot=Split-Path $PSScriptRoot -Parent
Import-Module (Join-Path $PSScriptRoot 'DevelopmentEnvelopePreparation.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceProtocolCommon.psm1') -Force
function Assert-Preparation([bool]$ok,[string]$message){if(-not$ok){throw "Development-envelope preparation self-test failed: $message"}}
function Write-PreparationJson([string]$path,[object]$value){[IO.Directory]::CreateDirectory((Split-Path $path -Parent))|Out-Null;[IO.File]::WriteAllText($path,(($value|ConvertTo-Json -Depth 64)+"`n"),[Text.UTF8Encoding]::new($false))}
function Copy-Preparation([object]$value){$value|ConvertTo-Json -Depth 64|ConvertFrom-Json}
function Hash([object]$value){Get-MorphospaceCanonicalJsonSha256 $value}
$temp=Join-Path ([IO.Path]::GetTempPath()) ('workenv-preparation-'+[guid]::NewGuid().ToString('N'))
try {
  $ws=Join-Path $temp 'morphospace';[IO.Directory]::CreateDirectory((Join-Path $ws 'iteration-units'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $ws 'receipts'))|Out-Null
  $source=Join-Path $temp 'planning-source';[IO.Directory]::CreateDirectory($source)|Out-Null;& git -C $temp init $source|Out-Null;& git -C $source config user.name 'Preparation Test';& git -C $source config user.email 'preparation@example.invalid';[IO.File]::WriteAllText((Join-Path $source 'README.md'),'fixture',[Text.UTF8Encoding]::new($false));& git -C $source add README.md;& git -C $source commit -m fixture|Out-Null
  $commit=(& git -C $source rev-parse HEAD).Trim().ToLowerInvariant();$tree=(& git -C $source rev-parse 'HEAD^{tree}').Trim().ToLowerInvariant()
  $project=[ordered]@{schema='rusty.morphospace.workflow.project_spec.v2';project_id='portable-envelope';revision=1;owner='owner';purpose='portable fixture';activation_model=[ordered]@{default='disabled';unlisted_modules='inert';runtime_rule='selected-lock-and-runtime-input'};composition=[ordered]@{selected_features=@();denied_features=@();selected_modules=@();denied_modules=@();allowed_permissions=@();denied_permissions=@();data_classes=@()};authority_map=@([ordered]@{parameter='project.composition';owner='owner';adapters=@()});repositories=@([ordered]@{repo_id='planning';role='planning';path='.';allowed_paths=@('morphospace/')});modules=@();non_scope=@('fixture-only');validation_profiles=@([ordered]@{profile_id='quick';commands=@('fixture')});acceptance_profiles=@([ordered]@{profile_id='rollback';commands=@('fixture')});release_policy=[ordered]@{versioning='semver';commit_policy='fixture';push_checkpoint='none';source_first=$true;planning_last=$true;force_push_allowed=$false};public_boundary=[ordered]@{mode='mixed';private_overlay='local/';prohibited_evidence=@('private-identities')}}
  $emptyEffects=[ordered]@{permissions=@();services=@();activities=@();queries=@();tools=@();assets=@();shaders=@();native_libraries=@();commands=@();routes=@();streams=@();inputs=@();scenes=@();markers=@()};function New-FixtureFeature([string]$id){[ordered]@{feature_id=$id;module_id=$id;version='1';owner_lane='owner';selected=$true;run_activation_default='disabled';descriptor=[ordered]@{path=('features/'+$id+'.json');sha256=('0'*64);source_repo='planning';source_revision=$commit;source_path=('features/'+$id+'.json');source_sha256=('0'*64)};dependencies=@();conflicts=@();exclusive_group=$null;effects=(Copy-Preparation $emptyEffects);parameter_authorities=@();activation=[ordered]@{rule='selected-lock-and-runtime-input';runtime_inputs=@('fixture-input');receipt_schema='fixture.receipt';effective_marker='fixture.marker'};validation_profile='quick';rollback_profile='rollback'}};$provider=New-FixtureFeature 'morphovision-debug-host-receipt-provider';$lock=[ordered]@{schema='rusty.morphospace.workflow.feature_lock.v2';project_id='portable-envelope';project_revision=1;revision=1;generated_at='2026-08-25T00:00:00Z';resolver_version='rusty-morphospace-feature-resolver/2';lock_fingerprint=('0'*64);default_activation='disabled';activation_rule='selected-lock-and-runtime-input';selected_features=@('morphovision-debug-host-receipt-provider');denied_features=@();features=@($provider);effect_union=(Copy-Preparation $emptyEffects)}
  $state=[ordered]@{schema='rusty.morphospace.workflow.workspace_state.v2';project_id='portable-envelope';plan_revision=1;current_unit=$null;next_ready_unit=$null;last_event_id='u001-accepted';last_accepted_receipt='receipts/u001-accepted.json';repository_heads=@();repository_checkpoints=@();module_registry=[ordered]@{lock_revision=1;lock_fingerprint=('0'*64);modules=@()};capability_registry=@();dirty_repositories=@();blockers=@();validation_checkpoint=$null;pending_push_bundle=$null};$u001=[ordered]@{project_id='portable-envelope';unit_id='u001';status='accepted'}
  Write-PreparationJson (Join-Path $ws 'project.spec.json') $project;Write-PreparationJson (Join-Path $ws 'feature.lock.json') $lock;Write-PreparationJson (Join-Path $ws 'workspace.state.json') $state;Write-PreparationJson (Join-Path $ws 'iteration-units\u001.json') $u001;Write-PreparationJson (Join-Path $ws 'repository-map.json') ([ordered]@{schema='rusty.morphospace.workflow.repository_map.v1';repositories=@([ordered]@{repo_id='planning';path=$source;role='planning'})});[IO.File]::WriteAllText((Join-Path $ws 'iteration-events.jsonl'),((@{schema='rusty.morphospace.workflow.iteration_event.v1';event_id='u001-accepted';sequence=1;timestamp='2026-08-25T00:00:00.0000000Z';project_id='portable-envelope';unit_id='u001';event_type='state-transition';summary='Accepted fixture.';receipts=@()}|ConvertTo-Json -Compress)+"`n"),[Text.UTF8Encoding]::new($false))
  $targetProject=Copy-Preparation $project;$targetProject.revision=2;$targetProject.composition.selected_features=@('projection-stack-stabilization');$targetProject.composition.allowed_permissions=@('CAMERA','HEADSET_CAMERA','SPATIAL_CAMERA','USE_SCENE','OPENXR','OPENXR_SYSTEM')
  $targetLock=Copy-Preparation $lock;$targetLock.project_revision=2;$targetLock.revision=2;$feature=New-FixtureFeature 'projection-stack-stabilization';$targetLock.features+=,$feature;$targetLock.selected_features=@('morphovision-debug-host-receipt-provider','projection-stack-stabilization');$targetLock.effect_union.permissions=@('CAMERA','HEADSET_CAMERA','SPATIAL_CAMERA','USE_SCENE','OPENXR','OPENXR_SYSTEM')
  $eventsPath=Join-Path $ws 'iteration-events.jsonl';$input=[ordered]@{schema='rusty.morphospace.workflow.development_envelope_preparation.v1';preparation_id='portable-envelope-prepare';project_id='portable-envelope';predecessor_unit_id='u001';envelope=[ordered]@{project=$targetProject;feature_lock=$targetLock;owner_repositories=@([ordered]@{repo_id='planning';source_roots=@('morphospace/')});public_private_boundary='mixed';allowed_change_categories=@('implementation','validation','documentation-only');allowed_effect_categories=@('filesystem','build','device');allowed_permission_categories=@('CAMERA','HEADSET_CAMERA','SPATIAL_CAMERA','USE_SCENE','OPENXR','OPENXR_SYSTEM');build_envelope=[ordered]@{class='product';allowed_profiles=@('quick-host','raw-projection-devfast','raw-projection-candidate','maximum-blend-control-candidate')};device_envelope=[ordered]@{requirement='required';allowed_kinds=@('quest-typed-deploy-launch-observe-stop','raw-projection-freshness','maximum-blend-fixed-90hz-cpu4-gpu4-ababa')};source_composition=[ordered]@{path='source-composition/prepared.json';repository_ids=@('planning')}};expected=[ordered]@{project_sha256=(Hash $project);state_sha256=(Hash $state);feature_lock_sha256=(Hash $lock);repository_map_path='repository-map.json';repository_map_sha256=(Get-MorphospaceFileSha256 (Join-Path $ws 'repository-map.json'));predecessor_unit_path='iteration-units/u001.json';predecessor_unit_sha256=(Hash $u001);events_sha256=(Get-MorphospaceFileSha256 $eventsPath);events_length=([IO.FileInfo]$eventsPath).Length;event_tail_id='u001-accepted'};does_not_prove=@('Does not admit a future unit or execute a device action.')}
  $inputPath=Join-Path $temp 'prepare.json';Write-PreparationJson $inputPath $input;$out=Join-Path $ws 'receipts\portable-envelope-prepare.json';$dry=Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $ws -DevelopmentEnvelopePreparation $inputPath -OutPath $out -Timestamp '2026-08-25T00:01:00.0000000Z';$inputHash=Get-MorphospaceFileSha256 $inputPath;$recoveryBase=Join-Path $temp 'recovery-base';Copy-Item $ws $recoveryBase -Recurse;$run=Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $ws -DevelopmentEnvelopePreparation $inputPath -ExpectedDevelopmentEnvelopePreparationSha256 $inputHash -OutPath $out -Timestamp '2026-08-25T00:01:00.0000000Z' -Execute;$automationReceiptV2=Join-Path (Split-Path $PSScriptRoot -Parent) 'schemas\work-unit-automation-receipt-v2.schema.json';Assert-Preparation ((Test-Json -Json ($dry|ConvertTo-Json -Depth 32 -Compress) -SchemaFile $automationReceiptV2)-and(Test-Json -Json ($run|ConvertTo-Json -Depth 32 -Compress) -SchemaFile $automationReceiptV2)) 'development-envelope owner emitted a receipt outside the shared v2 schema';Assert-Preparation ($run.executed-and(Test-Path $out)-and(Test-Path (Join-Path $ws 'source-composition\prepared.json'))-and$null-eq(Read-MorphospaceProtocolJson (Join-Path $ws 'workspace.state.json')).current_unit-and-not(Test-Path (Join-Path $ws 'iteration-units\u002.json'))) 'positive idle preparation did not preserve idle no-future-unit state'
  $dryReplay=Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $ws -DevelopmentEnvelopePreparation $inputPath -ExpectedDevelopmentEnvelopePreparationSha256 $inputHash -OutPath $out;Assert-Preparation (-not$dryReplay.executed-and$null-eq$dryReplay.event_id-and(Test-Json -Json ($dryReplay|ConvertTo-Json -Depth 32 -Compress) -SchemaFile $automationReceiptV2)) 'existing-intent dry preparation replay claimed execution/event or failed receipt-v2';$replay=Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $ws -DevelopmentEnvelopePreparation $inputPath -ExpectedDevelopmentEnvelopePreparationSha256 $inputHash -OutPath $out -Execute;Assert-Preparation ($replay.executed-and$null-ne$replay.event_id-and(Test-Json -Json ($replay|ConvertTo-Json -Depth 32 -Compress) -SchemaFile $automationReceiptV2)) 'exact preparation replay was not idempotent and schema-valid'
  foreach($cut in @('after-intent','after-artifacts','after-project','after-lock','after-state','after-event')){$root=Join-Path $temp ("recovery-"+$cut);Copy-Item $recoveryBase $root -Recurse;$cutOut=Join-Path $root 'receipts\portable-envelope-prepare.json';$interrupted=$false;try{Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $root -DevelopmentEnvelopePreparation $inputPath -ExpectedDevelopmentEnvelopePreparationSha256 $inputHash -OutPath $cutOut -Execute -FaultAfter $cut|Out-Null}catch{$interrupted=$true};$resumed=Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $root -DevelopmentEnvelopePreparation $inputPath -ExpectedDevelopmentEnvelopePreparationSha256 $inputHash -OutPath $cutOut -Execute;Assert-Preparation ($interrupted-and$resumed.executed-and(Test-Path $cutOut)-and(Test-Path (Join-Path $root 'receipts\transactions\portable-envelope-prepare-prepared-transition.completion.json'))) "recovery cut '$cut' did not resume its exact preparation intent"}
  $providerRoot=Join-Path $temp 'damage-provider-rewrite';Copy-Item $recoveryBase $providerRoot -Recurse;$providerRewrite=Copy-Preparation $input;$providerRewrite.envelope.feature_lock.features[0].version='2';$providerRewritePath=Join-Path $temp 'damage-provider-rewrite.json';Write-PreparationJson $providerRewritePath $providerRewrite;$providerRejected=$false;try{Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $providerRoot -DevelopmentEnvelopePreparation $providerRewritePath -OutPath (Join-Path $providerRoot 'receipts\portable-envelope-prepare.json')|Out-Null}catch{$providerRejected=$_.Exception.Message-ceq"Preparation rewrites existing feature 'morphovision-debug-host-receipt-provider'."};Assert-Preparation $providerRejected 'accepted rewrite of a prefixed predecessor feature or returned the wrong rejection'
  $duplicateRoot=Join-Path $temp 'damage-duplicate-predecessor';Copy-Item $recoveryBase $duplicateRoot -Recurse;$duplicateLock=Read-MorphospaceProtocolJson (Join-Path $duplicateRoot 'feature.lock.json');$duplicateLock.features+=,(Copy-Preparation $duplicateLock.features[0]);Write-PreparationJson (Join-Path $duplicateRoot 'feature.lock.json') $duplicateLock;$duplicateInput=Copy-Preparation $input;$duplicateInput.expected.feature_lock_sha256=Hash $duplicateLock;$duplicateInputPath=Join-Path $temp 'damage-duplicate-predecessor.json';Write-PreparationJson $duplicateInputPath $duplicateInput;$duplicateRejected=$false;try{Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $duplicateRoot -DevelopmentEnvelopePreparation $duplicateInputPath -OutPath (Join-Path $duplicateRoot 'receipts\portable-envelope-prepare.json')|Out-Null}catch{$duplicateRejected=$_.Exception.Message-ceq"Preparation current feature lock repeats 'morphovision-debug-host-receipt-provider'."};Assert-Preparation $duplicateRejected 'accepted a duplicate prefixed predecessor feature or returned the wrong rejection'
  foreach($damage in @('permission','root','future-unit')){$root=Join-Path $temp ("damage-"+$damage);Copy-Item $ws $root -Recurse;$d=Copy-Preparation $input;if($damage-eq'permission'){$d.envelope.allowed_permission_categories+=,'INTERNET'}elseif($damage-eq'root'){$d.envelope.owner_repositories[0].source_roots=@('../outside/')}else{Write-PreparationJson (Join-Path $root 'iteration-units\future.json') ([ordered]@{unit_id='future'})};$path=Join-Path $temp ("damage-"+$damage+'.json');Write-PreparationJson $path $d;$rejected=$false;try{Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $root -DevelopmentEnvelopePreparation $path -OutPath (Join-Path $root 'receipts\portable-envelope-prepare.json')|Out-Null}catch{$rejected=$true};Assert-Preparation $rejected "accepted $damage damage"}
  Write-Host 'Development-envelope preparation self-test passed.'
} finally {if(Test-Path $temp){Remove-Item -LiteralPath $temp -Recurse -Force}}
