[CmdletBinding()]
param([string]$OutPath="",[ValidateRange(0,1)][int]$Attempt=0,[switch]$SelfTest)
Set-StrictMode -Version 2.0; $ErrorActionPreference='Stop'
$toolRequirements=@([pscustomobject][ordered]@{name='git';required=$true},[pscustomobject][ordered]@{name='pwsh';required=$true},[pscustomobject][ordered]@{name='rg';required=$false})
function New-AffectedValidationInfrastructureResult([int]$ResultAttempt,[hashtable]$Availability){
    if($Availability.Count -ne $toolRequirements.Count){throw 'Infrastructure availability must contain exactly the closed tool set.'}
    $tools=@(foreach($requirement in $toolRequirements){$toolName=[string]$requirement.name;if(-not $Availability.ContainsKey($toolName)){throw "Infrastructure availability omits '$toolName'."};[pscustomobject][ordered]@{name=$toolName;required=[bool]$requirement.required;available=[bool]$Availability[$toolName]}})
    $requiredUnavailable=@($tools|Where-Object{$_.required -and -not $_.available}).Count -gt 0
    return [pscustomobject][ordered]@{schema='rusty.morphospace.workflow.affected_validation_infrastructure.v1';attempt=$ResultAttempt;classification=$(if($requiredUnavailable){'pending-infra'}else{'ready'});tools=$tools;claims=[pscustomobject][ordered]@{acceptance_authority=$false;publication_authority=$false}}
}
$availability=@{};foreach($requirement in $toolRequirements){$toolName=[string]$requirement.name;$availability[$toolName]=($null -ne (Get-Command $toolName -ErrorAction SilentlyContinue))}
$result=New-AffectedValidationInfrastructureResult -ResultAttempt $Attempt -Availability $availability
$json=$result|ConvertTo-Json -Depth 16 -Compress
$schema=Join-Path $PSScriptRoot '..\schemas\affected-validation-infrastructure-v1.schema.json';if(-not(Test-Json -Json $json -SchemaFile $schema -ErrorAction Stop)){throw 'Infrastructure result fails its closed schema.'}
if($SelfTest){if($result.classification-cne'ready'){throw 'Local infrastructure self-test requires git and pwsh.'};$optionalMissing=New-AffectedValidationInfrastructureResult -ResultAttempt 0 -Availability @{git=$true;pwsh=$true;rg=$false};if($optionalMissing.classification-cne'ready' -or -not(Test-Json -Json ($optionalMissing|ConvertTo-Json -Depth 16 -Compress) -SchemaFile $schema -ErrorAction Stop)){throw 'Infrastructure self-test accepted optional rg absence as pending or invalid.'};$optionalPending=$optionalMissing|ConvertTo-Json -Depth 16|ConvertFrom-Json -Depth 16;$optionalPending.classification='pending-infra';if(Test-Json -Json ($optionalPending|ConvertTo-Json -Depth 16 -Compress) -SchemaFile $schema -ErrorAction SilentlyContinue){throw 'Infrastructure schema accepted pending classification for absent optional rg.'};$requiredMissing=New-AffectedValidationInfrastructureResult -ResultAttempt 1 -Availability @{git=$false;pwsh=$true;rg=$false};if($requiredMissing.classification-cne'pending-infra' -or -not(Test-Json -Json ($requiredMissing|ConvertTo-Json -Depth 16 -Compress) -SchemaFile $schema -ErrorAction Stop)){throw 'Infrastructure self-test did not classify missing required git as pending.'};$requiredReady=$requiredMissing|ConvertTo-Json -Depth 16|ConvertFrom-Json -Depth 16;$requiredReady.classification='ready';if(Test-Json -Json ($requiredReady|ConvertTo-Json -Depth 16 -Compress) -SchemaFile $schema -ErrorAction SilentlyContinue){throw 'Infrastructure schema accepted ready classification for absent required git.'};Write-Host 'Affected-validation infrastructure self-test passed.';return}
if([string]::IsNullOrWhiteSpace($OutPath)){throw 'Infrastructure classification requires an exact output path.'}
[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutPath),$json+[Environment]::NewLine,[Text.UTF8Encoding]::new($false));$result
