param([switch]$SelfTest,[switch]$Child,[string]$OldCommit='',[string]$NewCommit='',[string]$HarnessRoot='',[ValidateSet('all','lifecycle','recovery','product-negative','provenance-negative')][string]$Scenario='all')
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$script:TestClosurePaths=$null
$script:ToolingTestClock=[Diagnostics.Stopwatch]::StartNew()
function Write-TCPhase([string]$Name){[Console]::Error.WriteLine(('tooling_context_phase={0}; elapsed_seconds={1:N1}' -f $Name,$script:ToolingTestClock.Elapsed.TotalSeconds))}
if(-not$SelfTest){throw 'Test-ToolingContext requires -SelfTest.'}
trap { [Console]::Error.WriteLine("$($_.Exception.Message)`n$($_.ScriptStackTrace)"); exit 1 }

function Remove-ToolingTestRoot([string]$Path){$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\','/');$target=[IO.Path]::GetFullPath($Path).TrimEnd('\','/');if(-not([IO.Path]::GetDirectoryName($target).Equals($temp,[StringComparison]::OrdinalIgnoreCase))-or-not([IO.Path]::GetFileName($target).StartsWith('tooling-context-', [StringComparison]::Ordinal))){throw "Refusing tooling-context fixture cleanup: $target"};if(Test-Path $target){Remove-Item -LiteralPath $target -Recurse -Force}}
if(-not$Child){
 $sourceRoot=Split-Path $PSScriptRoot -Parent;$root=Join-Path ([IO.Path]::GetTempPath()) ('tooling-context-'+[guid]::NewGuid().ToString('N'));$tool=Join-Path $root 'tool-owner'
 try{
  [IO.Directory]::CreateDirectory($tool)|Out-Null;foreach($name in @('.github','config','docs','examples','fixtures','manifests','schemas','scripts','skills','templates','tools')){Copy-Item -LiteralPath (Join-Path $sourceRoot $name) -Destination (Join-Path $tool $name) -Recurse};foreach($name in @('.gitattributes','.gitignore','AGENTS.md','CHANGELOG.md','CONTRIBUTING.md','LICENSE','NOTICE.md','README.md','SECURITY.md')){Copy-Item -LiteralPath (Join-Path $sourceRoot $name) -Destination (Join-Path $tool $name)};foreach($file in @(Get-ChildItem -LiteralPath $tool -Recurse -File)){if(@('.ps1','.psm1','.psd1','.json','.md','.yml','.yaml','.toml','.txt','.gitignore','.gitattributes')-contains$file.Extension-or$file.Name-in@('.gitignore','.gitattributes')){$text=[IO.File]::ReadAllText($file.FullName);if($text.IndexOf([char]0)-lt0){[IO.File]::WriteAllText($file.FullName,$text.Replace("`r`n","`n"),[Text.UTF8Encoding]::new($false))}}}
  & git -C $tool init --initial-branch=main|Out-Null;& git -C $tool config user.name 'Tooling Context Test';& git -C $tool config user.email 'tooling-context@example.invalid';& git -C $tool config commit.gpgsign false;& git -C $tool config core.autocrlf false;& git -C $tool remote add origin 'https://example.invalid/work-environment.git';& git -C $tool add --all;& git -C $tool commit -m 'old tooling context'|Out-Null;& git -C $tool checkout-index -a -f;& git -C $tool reset --hard HEAD|Out-Null;$old=(& git -C $tool rev-parse HEAD).Trim().ToLowerInvariant()
  [IO.File]::AppendAllText((Join-Path $tool 'scripts/ToolingContextUpgrade.psm1'),"`n# fixture new tooling revision`n",[Text.UTF8Encoding]::new($false));& git -C $tool add scripts/ToolingContextUpgrade.psm1;& git -C $tool commit -m 'new tooling context'|Out-Null;& git -C $tool checkout-index -a -f;& git -C $tool reset --hard HEAD|Out-Null
   $new=(& git -C $tool rev-parse HEAD).Trim().ToLowerInvariant();& pwsh -NoProfile -File (Join-Path $tool 'scripts/Test-ToolingContext.ps1') -SelfTest -Child -OldCommit $old -NewCommit $new -HarnessRoot $root -Scenario $Scenario
  if($LASTEXITCODE-ne0){throw "Tooling-context bound-child self-test failed with exit code $LASTEXITCODE."}
 }finally{Remove-ToolingTestRoot $root}
 return
}

$repoRoot=Split-Path $PSScriptRoot -Parent
& git -C $repoRoot checkout --detach $OldCommit|Out-Null;if($LASTEXITCODE-ne0){throw 'Fixture could not materialize old tooling HEAD.'}
Import-Module (Join-Path $PSScriptRoot 'DevelopmentUnitAdmission.psm1')
$protocolModule=Import-Module (Join-Path $PSScriptRoot 'lib/MorphospaceProtocolCommon.psm1') -PassThru
$ledgerModule=Import-Module (Join-Path $PSScriptRoot 'lib/MorphospaceTransitionLedger.psm1') -PassThru
$automationModule=Import-Module (Join-Path $PSScriptRoot 'WorkUnitAutomation.psm1') -PassThru
$provenanceModule=Import-Module (Join-Path $PSScriptRoot 'ToolingContextProvenance.psm1') -Force -PassThru
$upgradeModule=Import-Module (Join-Path $PSScriptRoot 'ToolingContextUpgrade.psm1') -Force -PassThru
. (Join-Path $PSScriptRoot 'test-support/DevelopmentAdmissionFixture.ps1')
function Get-MorphospaceToolingContextAllowedActions { &$provenanceModule {Get-MorphospaceToolingContextAllowedActions} }
function New-MorphospaceToolingContext { [CmdletBinding()]param([string]$ContextId,[string]$ProjectId,[string]$PreparationId,[object]$ProductProjection,[object]$Resolver,[object]$Executor,[object[]]$Routers,[object]$Compatibility);&$provenanceModule {param($p)New-MorphospaceToolingContext @p} $PSBoundParameters }
function Invoke-MorphospaceUpgradeToolingContext { [CmdletBinding()]param([string]$WorkspaceRoot,[string]$UnitId,[string]$ToolingContextUpgrade,[string]$ExpectedToolingContextUpgradeSha256,[string]$OutPath,[string]$Timestamp,[string]$FaultAfter,[switch]$Execute);&$upgradeModule {param($p)Invoke-MorphospaceUpgradeToolingContext @p} $PSBoundParameters }
function Test-MorphospaceHistoricalToolingContextUpgrade { param([string]$WorkspaceRoot,[object]$ExpectedEvent);&$upgradeModule {param($w,$e)Test-MorphospaceHistoricalToolingContextUpgrade -WorkspaceRoot $w -ExpectedEvent $e} $WorkspaceRoot $ExpectedEvent }
function Assert-TC([bool]$Value,[string]$Name){if(-not$Value){throw "Tooling-context self-test failed: $Name"}}
function Read-TC([string]$Path){&$protocolModule {param($p)Read-MorphospaceProtocolJson $p} $Path}
function ToBytes([object]$Value){&$protocolModule {param($v),[byte[]](ConvertTo-MorphospaceProtocolJsonBytes $v)} $Value}
function FromBytes([byte[]]$Bytes){&$protocolModule {param($b)ConvertFrom-MorphospaceProtocolJsonBytes $b} $Bytes}
function BytesHash([byte[]]$Bytes){&$protocolModule {param($b)Get-MorphospaceSha256Bytes $b} $Bytes}
function Write-TC([string]$Path,[object]$Value){$parent=Split-Path $Path -Parent;if(-not(Test-Path $parent)){[IO.Directory]::CreateDirectory($parent)|Out-Null};[IO.File]::WriteAllBytes($Path,(ToBytes $Value))}
function FileHash([string]$Path){&$protocolModule {param($p)Get-MorphospaceFileSha256 $p} $Path}
function Canonical([object]$Value){&$protocolModule {param($v)Get-MorphospaceCanonicalJsonSha256 $v} $Value}
function Clone([object]$Value){$Value|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String}
function GitScalar([string]$Root,[string[]]$Arguments){$rows=@(& git -C $Root @Arguments 2>&1);if($LASTEXITCODE-ne0-or$rows.Count-ne1){throw "Fixture Git failed: $($Arguments-join' ')"};([string]$rows[0]).Trim().ToLowerInvariant()}
function GitBlob([string]$Root,[string]$Commit,[string]$Path){$start=[Diagnostics.ProcessStartInfo]::new();$start.FileName=(@(Get-Command git -CommandType Application)[0]).Source;$start.UseShellExecute=$false;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;foreach($a in @('-C',$Root,'cat-file','blob',"$Commit`:$Path")){[void]$start.ArgumentList.Add($a)};$p=[Diagnostics.Process]::new();$p.StartInfo=$start;[void]$p.Start();$m=[IO.MemoryStream]::new();$p.StandardOutput.BaseStream.CopyTo($m);$err=$p.StandardError.ReadToEnd();$p.WaitForExit();if($p.ExitCode-ne0){throw $err};$m.ToArray()}
function GitBlobMap([string]$Root,[string]$Commit,[string[]]$Paths){$start=[Diagnostics.ProcessStartInfo]::new();$start.FileName=(@(Get-Command git -CommandType Application)[0]).Source;$start.UseShellExecute=$false;$start.RedirectStandardInput=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;$start.StandardInputEncoding=[Text.UTF8Encoding]::new($false);foreach($a in @('-C',$Root,'cat-file','--batch')){[void]$start.ArgumentList.Add($a)};$p=[Diagnostics.Process]::new();$p.StartInfo=$start;[void]$p.Start();$inputText=(@($Paths|ForEach-Object{"$Commit`:$($_)"})-join"`n")+"`n";$writeTask=$p.StandardInput.WriteAsync($inputText);$s=$p.StandardOutput.BaseStream;$map=@{};foreach($path in $Paths){$h=[Collections.Generic.List[byte]]::new();while(($b=$s.ReadByte())-ne10){if($b-lt0){throw 'Fixture batch header ended.'};if($b-ne13){$h.Add([byte]$b)}};$header=[Text.Encoding]::ASCII.GetString($h.ToArray());if($header-cnotmatch'^[0-9a-f]{40} blob (?<size>[0-9]+)$'){throw $header};$bytes=[byte[]]::new([int]$Matches.size);$o=0;while($o-lt$bytes.Length){$n=$s.Read($bytes,$o,$bytes.Length-$o);if($n-le0){throw 'Fixture batch payload ended.'};$o+=$n};if($s.ReadByte()-ne10){throw 'Fixture batch delimiter absent.'};$map[$path]=$bytes};[void]$writeTask.GetAwaiter().GetResult();$p.StandardInput.Close();$err=$p.StandardError.ReadToEnd();$p.WaitForExit();if($p.ExitCode-ne0){throw $err};$map}
function Get-ClosurePaths([string]$Root){
 if($null-ne$script:TestClosurePaths){return @($script:TestClosurePaths)}
 $records=@(git -C $Root ls-tree -r --full-tree HEAD|ForEach-Object{if([string]$_ -cnotmatch'^(?<mode>[0-9]{6})\s+(?<type>blob|tree|commit)\s+(?<oid>[0-9a-f]{40})\t(?<path>.+)$'){throw 'Fixture tree inventory malformed.'};[pscustomobject]@{mode=[string]$Matches.mode;type=[string]$Matches.type;oid=[string]$Matches.oid;path=([string]$Matches.path).Replace('\','/')}})
 $script:TestClosurePaths=@($records|Where-Object{[string]$_.type-ceq'blob'}|ForEach-Object{[string]$_.path}|Sort-Object -CaseSensitive);@($script:TestClosurePaths)
}
function New-Closure([string]$Tool,[string]$Commit){$paths=@(Get-ClosurePaths $Tool);$head=GitScalar $Tool @('rev-parse','HEAD');$blobs=$(if($Commit-cne$head){GitBlobMap $Tool $Commit $paths}else{$null});@($paths|ForEach-Object{$path=[string]$_;$bytes=if($null-eq$blobs){[IO.File]::ReadAllBytes((Join-Path $Tool $path))}else{[byte[]]($blobs[$path])};if($null-eq$bytes){throw "Fixture batch omitted '$path' ($($blobs.GetType().FullName)); count=$(@($blobs).Count)"};[pscustomobject][ordered]@{path=$path;sha256=BytesHash $bytes}})}
function New-RouterRoot([string]$Root,[string]$Id,[string]$Commit,[string]$Tree,[string]$Tool){$router=Join-Path $Root $Id;[IO.Directory]::CreateDirectory($router)|Out-Null;[IO.File]::WriteAllText((Join-Path $router 'SKILL.md'),"# $Id`n",[Text.UTF8Encoding]::new($false));$sha=FileHash (Join-Path $router 'SKILL.md');$fingerprint=Canonical ([pscustomobject]@{files=@([pscustomobject]@{path='SKILL.md';sha256=$sha})});$record=[pscustomobject][ordered]@{schema='rusty.morphospace.local_skill_source.v1';skill_id=$Id;installed_at='2026-09-15T08:00:00.0000000Z';source_repository='https://example.invalid/work-environment.git';source_commit=$Commit;source_worktree_dirty=$false;source_release='fixture';source_tree_sha256=$fingerprint;source_files=@([pscustomobject][ordered]@{path='SKILL.md';sha256=$sha});work_environment_root=$Tool};Write-TC (Join-Path $router '.morphospace-skill-source.json') $record;[pscustomobject]@{root=$router;row=[pscustomobject][ordered]@{skill_id=$Id;source_repo_id='workflow';commit=$Commit;tree=$Tree;source_fingerprint=$fingerprint;managed_files=@([pscustomobject][ordered]@{path='SKILL.md';sha256=$sha})}}}
function New-OwnerValidation([string]$BaseCommit,[string]$BaseTree,[string]$HeadCommit,[string]$HeadTree){$empty='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.affected_validation_evidence.v1';repository='MesmerPrism/rusty-morphospace-work-environment';base=[pscustomobject]@{commit=$BaseCommit;tree=$BaseTree};head=[pscustomobject]@{commit=$HeadCommit;tree=$HeadTree};plan_sha256='1'*64;platform='windows';runner=[pscustomobject]@{os_description='Windows tooling-context fixture';powershell_version=$PSVersionTable.PSVersion.ToString()};check_results=@([pscustomobject][ordered]@{check_id='tooling-context-contracts';command_path='scripts/Test-WorkflowContracts.ps1';command_blob_sha1=$HeadCommit;mode='executed';result='pass';started=$true;failure_kind=$null;exit_code=0;timed_out=$false;output_truncated=$false;post_kill_drain_timed_out=$false;stdout_sha256=$empty;stderr_sha256=$empty;stdout_bytes=0;stderr_bytes=0});result='pass';claims=[pscustomobject]@{historical_aggregate_reused=$false;acceptance_authority=$false;publication_authority=$false}}}
function Save-Request([string]$Root,[object]$Request,[string]$Name){$path=Join-Path $Root $Name;Write-TC $path $Request;$path}
function Set-ContextFingerprint([object]$Context){$identity=[ordered]@{context_id=$Context.context_id;project_id=$Context.project_id;preparation_id=$Context.preparation_id;product_projection=$Context.product_projection;resolver=$Context.resolver;executor=$Context.executor;routers=$Context.routers;compatibility=$Context.compatibility;limits=$Context.limits;status=$Context.status};$Context.fingerprint=Canonical $identity;$Context}
function Invoke-Upgrade([object]$Fixture,[string]$RequestPath,[string]$Fault='none'){Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $Fixture.workspace -UnitId 'u002' -ToolingContextUpgrade $RequestPath -ExpectedToolingContextUpgradeSha256 (FileHash $RequestPath) -OutPath (Join-Path $Fixture.workspace "receipts/$([string](Read-TC $RequestPath).upgrade_id)-tooling-context-upgrade-request.json") -Timestamp '2026-09-15T09:00:00.0000000Z' -Execute -FaultAfter $Fault}
function WorkspaceFingerprint([string]$Workspace){Canonical @(Get-ChildItem $Workspace -Recurse -File|Sort-Object FullName|ForEach-Object{[pscustomobject]@{p=$_.FullName.Substring($Workspace.Length).Replace('\','/');h=FileHash $_.FullName}})}

$tool=$repoRoot;$newCommit=$NewCommit;$oldTree=GitScalar $tool @('rev-parse',"$OldCommit^{tree}");$newTree=GitScalar $tool @('rev-parse',"$newCommit^{tree}");$fixtureRoot=Join-Path $HarnessRoot 'project-fixture';$workspace=Join-Path $fixtureRoot 'morphospace';foreach($d in @('receipts','local','tooling-contexts')){[IO.Directory]::CreateDirectory((Join-Path $workspace $d))|Out-Null}
Write-TC (Join-Path $workspace 'receipts/tool-validation-old.json') (New-OwnerValidation $OldCommit $oldTree $OldCommit $oldTree);Write-TC (Join-Path $workspace 'receipts/tool-validation-new.json') (New-OwnerValidation $OldCommit $oldTree $newCommit $newTree);$oldValidation=[pscustomobject]@{path='receipts/tool-validation-old.json';sha256=FileHash (Join-Path $workspace 'receipts/tool-validation-old.json')};$newValidation=[pscustomobject]@{path='receipts/tool-validation-new.json';sha256=FileHash (Join-Path $workspace 'receipts/tool-validation-new.json')}
$actions=@(Get-MorphospaceToolingContextAllowedActions);$protocol=[pscustomobject][ordered]@{protocol_id='tooling-context-v1';product_lock_schema='rusty.morphospace.workflow.development_envelope_source_composition.v3';repository_map_schema='rusty.morphospace.workflow.repository_map.v1';allowed_actions=$actions}
Write-TC (Join-Path $workspace 'receipts/tool-publication-old.json') ([pscustomobject][ordered]@{schema='rusty.morphospace.workflow.tooling_context_publication_evidence.v1';publication_id='tool-old-observed';executor=[pscustomobject][ordered]@{repo_id='workflow';remote_url='https://example.invalid/work-environment.git';commit=$OldCommit;tree=$oldTree};validation=$oldValidation;status='source-observed';does_not_prove=@('Does not independently prove remote publication authority.')})
Write-TC (Join-Path $workspace 'receipts/tool-publication-new.json') ([pscustomobject][ordered]@{schema='rusty.morphospace.workflow.tooling_context_publication_evidence.v1';publication_id='tool-new-observed';executor=[pscustomobject][ordered]@{repo_id='workflow';remote_url='https://example.invalid/work-environment.git';commit=$newCommit;tree=$newTree};validation=$newValidation;status='source-observed';does_not_prove=@('Does not independently prove remote publication authority.')})
Write-TC (Join-Path $workspace 'receipts/tool-protocol-old.json') ([pscustomobject][ordered]@{schema='rusty.morphospace.workflow.tooling_context_protocol_receipt.v1';receipt_id='tool-old-protocol';executor=[pscustomobject][ordered]@{repo_id='workflow';commit=$OldCommit;tree=$oldTree};protocol=$protocol;validation=$oldValidation;status='compatible';does_not_prove=@('Does not authorize product mutation.')})
Write-TC (Join-Path $workspace 'receipts/tool-protocol-new.json') ([pscustomobject][ordered]@{schema='rusty.morphospace.workflow.tooling_context_protocol_receipt.v1';receipt_id='tool-new-protocol';executor=[pscustomobject][ordered]@{repo_id='workflow';commit=$newCommit;tree=$newTree};protocol=$protocol;validation=$newValidation;status='compatible';does_not_prove=@('Does not authorize product mutation.')})
$oldRouterRoot=Join-Path $HarnessRoot 'router-old';$newRouterRoot=Join-Path $HarnessRoot 'router-new';$oldRouter=New-RouterRoot $oldRouterRoot 'rusty-morphospace' $OldCommit $oldTree $tool;$oldSystemRouter=New-RouterRoot $oldRouterRoot 'system-engineering' $OldCommit $oldTree $tool;$newRouter=New-RouterRoot $newRouterRoot 'rusty-morphospace' $newCommit $newTree $tool;$newSystemRouter=New-RouterRoot $newRouterRoot 'system-engineering' $newCommit $newTree $tool
foreach($row in @([pscustomobject]@{id='ctx-old';routers=@($oldRouter,$oldSystemRouter)},[pscustomobject]@{id='ctx-new';routers=@($newRouter,$newSystemRouter)})){Write-TC (Join-Path $workspace "local/$($row.id)-resolver.json") ([pscustomobject][ordered]@{schema='rusty.morphospace.workflow.tooling_context_resolver.v1';context_id=$row.id;executor_root=$tool;routers=@($row.routers|ForEach-Object{[pscustomobject][ordered]@{skill_id=[string]$_.row.skill_id;root=[string]$_.root}});status='resolved';does_not_prove=@('Local resolution only.')})}
$oldCompat=[pscustomobject][ordered]@{protocol_id='tooling-context-v1';product_lock_schema='rusty.morphospace.workflow.development_envelope_source_composition.v3';repository_map_schema='rusty.morphospace.workflow.repository_map.v1';allowed_actions=$actions;receipt=[pscustomobject]@{path='receipts/tool-protocol-old.json';sha256=FileHash (Join-Path $workspace 'receipts/tool-protocol-old.json')}};$newCompat=Clone $oldCompat;$newCompat.receipt=[pscustomobject]@{path='receipts/tool-protocol-new.json';sha256=FileHash (Join-Path $workspace 'receipts/tool-protocol-new.json')}
$oldExecutor=[pscustomobject][ordered]@{repo_id='workflow';remote_url='https://example.invalid/work-environment.git';commit=$OldCommit;tree=$oldTree;publication_evidence=[pscustomobject]@{path='receipts/tool-publication-old.json';sha256=FileHash (Join-Path $workspace 'receipts/tool-publication-old.json')};entrypoint='scripts/ToolingContextUpgrade.psm1';closure=New-Closure $tool $OldCommit};$newExecutor=Clone $oldExecutor;$newExecutor.commit=$newCommit;$newExecutor.tree=$newTree;$newExecutor.publication_evidence=[pscustomobject]@{path='receipts/tool-publication-new.json';sha256=FileHash (Join-Path $workspace 'receipts/tool-publication-new.json')};$newExecutor.closure=New-Closure $tool $newCommit
$descriptor=[pscustomobject][ordered]@{context_id='ctx-old';path='tooling-contexts/ctx-old.json';resolver=[pscustomobject]@{path='local/ctx-old-resolver.json';sha256=FileHash (Join-Path $workspace 'local/ctx-old-resolver.json')};executor=$oldExecutor;routers=@($oldRouter.row,$oldSystemRouter.row);compatibility=$oldCompat}
$seed=New-EnvelopeAdmissionPreparedFixture -Root $fixtureRoot -RepositoryRoot $repoRoot -TransitionLedgerModule $ledgerModule -OwnerProducedPreparation -ToolingContextDescriptor $descriptor;$workspace=$seed.workspace
$projection=[pscustomobject][ordered]@{source_composition=[pscustomobject][ordered]@{path='source-composition.json';sha256=FileHash (Join-Path $workspace 'source-composition.json')};repository_map=[pscustomobject][ordered]@{path='repository-map.json';sha256=FileHash (Join-Path $workspace 'repository-map.json')};feature_lock=[pscustomobject][ordered]@{path='feature.lock.json';sha256=FileHash (Join-Path $workspace 'feature.lock.json')}}
$old=Read-TC (Join-Path $workspace 'tooling-contexts/ctx-old.json')
$new=New-MorphospaceToolingContext -ContextId 'ctx-new' -ProjectId 'envelope-test' -PreparationId 'u002-envelope' -ProductProjection $projection -Resolver ([pscustomobject]@{path='local/ctx-new-resolver.json';sha256=FileHash (Join-Path $workspace 'local/ctx-new-resolver.json')}) -Executor $newExecutor -Routers @($newRouter.row,$newSystemRouter.row) -Compatibility $newCompat
$oldPointer=Clone $seed.preparation_receipt.tooling_context
$admission=Clone $seed.admission_template;if($admission.PSObject.Properties.Name-cnotcontains'admission_kind'){$admission|Add-Member -NotePropertyName admission_kind -NotePropertyValue 'ordinary'};if($admission.preparation.PSObject.Properties.Name-cnotcontains'preparation_kind'){$admission.preparation|Add-Member -NotePropertyName preparation_kind -NotePropertyValue 'ordinary'};$admission.unit.instruction_impact='none';$admission.unit.instruction_surfaces=@();$admission.unit.instruction_none_justification='This documentation-only fixture changes no portable instruction contract.';$admissionPath=Join-Path $HarnessRoot 'admission.json';Write-TC $admissionPath $admission;Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $workspace -DevelopmentUnitAdmission $admissionPath -ExpectedDevelopmentUnitAdmissionSha256 (FileHash $admissionPath) -OutPath (Join-Path $workspace 'receipts/u002-admission.json') -Timestamp '2026-09-15T08:10:00.0000000Z' -Execute|Out-Null
$args=@{WorkspaceRoot=$workspace;UnitId='u002';RepoMapPath=(Join-Path $workspace 'repository-map.json');ValidationTier='quick'};&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a -Action Ready -Timestamp '2026-09-15T08:11:00.0000000Z' -Execute} $args|Out-Null;&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a -Action Claim -Timestamp '2026-09-15T08:12:00.0000000Z' -Execute} $args|Out-Null
& git -C $tool checkout --detach $newCommit|Out-Null;if($LASTEXITCODE-ne0){throw 'Fixture could not advance to new tooling HEAD.'};$automationModule=Import-Module (Join-Path $PSScriptRoot 'WorkUnitAutomation.psm1') -Force -PassThru;$provenanceModule=Import-Module (Join-Path $PSScriptRoot 'ToolingContextProvenance.psm1') -Force -PassThru;$upgradeModule=Import-Module (Join-Path $PSScriptRoot 'ToolingContextUpgrade.psm1') -Force -PassThru
$base=Join-Path $HarnessRoot 'active-base';Copy-Item -LiteralPath $workspace -Destination $base -Recurse
Write-TCPhase 'setup-complete'
function New-UpgradeRequest([string]$Workspace,[string]$Id,[object]$NewContext=$new){
 $state=Read-TC (Join-Path $Workspace 'workspace.state.json');$unit=Read-TC (Join-Path $Workspace 'iteration-units/u002.json');$events=Join-Path $Workspace 'iteration-events.jsonl';$newBytes=ToBytes $NewContext
 $proof=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.tooling_context_compatibility_receipt.v1';proof_id="$Id-proof";project_id='envelope-test';old_context=[pscustomobject]@{context_id=$old.context_id;fingerprint=$old.fingerprint;commit=$old.executor.commit;tree=$old.executor.tree};new_context=[pscustomobject]@{context_id=$NewContext.context_id;fingerprint=$NewContext.fingerprint;commit=$NewContext.executor.commit;tree=$NewContext.executor.tree};consumer=[pscustomobject]@{protocol_id='tooling-context-v1';product_projection=$projection;allowed_actions=$actions};validation=[pscustomobject]@{evidence=[pscustomobject]@{path='receipts/tool-validation-new.json';sha256=FileHash (Join-Path $Workspace 'receipts/tool-validation-new.json')};result='pass'};claims=[pscustomobject]@{same_product_projection=$true;protocol_compatible=$true};status='compatible';does_not_prove=@('Does not validate or publish product bytes.')};$proofPath="receipts/$Id-compatibility.json";Write-TC (Join-Path $Workspace $proofPath) $proof
 [pscustomobject][ordered]@{schema='rusty.morphospace.workflow.tooling_context_upgrade.v1';upgrade_id=$Id;project_id='envelope-test';unit_id='u002';old_context=$oldPointer;new_context=[pscustomobject][ordered]@{path="tooling-contexts/$($NewContext.context_id).json";sha256=BytesHash $newBytes;canonical_sha256=Canonical $NewContext;protocol_id='tooling-context-v1';document=$NewContext};product_projection=$projection;compatibility_receipt=[pscustomobject]@{path=$proofPath;sha256=FileHash (Join-Path $Workspace $proofPath)};expected=[pscustomobject][ordered]@{state_sha256=Canonical $state;state_raw_sha256=FileHash (Join-Path $Workspace 'workspace.state.json');unit_sha256=Canonical $unit;unit_raw_sha256=FileHash (Join-Path $Workspace 'iteration-units/u002.json');events_sha256=FileHash $events;events_length=[IO.FileInfo]::new($events).Length;event_tail_id=[string]$state.last_event_id};does_not_prove=@('Does not mutate product inputs.')}
}
function New-Case([string]$Name){$case=Join-Path $HarnessRoot $Name;Copy-Item -LiteralPath $base -Destination $case -Recurse;[pscustomobject]@{workspace=$case}}

if($Scenario-in@('all','lifecycle')){$positive=New-Case 'positive';$request=New-UpgradeRequest $positive.workspace 'upgrade-positive';$requestPath=Save-Request $HarnessRoot $request 'upgrade-positive.json';$productBefore=(@($projection.PSObject.Properties|ForEach-Object{FileHash (Join-Path $positive.workspace ([string]$_.Value.path))}))-join'|';$dry=Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $positive.workspace -UnitId u002 -ToolingContextUpgrade $requestPath -OutPath (Join-Path $positive.workspace 'receipts/upgrade-positive-tooling-context-upgrade-request.json') -Timestamp '2026-09-15T09:00:00.0000000Z';Assert-TC (-not$dry.executed) 'dry run';$done=Invoke-Upgrade $positive $requestPath;Assert-TC $done.executed 'positive execute'
$unitAfter=Read-TC (Join-Path $positive.workspace 'iteration-units/u002.json');Assert-TC ([string]$unitAfter.tooling_context.path-ceq'tooling-contexts/ctx-new.json') 'positive pointer';Assert-TC (((@($projection.PSObject.Properties|ForEach-Object{FileHash (Join-Path $positive.workspace ([string]$_.Value.path))}))-join'|')-ceq$productBefore) 'positive preserved product bytes';$inspectArgs=@{WorkspaceRoot=$positive.workspace;UnitId='u002';RepoMapPath=(Join-Path $positive.workspace 'repository-map.json');ValidationTier='quick'};$inspection=&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a -Action Inspect} $inspectArgs;Assert-TC ([string]$inspection.action-ceq'Inspect') 'post-upgrade Inspect';$beforeReplay=WorkspaceFingerprint $positive.workspace;$replay=Invoke-Upgrade $positive $requestPath;Assert-TC ($replay.executed-and(WorkspaceFingerprint $positive.workspace)-ceq$beforeReplay) 'exact replay';$event=@(Get-Content -LiteralPath (Join-Path $positive.workspace 'iteration-events.jsonl')|Where-Object{$_}|ForEach-Object{FromBytes ([Text.UTF8Encoding]::new($false).GetBytes([string]$_))})[-1];Test-MorphospaceHistoricalToolingContextUpgrade $positive.workspace $event|Out-Null;Write-TCPhase 'lifecycle-complete'}

if($Scenario-in@('all','recovery')){foreach($fault in @('after-intent','after-artifact','after-projection','after-event')){$f=New-Case "recovery-$fault";$r=New-UpgradeRequest $f.workspace "upgrade-$fault";$rp=Save-Request $HarnessRoot $r "upgrade-$fault.json";$threw=$false;try{Invoke-Upgrade $f $rp $fault|Out-Null}catch{$threw=$_.Exception.Message-like'Injected interruption*'};Assert-TC $threw "fault $fault";$recovered=Invoke-Upgrade $f $rp;Assert-TC $recovered.executed "recovery $fault";$replayed=Invoke-Upgrade $f $rp;Assert-TC $replayed.executed "replay $fault";Write-TCPhase "recovery-$fault-complete"}}

if($Scenario-in@('all','product-negative')){$negative=New-Case 'negative-product';$stale=New-UpgradeRequest $negative.workspace 'upgrade-stale';$stale.expected.unit_raw_sha256='0'*64;$stalePath=Save-Request $HarnessRoot $stale 'stale.json';$rejected=$false;try{Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $negative.workspace -UnitId u002 -ToolingContextUpgrade $stalePath -OutPath (Join-Path $negative.workspace 'receipts/upgrade-stale-tooling-context-upgrade-request.json')|Out-Null}catch{$rejected=$true};Assert-TC $rejected 'stale CAS rejection'
$mapBytes=[IO.File]::ReadAllBytes((Join-Path $negative.workspace 'repository-map.json'));try{[IO.File]::AppendAllText((Join-Path $negative.workspace 'repository-map.json'),' ');$r=New-UpgradeRequest $negative.workspace 'upgrade-map';$r.product_projection=$projection;$rp=Save-Request $HarnessRoot $r 'map.json';$rejected=$false;try{Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $negative.workspace -UnitId u002 -ToolingContextUpgrade $rp -OutPath (Join-Path $negative.workspace 'receipts/upgrade-map-tooling-context-upgrade-request.json')|Out-Null}catch{$rejected=$true};Assert-TC $rejected 'changed map rejection'}finally{[IO.File]::WriteAllBytes((Join-Path $negative.workspace 'repository-map.json'),$mapBytes)}
$sourceBytes=[IO.File]::ReadAllBytes((Join-Path $seed.source_repository 'morphospace/README.md'));try{[IO.File]::AppendAllText((Join-Path $seed.source_repository 'morphospace/README.md'),' ');$r=New-UpgradeRequest $negative.workspace 'upgrade-source';$rp=Save-Request $HarnessRoot $r 'source.json';$rejected=$false;try{Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $negative.workspace -UnitId u002 -ToolingContextUpgrade $rp -OutPath (Join-Path $negative.workspace 'receipts/upgrade-source-tooling-context-upgrade-request.json')|Out-Null}catch{$rejected=$true};Assert-TC $rejected 'changed source rejection'}finally{[IO.File]::WriteAllBytes((Join-Path $seed.source_repository 'morphospace/README.md'),$sourceBytes)};Write-TCPhase 'product-negative-complete'}
if($Scenario-in@('all','provenance-negative')){$negative=New-Case 'negative-provenance';$closurePath=Join-Path $tool 'scripts/ToolingContextUpgrade.psm1';$closureBytes=[IO.File]::ReadAllBytes($closurePath);try{[IO.File]::AppendAllText($closurePath,' ');$r=New-UpgradeRequest $negative.workspace 'upgrade-closure';$rp=Save-Request $HarnessRoot $r 'closure.json';$rejected=$false;try{Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $negative.workspace -UnitId u002 -ToolingContextUpgrade $rp -OutPath (Join-Path $negative.workspace 'receipts/upgrade-closure-tooling-context-upgrade-request.json')|Out-Null}catch{$rejected=$true};Assert-TC $rejected 'changed closure rejection'}finally{[IO.File]::WriteAllBytes($closurePath,$closureBytes)}
$maskedPath='docs/TOOLING_CONTEXT.md';$maskedAbsolute=Join-Path $tool $maskedPath;$maskedBytes=[IO.File]::ReadAllBytes($maskedAbsolute);try{[IO.File]::AppendAllText($maskedAbsolute,' ');& git -C $tool update-index --assume-unchanged -- $maskedPath;if($LASTEXITCODE-ne0){throw 'Fixture could not mask the historical-blob negative.'};$masked=Clone $new;@($masked.executor.closure|Where-Object{[string]$_.path-ceq$maskedPath})[0].sha256=FileHash $maskedAbsolute;$masked=Set-ContextFingerprint $masked;$r=New-UpgradeRequest $negative.workspace 'upgrade-masked-closure' $masked;$rp=Save-Request $HarnessRoot $r 'masked-closure.json';$rejected=$false;try{Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $negative.workspace -UnitId u002 -ToolingContextUpgrade $rp -OutPath (Join-Path $negative.workspace 'receipts/upgrade-masked-closure-tooling-context-upgrade-request.json')|Out-Null}catch{$rejected=$true};Assert-TC $rejected 'assume-unchanged historical blob rejection'}finally{& git -C $tool update-index --no-assume-unchanged -- $maskedPath;[IO.File]::WriteAllBytes($maskedAbsolute,$maskedBytes)}
$dynamic=New-Case 'missing-dynamic-dependency';Write-TC (Join-Path $dynamic.workspace 'local/ctx-missing-dependency-resolver.json') ([pscustomobject][ordered]@{schema='rusty.morphospace.workflow.tooling_context_resolver.v1';context_id='ctx-missing-dependency';executor_root=$tool;routers=@([pscustomobject][ordered]@{skill_id='rusty-morphospace';root=$newRouter.root},[pscustomobject][ordered]@{skill_id='system-engineering';root=$newSystemRouter.root});status='resolved';does_not_prove=@('Local resolution only.')});$missingExecutor=Clone $newExecutor;$missingExecutor.closure=@($missingExecutor.closure|Where-Object{[string]$_.path-cne'scripts/Invoke-WorkUnitAutomation.ps1'});Assert-TC ($missingExecutor.closure.Count-lt$newExecutor.closure.Count) 'dynamic dependency fixture selection';$missing=New-MorphospaceToolingContext -ContextId 'ctx-missing-dependency' -ProjectId 'envelope-test' -PreparationId 'u002-envelope' -ProductProjection $projection -Resolver ([pscustomobject]@{path='local/ctx-missing-dependency-resolver.json';sha256=FileHash (Join-Path $dynamic.workspace 'local/ctx-missing-dependency-resolver.json')}) -Executor $missingExecutor -Routers @($newRouter.row,$newSystemRouter.row) -Compatibility $newCompat;$r=New-UpgradeRequest $dynamic.workspace 'upgrade-missing-dependency' $missing;$rp=Save-Request $HarnessRoot $r 'missing-dependency.json';$rejected=$false;try{Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $dynamic.workspace -UnitId u002 -ToolingContextUpgrade $rp -OutPath (Join-Path $dynamic.workspace 'receipts/upgrade-missing-dependency-tooling-context-upgrade-request.json')|Out-Null}catch{$rejected=$true};Assert-TC $rejected 'undeclared dynamic dependency rejection'
$forged=New-Case 'forged';$r=New-UpgradeRequest $forged.workspace 'upgrade-forged';$proofPath=Join-Path $forged.workspace $r.compatibility_receipt.path;$proof=Read-TC $proofPath;$proof.new_context.commit=$OldCommit;Write-TC $proofPath $proof;$r.compatibility_receipt.sha256=FileHash $proofPath;$rp=Save-Request $HarnessRoot $r 'forged.json';$rejected=$false;try{Invoke-MorphospaceUpgradeToolingContext -WorkspaceRoot $forged.workspace -UnitId u002 -ToolingContextUpgrade $rp -OutPath (Join-Path $forged.workspace 'receipts/upgrade-forged-tooling-context-upgrade-request.json')|Out-Null}catch{$rejected=$true};Assert-TC $rejected 'forged compatibility rejection';Write-TCPhase 'provenance-negative-complete'}
[pscustomobject]@{result='pass';action='UpgradeToolingContext';scenario=$Scenario;faults=$(if($Scenario-in@('all','recovery')){@('after-intent','after-artifact','after-projection','after-event')}else{@()});real_git=$true;bound_executor=$true;remote_mutation_performed=$false}|ConvertTo-Json -Compress
