[CmdletBinding()]
param([switch]$SelfTest)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'ValidationOnlyWriteScopeNarrowing.psm1') -Force
$script:Protocol=Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceProtocolCommon.psm1') -Force -PassThru
$script:SourceComposition=Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceSourceCompositionIdentity.psm1') -Force -PassThru
$script:GitExe=(@(Get-Command git -CommandType Application -ErrorAction Stop)[0]).Source
function Assert-Narrow([bool]$Condition,[string]$Message){if(-not $Condition){throw "NarrowValidationOnlyWriteScope self-test failed: $Message"}}
function Write-Json([string]$Path,[object]$Value){[IO.Directory]::CreateDirectory((Split-Path $Path -Parent))|Out-Null;[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 64)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))}
function Read-Json([string]$Path){Get-Content -Raw -LiteralPath $Path|ConvertFrom-Json -DateKind String}
function Write-ProtocolJson([string]$Path,[object]$Value){[IO.Directory]::CreateDirectory((Split-Path $Path -Parent))|Out-Null;& $script:Protocol {param($p,$v)[IO.File]::WriteAllBytes($p,(ConvertTo-MorphospaceProtocolJsonBytes $v))} $Path $Value}
function Clone([object]$Value){$Value|ConvertTo-Json -Depth 64|ConvertFrom-Json -DateKind String}
function Git([string]$Path,[string[]]$Arguments){$out=@(& $script:GitExe -C $Path @Arguments 2>&1|ForEach-Object{[string]$_});if($LASTEXITCODE-ne0){throw "fixture git $($Arguments-join' ') failed: $($out-join'; ')"};@($out)}
function FileHash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Canonical([object]$Value){& $script:Protocol {param($v)Get-MorphospaceCanonicalJsonSha256 $v} $Value}
function Fingerprint([string]$Root){@(Get-ChildItem -LiteralPath $Root -Recurse -File|Sort-Object FullName|ForEach-Object{"$([IO.Path]::GetRelativePath($Root,$_.FullName).Replace('\','/'))|$(FileHash $_.FullName)"})-join'|'}
function Assert-Rejected([scriptblock]$Action,[string]$Name,[object]$Fixture){$before=Fingerprint $Fixture.workspace;$heads=@($Fixture.sources|ForEach-Object{@(Git $_.path @('rev-parse','HEAD'))[0].Trim()})-join'|';$rejected=$false;try{&$Action|Out-Null}catch{$rejected=$true};Assert-Narrow $rejected "accepted $Name";Assert-Narrow ((Fingerprint $Fixture.workspace)-ceq$before) "rejected $Name mutated workspace bytes";Assert-Narrow ((@($Fixture.sources|ForEach-Object{@(Git $_.path @('rev-parse','HEAD'))[0].Trim()})-join'|')-ceq$heads) "rejected $Name changed locked sources"}
function New-Source([string]$Root,[int]$Ordinal){$id="source-$Ordinal";$path=Join-Path $Root $id;[IO.Directory]::CreateDirectory($path)|Out-Null;Git $path @('init','--initial-branch=main')|Out-Null;Git $path @('config','core.autocrlf','false')|Out-Null;Git $path @('config','user.email','fixture@example.invalid')|Out-Null;Git $path @('config','user.name','Fixture')|Out-Null;[IO.File]::WriteAllText((Join-Path $path 'README.md'),"source-$Ordinal",[Text.UTF8Encoding]::new($false));Git $path @('add','README.md')|Out-Null;Git $path @('commit','-m','fixture')|Out-Null;[pscustomobject]@{id=$id;path=$path;commit=@(Git $path @('rev-parse','HEAD'))[0].Trim().ToLowerInvariant();tree=@(Git $path @('rev-parse','HEAD^{tree}'))[0].Trim().ToLowerInvariant()}}
function New-Fixture([string]$Root,[ValidateRange(1,2)][int]$SourceCount=2,[ValidateSet('active','validating')][string]$Status='validating'){
 [IO.Directory]::CreateDirectory($Root)|Out-Null;$workspace=Join-Path $Root 'morphospace';foreach($dir in @('iteration-units','receipts','source-compositions')){[IO.Directory]::CreateDirectory((Join-Path $workspace $dir))|Out-Null};$sources=@(1..$SourceCount|ForEach-Object{New-Source $Root $_});$repos=@($sources|ForEach-Object{[pscustomobject][ordered]@{repo_id=$_.id;role='application';path="<$($_.id)>";allowed_paths=@('morphospace')}})
 $project=[pscustomobject][ordered]@{'$schema'='https://github.com/MesmerPrism/rusty-morphospace-work-environment/schemas/project-spec-v2.schema.json';schema='rusty.morphospace.workflow.project_spec.v2';project_id='narrowing-project';revision=1;owner='fixture';purpose='Narrow test.';activation_model=[pscustomobject]@{default='disabled';unlisted_modules='inert';runtime_rule='selected-lock-and-runtime-input'};composition=[pscustomobject]@{selected_features=@();denied_features=@();selected_modules=@();denied_modules=@();allowed_permissions=@();denied_permissions=@();data_classes=@('fixture')};authority_map=@([pscustomobject]@{parameter='project.composition';owner=$sources[0].id;adapters=@()});repositories=$repos;modules=@();non_scope=@('No source mutation.');validation_profiles=@([pscustomobject]@{profile_id='quick';commands=@('fixture')});acceptance_profiles=@([pscustomobject]@{profile_id='rollback';commands=@('fixture')});release_policy=[pscustomobject]@{versioning='semver';commit_policy='fixture';push_checkpoint='local-only';source_first=$true;planning_last=$true;force_push_allowed=$false};public_boundary=[pscustomobject]@{mode='public';private_overlay='local/';prohibited_evidence=@('private')}}
 $allowed=@($sources|ForEach-Object{[pscustomobject][ordered]@{repo_id=$_.id;allowed_paths=@('morphospace')}})
 $unit=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.iteration_unit.v1';unit_id='validation-only-001';project_id='narrowing-project';status=$Status;work_mode='validation-only';objective='Narrow declared validation-only paths.';change_categories=@('validation');instruction_impact='review';instruction_surfaces=@([pscustomobject]@{path='README.md';surface_kind='readme';owner='fixture';change_reason='Review the bounded validation-only declaration.';action='review-no-change';status='complete';validation='fixture';skill_id=$null});instruction_none_justification=$null;prerequisites=@();allowed_repositories=$allowed;read_only_dependencies=@();non_scope=@('No source mutation.');acceptance=@([pscustomobject]@{acceptance_id='scope';proof='No source bytes change.';command='fixture'});risk_tier='quick';device_requirement='forbidden';validation=@([pscustomobject]@{profile_id='quick';command='fixture'});outputs=@('receipt');commit_policy='fixture';push_checkpoint='local-only';source_composition=[pscustomobject]@{mode='exact-lock';lock_path='source-compositions/validation-only-001.lock.json';materialization_receipt=$null};claim_requirements=[pscustomobject]@{minimum_free_disk_mib=0;required_tools=@();product_inputs=@()}}
 $eventId='validation-only-001-inflight-0001';$state=[pscustomobject][ordered]@{'$schema'='https://github.com/MesmerPrism/rusty-morphospace-work-environment/schemas/workspace-state-v2.schema.json';schema='rusty.morphospace.workflow.workspace_state.v2';project_id='narrowing-project';plan_revision=1;current_unit='validation-only-001';next_ready_unit=$null;last_event_id=$eventId;last_accepted_receipt=$null;repository_heads=@();module_registry=[pscustomobject]@{lock_revision=1;lock_fingerprint=('0'*64);modules=@()};capability_registry=@();dirty_repositories=@();blockers=@();validation_checkpoint=$null;pending_push_bundle=$null};$event=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.iteration_event.v1';event_id=$eventId;sequence=1;timestamp='2026-09-08T10:00:00.0000000Z';project_id='narrowing-project';unit_id='validation-only-001';event_type='state-transition';summary='fixture';receipts=@()}
 $rows=@($sources|ForEach-Object{[pscustomobject][ordered]@{repo_id=$_.id;role='source';remote_url="https://example.invalid/$($_.id).git";branch='main';commit=$_.commit;tree=$_.tree;materialization_path=$_.id;tracked_worktree_clean=$true}});$lock=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.source_composition_lock.v1';lock_id='validation-only-001-lock';project_id='narrowing-project';unit_id='validation-only-001';created_at='2026-09-08T10:00:00.0000000Z';status='locked';repositories=$rows;fingerprint=(& $script:SourceComposition {param($r)Get-MorphospaceSourceCompositionFingerprint -ProjectId 'narrowing-project' -UnitId 'validation-only-001' -Repositories $r} $rows);does_not_prove=@('No source mutation.')}
 $p=[pscustomobject]@{workspace=$workspace;project=(Join-Path $workspace 'project.spec.json');state=(Join-Path $workspace 'workspace.state.json');unit=(Join-Path $workspace 'iteration-units\validation-only-001.json');events=(Join-Path $workspace 'iteration-events.jsonl');lock=(Join-Path $workspace 'source-compositions\validation-only-001.lock.json');map=(Join-Path $Root 'repository-map.json');out=(Join-Path $workspace 'receipts\validation-only-001-narrowed.json')}
 if($Status -ceq 'validating'){$state.validation_checkpoint=[pscustomobject][ordered]@{tier='quick';result='pass';receipt='receipts/predecessor-pass.json'};Write-Json (Join-Path $workspace 'receipts\predecessor-pass.json') ([pscustomobject]@{unit_id='predecessor-016'})}
 Write-ProtocolJson $p.project $project
 Write-Json $p.state $state
 Write-Json $p.unit $unit
 Write-Json $p.lock $lock
 [IO.File]::WriteAllText($p.events,(($event|ConvertTo-Json -Compress)+[Environment]::NewLine),[Text.UTF8Encoding]::new($false))
 $map=[pscustomobject]@{schema='rusty.morphospace.workflow.repository_map.v1';repositories=@($sources|ForEach-Object{[pscustomobject]@{repo_id=$_.id;path=$_.path;role='source'}})}
 Write-Json $p.map $map
 [pscustomobject]@{root=$Root;workspace=$workspace;sources=$sources;paths=$p;tail=$eventId}
}
function New-Request([object]$F,[string]$Id='validation-only-001-narrowed'){$project=Read-Json $F.paths.project;$state=Read-Json $F.paths.state;$unit=Read-Json $F.paths.unit;$after=@($unit.allowed_repositories|ForEach-Object{Clone $_});$after[0].allowed_paths=@();[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.validation_only_write_scope_narrowing.v1';narrowing_id=$Id;project_id='narrowing-project';unit_id='validation-only-001';expected=[pscustomobject][ordered]@{status=[string]$unit.status;current_unit='validation-only-001';project_sha256=(Canonical $project);project_raw_sha256=(FileHash $F.paths.project);state_sha256=(Canonical $state);state_raw_sha256=(FileHash $F.paths.state);unit_sha256=(Canonical $unit);unit_raw_sha256=(FileHash $F.paths.unit);source_composition_path='source-compositions/validation-only-001.lock.json';source_composition_sha256=(FileHash $F.paths.lock);repository_map_sha256=(FileHash $F.paths.map);events_sha256=(FileHash $F.paths.events);events_length=[IO.FileInfo]::new($F.paths.events).Length;event_tail_id=$F.tail};before_allowed_repositories=@($unit.allowed_repositories|ForEach-Object{Clone $_});after_allowed_repositories=$after;does_not_prove=@('No source mutation, validation, or publication.')}}
function Save-Request([object]$F,[object]$R,[string]$Name='request.json'){$path=Join-Path $F.root $Name;Write-Json $path $R;$path}
function Invoke-Narrow([object]$F,[string]$RequestPath,[switch]$Execute,[string]$Expected='',[scriptblock]$Hook=$null){Invoke-MorphospaceNarrowValidationOnlyWriteScope -WorkspaceRoot $F.workspace -UnitId 'validation-only-001' -RepoMapPath $F.paths.map -ValidationOnlyWriteScopeNarrowing $RequestPath -ExpectedValidationOnlyWriteScopeNarrowingSha256 $Expected -OutPath $F.paths.out -Timestamp '2026-09-08T11:00:00.0000000Z' -BeforeTransitionHook $Hook -Execute:$Execute}
function Invoke-NarrowControl([object]$Fixture,[string]$RequestPath,[string]$Expected='',[string]$Timestamp='',[string]$FaultAfter='none'){
    $request=Read-Json $RequestPath;$outPath=Join-Path $Fixture.workspace ("receipts/$([string]$request.narrowing_id).json")
    $arguments=@{WorkspaceRoot=$Fixture.workspace;UnitId='validation-only-001';RepoMapPath=$Fixture.paths.map;ValidationOnlyWriteScopeNarrowing=$RequestPath;OutPath=$outPath;Execute=$true}
    if($Expected){$arguments.ExpectedValidationOnlyWriteScopeNarrowingSha256=$Expected}
    if($Timestamp){$arguments.Timestamp=$Timestamp}
    if($FaultAfter-ne'none'){$arguments.FaultAfter=$FaultAfter}
    Invoke-MorphospaceNarrowValidationOnlyWriteScope @arguments
}
function Assert-RecoveryFault([scriptblock]$Action,[string]$Stage,[object]$Fixture,[object]$Request){
    $messages=@{'after-intent'='Injected interruption after intent publication.';'after-artifact'='Injected interruption after artifact installation.';'after-projection'='Injected interruption after projections.';'after-event'='Injected interruption after event append.'}
    $faulted=$false
    try{&$Action|Out-Null}catch{if($_.Exception.Message-cne$messages[$Stage]){throw "Unexpected $Stage fault: $($_.Exception.Message)"};$faulted=$true}
    Assert-Narrow $faulted "missing $Stage fault"
    $eventId="$($Request.narrowing_id)-recorded";$intent=Join-Path $Fixture.workspace "receipts/transactions/$eventId-transition.intent.json"
    Assert-Narrow (Test-Path $intent) "$Stage did not write transition intent"
    if($Stage-ne'after-intent'){$artifact=Join-Path $Fixture.workspace ("receipts/$([string]$Request.narrowing_id).json");Assert-Narrow (Test-Path $artifact) "$Stage did not install request artifact"}
    if($Stage-in@('after-projection','after-event')){Assert-Narrow ([string](Read-Json $Fixture.paths.state).last_event_id-ceq$eventId) "$Stage did not project state tail"}
    if($Stage-eq'after-event'){$events=@(Get-Content $Fixture.paths.events|ForEach-Object{ConvertFrom-Json $_});Assert-Narrow ([string]$events[-1].event_id-ceq$eventId) "$Stage did not append event"}
}
function Exercise-NarrowRecovery([string]$Root,[string]$Stage){
    $fixture=New-Fixture (Join-Path $Root "recovery-$Stage") -SourceCount 1
    $request=New-Request $fixture "recovery-$Stage";$requestPath=Save-Request $fixture $request "recovery-$Stage.json";$hash=FileHash $requestPath;$originalTimestamp='2026-09-08T12:00:00.0000000Z'
    Assert-RecoveryFault {Invoke-NarrowControl $fixture $requestPath $hash $originalTimestamp $Stage} $Stage $fixture $request
    $changed=Join-Path $fixture.root "recovery-$Stage-changed.json";[IO.File]::WriteAllText($changed,((Get-Content -Raw $requestPath)+' '),[Text.UTF8Encoding]::new($false))
    Assert-Rejected {Invoke-NarrowControl $fixture $changed (FileHash $changed)} "$Stage recovery changed request" $fixture
    $recovered=Invoke-NarrowControl $fixture $requestPath $hash
    Assert-Narrow ($recovered.executed-and[string]$recovered.timestamp-ceq$originalTimestamp-and[string]$recovered.event_id-ceq"$($request.narrowing_id)-recorded") "$Stage recovery did not retain original committed semantics"
    $beforeReplay=Fingerprint $fixture.workspace;$replay=Invoke-NarrowControl $fixture $requestPath $hash
    Assert-Narrow ($replay.executed-and[string]$replay.timestamp-ceq$originalTimestamp-and[string]$replay.event_id-ceq$recovered.event_id) "$Stage committed replay did not return original committed truth"
    Assert-Narrow ((Fingerprint $fixture.workspace)-ceq$beforeReplay) "$Stage committed replay mutated authoritative workspace bytes"
    $events=@(Get-Content $fixture.paths.events|ForEach-Object{ConvertFrom-Json $_});Assert-Narrow (@($events|Where-Object{[string]$_.event_id-ceq$recovered.event_id}).Count-eq1) "$Stage recovery duplicated its event"
}
function Exercise-ForgedNarrowIntent([string]$Root){
    $fixture=New-Fixture (Join-Path $Root 'forged-intent') -SourceCount 1
    $request=New-Request $fixture 'forged-intent';$requestPath=Save-Request $fixture $request 'forged-intent.json';$hash=FileHash $requestPath
    Assert-RecoveryFault {Invoke-NarrowControl $fixture $requestPath $hash '2026-09-08T12:00:00.0000000Z' 'after-intent'} 'after-intent' $fixture $request
    $intentPath=Join-Path $fixture.workspace "receipts/transactions/$($request.narrowing_id)-recorded-transition.intent.json";$intent=Read-Json $intentPath;$intent.target.unit.document.allowed_repositories[0].allowed_paths=@('morphospace');Write-Json $intentPath $intent
    Assert-Rejected {Invoke-NarrowControl $fixture $requestPath $hash} 'forged recovery target intent' $fixture
}
function Remove-Fixture([string]$Root){$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\','/');$candidate=[IO.Path]::GetFullPath($Root).TrimEnd('\','/');if(-not([IO.Path]::GetDirectoryName($candidate).TrimEnd('\','/').Equals($temp,[StringComparison]::OrdinalIgnoreCase))-or-not([IO.Path]::GetFileName($candidate).StartsWith('validation-only-narrowing-',[StringComparison]::Ordinal))){throw "refusing fixture cleanup $candidate"};if(Test-Path $candidate){Remove-Item -LiteralPath $candidate -Recurse -Force}}
$root=Join-Path ([IO.Path]::GetTempPath())('validation-only-narrowing-'+[guid]::NewGuid().ToString('N'))
try{
 foreach($count in @(1,2)){$f=New-Fixture (Join-Path $root "success-$count") -SourceCount $count;$r=New-Request $f;$rp=Save-Request $f $r "success-$count.json";$before=Fingerprint $f.workspace;$dry=Invoke-Narrow $f $rp;Assert-Narrow (-not$dry.executed-and$null-eq$dry.event_id) "dry $count source result";Assert-Narrow ((Fingerprint $f.workspace)-ceq$before) "dry $count source mutation";Assert-Narrow (-not(Test-Path $f.paths.out)) "dry $count created artifact";if($count-eq2){$wrapped=&(Join-Path $PSScriptRoot 'Invoke-WorkUnitAutomation.ps1') -Action NarrowValidationOnlyWriteScope -WorkspaceRoot $f.workspace -UnitId 'validation-only-001' -RepoMapPath $f.paths.map -ValidationOnlyWriteScopeNarrowing $rp -OutPath $f.paths.out -Timestamp '2026-09-08T11:00:00.0000000Z'|ConvertFrom-Json;Assert-Narrow ([string]$wrapped.action-ceq'NarrowValidationOnlyWriteScope') 'wrapper forwarding'};$hash=FileHash $rp;Assert-Rejected {Invoke-Narrow $f $rp -Execute} "execute without reviewed hash ($count)" $f;$done=Invoke-Narrow $f $rp -Execute -Expected $hash;Assert-Narrow ($done.executed-and[string]$done.event_id-ceq"$($r.narrowing_id)-recorded") "execute $count receipt";$unit=Read-Json $f.paths.unit;$state=Read-Json $f.paths.state;Assert-Narrow (@($unit.allowed_repositories).Count-eq$count-and@($unit.allowed_repositories[0].allowed_paths).Count-eq0) "execute $count empty validation-only row";Assert-Narrow ([string]$state.current_unit-ceq'validation-only-001'-and[string]$state.last_event_id-ceq"$($r.narrowing_id)-recorded") "execute $count state drift";Assert-Narrow ((FileHash $f.paths.out)-ceq$hash) "execute $count artifact bytes";Assert-Narrow ((Test-Path (Join-Path $f.workspace "receipts/transactions/$($r.narrowing_id)-recorded-transition.intent.json"))-and(Test-Path (Join-Path $f.workspace "receipts/transactions/$($r.narrowing_id)-recorded-transition.completion.json"))) "execute $count transaction evidence"}
    Assert-Narrow ([string]$state.validation_checkpoint.receipt-ceq'receipts/predecessor-pass.json') "execute $count did not preserve predecessor validation checkpoint";
 $f=New-Fixture (Join-Path $root 'negatives') -SourceCount 2;$r=New-Request $f;$rp=Save-Request $f $r;$newPath=Clone $r;$newPath.after_allowed_repositories[0].allowed_paths=@('morphospace','new-path');Assert-Rejected {Invoke-Narrow $f (Save-Request $f $newPath 'new-path.json')} 'new path' $f;$newRepo=Clone $r;$newRepo.after_allowed_repositories[0].repo_id='new-repository';Assert-Rejected {Invoke-Narrow $f (Save-Request $f $newRepo 'new-repo.json')} 'new repository' $f;$stale=Clone $r;$stale.expected.unit_raw_sha256='0'*64;Assert-Rejected {Invoke-Narrow $f (Save-Request $f $stale 'stale.json')} 'stale raw unit hash' $f
 $feature=New-Fixture (Join-Path $root 'feature') -SourceCount 1 -Status active;$u=Read-Json $feature.paths.unit;$u.work_mode='feature';$u.allowed_repositories[0].allowed_paths=@();Write-Json $feature.paths.unit $u;Assert-Rejected {Invoke-Narrow $feature (Save-Request $feature (New-Request $feature))} 'feature empty scope' $feature
 $wrongStatus=New-Fixture (Join-Path $root 'status') -SourceCount 1;$u=Read-Json $wrongStatus.paths.unit;$u.status='ready';Write-Json $wrongStatus.paths.unit $u;Assert-Rejected {Invoke-Narrow $wrongStatus (Save-Request $wrongStatus (New-Request $wrongStatus))} 'wrong status' $wrongStatus
 $wrongCurrent=New-Fixture (Join-Path $root 'current') -SourceCount 1;$s=Read-Json $wrongCurrent.paths.state;$s.current_unit='other-unit';Write-Json $wrongCurrent.paths.state $s;Assert-Rejected {Invoke-Narrow $wrongCurrent (Save-Request $wrongCurrent (New-Request $wrongCurrent))} 'wrong current unit' $wrongCurrent
 $checkpoint=New-Fixture (Join-Path $root 'checkpoint') -SourceCount 1;Write-Json (Join-Path $checkpoint.workspace 'receipts\same.json') ([pscustomobject]@{unit_id='validation-only-001'});$s=Read-Json $checkpoint.paths.state;$s.validation_checkpoint=[pscustomobject]@{tier='quick';result='pass';receipt='receipts/same.json'};Write-Json $checkpoint.paths.state $s;Assert-Rejected {Invoke-Narrow $checkpoint (Save-Request $checkpoint (New-Request $checkpoint))} 'same-unit checkpoint' $checkpoint
 $pending=New-Fixture (Join-Path $root 'pending') -SourceCount 1;Write-Json (Join-Path $pending.workspace 'receipts\transactions\foreign-transition.intent.json') ([pscustomobject]@{transaction_id='foreign-transition'});Assert-Rejected {Invoke-Narrow $pending (Save-Request $pending (New-Request $pending))} 'foreign pending transaction' $pending
 foreach($kind in @('map','lock','source')){
   $h=New-Fixture (Join-Path $root "hook-$kind") -SourceCount 1
   $request=New-Request $h;$path=Save-Request $h $request;$hash=FileHash $path
   $beforeWorkspace=Fingerprint $h.workspace
   $authorityBefore=@($h.paths.project,$h.paths.state,$h.paths.unit,$h.paths.events|ForEach-Object{FileHash $_})-join'|'
   $target=if($kind-eq'map'){$h.paths.map}elseif($kind-eq'lock'){$h.paths.lock}else{Join-Path $h.sources[0].path 'README.md'}
   $rejected=$false
   try{Invoke-Narrow $h $path -Execute -Expected $hash -Hook {[IO.File]::AppendAllText($target,' ')}|Out-Null}catch{$rejected=$true}
   Assert-Narrow $rejected "after-hook $kind drift accepted"
   $authorityAfter=@($h.paths.project,$h.paths.state,$h.paths.unit,$h.paths.events|ForEach-Object{FileHash $_})-join'|'
   Assert-Narrow ($authorityAfter-ceq$authorityBefore) "after-hook $kind wrote project, state, unit, or event bytes"
   Assert-Narrow (-not(Test-Path $h.paths.out)) "after-hook $kind installed an owned receipt"
   if($kind-eq'source'){Assert-Narrow ((Fingerprint $h.workspace)-ceq$beforeWorkspace) 'after-hook source drift wrote authoritative workspace bytes'}
 }
 foreach($stage in @('after-intent','after-artifact','after-projection','after-event')){Exercise-NarrowRecovery $root $stage}
 Exercise-ForgedNarrowIntent $root
 [pscustomobject]@{result='pass';action='NarrowValidationOnlyWriteScope';source_counts=@(1,2);device_mutation_performed=$false;remote_mutation_performed=$false}|ConvertTo-Json -Compress
}finally{if(Test-Path $root){Remove-Fixture $root}}
