param([string]$Path="",[string]$WorkspaceRoot="",[switch]$SelfTest)
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospacePlannedPublication.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospacePublishedPrerequisiteSuffix.psm1') -Force
function Write-Json($Path,$Value){$parent=Split-Path -Parent $Path;if($parent-and-not(Test-Path $parent)){New-Item -ItemType Directory $parent|Out-Null};[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 32)+"`n",[Text.UTF8Encoding]::new($false))}
function Hash($Path){(Get-FileHash $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Invoke-FixtureGit($Repo,[string[]]$GitArgs){$o=@(& (Get-Command git -CommandType Application).Source -C $Repo @GitArgs 2>&1);if($LASTEXITCODE){throw "git $($GitArgs-join' ') failed: $($o-join' ')"};if($o.Count){([string]($o|Select-Object -Last 1)).Trim()}else{''}}
function Clone($Value){$Value|ConvertTo-Json -Depth 32|ConvertFrom-Json}
function Reject([scriptblock]$Action,[string]$Name){try{&$Action|Out-Null}catch{return};throw "Damaged published-prerequisite case '$Name' was accepted."}

if($SelfTest){
 $root=Join-Path ([IO.Path]::GetTempPath()) ('published-prerequisite-'+[guid]::NewGuid().ToString('N'));$ws=Join-Path $root 'planning\project\morphospace';$src=Join-Path $root 'source';$planning=Split-Path (Split-Path $ws -Parent) -Parent
 try{
  foreach($repo in @($src,$planning)){New-Item -ItemType Directory $repo -Force|Out-Null;Invoke-FixtureGit $repo @('init','-q');Invoke-FixtureGit $repo @('config','user.email','fixture@example.invalid');Invoke-FixtureGit $repo @('config','user.name','Fixture');Invoke-FixtureGit $repo @('config','core.autocrlf','false');Invoke-FixtureGit $repo @('checkout','-q','-b','main');[IO.File]::WriteAllText((Join-Path $repo 'base.txt'),"base`n");Invoke-FixtureGit $repo @('add','.');Invoke-FixtureGit $repo @('commit','-q','-m','base')}
  $srcOld=Invoke-FixtureGit $src @('rev-parse','HEAD');[IO.File]::WriteAllText((Join-Path $src 'accepted.txt'),"accepted`n");Invoke-FixtureGit $src @('add','.');Invoke-FixtureGit $src @('commit','-q','-m','accepted source');$srcFinal=Invoke-FixtureGit $src @('rev-parse','HEAD');$srcTree=Invoke-FixtureGit $src @('rev-parse','HEAD^{tree}')
  $planOld=Invoke-FixtureGit $planning @('rev-parse','HEAD');New-Item -ItemType Directory $ws -Force|Out-Null;[IO.File]::WriteAllText((Join-Path $ws 'prepared.txt'),"prepared`n");Invoke-FixtureGit $planning @('add','.');Invoke-FixtureGit $planning @('commit','-q','-m','prepare');$prepared=Invoke-FixtureGit $planning @('rev-parse','HEAD')
  New-Item -ItemType Directory (Join-Path $ws 'receipts') -Force|Out-Null;Write-Json (Join-Path $ws 'unit-status.json') ([ordered]@{unit_id='trigger-unit';status='accepted'});Write-Json (Join-Path $ws 'prepared-event.json') ([ordered]@{event_id='trigger-unit-push-prepared-0001';event_type='commit'})
  $plan=[ordered]@{schema='rusty.morphospace.workflow.push_bundle_plan.v1';bundle_id='trigger-unit-push-bundle';project_id='test-project';unit_ids=@('trigger-unit');prepared_at='2026-07-20T10:00:00Z';dependency_order=@('source-repo','planning-repo');repositories=@([ordered]@{repo_id='source-repo';role='source';branch='main';commit=$srcFinal;upstream='origin/main';ahead=0;behind=0},[ordered]@{repo_id='planning-repo';role='planning';branch='main';commit=$prepared;upstream='origin/main';ahead=0;behind=0});source_first=$true;planning_last=$true;execution='not-performed';force_push_allowed=$false};Write-Json (Join-Path $ws 'receipts\plan.json') $plan
  $executed=[ordered]@{schema='rusty.morphospace.workflow.executed_push_receipt.v1';receipt_id='executed-receipt';bundle_id=$plan.bundle_id;project_id=$plan.project_id;unit_ids=@('trigger-unit');prepared_plan_id=$plan.bundle_id;started_at='2026-07-20T10:01:00Z';finished_at='2026-07-20T10:02:00Z';status='validated-pushed';execution='externally-performed';dependency_order=@('source-repo','planning-repo');execution_order=@('source-repo','planning-repo');repositories=@([ordered]@{repo_id='source-repo';old_revision=$srcOld;new_revision=$srcFinal;observed_remote_revision=$srcFinal},[ordered]@{repo_id='planning-repo';old_revision=$planOld;new_revision=$prepared;observed_remote_revision=$prepared});force_push_used=$false;remote_readback_complete=$true;failure=$null};$executedPath=Join-Path $ws 'receipts\executed.json';Write-Json $executedPath $executed
  $account=[ordered]@{schema='rusty.morphospace.workflow.planned_publication_accounting.v1';accounting_id='publication-accounting';project_id='test-project';bundle_id=$plan.bundle_id;trigger_unit_id='trigger-unit';prepared_plan=[ordered]@{path='receipts/plan.json';sha256=Hash (Join-Path $ws 'receipts\plan.json')};prepared_event=[ordered]@{event_id='trigger-unit-push-prepared-0001';path='prepared-event.json';sha256=Hash (Join-Path $ws 'prepared-event.json')};executed_push_receipt=[ordered]@{path='receipts/executed.json';sha256=Hash $executedPath};chronology=[ordered]@{prepared_at='2026-07-20T10:00:00Z';push_started_at='2026-07-20T10:01:00Z';push_finished_at='2026-07-20T10:02:00Z';accounted_at='2026-07-20T10:03:00Z'};dependency_order=@('source-repo','planning-repo');execution_order=@('source-repo','planning-repo');repositories=@([ordered]@{repo_id='source-repo';role='source';branch='main';upstream='origin/main';old_revision=$srcOld;prepared_revision=$srcFinal;final_revision=$srcFinal;remote_readback_revision=$srcFinal;source_first=$true;planning_last=$false;fast_forward_verified=$true;force_push_used=$false;worktree_clean=$true;units=@([ordered]@{unit_id='trigger-unit';role='triggering-unit';status_at_publication='accepted';status_evidence=[ordered]@{path='unit-status.json';sha256=Hash (Join-Path $ws 'unit-status.json')};no_acceptance_claim=$false});commits=@([ordered]@{revision=$srcFinal;role='triggering-unit';unit_id='trigger-unit';changed_paths=@('accepted.txt')});allowed_finalization_paths=@()},[ordered]@{repo_id='planning-repo';role='planning-transport';branch='main';upstream='origin/main';old_revision=$planOld;prepared_revision=$prepared;final_revision=$prepared;remote_readback_revision=$prepared;source_first=$false;planning_last=$true;fast_forward_verified=$true;force_push_used=$false;worktree_clean=$true;units=@([ordered]@{unit_id='trigger-unit';role='triggering-unit';status_at_publication='accepted';status_evidence=[ordered]@{path='unit-status.json';sha256=Hash (Join-Path $ws 'unit-status.json')};no_acceptance_claim=$false});commits=@([ordered]@{revision=$prepared;role='triggering-unit';unit_id='trigger-unit';changed_paths=@('project/morphospace/prepared.txt')});allowed_finalization_paths=@()});workspace_transition=[ordered]@{pending_push_bundle_before=$plan.bundle_id;pending_push_bundle_after=$null};force_push_used=$false;remote_readback_complete=$true;failure=$null};$accountPath=Join-Path $ws 'receipts\accounting.json';Write-Json $accountPath $account;Test-MorphospacePlannedPublicationDocument $accountPath $ws|Out-Null
  $executedRel='project/morphospace/receipts/executed.json';$accountRel='project/morphospace/receipts/accounting.json';Invoke-FixtureGit $planning @('add',$executedRel,$accountRel);Invoke-FixtureGit $planning @('commit','-q','-m','publish exact prerequisites');$suffix=Invoke-FixtureGit $planning @('rev-parse','HEAD');$suffixTree=Invoke-FixtureGit $planning @('rev-parse','HEAD^{tree}');$preparedTree=Invoke-FixtureGit $planning @('rev-parse',"$prepared^{tree}")
  Invoke-FixtureGit $src @('update-ref','refs/remotes/origin/main',$srcFinal);Invoke-FixtureGit $planning @('update-ref','refs/remotes/origin/main',$suffix)
  $doc=[ordered]@{schema='rusty.morphospace.workflow.published_prerequisite_suffix_reconciliation.v1';reconciliation_id='published-prerequisite-reconciliation';project_id='test-project';bundle_id=$plan.bundle_id;trigger_unit_id='trigger-unit';planned_publication_accounting=[ordered]@{path='receipts/accounting.json';sha256=Hash $accountPath};planning_repository=[ordered]@{repo_id='planning-repo';branch='main';upstream='origin/main';execution_final_revision=$prepared;execution_final_tree=$preparedTree;published_suffix_revision=$suffix;published_suffix_tree=$suffixTree;published_suffix_parent=$prepared;current_remote_readback_revision=$suffix;executed_push_receipt=[ordered]@{path=$executedRel;sha256=Hash $executedPath};publication_accounting_receipt=[ordered]@{path=$accountRel;sha256=Hash $accountPath};worktree_clean=$true};source_repositories=@([ordered]@{repo_id='source-repo';branch='main';upstream='origin/main';execution_final_revision=$srcFinal;execution_final_tree=$srcTree;current_remote_readback_revision=$srcFinal;history_unchanged=$true;worktree_clean=$true});publication=[ordered]@{scope='planning-published-prerequisite-suffix';commit_count=1;changed_paths=@($accountRel,$executedRel);fast_forward_verified=$true;force_push_used=$false;force_with_lease_used=$false;rewrite_used=$false;observed_at='2026-07-20T10:04:00Z'};workspace_transition=[ordered]@{pending_push_bundle_before=$plan.bundle_id;pending_push_bundle_after=$null;validation_unchanged=$true;acceptance_unchanged=$true};failure=$null};$docPath=Join-Path $ws 'receipts\reconciliation.json';Write-Json $docPath $doc
  $spec=[pscustomobject]@{project_id='test-project'};$state=[pscustomobject]@{current_unit=$null;pending_push_bundle=[pscustomobject]@{bundle_id=$plan.bundle_id;unit_ids=@('trigger-unit');repo_ids=@('source-repo','planning-repo')}};$map=@{'source-repo'=[pscustomobject]@{path=$src};'planning-repo'=[pscustomobject]@{path=$planning}};$sourceState=[pscustomobject]@{repo_id='source-repo';dirty=$false;diverged=$false;ahead=0;behind=0;head=$srcFinal;branch='main';upstream='origin/main'};$planningState=[pscustomobject]@{repo_id='planning-repo';dirty=$false;diverged=$false;ahead=0;behind=0;head=$suffix;branch='main';upstream='origin/main'}
  Test-MorphospacePublishedPrerequisiteSuffixLive $docPath $ws $spec $state $map @($sourceState,$planningState)|Out-Null
  $cases=@('extra-path','extra-commit','bad-accounting-hash','bad-executed-hash','dirty','ahead','behind','diverged','nonancestor','alternate-history','source-drift','force','rewrite','wrong-unit','wrong-bundle','missing-receipt','missing-object','repeated-consumption')
  foreach($case in $cases){$bad=Clone $doc;$badState=Clone $state;$badSource=Clone $sourceState;$badPlanning=Clone $planningState;switch($case){'extra-path'{$bad.publication.changed_paths[0]='extra.json'}'extra-commit'{$bad.publication.commit_count=2}'bad-accounting-hash'{$bad.planned_publication_accounting.sha256=('0'*64)}'bad-executed-hash'{$bad.planning_repository.executed_push_receipt.sha256=('0'*64)}'dirty'{$badPlanning.dirty=$true}'ahead'{$badPlanning.ahead=1}'behind'{$badPlanning.behind=1}'diverged'{$badPlanning.diverged=$true}'nonancestor'{$bad.planning_repository.published_suffix_parent=$srcOld}'alternate-history'{$bad.planning_repository.execution_final_revision=$srcOld;$bad.planning_repository.published_suffix_parent=$srcOld}'source-drift'{$bad.source_repositories[0].current_remote_readback_revision=$srcOld}'force'{$bad.publication.force_push_used=$true}'rewrite'{$bad.publication.rewrite_used=$true}'wrong-unit'{$bad.trigger_unit_id='wrong-unit'}'wrong-bundle'{$bad.bundle_id='wrong-bundle'}'missing-receipt'{$bad.planned_publication_accounting.path='receipts/missing.json'}'missing-object'{$bad.planning_repository.published_suffix_revision=('f'*40);$bad.planning_repository.current_remote_readback_revision=('f'*40)}'repeated-consumption'{$badState.pending_push_bundle=$null}};$badPath=Join-Path $ws "receipts\bad-$case.json";Write-Json $badPath $bad;Reject {Test-MorphospacePublishedPrerequisiteSuffixLive $badPath $ws $spec $badState $map @($badSource,$badPlanning)} $case}
  "Published-prerequisite suffix reconciliation self-test passed (1 positive, $($cases.Count) damaged cases)."
 }finally{if(Test-Path $root){Remove-Item -Recurse -Force $root}}
 exit 0
}
if(-not$Path-or-not$WorkspaceRoot){throw 'Path and WorkspaceRoot are required unless -SelfTest is used.'}
Test-MorphospacePublishedPrerequisiteSuffixDocument -Path $Path -WorkspaceRoot $WorkspaceRoot|ConvertTo-Json -Depth 16
