param([switch]$SelfTest,[switch]$MigrationOnly,[switch]$InsideCleanExecutor,[string]$ExecutorRoot='')
$ErrorActionPreference='Stop'
$script:ExecutorClosureCache=@{}

function Assert-ToolingPreparation([bool]$Condition,[string]$Message){if(-not$Condition){throw "Tooling preparation integration self-test failed: $Message"}}
function Invoke-ToolingPreparationGit([string]$Root,[string[]]$Arguments){$rows=@(& git -C $Root @Arguments 2>&1);if($LASTEXITCODE-ne0){throw "Git fixture failed: $($rows-join' ')"};@($rows|ForEach-Object{[string]$_})}
function Write-ToolingPreparationJson([string]$Path,[object]$Value){[IO.Directory]::CreateDirectory((Split-Path $Path -Parent))|Out-Null;[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 64)+"`n"),[Text.UTF8Encoding]::new($false))}
function Remove-ToolingPreparationTemp([string]$Path){$full=[IO.Path]::GetFullPath($Path).TrimEnd('\','/');$temp=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\','/');if([IO.Path]::GetDirectoryName($full)-ine$temp-or[IO.Path]::GetFileName($full)-cnotmatch'^morphospace-tooling-(?:executor|preparation)-[0-9a-f]{32}$'){throw "Refusing to remove unexpected tooling preparation test path '$full'."};if([IO.Directory]::Exists($full)){Remove-Item -LiteralPath $full -Recurse -Force}}

if(-not$InsideCleanExecutor){
    $sourceRoot=Split-Path $PSScriptRoot -Parent;$outerTemp=Join-Path ([IO.Path]::GetTempPath()) ('morphospace-tooling-executor-'+[guid]::NewGuid().ToString('N'));$cleanRoot=Join-Path $outerTemp 'executor'
    try{
        [IO.Directory]::CreateDirectory($cleanRoot)|Out-Null
        foreach($relative in @(& git -C $sourceRoot ls-files --cached --others --exclude-standard)){if(([string]$relative)-ceq'.gitattributes'){continue};$from=Join-Path $sourceRoot $relative;if(-not[IO.File]::Exists($from)){continue};$to=Join-Path $cleanRoot $relative;[IO.Directory]::CreateDirectory((Split-Path $to -Parent))|Out-Null;[IO.File]::Copy($from,$to,$true)}
        Invoke-ToolingPreparationGit $cleanRoot @('init')|Out-Null;Invoke-ToolingPreparationGit $cleanRoot @('config','core.autocrlf','false')|Out-Null;Invoke-ToolingPreparationGit $cleanRoot @('config','core.eol','lf')|Out-Null;Invoke-ToolingPreparationGit $cleanRoot @('config','user.name','Tooling Context Test')|Out-Null;Invoke-ToolingPreparationGit $cleanRoot @('config','user.email','tooling-context@example.invalid')|Out-Null;Invoke-ToolingPreparationGit $cleanRoot @('remote','add','origin','https://example.invalid/tooling-executor.git')|Out-Null;Invoke-ToolingPreparationGit $cleanRoot @('add','.')|Out-Null;Invoke-ToolingPreparationGit $cleanRoot @('commit','-m','exact tooling executor fixture')|Out-Null;Invoke-ToolingPreparationGit $cleanRoot @('checkout-index','-a','-f')|Out-Null
        $childArguments=@('-NoProfile','-File',(Join-Path $cleanRoot 'scripts/Test-ToolingPreparationIntegration.ps1'),'-InsideCleanExecutor','-ExecutorRoot',$cleanRoot);if($MigrationOnly){$childArguments+='-MigrationOnly'};& pwsh @childArguments
        if($LASTEXITCODE-ne0){throw 'Clean tooling executor child failed.'}
    }finally{Remove-ToolingPreparationTemp $outerTemp}
    return
}

$ExecutorRoot=(Resolve-Path -LiteralPath $ExecutorRoot).Path
$repoRoot=Split-Path $PSScriptRoot -Parent
Assert-ToolingPreparation ([IO.Path]::GetFullPath($repoRoot)-ieq[IO.Path]::GetFullPath($ExecutorRoot)) 'child is not executing the copied clean owner repository'
$protocolModule=Import-Module (Join-Path $PSScriptRoot 'lib/MorphospaceProtocolCommon.psm1') -Force -PassThru
$transitionLedgerModule=Import-Module (Join-Path $PSScriptRoot 'lib/MorphospaceTransitionLedger.psm1') -Force -PassThru
$dependencyClosureModule=Import-Module (Join-Path $PSScriptRoot 'lib/MorphospaceAffectedValidationDependencyClosure.psm1') -Force -PassThru
Import-Module (Join-Path $PSScriptRoot 'DevelopmentEnvelopePreparation.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'DevelopmentUnitAdmission.psm1') -Force
$toolingModule=Import-Module (Join-Path $PSScriptRoot 'ToolingContextProvenance.psm1') -Force -PassThru
$automationModule=Import-Module (Join-Path $PSScriptRoot 'WorkUnitAutomation.psm1') -Force -PassThru
$candidateModule=Import-Module (Join-Path $PSScriptRoot 'CandidateFreeze.psm1') -Force -PassThru
$retirementModule=Import-Module (Join-Path $PSScriptRoot 'ActiveUnitRetirement.psm1') -PassThru
. (Join-Path $PSScriptRoot 'test-support/DevelopmentAdmissionFixture.ps1')
. (Join-Path $PSScriptRoot 'test-support/ActiveUnitRetirementFixture.ps1')
function FileHash([string]$Path){&$protocolModule {param($p)Get-MorphospaceFileSha256 $p} $Path}
function ReadProtocol([string]$Path){&$protocolModule {param($p)Read-MorphospaceProtocolJson $p} $Path}

function Get-ExecutorClosure([string]$Root=$ExecutorRoot) {
    $rootFull=[IO.Path]::GetFullPath($Root);$head=(@(Invoke-ToolingPreparationGit $rootFull @('rev-parse','HEAD'))[0]).Trim().ToLowerInvariant();$cacheKey="$rootFull|$head";if($script:ExecutorClosureCache.ContainsKey($cacheKey)){return @($script:ExecutorClosureCache[$cacheKey])}
    $records=@(Invoke-ToolingPreparationGit $rootFull @('ls-tree','-r','--full-tree','HEAD')|ForEach-Object{if([string]$_-cnotmatch'^(?<mode>[0-9]{6})\s+(?<type>blob|tree|commit)\s+(?<oid>[0-9a-f]{40})\t(?<path>.+)$'){throw 'Tooling fixture tree inventory is malformed.'};[pscustomobject]@{mode=[string]$Matches.mode;type=[string]$Matches.type;oid=[string]$Matches.oid;path=([string]$Matches.path).Replace('\','/')}})
    $closure=@($records|Where-Object{[string]$_.type-ceq'blob'}|ForEach-Object {
        [pscustomobject][ordered]@{path=[string]$_.path;sha256=FileHash (Join-Path $rootFull ([string]$_.path))}
    })
    $script:ExecutorClosureCache[$cacheKey]=$closure
    @($closure)
}

function New-ToolingDescriptor([string]$CaseRoot,[string]$BoundExecutorRoot=$ExecutorRoot,[string]$ContextId='u002-tooling'){
    $BoundExecutorRoot=[IO.Path]::GetFullPath($BoundExecutorRoot)
    $workspace=Join-Path $CaseRoot 'morphospace';$routerParent=Join-Path $CaseRoot 'installed-skills';[IO.Directory]::CreateDirectory((Join-Path $workspace 'local'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $workspace 'receipts'))|Out-Null;[IO.Directory]::CreateDirectory($routerParent)|Out-Null
    $head=(@(Invoke-ToolingPreparationGit $BoundExecutorRoot @('rev-parse','HEAD'))[0]).Trim().ToLowerInvariant();$tree=(@(Invoke-ToolingPreparationGit $BoundExecutorRoot @('rev-parse','HEAD^{tree}'))[0]).Trim().ToLowerInvariant()
    $resolverRouters=@();$contextRouters=@();foreach($skillId in @('rusty-morphospace','system-engineering','rust-work-graph')){$routerRoot=Join-Path $routerParent $skillId;[IO.Directory]::CreateDirectory($routerRoot)|Out-Null;$skillSource=Join-Path $BoundExecutorRoot "skills/$skillId/SKILL.md";$skillTarget=Join-Path $routerRoot 'SKILL.md';[IO.File]::Copy($skillSource,$skillTarget,$true);$skillHash=FileHash $skillTarget;$fingerprintInput="SKILL.md:$skillHash`n";$sha=[Security.Cryptography.SHA256]::Create();try{$sourceFingerprint=[Convert]::ToHexString($sha.ComputeHash([Text.UTF8Encoding]::new($false).GetBytes($fingerprintInput))).ToLowerInvariant()}finally{$sha.Dispose()};$record=[ordered]@{schema='rusty.morphospace.local_skill_source.v1';skill_id=$skillId;installed_at='2026-09-15T00:00:00.0000000Z';source_repository='https://example.invalid/tooling-executor.git';source_commit=$head;source_worktree_dirty=$false;source_release='fixture';source_tree_sha256=$sourceFingerprint;source_files=@([ordered]@{path='SKILL.md';sha256=$skillHash});work_environment_root=$BoundExecutorRoot};Write-ToolingPreparationJson (Join-Path $routerRoot '.morphospace-skill-source.json') $record;$resolverRouters+=,[ordered]@{skill_id=$skillId;root=$routerRoot};$contextRouters+=,[ordered]@{skill_id=$skillId;source_repo_id='workflow-tooling';commit=$head;tree=$tree;source_fingerprint=$sourceFingerprint;managed_files=@([ordered]@{path='SKILL.md';sha256=$skillHash})}}
    $actions=@(&$toolingModule {Get-MorphospaceToolingContextAllowedActions});$validationRelative='receipts/tooling-validation.json';$validationPath=Join-Path $workspace $validationRelative;$emptyHash='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';$validation=[ordered]@{schema='rusty.morphospace.workflow.affected_validation_evidence.v1';repository='MesmerPrism/rusty-morphospace-work-environment';base=[ordered]@{commit=$head;tree=$tree};head=[ordered]@{commit=$head;tree=$tree};plan_sha256=('1'*64);platform='windows';runner=[ordered]@{os_description='Windows tooling preparation integration fixture';powershell_version=$PSVersionTable.PSVersion.ToString()};check_results=@([ordered]@{check_id='tooling-preparation-integration';command_path='scripts/Test-ToolingPreparationIntegration.ps1';command_blob_sha1=$head;mode='executed';result='pass';started=$true;failure_kind=$null;exit_code=0;timed_out=$false;output_truncated=$false;post_kill_drain_timed_out=$false;stdout_sha256=$emptyHash;stderr_sha256=$emptyHash;stdout_bytes=0;stderr_bytes=0});result='pass';claims=[ordered]@{historical_aggregate_reused=$false;acceptance_authority=$false;publication_authority=$false}};Write-ToolingPreparationJson $validationPath $validation
    $publication=[ordered]@{schema='rusty.morphospace.workflow.tooling_context_publication_evidence.v1';publication_id='tooling-publication';executor=[ordered]@{repo_id='workflow-tooling';remote_url='https://example.invalid/tooling-executor.git';commit=$head;tree=$tree};validation=[ordered]@{path=$validationRelative;sha256=FileHash $validationPath};status='source-observed';does_not_prove=@('Does not independently prove remote publication authority.')};Write-ToolingPreparationJson (Join-Path $workspace 'receipts/tooling-publication.json') $publication
    $protocolReceipt=[ordered]@{schema='rusty.morphospace.workflow.tooling_context_protocol_receipt.v1';receipt_id='tooling-protocol';executor=[ordered]@{repo_id='workflow-tooling';commit=$head;tree=$tree};protocol=[ordered]@{protocol_id='tooling-context-v1';product_lock_schema='rusty.morphospace.workflow.development_envelope_source_composition.v3';repository_map_schema='rusty.morphospace.workflow.repository_map.v1';allowed_actions=$actions};validation=[ordered]@{path=$validationRelative;sha256=FileHash $validationPath};status='compatible';does_not_prove=@('Fixture protocol receipt does not grant product mutation authority.')};Write-ToolingPreparationJson (Join-Path $workspace 'receipts/tooling-compatibility.json') $protocolReceipt
    $resolver=[ordered]@{schema='rusty.morphospace.workflow.tooling_context_resolver.v1';context_id=$ContextId;executor_root=$BoundExecutorRoot;routers=$resolverRouters;status='resolved';does_not_prove=@('Fixture resolver does not install tooling.')};$resolverPath=Join-Path $workspace 'local/tooling-resolver.json';Write-ToolingPreparationJson $resolverPath $resolver
    $protocolId=&$toolingModule {Get-MorphospaceToolingContextProtocolId}
    [ordered]@{context_id=$ContextId;path="tooling-contexts/$ContextId.json";resolver=[ordered]@{path='local/tooling-resolver.json';sha256=FileHash $resolverPath};executor=[ordered]@{repo_id='workflow-tooling';remote_url='https://example.invalid/tooling-executor.git';commit=$head;tree=$tree;publication_evidence=[ordered]@{path='receipts/tooling-publication.json';sha256=FileHash (Join-Path $workspace 'receipts/tooling-publication.json')};entrypoint='scripts/DevelopmentEnvelopePreparation.psm1';closure=@(Get-ExecutorClosure -Root $BoundExecutorRoot)};routers=$contextRouters;compatibility=[ordered]@{protocol_id=$protocolId;product_lock_schema='rusty.morphospace.workflow.development_envelope_source_composition.v3';repository_map_schema='rusty.morphospace.workflow.repository_map.v1';allowed_actions=$actions;receipt=[ordered]@{path='receipts/tooling-compatibility.json';sha256=FileHash (Join-Path $workspace 'receipts/tooling-compatibility.json')}}}
}

function Invoke-LegacyToolingMigrationIntegration {
    $case=Join-Path ([IO.Path]::GetTempPath()) ('morphospace-tooling-preparation-'+[guid]::NewGuid().ToString('N'))
    try{
        [IO.Directory]::CreateDirectory($case)|Out-Null;$legacyRoot=Join-Path $ExecutorRoot 'skills';$legacyPaths=@('rusty-morphospace/SKILL.md','system-engineering/SKILL.md','rust-work-graph/SKILL.md')
        $seed=New-EnvelopeAdmissionPreparedFixture -Root $case -RepositoryRoot $repoRoot -TransitionLedgerModule $transitionLedgerModule -OwnerProducedPreparation -LegacyToolRepositoryRoot $legacyRoot -LegacyToolAllowedPaths $legacyPaths -RepositoryMapRelative 'local/repository-map-old.json'
        $workspace=$seed.workspace;$oldMapPath=Join-Path $workspace 'local/repository-map-old.json';$admissionPath=Join-Path $case 'u002-admission.json';Write-ToolingPreparationJson $admissionPath $seed.admission_template
        Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $workspace -DevelopmentUnitAdmission $admissionPath -ExpectedDevelopmentUnitAdmissionSha256 (FileHash $admissionPath) -OutPath (Join-Path $workspace 'receipts/u002-admission.json') -Timestamp '2026-09-15T03:00:00.0000000Z' -Execute|Out-Null
        $lifecycle=@{WorkspaceRoot=$workspace;UnitId='u002';RepoMapPath=$oldMapPath;ValidationTier='quick'};&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a -Action Ready -Timestamp '2026-09-15T03:01:00.0000000Z' -Execute} $lifecycle|Out-Null;&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a -Action Claim -Timestamp '2026-09-15T03:02:00.0000000Z' -Execute} $lifecycle|Out-Null
        $project=ReadProtocol (Join-Path $workspace 'project.spec.json');$state=ReadProtocol (Join-Path $workspace 'workspace.state.json');$unit=ReadProtocol (Join-Path $workspace 'iteration-units/u002.json');$lock=ReadProtocol (Join-Path $workspace 'feature.lock.json');$eventsPath=Join-Path $workspace 'iteration-events.jsonl';$sourcePath=Join-Path $workspace 'source-composition.json'
        $freeze=[ordered]@{schema='rusty.morphospace.workflow.candidate_freeze.v1';freeze_id='u002-migration-freeze';project_id='envelope-test';unit_id='u002';expected=[ordered]@{project_sha256=Get-EnvelopeCanonicalJsonSha256 $project;state_sha256=Get-EnvelopeCanonicalJsonSha256 $state;unit_sha256=Get-EnvelopeCanonicalJsonSha256 $unit;feature_lock_sha256=Get-EnvelopeCanonicalJsonSha256 $lock;source_composition_path='source-composition.json';source_composition_sha256=FileHash $sourcePath;repository_map_path='local/repository-map-old.json';repository_map_sha256=FileHash $oldMapPath;events_sha256=FileHash $eventsPath;events_length=([IO.FileInfo]$eventsPath).Length;event_tail_id=[string]$state.last_event_id};final_repositories=@([ordered]@{repo_id='project-shell';commit=$seed.source_commit;tree=$seed.source_tree});changed_paths=@([ordered]@{repo_id='project-shell';paths=@('morphospace/')});cleanliness_policy='clean-only';instruction_surfaces=@([ordered]@{path='README.md';disposition='reviewed-no-change'});feature_lock=[ordered]@{revision=[int]$lock.revision;sha256=Get-EnvelopeCanonicalJsonSha256 $lock};effects=@('none');permissions=@('none');device_use=@('none');test_matrix=@([ordered]@{test_id='legacy-tooling-migration';command='Test-ToolingPreparationIntegration.ps1 -MigrationOnly'});cleanup_evidence=@('The disposable migration fixture is removed by its guarded finally block.');source_composition=[ordered]@{path='source-composition.json';sha256=FileHash $sourcePath};does_not_prove=@('Does not validate, accept, publish, install tooling, or mutate a device.')}
        $freezePath=Join-Path $case 'u002-freeze.json';Write-ToolingPreparationJson $freezePath $freeze;$freezeOut=Join-Path $workspace 'receipts/u002-migration-freeze.json';$dry=&$candidateModule {param($a)Invoke-MorphospaceFreezeCandidate @a} @{WorkspaceRoot=$workspace;UnitId='u002';CandidateFreeze=$freezePath;OutPath=$freezeOut;Timestamp='2026-09-15T03:03:00.0000000Z'};&$candidateModule {param($a)Invoke-MorphospaceFreezeCandidate @a} @{WorkspaceRoot=$workspace;UnitId='u002';CandidateFreeze=$freezePath;ExpectedCandidateFreezeSha256=[string]$dry.audit_receipt.sha256;OutPath=$freezeOut;Timestamp='2026-09-15T03:03:00.0000000Z';Execute=$true}|Out-Null
        $retirement=New-ActiveUnitRetirementRequest -WorkspaceRoot $workspace -RepoMapPath $oldMapPath -RetirementId 'retire-u002-migration' -ReplacementUnitId 'u003';$retirementPath=Join-Path $case 'retire-u002.json';Write-ToolingPreparationJson $retirementPath $retirement;$retirementOut=Join-Path $workspace 'receipts/retire-u002-migration.json';&$retirementModule {param($a)Invoke-MorphospaceRetireActive @a} @{WorkspaceRoot=$workspace;UnitId='u002';RepoMapPath=$oldMapPath;ActiveUnitRetirement=$retirementPath;ExpectedActiveUnitRetirementSha256=(FileHash $retirementPath);OutPath=$retirementOut;Timestamp='2026-09-15T03:04:00.0000000Z';Execute=$true}|Out-Null
        [IO.File]::WriteAllText((Join-Path $ExecutorRoot 'skills/rusty-morphospace/SKILL.md'),"# Updated tooling router`n",[Text.UTF8Encoding]::new($false));Invoke-ToolingPreparationGit $ExecutorRoot @('add','skills/rusty-morphospace/SKILL.md')|Out-Null;Invoke-ToolingPreparationGit $ExecutorRoot @('commit','-m','advance tooling after retirement')|Out-Null
        $descriptor=New-ToolingDescriptor -CaseRoot $case -ContextId 'u003-tooling';$oldMap=ReadProtocol $oldMapPath;$targetMap=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.repository_map.v1';repositories=@($oldMap.repositories|Where-Object{[string]$_.repo_id-cne'legacy-skill-surfaces'})};$targetMapRelative='local/repository-map-target.json';$targetMapPath=Join-Path $workspace $targetMapRelative;Write-ToolingPreparationJson $targetMapPath $targetMap
        $project=ReadProtocol (Join-Path $workspace 'project.spec.json');$state=ReadProtocol (Join-Path $workspace 'workspace.state.json');$lock=ReadProtocol (Join-Path $workspace 'feature.lock.json');$targetProject=Copy-Envelope $project;$targetProject.revision=[int]$project.revision+1;$targetProject.repositories=@($targetProject.repositories|Where-Object{[string]$_.repo_id-cne'legacy-skill-surfaces'});$shell=@($targetProject.repositories|Where-Object{[string]$_.repo_id-ceq'project-shell'})[0];$shell.allowed_paths+=,'broker-contracts/'
        $targetLock=Copy-Envelope $lock;$targetLock.project_revision=[int]$targetProject.revision;$targetLock.revision=[int]$lock.revision+1;$targetLock.generated_at='2026-09-15T03:05:00.0000000Z';$targetLock.lock_fingerprint='0'*64;$targetLock.lock_fingerprint=Get-EnvelopeLockFingerprint $targetLock
        $oldSource=ReadProtocol $sourcePath;$oldToolRow=@($oldSource.repositories|Where-Object{[string]$_.repo_id-ceq'legacy-skill-surfaces'})[0];$oldProjectRow=@($project.repositories|Where-Object{[string]$_.repo_id-ceq'legacy-skill-surfaces'})[0];$oldMapRow=@($oldMap.repositories|Where-Object{[string]$_.repo_id-ceq'legacy-skill-surfaces'})[0]
        $reclassification=[ordered]@{schema='rusty.morphospace.workflow.legacy_tooling_reclassification.v1';reclassification_id='u003-legacy-tooling';old_repository_map=[ordered]@{path='local/repository-map-old.json';sha256=FileHash $oldMapPath};target_repository_map=[ordered]@{path=$targetMapRelative;sha256=FileHash $targetMapPath};removed_tool_repositories=@([ordered]@{repo_id='legacy-skill-surfaces';project_row_sha256=Get-EnvelopeCanonicalJsonSha256 $oldProjectRow;map_row_sha256=Get-EnvelopeCanonicalJsonSha256 $oldMapRow;source_composition=[ordered]@{path='source-composition.json';sha256=FileHash $sourcePath;canonical_sha256=Get-EnvelopeCanonicalJsonSha256 $oldSource};source_row_sha256=Get-EnvelopeCanonicalJsonSha256 $oldToolRow;commit=[string]$oldToolRow.commit;tree=[string]$oldToolRow.tree;materialization_path=[string]$oldToolRow.materialization_path;canonical_allowed_paths=$legacyPaths;router_skill_ids=@('rusty-morphospace','system-engineering','rust-work-graph')});status='reviewed';does_not_prove=@('Does not remove product or planning source authority.')}
        $predecessor=ReadProtocol (Join-Path $workspace 'iteration-units/u001.json');$events=@(Get-Content $eventsPath|Where-Object{$_}|ForEach-Object{$_|ConvertFrom-Json -DateKind String});$scope=Copy-Envelope $seed.scope;$scope.owner_repositories=@($scope.owner_repositories|Where-Object{[string]$_.repo_id-cne'legacy-skill-surfaces'});$scope.owner_repositories[0].source_roots+=,'broker-contracts/';$scope.allowed_change_categories=@('documentation-only','workflow-automation');$reviewProbe=Copy-Envelope $seed.u002;$reviewProbe.unit_id='u003';$reviewProbe.status='proposed';$reviewProbe.change_categories=@('documentation-only','workflow-automation');$reviewProbe|Add-Member -NotePropertyName work_mode -NotePropertyValue 'feature';$reviewProbe|Add-Member -NotePropertyName claim_requirements -NotePropertyValue ([pscustomobject][ordered]@{minimum_free_disk_mib=1;required_tools=@();product_inputs=@()});$reviewProbe.agent_scope_assessment=$scope;$reviewProbe.allowed_repositories[0].allowed_paths+=,'broker-contracts/';$reviewProbe.instruction_surfaces=@($reviewProbe.instruction_surfaces|Where-Object{[string]$_.surface_kind-cne'skill'});foreach($skillId in @('rusty-morphospace','system-engineering','rust-work-graph')){$reviewProbe.instruction_surfaces+=,[ordered]@{surface_kind='skill';path="<skills-root>/$skillId/SKILL.md";owner='workflow-maintainer';change_reason='Review the separately resolved tooling router.';action='review-no-change';status='complete';validation='Exact tooling-context managed-file hash.';skill_id=$skillId}};Assert-EnvelopeFixtureSchema -Value $reviewProbe -SchemaName 'iteration-unit.schema.json' -Context 'migration unit before preparation';Assert-EnvelopeFixtureSchema -Value $scope -SchemaName 'agent-scope-assessment-v1.schema.json' -Context 'migration scope before preparation';Assert-EnvelopeStaticToolingReviewCompatibility -Unit $reviewProbe -State $state
        $preparation=[ordered]@{schema='rusty.morphospace.workflow.development_envelope_preparation.v1';preparation_kind='legacy-tooling-reclassification';preparation_id='u003-envelope';project_id='envelope-test';predecessor_unit_id='u001';envelope=[ordered]@{project=$targetProject;feature_lock=$targetLock;owner_repositories=$scope.owner_repositories;public_private_boundary=$scope.public_private_boundary;allowed_change_categories=$scope.allowed_change_categories;allowed_effect_categories=$scope.allowed_effect_categories;allowed_permission_categories=$scope.allowed_permission_categories;build_envelope=$scope.build_envelope;device_envelope=$scope.device_envelope;source_composition=[ordered]@{path='source-composition-u003.json';repository_ids=@($targetMap.repositories|ForEach-Object{[string]$_.repo_id})}};tooling_context=$descriptor;legacy_tooling_reclassification=$reclassification;expected=[ordered]@{project_sha256=Get-EnvelopeCanonicalJsonSha256 $project;state_sha256=Get-EnvelopeCanonicalJsonSha256 $state;feature_lock_sha256=Get-EnvelopeCanonicalJsonSha256 $lock;repository_map_path='local/repository-map-old.json';repository_map_sha256=FileHash $oldMapPath;predecessor_unit_path='iteration-units/u001.json';predecessor_unit_sha256=Get-EnvelopeCanonicalJsonSha256 $predecessor;events_sha256=FileHash $eventsPath;events_length=([IO.FileInfo]$eventsPath).Length;event_tail_id=[string]$events[-1].event_id};does_not_prove=@('Does not admit, claim, validate, accept, publish, install tooling, or mutate a device.')}
        $preparationPath=Join-Path $case 'u003-preparation.json';Write-ToolingPreparationJson $preparationPath $preparation;$preparationOut=Join-Path $workspace 'receipts/u003-envelope.json';$interrupted=$false;try{Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $workspace -DevelopmentEnvelopePreparation $preparationPath -ExpectedDevelopmentEnvelopePreparationSha256 (FileHash $preparationPath) -OutPath $preparationOut -Timestamp '2026-09-15T03:05:00.0000000Z' -Execute -FaultAfter after-artifacts|Out-Null}catch{$interrupted=$_.Exception.Message-like'*Injected preparation interruption*'};Assert-ToolingPreparation $interrupted 'combined migration did not retain its after-artifacts recovery boundary';Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $workspace -DevelopmentEnvelopePreparation $preparationPath -ExpectedDevelopmentEnvelopePreparationSha256 (FileHash $preparationPath) -OutPath $preparationOut -Timestamp '2026-09-15T03:05:00.0000000Z' -Execute|Out-Null
        $receipt=ReadProtocol $preparationOut;$pointer=$receipt.tooling_context;$newProject=ReadProtocol (Join-Path $workspace 'project.spec.json');$newState=ReadProtocol (Join-Path $workspace 'workspace.state.json');$newLock=ReadProtocol (Join-Path $workspace 'feature.lock.json');$newSourcePath=Join-Path $workspace 'source-composition-u003.json';$newSource=ReadProtocol $newSourcePath;$u003=Copy-Envelope $seed.u002;$u003.unit_id='u003';$u003.status='proposed';$u003.prerequisites=@('u001');$u003.change_categories=@('documentation-only','workflow-automation');$u003|Add-Member -NotePropertyName work_mode -NotePropertyValue 'feature';$u003|Add-Member -NotePropertyName claim_requirements -NotePropertyValue ([pscustomobject][ordered]@{minimum_free_disk_mib=1;required_tools=@();product_inputs=@()});$u003.agent_scope_assessment=$scope;$u003.read_only_dependencies=@($u003.read_only_dependencies|Where-Object{[string]$_.repo_id-cne'legacy-skill-surfaces'});$u003.allowed_repositories[0].allowed_paths+=,'broker-contracts/';$u003.source_composition.lock_path='source-composition-u003.json';$u003|Add-Member -NotePropertyName tooling_context -NotePropertyValue (Copy-Envelope $pointer);$u003.instruction_impact='update';$u003.instruction_none_justification=$null;$u003.instruction_surfaces=@($u003.instruction_surfaces|Where-Object{[string]$_.surface_kind-cne'skill'});foreach($skillId in @('rusty-morphospace','system-engineering','rust-work-graph')){$u003.instruction_surfaces+=,[ordered]@{surface_kind='skill';path="<skills-root>/$skillId/SKILL.md";owner='workflow-maintainer';change_reason='Review the separately resolved tooling router.';action='review-no-change';status='complete';validation='Exact tooling-context managed-file hash.';skill_id=$skillId}};Assert-EnvelopeFixtureSchema -Value $u003 -SchemaName 'iteration-unit.schema.json' -Context 'migration unit after context binding';Assert-EnvelopeFixtureSchema -Value $scope -SchemaName 'agent-scope-assessment-v1.schema.json' -Context 'migration scope after context binding';Assert-EnvelopeStaticToolingReviewCompatibility -Unit $u003 -State $newState
        $admission=[ordered]@{schema='rusty.morphospace.workflow.development_unit_admission.v1';admission_kind='ordinary';admission_id='u003-admission';project_id='envelope-test';unit_id='u003';preparation=[ordered]@{preparation_kind='ordinary';preparation_id='u003-envelope';receipt_path='receipts/u003-envelope.json';receipt_sha256=FileHash $preparationOut;source_composition_path='source-composition-u003.json';source_composition_sha256=FileHash $newSourcePath};tooling_context=Copy-Envelope $pointer;agent_scope_assessment=$scope;unit=$u003;expected=[ordered]@{project_sha256=Get-EnvelopeCanonicalJsonSha256 $newProject;state_sha256=Get-EnvelopeCanonicalJsonSha256 $newState;feature_lock_sha256=Get-EnvelopeCanonicalJsonSha256 $newLock;source_composition_path='source-composition-u003.json';source_composition_sha256=FileHash $newSourcePath;repository_map_path=$targetMapRelative;repository_map_sha256=FileHash $targetMapPath;events_sha256=FileHash $eventsPath;events_length=([IO.FileInfo]$eventsPath).Length;event_tail_id=[string]$newState.last_event_id;tooling_context=Copy-Envelope $pointer};does_not_prove=@('Does not claim, validate, accept, or publish.')};$admissionPath3=Join-Path $case 'u003-admission.json';Write-ToolingPreparationJson $admissionPath3 $admission;Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $workspace -DevelopmentUnitAdmission $admissionPath3 -ExpectedDevelopmentUnitAdmissionSha256 (FileHash $admissionPath3) -OutPath (Join-Path $workspace 'receipts/u003-admission.json') -Timestamp '2026-09-15T03:06:00.0000000Z' -Execute|Out-Null;&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a -Action Ready -Timestamp '2026-09-15T03:07:00.0000000Z' -Execute} @{WorkspaceRoot=$workspace;UnitId='u003';RepoMapPath=$targetMapPath;ValidationTier='quick'}|Out-Null
        Assert-ToolingPreparation (@($newProject.repositories|Where-Object{[string]$_.repo_id-ceq'legacy-skill-surfaces'}).Count-eq0-and@($newProject.repositories|Where-Object{[string]$_.repo_id-ceq'project-shell'-and@($_.allowed_paths)-ccontains'broker-contracts/'}).Count-eq1-and@($newSource.repositories|Where-Object{[string]$_.repo_id-ceq'legacy-skill-surfaces'}).Count-eq0-and[string]$newSource.schema-ceq'rusty.morphospace.workflow.development_envelope_source_composition.v3') 'combined migration did not remove only the tool row, add the reviewed root, and install v3 product pins'
        'Legacy tooling Retire -> combined Prepare recovery -> Admit -> Ready integration passed.'
    }finally{Remove-ToolingPreparationTemp $case}
}

if($MigrationOnly){Invoke-LegacyToolingMigrationIntegration;return}

$temp=Join-Path ([IO.Path]::GetTempPath()) ('morphospace-tooling-preparation-'+[guid]::NewGuid().ToString('N'))
try{
    $caseA=Join-Path $temp 'success';[IO.Directory]::CreateDirectory($caseA)|Out-Null;$descriptorA=New-ToolingDescriptor $caseA;$fixtureA=New-EnvelopeAdmissionPreparedFixture -Root $caseA -RepositoryRoot $repoRoot -TransitionLedgerModule $transitionLedgerModule -OwnerProducedPreparation -ToolingContextDescriptor $descriptorA
    $sourceA=ReadProtocol (Join-Path $fixtureA.workspace 'source-composition.json');$intentA=ReadProtocol (Join-Path $fixtureA.workspace 'receipts/transactions/u002-envelope-prepared-transition.intent.json')
    Assert-ToolingPreparation ([string]$sourceA.schema-ceq'rusty.morphospace.workflow.development_envelope_source_composition.v3'-and@($sourceA.repositories).Count-eq2-and@($sourceA.repositories|Where-Object{$_.role-cnotin@('source','planning')}).Count-eq0-and[string]$sourceA.tooling_protocol.protocol_id-ceq'tooling-context-v1'-and@($intentA.artifacts).Count-eq3) 'fresh preparation did not separate product repositories from tooling provenance'
    $admissionPathA=Join-Path $caseA 'admission.json';Write-ToolingPreparationJson $admissionPathA $fixtureA.admission_template;$admissionHashA=FileHash $admissionPathA;$admissionOutA=Join-Path $fixtureA.workspace 'receipts/u002-admission.json';Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $fixtureA.workspace -DevelopmentUnitAdmission $admissionPathA -OutPath $admissionOutA -Timestamp '2026-08-25T00:01:00.0000000Z'|Out-Null;Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $fixtureA.workspace -DevelopmentUnitAdmission $admissionPathA -ExpectedDevelopmentUnitAdmissionSha256 $admissionHashA -OutPath $admissionOutA -Timestamp '2026-08-25T00:01:00.0000000Z' -Execute|Out-Null
    $admitted=ReadProtocol (Join-Path $fixtureA.workspace 'iteration-units/u002.json');Assert-ToolingPreparation ((Get-EnvelopeCanonicalJsonSha256 $admitted.tooling_context)-ceq(Get-EnvelopeCanonicalJsonSha256 $fixtureA.admission_template.tooling_context)) 'admission did not install the exact initial tooling pointer'

    $repoMapA=Join-Path $fixtureA.workspace 'repository-map.json';$routerSkillA=Join-Path $caseA 'installed-skills/rusty-morphospace/SKILL.md';$routerBytesA=[IO.File]::ReadAllBytes($routerSkillA);$workspaceBeforeRouterDrift=Get-EnvelopeWorkspaceByteInventorySha256 $fixtureA.workspace
    [IO.File]::AppendAllText($routerSkillA,"`nrouter drift`n",[Text.UTF8Encoding]::new($false));$routerDriftRejected=$false
    try{&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a} @{Action='Ready';WorkspaceRoot=$fixtureA.workspace;UnitId='u002';RepoMapPath=$repoMapA;Timestamp='2026-08-25T00:02:00.0000000Z';Execute=$true}|Out-Null}catch{$routerDriftRejected=$true}
    Assert-ToolingPreparation ($routerDriftRejected-and$workspaceBeforeRouterDrift-ceq(Get-EnvelopeWorkspaceByteInventorySha256 $fixtureA.workspace)) 'installed-router drift did not block Ready without lifecycle mutation'
    [IO.File]::WriteAllBytes($routerSkillA,$routerBytesA)
    $ready=&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a} @{Action='Ready';WorkspaceRoot=$fixtureA.workspace;UnitId='u002';RepoMapPath=$repoMapA;Timestamp='2026-08-25T00:02:00.0000000Z';Execute=$true}
    $inspect=&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a} @{Action='Inspect';WorkspaceRoot=$fixtureA.workspace;UnitId='u002';RepoMapPath=$repoMapA;Timestamp='2026-08-25T00:02:30.0000000Z'}
    $claim=&$automationModule {param($a)Invoke-MorphospaceWorkUnitAutomation @a} @{Action='Claim';WorkspaceRoot=$fixtureA.workspace;UnitId='u002';RepoMapPath=$repoMapA;Timestamp='2026-08-25T00:03:00.0000000Z';Execute=$true}
    $instructionCheck=@($inspect.claim_preflight.coverage.checks|Where-Object{[string]$_.check_id-ceq'instruction-action-compatibility'})
    $productMapA=ReadProtocol $repoMapA;$mapPathsA=@($productMapA.repositories|ForEach-Object{[IO.Path]::GetFullPath([string]$_.path)});$routerRootA=[IO.Path]::GetFullPath((Split-Path $routerSkillA -Parent))
    Assert-ToolingPreparation ([string]$ready.transition-ceq'proposed-to-ready'-and$inspect.claim_preflight.ready_to_claim-and$instructionCheck.Count-eq1-and[string]$instructionCheck[0].outcome-ceq'pass'-and[string]$claim.transition-ceq'ready-to-active'-and@($productMapA.repositories).Count-eq2-and$mapPathsA-cnotcontains$routerRootA) 'separate installed instruction router did not pass Ready, Inspect, and Claim without entering the product map'

    $projectA=ReadProtocol (Join-Path $fixtureA.workspace 'project.spec.json');$stateA=ReadProtocol (Join-Path $fixtureA.workspace 'workspace.state.json');$unitA=ReadProtocol (Join-Path $fixtureA.workspace 'iteration-units/u002.json');$lockA=ReadProtocol (Join-Path $fixtureA.workspace 'feature.lock.json');$eventsA=Join-Path $fixtureA.workspace 'iteration-events.jsonl';$sourcePathA=Join-Path $fixtureA.workspace 'source-composition.json'
    $freezeA=[ordered]@{schema='rusty.morphospace.workflow.candidate_freeze.v1';freeze_id='u002-freeze';project_id='envelope-test';unit_id='u002';expected=[ordered]@{project_sha256=Get-EnvelopeCanonicalJsonSha256 $projectA;state_sha256=Get-EnvelopeCanonicalJsonSha256 $stateA;unit_sha256=Get-EnvelopeCanonicalJsonSha256 $unitA;feature_lock_sha256=Get-EnvelopeCanonicalJsonSha256 $lockA;source_composition_path='source-composition.json';source_composition_sha256=FileHash $sourcePathA;repository_map_path='repository-map.json';repository_map_sha256=FileHash $repoMapA;events_sha256=FileHash $eventsA;events_length=([IO.FileInfo]$eventsA).Length;event_tail_id=[string]$stateA.last_event_id};final_repositories=@([ordered]@{repo_id='project-shell';commit=$fixtureA.source_commit;tree=$fixtureA.source_tree});changed_paths=@([ordered]@{repo_id='project-shell';paths=@('morphospace/')});cleanliness_policy='clean-only';instruction_surfaces=@([ordered]@{path='<skills-root>/rusty-morphospace/SKILL.md';disposition='reviewed-no-change'});feature_lock=[ordered]@{revision=[int]$lockA.revision;sha256=Get-EnvelopeCanonicalJsonSha256 $lockA};effects=@('none');permissions=@('none');device_use=@('none');test_matrix=@([ordered]@{test_id='tooling-provenance';command='Test-ToolingPreparationIntegration.ps1 -SelfTest'});cleanup_evidence=@('Disposable product and tooling fixtures are removed by the test finally block.');source_composition=[ordered]@{path='source-composition.json';sha256=FileHash $sourcePathA};does_not_prove=@('Does not validate, accept, publish, install, or mutate tooling.')}
    $freezePathA=Join-Path $caseA 'freeze.json';Write-ToolingPreparationJson $freezePathA $freezeA;$freezeOutA=Join-Path $fixtureA.workspace 'receipts/u002-freeze.json';$freezeDryA=&$candidateModule {param($a)Invoke-MorphospaceFreezeCandidate @a} @{WorkspaceRoot=$fixtureA.workspace;UnitId='u002';CandidateFreeze=$freezePathA;OutPath=$freezeOutA;Timestamp='2026-08-25T00:04:00.0000000Z'};$freezeRunA=&$candidateModule {param($a)Invoke-MorphospaceFreezeCandidate @a} @{WorkspaceRoot=$fixtureA.workspace;UnitId='u002';CandidateFreeze=$freezePathA;ExpectedCandidateFreezeSha256=$freezeDryA.audit_receipt.sha256;OutPath=$freezeOutA;Timestamp='2026-08-25T00:04:00.0000000Z';Execute=$true}
    Assert-ToolingPreparation ([string]$freezeRunA.transition-ceq'candidate-frozen'-and[string](ReadProtocol (Join-Path $fixtureA.workspace 'iteration-units/u002.json')).candidate_freeze.freeze_id-ceq'u002-freeze'-and[string](ReadProtocol $sourcePathA).schema-ceq'rusty.morphospace.workflow.development_envelope_source_composition.v3') 'tooling-bound active unit did not freeze the separated product source v3 closure'

    $wrongExecutor=Join-Path $temp 'other-executor';Invoke-ToolingPreparationGit $temp @('-c','core.autocrlf=false','clone','--no-local',$ExecutorRoot,$wrongExecutor)|Out-Null;Invoke-ToolingPreparationGit $wrongExecutor @('config','core.autocrlf','false')|Out-Null;Invoke-ToolingPreparationGit $wrongExecutor @('remote','set-url','origin','https://example.invalid/tooling-executor.git')|Out-Null;Invoke-ToolingPreparationGit $wrongExecutor @('reset','--hard','HEAD')|Out-Null
    $wrongCase=Join-Path $temp 'wrong-executor';[IO.Directory]::CreateDirectory($wrongCase)|Out-Null;$wrongDescriptor=New-ToolingDescriptor $wrongCase $wrongExecutor;$wrongRejected=$false;try{New-EnvelopeAdmissionPreparedFixture -Root $wrongCase -RepositoryRoot $repoRoot -TransitionLedgerModule $transitionLedgerModule -OwnerProducedPreparation -ToolingContextDescriptor $wrongDescriptor|Out-Null}catch{$wrongRejected=$_.Exception.Message-like'*context-bound executor*'}
    $wrongWorkspace=Join-Path $wrongCase 'morphospace';Assert-ToolingPreparation ($wrongRejected-and-not(Test-Path (Join-Path $wrongWorkspace 'source-composition.json'))-and-not(Test-Path (Join-Path $wrongWorkspace 'receipts/u002-envelope.json'))-and-not(Test-Path (Join-Path $wrongWorkspace 'receipts/transactions/u002-envelope-prepared-transition.intent.json'))) 'wrong executor was accepted or published preparation artifacts'

    $legacyCase=Join-Path $temp 'legacy';[IO.Directory]::CreateDirectory($legacyCase)|Out-Null;$legacyFixture=New-EnvelopeAdmissionPreparedFixture -Root $legacyCase -RepositoryRoot $repoRoot -TransitionLedgerModule $transitionLedgerModule -OwnerProducedPreparation;$legacyAdmissionPath=Join-Path $legacyCase 'admission.json';Write-ToolingPreparationJson $legacyAdmissionPath $legacyFixture.admission_template;$legacyOut=Join-Path $legacyFixture.workspace 'receipts/u002-admission.json';Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $legacyFixture.workspace -DevelopmentUnitAdmission $legacyAdmissionPath -OutPath $legacyOut|Out-Null;Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $legacyFixture.workspace -DevelopmentUnitAdmission $legacyAdmissionPath -ExpectedDevelopmentUnitAdmissionSha256 (FileHash $legacyAdmissionPath) -OutPath $legacyOut -Execute|Out-Null;$legacySource=ReadProtocol (Join-Path $legacyFixture.workspace 'source-composition.json');$legacyIntent=ReadProtocol (Join-Path $legacyFixture.workspace 'receipts/transactions/u002-envelope-prepared-transition.intent.json');$legacyUnit=ReadProtocol (Join-Path $legacyFixture.workspace 'iteration-units/u002.json')
    Assert-ToolingPreparation ([string]$legacySource.schema-ceq'rusty.morphospace.workflow.development_envelope_source_composition.v1'-and@($legacyIntent.artifacts).Count-eq2-and$legacyUnit.PSObject.Properties.Name-cnotcontains'tooling_context') 'absent tooling opt-in changed the legacy v1 preparation/admission contract'

    $caseB=Join-Path $temp 'drift';[IO.Directory]::CreateDirectory($caseB)|Out-Null;$descriptorB=New-ToolingDescriptor $caseB;$fixtureB=New-EnvelopeAdmissionPreparedFixture -Root $caseB -RepositoryRoot $repoRoot -TransitionLedgerModule $transitionLedgerModule -OwnerProducedPreparation -ToolingContextDescriptor $descriptorB;$sourcePathB=Join-Path $fixtureB.workspace 'source-composition.json';$sourceBefore=FileHash $sourcePathB;$pinsBefore=Get-EnvelopeCanonicalJsonSha256 (ReadProtocol $sourcePathB).repositories
    $preparationInputB=Join-Path $caseB 'u002-envelope-preparation.json';$preparationOutB=Join-Path $fixtureB.workspace 'receipts/u002-envelope.json';$intentPathB=Join-Path $fixtureB.workspace 'receipts/transactions/u002-envelope-prepared-transition.intent.json';$completionPathB=Join-Path $fixtureB.workspace 'receipts/transactions/u002-envelope-prepared-transition.completion.json';$intentB=ReadProtocol $intentPathB
    foreach($name in @('project','state','feature_lock')){$path=$(switch($name){project{'project.spec.json'}state{'workspace.state.json'}feature_lock{'feature.lock.json'}});Write-ToolingPreparationJson (Join-Path $fixtureB.workspace $path) $intentB.pre.$name.document};Remove-Item -LiteralPath $completionPathB -Force
    $eventsPathB=Join-Path $fixtureB.workspace 'iteration-events.jsonl';$eventLinesB=@(Get-Content -LiteralPath $eventsPathB);[IO.File]::WriteAllText($eventsPathB,(($eventLinesB[0..($eventLinesB.Count-2)]-join"`n")+"`n"),[Text.UTF8Encoding]::new($false));Assert-ToolingPreparation ((FileHash $eventsPathB)-ceq[string]$intentB.pre.events.sha256) 'could not reconstruct the exact after-artifacts recovery boundary'
    $contextArtifactB=@($intentB.artifacts|Where-Object{[string]$_.path-ceq[string]$intentB.tooling_context.path})[0];$contextPathB=Join-Path $fixtureB.workspace ([string]$contextArtifactB.path);$sourceArtifactB=@($intentB.artifacts|Where-Object{[string]$_.path-ceq[string]$intentB.artifacts[1].path})[0]
    Write-ToolingPreparationJson $contextPathB (ReadProtocol $contextPathB);$contextRawRejected=$false;try{Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $fixtureB.workspace -DevelopmentEnvelopePreparation $preparationInputB -ExpectedDevelopmentEnvelopePreparationSha256 (FileHash $preparationInputB) -OutPath $preparationOutB -Execute|Out-Null}catch{$contextRawRejected=$_.Exception.Message-like'*context*raw*'}
    Assert-ToolingPreparation ($contextRawRejected-and-not(Test-Path $completionPathB)-and(FileHash $eventsPathB)-ceq[string]$intentB.pre.events.sha256) 'same-canonical/different-raw context drift entered recovery';[IO.File]::WriteAllBytes($contextPathB,[Convert]::FromBase64String([string]$contextArtifactB.bytes_base64))
    Write-ToolingPreparationJson $sourcePathB (ReadProtocol $sourcePathB);$sourceRawRejected=$false;try{Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $fixtureB.workspace -DevelopmentEnvelopePreparation $preparationInputB -ExpectedDevelopmentEnvelopePreparationSha256 (FileHash $preparationInputB) -OutPath $preparationOutB -Execute|Out-Null}catch{$sourceRawRejected=$_.Exception.Message-like'*source*raw*'}
    Assert-ToolingPreparation ($sourceRawRejected-and-not(Test-Path $completionPathB)-and(FileHash $eventsPathB)-ceq[string]$intentB.pre.events.sha256) 'same-canonical/different-raw source drift entered recovery';[IO.File]::WriteAllBytes($sourcePathB,[Convert]::FromBase64String([string]$sourceArtifactB.bytes_base64))
    Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $fixtureB.workspace -DevelopmentEnvelopePreparation $preparationInputB -ExpectedDevelopmentEnvelopePreparationSha256 (FileHash $preparationInputB) -OutPath $preparationOutB -Execute|Out-Null
    [IO.File]::WriteAllText((Join-Path $ExecutorRoot 'tooling-advance.txt'),"advance`n",[Text.UTF8Encoding]::new($false));Invoke-ToolingPreparationGit $ExecutorRoot @('add','tooling-advance.txt')|Out-Null;Invoke-ToolingPreparationGit $ExecutorRoot @('commit','-m','advance tooling only')|Out-Null
    $admissionPathB=Join-Path $caseB 'admission.json';Write-ToolingPreparationJson $admissionPathB $fixtureB.admission_template;$failed=$false;try{Invoke-MorphospaceAdmitDevelopmentUnit -WorkspaceRoot $fixtureB.workspace -DevelopmentUnitAdmission $admissionPathB -OutPath (Join-Path $fixtureB.workspace 'receipts/u002-admission.json') -Timestamp '2026-08-25T00:01:00.0000000Z'|Out-Null}catch{$failed=$_.Exception.Message-like'*tooling*drift*'}
    Assert-ToolingPreparation ($failed-and-not(Test-Path (Join-Path $fixtureB.workspace 'receipts/transactions/u002-admission-admitted-transition.intent.json'))) 'tooling drift did not fail admission before intent publication'
    $replayFailed=$false;try{Invoke-MorphospacePrepareDevelopmentEnvelope -WorkspaceRoot $fixtureB.workspace -DevelopmentEnvelopePreparation (Join-Path $caseB 'u002-envelope-preparation.json') -ExpectedDevelopmentEnvelopePreparationSha256 (FileHash (Join-Path $caseB 'u002-envelope-preparation.json')) -OutPath (Join-Path $fixtureB.workspace 'receipts/u002-envelope.json') -Execute|Out-Null}catch{$replayFailed=$_.Exception.Message-like'*tooling*drift*'}
    Assert-ToolingPreparation ($replayFailed-and(FileHash $sourcePathB)-ceq$sourceBefore-and(Get-EnvelopeCanonicalJsonSha256 (ReadProtocol $sourcePathB).repositories)-ceq$pinsBefore) 'tooling drift changed product pins or entered preparation recovery'
    'Tooling preparation/admission separation self-tests passed.'
}finally{Remove-ToolingPreparationTemp $temp}
