param([switch]$SelfTest)
$ErrorActionPreference='Stop'
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Assert-Rejected([scriptblock]$Action,[string]$Message){$ok=$false;try{&$Action|Out-Null}catch{$ok=$true};if(-not$ok){throw $Message}}
function Invoke-TestGit([string]$Root,[string[]]$Arguments){$o=@(& git -C $Root @Arguments 2>&1|ForEach-Object{[string]$_});if($LASTEXITCODE-ne0){throw "git $($Arguments-join' ') failed: $($o-join"`n")"};@($o)}
function New-Repo([string]$Path){[IO.Directory]::CreateDirectory($Path)|Out-Null;Invoke-TestGit $Path @('init','-q')|Out-Null;Invoke-TestGit $Path @('config','user.name','fixture')|Out-Null;Invoke-TestGit $Path @('config','user.email','fixture@example.invalid')|Out-Null;Invoke-TestGit $Path @('config','core.autocrlf','false')|Out-Null;'fixture'|Set-Content (Join-Path $Path 'README.md') -Encoding utf8;Invoke-TestGit $Path @('add','README.md')|Out-Null;Invoke-TestGit $Path @('commit','-q','-m','base')|Out-Null;Invoke-TestGit $Path @('branch','-M','main')|Out-Null}
function Hash([string]$Path){([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([IO.File]::ReadAllBytes($Path)))).ToLowerInvariant()}
function New-Input([string]$Source,[string]$Planning,[string]$Path,[string]$Destination='projects/fixture/morphospace',[string]$Receipt='receipts/unpublished-authority.json'){
 $workspace=Join-Path $Source 'project/morphospace';$rows=@();$i=0
 foreach($f in @(Get-ChildItem $workspace -File -Recurse|Sort-Object FullName)){$rel=$f.FullName.Substring($workspace.Length+1).Replace('\','/');$rows+=[ordered]@{ordinal=$i;path=$rel;type='file';size=[int64]$f.Length;sha256=Hash $f.FullName};$i++}
 $doc=[ordered]@{'$schema'='../schemas/unpublished-workspace-materialization-v1.schema.json';schema='rusty.morphospace.workflow.unpublished_workspace_materialization.v1';materialization_id='fixture-unpublished-materialization';project_id='fixture-project';source=[ordered]@{repo_id='source-owner';head=([string]@(Invoke-TestGit $Source @('rev-parse','HEAD'))[0]).Trim();tree=([string]@(Invoke-TestGit $Source @('rev-parse','HEAD^{tree}'))[0]).Trim();branch='main';workspace_path='project/morphospace';inventory=$rows;state_anchor=[ordered]@{path='workspace.state.json';sha256=Hash (Join-Path $workspace 'workspace.state.json')}};planning=[ordered]@{repo_id='planning-owner';base_commit=([string]@(Invoke-TestGit $Planning @('rev-parse','HEAD'))[0]).Trim();base_tree=([string]@(Invoke-TestGit $Planning @('rev-parse','HEAD^{tree}'))[0]).Trim();branch='main';destination_workspace_path=$Destination;receipt_path=$Receipt};claims=@('owner-authorized one-time unpublished workspace materialization')}
 [IO.File]::WriteAllText($Path,($doc|ConvertTo-Json -Depth 20)+"`n",[Text.UTF8Encoding]::new($false));$doc
}
$root=Join-Path ([IO.Path]::GetTempPath()) ('unpublished-authority-'+[guid]::NewGuid().ToString('N'));$source=Join-Path $root source;$planning=Join-Path $root planning;$input=Join-Path $root input.json;$script=Join-Path $PSScriptRoot 'MaterializeUnpublishedPlanningAuthority.ps1'
try{
 New-Repo $source;New-Repo $planning;$workspace=Join-Path $source 'project/morphospace';[IO.Directory]::CreateDirectory((Join-Path $workspace 'iteration-units'))|Out-Null
 [IO.File]::WriteAllText((Join-Path $workspace 'project.spec.json'),'{"schema":"rusty.morphospace.workflow.project_spec.v2","project_id":"fixture-project"}',[Text.UTF8Encoding]::new($false))
 [IO.File]::WriteAllText((Join-Path $workspace 'workspace.state.json'),'{"schema":"rusty.morphospace.workflow.workspace_state.v2","current_unit":null}',[Text.UTF8Encoding]::new($false))
 [IO.File]::WriteAllText((Join-Path $workspace 'iteration-events.jsonl'),'{"schema":"rusty.morphospace.workflow.iteration_event.v1"}'+"`n",[Text.UTF8Encoding]::new($false))
 'unrelated dirty byte'|Set-Content (Join-Path $source 'unrelated.txt') -Encoding utf8
 $doc=New-Input $source $planning $input;$sourceBefore=Hash (Join-Path $workspace 'workspace.state.json');$sourceHead=([string]@(Invoke-TestGit $source @('rev-parse','HEAD'))[0]).Trim();$planningHead=([string]@(Invoke-TestGit $planning @('rev-parse','HEAD'))[0]).Trim()
 $plan=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning|ConvertFrom-Json;Assert-True(-not(Test-Path(Join-Path $planning 'projects/fixture/morphospace')))'Inspect mode created the destination.';Assert-True([string]$plan.schema-ceq'rusty.morphospace.workflow.unpublished_planning_authority_plan.v1')'Inspect mode returned the wrong plan.'
 $bad=$doc|ConvertTo-Json -Depth 20|ConvertFrom-Json;$bad.source.state_anchor.sha256='f'*64;$bad|ConvertTo-Json -Depth 20|Set-Content $input -Encoding utf8;Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'Anchor mismatch was accepted.'
 $doc=New-Input $source $planning $input;$bad=$doc|ConvertTo-Json -Depth 20|ConvertFrom-Json;$bad.source.inventory[0].sha256='e'*64;$bad|ConvertTo-Json -Depth 20|Set-Content $input -Encoding utf8;Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'Inventory tamper was accepted.'
 $doc=New-Input $source $planning $input;$bad=$doc|ConvertTo-Json -Depth 20|ConvertFrom-Json;$bad.planning.base_commit='d'*40;$bad|ConvertTo-Json -Depth 20|Set-Content $input -Encoding utf8;Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'Wrong planning identity was accepted.'
 $doc=New-Input $source $planning $input;'dirty'|Set-Content(Join-Path $planning dirty.txt);Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'Dirty planning checkout was accepted.';Remove-Item(Join-Path $planning dirty.txt)
 Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $source} 'Same repository was accepted.'
 Invoke-TestGit $planning @('checkout','--detach','-q')|Out-Null;Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'Detached planning checkout was accepted.';Invoke-TestGit $planning @('checkout','-q','main')|Out-Null;Invoke-TestGit $planning @('restore','README.md')|Out-Null
 $doc=New-Input $source $planning $input;$bad=$doc|ConvertTo-Json -Depth 20|ConvertFrom-Json;$bad.source.branch='other';$bad|ConvertTo-Json -Depth 20|Set-Content $input -Encoding utf8;Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'Stale source branch was accepted.'
 $doc=New-Input $source $planning $input;$bad=$doc|ConvertTo-Json -Depth 20|ConvertFrom-Json;$bad.source.inventory[1].path=$bad.source.inventory[0].path.ToUpperInvariant();$bad|ConvertTo-Json -Depth 20|Set-Content $input -Encoding utf8;Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'Path/case tamper was accepted.'
 $doc=New-Input $source $planning $input 'projects/collision/morphospace' 'workspace.state.json';Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning -Execute} 'Receipt collision was accepted.';Assert-True(-not(Test-Path(Join-Path $planning 'projects/collision/morphospace')))'Failed staging left a destination.'
 $doc=New-Input $source $planning $input
 $receipt=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning -Timestamp '2026-08-07T12:00:00Z' -Execute|ConvertFrom-Json;$destination=Join-Path $planning 'projects/fixture/morphospace';Assert-True(Test-Path(Join-Path $destination 'receipts/unpublished-authority.json'))'Receipt was not atomically installed.';Assert-True([string]$receipt.authority.destination_workspace-ceq'sole-workspace-authority')'Receipt has the wrong authority designation.'
 Assert-True((Hash(Join-Path $workspace 'workspace.state.json'))-ceq$sourceBefore)'Source workspace was modified.';Assert-True(([string]@(Invoke-TestGit $source @('rev-parse','HEAD'))[0]).Trim()-ceq$sourceHead)'Source ref changed.';Assert-True(([string]@(Invoke-TestGit $planning @('rev-parse','HEAD'))[0]).Trim()-ceq$planningHead)'Planning ref changed.'
 Assert-Rejected {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning -Execute} 'Second execution was accepted.'
 $receiptPath=Join-Path $destination 'receipts/unpublished-authority.json';$receiptDoc=Get-Content -Raw $receiptPath|ConvertFrom-Json;$receiptDoc.input.sha256='0'*64;$receiptDoc|ConvertTo-Json -Depth 20|Set-Content $receiptPath -Encoding utf8;Assert-True((Get-Content -Raw $receiptPath)-match('0'*64))'Receipt tamper fixture failed.'
 if([Environment]::OSVersion.Platform-eq[PlatformID]::Win32NT){$link=Join-Path $workspace 'link.json';try{New-Item -ItemType SymbolicLink -Path $link -Target (Join-Path $workspace 'workspace.state.json') -ErrorAction Stop|Out-Null;$null=New-Input $source $planning (Join-Path $root link-input.json) 'projects/link/morphospace';Assert-Rejected {&$script -InputPath (Join-Path $root link-input.json) -SourceRepository $source -PlanningRepository $planning} 'Reparse point was accepted.'}catch{Write-Host 'Reparse-point fixture skipped: symbolic-link creation is unavailable.'}finally{Remove-Item $link -Force -ErrorAction SilentlyContinue}}
 Write-Host 'Unpublished planning-authority materialization self-test passed.'
}finally{if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force}}
