param([switch]$SelfTest)
$ErrorActionPreference='Stop'
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Reject([scriptblock]$Action,[string]$Label){$rejected=$false;try{&$Action|Out-Null}catch{$rejected=$true};if(-not$rejected){throw "Expected rejection: $Label"}}
function Git([string]$Root,[string[]]$Arguments){$o=@(& git.exe -C $Root @Arguments 2>&1|ForEach-Object{[string]$_});if($LASTEXITCODE-ne0){throw "Fixture git failed: $($Arguments-join' '): $($o-join'; ')"};@($o)}
function Hash([string]$Path){$s=[IO.File]::OpenRead($Path);try{([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($s))).ToLowerInvariant()}finally{$s.Dispose()}}
function New-Repo([string]$Path){[IO.Directory]::CreateDirectory($Path)|Out-Null;Git $Path @('init','-q')|Out-Null;Git $Path @('config','user.name','fixture')|Out-Null;Git $Path @('config','user.email','fixture@example.invalid')|Out-Null;Git $Path @('config','core.autocrlf','false')|Out-Null;[IO.File]::WriteAllText((Join-Path $Path 'README.md'),"fixture`n",[Text.UTF8Encoding]::new($false));Git $Path @('add','README.md')|Out-Null;Git $Path @('commit','-q','-m','base')|Out-Null;Git $Path @('branch','-M','main')|Out-Null}
function Write-State([string]$Workspace){$state=[ordered]@{'$schema'='../schemas/workspace-state-v2.schema.json';schema='rusty.morphospace.workflow.workspace_state.v2';project_id='fixture-project';plan_revision=1;current_unit=$null;next_ready_unit=$null;last_event_id=$null;last_accepted_receipt=$null;repository_heads=@();module_registry=[ordered]@{lock_revision=$null;lock_fingerprint=$null;modules=@()};capability_registry=@();dirty_repositories=@('source-owner');blockers=@();validation_checkpoint=$null;pending_push_bundle=$null};[IO.File]::WriteAllText((Join-Path $Workspace 'workspace.state.json'),($state|ConvertTo-Json -Depth 20 -Compress),[Text.UTF8Encoding]::new($false))}
function New-Workspace([string]$Source){$ws=Join-Path $Source 'morphospace';[IO.Directory]::CreateDirectory((Join-Path $ws 'iteration-units'))|Out-Null;[IO.File]::WriteAllText((Join-Path $ws 'project.spec.json'),'{"schema":"rusty.morphospace.workflow.project_spec.v2","project_id":"fixture-project"}',[Text.UTF8Encoding]::new($false));Write-State $ws;[IO.File]::WriteAllText((Join-Path $ws 'iteration-events.jsonl'),'{"schema":"rusty.morphospace.workflow.iteration_event.v1"}'+"`n",[Text.UTF8Encoding]::new($false));$ws}
function Inventory([string]$Workspace){$rows=@();$i=0;foreach($f in @(Get-ChildItem $Workspace -File -Recurse|Sort-Object FullName)){$rel=$f.FullName.Substring($Workspace.Length+1).Replace('\','/');$rows+=[ordered]@{ordinal=$i;path=$rel;type='file';size=[int64]$f.Length;sha256=Hash $f.FullName};$i++};@($rows)}
function New-Input([string]$Source,[string]$Planning,[string]$Path,[string]$Destination='projects/fixture/morphospace',[string]$Receipt='receipts/unpublished-authority.json'){$ws=Join-Path $Source 'morphospace';$doc=[ordered]@{'$schema'='../schemas/unpublished-workspace-materialization-v1.schema.json';schema='rusty.morphospace.workflow.unpublished_workspace_materialization.v1';materialization_id='fixture-unpublished-materialization';project_id='fixture-project';source=[ordered]@{repo_id='source-owner';head=([string]@(Git $Source @('rev-parse','HEAD'))[0]).Trim();tree=([string]@(Git $Source @('rev-parse','HEAD^{tree}'))[0]).Trim();branch='main';workspace_path='morphospace';inventory=@(Inventory $ws);state_anchor=[ordered]@{path='workspace.state.json';sha256=Hash(Join-Path $ws 'workspace.state.json')}};planning=[ordered]@{repo_id='planning-owner';base_commit=([string]@(Git $Planning @('rev-parse','HEAD'))[0]).Trim();base_tree=([string]@(Git $Planning @('rev-parse','HEAD^{tree}'))[0]).Trim();branch='main';destination_workspace_path=$Destination;receipt_path=$Receipt}};[IO.File]::WriteAllText($Path,($doc|ConvertTo-Json -Depth 20)+"`n",[Text.UTF8Encoding]::new($false));$doc}
function Write-Doc([object]$Doc,[string]$Path){[IO.File]::WriteAllText($Path,($Doc|ConvertTo-Json -Depth 40)+"`n",[Text.UTF8Encoding]::new($false))}
function Clone($Doc){$Doc|ConvertTo-Json -Depth 40|ConvertFrom-Json -Depth 40}
function Try-Junction([string]$Path,[string]$Target){try{New-Item -ItemType Junction -Path $Path -Target $Target -ErrorAction Stop}catch{return $false};$true}
function Try-HardLink([string]$Path,[string]$Target){try{New-Item -ItemType HardLink -Path $Path -Target $Target -ErrorAction Stop|Out-Null}catch{return $false};$true}
function Wait-JobDone($Job){Wait-Job $Job -Timeout 20|Out-Null;Receive-Job $Job -ErrorAction SilentlyContinue|Out-Null;Remove-Job $Job -Force -ErrorAction SilentlyContinue}

$root=Join-Path ([IO.Path]::GetTempPath()) ('unpublished-authority-security-'+[guid]::NewGuid().ToString('N'));$source=Join-Path $root source;$planning=Join-Path $root planning;$input=Join-Path $root input.json;$script=Join-Path $PSScriptRoot 'MaterializeUnpublishedPlanningAuthority.ps1';$inputSchema=Join-Path (Split-Path -Parent $PSScriptRoot) 'schemas\unpublished-workspace-materialization-v1.schema.json'
try{
 New-Repo $source;New-Repo $planning;$workspace=New-Workspace $source;[IO.File]::WriteAllText((Join-Path $source 'unrelated.txt'),'unrelated dirty byte',[Text.UTF8Encoding]::new($false));$doc=New-Input $source $planning $input;$sourceSnapshot=@(Inventory $workspace)|ConvertTo-Json -Depth 10 -Compress;$sourceHead=([string]@(Git $source @('rev-parse','HEAD'))[0]).Trim();$planningHead=([string]@(Git $planning @('rev-parse','HEAD'))[0]).Trim()

 $plan=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning|ConvertFrom-Json -Depth 40;Assert-True(-not(Test-Path(Join-Path $planning 'projects/fixture/morphospace')))'Inspect mutated destination.';Assert-True($plan.route_eligibility.planning_workspace_projection_applicable-eq$false)'Inspect omitted derived route proof.'

 $bad=Clone $doc;$bad.source.workspace_path='arbitrary/clean';Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'arbitrary non-morphospace path'
 $bad=Clone $doc;$bad.source.state_anchor.path='project.spec.json';Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'wrong anchor path'
 $bad=Clone $doc;$bad|Add-Member claims @('validated','accepted','published','source-authoritative');Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'caller claims and contradictory authority prose'
 $bad=Clone $doc;$bad.source.inventory[0].path='CON.json';Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'reserved Windows name'
 $bad=Clone $doc;$bad.source.inventory[1].path=$bad.source.inventory[0].path.ToUpperInvariant();Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'case-equivalent inventory collision'
 $bad=Clone $doc;$bad.source.inventory[0].path='name. ';Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'trailing-dot-space path'
 $bad=Clone $doc;$bad.source.state_anchor.sha256='f'*64;Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'state anchor mismatch'

 $cleanSource=Join-Path $root clean-source;New-Repo $cleanSource;$cleanWs=New-Workspace $cleanSource;Git $cleanSource @('add','morphospace')|Out-Null;Git $cleanSource @('commit','-q','-m','published-workspace')|Out-Null;$cleanInput=Join-Path $root clean.json;New-Input $cleanSource $planning $cleanInput|Out-Null;Reject {&$script -InputPath $cleanInput -SourceRepository $cleanSource -PlanningRepository $planning} 'clean tracked projection-eligible input'
 [IO.File]::WriteAllText((Join-Path $cleanWs 'workspace.state.json'),(Get-Content -Raw(Join-Path $cleanWs 'workspace.state.json'))+' ',[Text.UTF8Encoding]::new($false));$dirtyPublished=Join-Path $root dirty-published.json;New-Input $cleanSource $planning $dirtyPublished|Out-Null;$projectionPlan=&$script -InputPath $dirtyPublished -SourceRepository $cleanSource -PlanningRepository $planning|ConvertFrom-Json;Assert-True($projectionPlan.route_eligibility.pinned_tree_inventory_equal-eq$false)'Divergent tracked bytes were not identified.'

 $doc=New-Input $source $planning $input;$bad=Clone $doc;$bad.source.inventory[0].sha256='e'*64;Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'inventory tamper'
 $bad=Clone $doc;$bad.planning.base_commit='d'*40;Write-Doc $bad $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'wrong planning identity'
 [IO.File]::WriteAllText((Join-Path $planning 'dirty.txt'),'dirty',[Text.UTF8Encoding]::new($false));Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'dirty destination repository';Remove-Item(Join-Path $planning 'dirty.txt')
 Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $source} 'same repository';Git $planning @('checkout','--detach','-q')|Out-Null;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'detached planning';Git $planning @('checkout','-q','main')|Out-Null

 if($IsWindows){
   $outside=Join-Path $root outside;[IO.Directory]::CreateDirectory($outside)|Out-Null;$junction=Join-Path $workspace 'junction-dir';if(Try-Junction $junction $outside){$junctionInput=Join-Path $root junction.json;New-Input $source $planning $junctionInput|Out-Null;Reject {&$script -InputPath $junctionInput -SourceRepository $source -PlanningRepository $planning} 'source ancestor junction/reparse';Remove-Item $junction -Force}else{Write-Host 'CAPABILITY-SKIP source-junction: New-Item -ItemType Junction setup unavailable.'}
   $projects=Join-Path $planning projects;if(Try-Junction $projects $outside){$doc=New-Input $source $planning $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'destination-parent junction';Remove-Item $projects -Force}else{Write-Host 'CAPABILITY-SKIP destination-junction: New-Item -ItemType Junction setup unavailable.'}
   $hard=Join-Path $workspace 'hardlink-state.json';if(Try-HardLink $hard (Join-Path $workspace 'workspace.state.json')){$hardInput=Join-Path $root hardlink.json;New-Input $source $planning $hardInput|Out-Null;Reject {&$script -InputPath $hardInput -SourceRepository $source -PlanningRepository $planning} 'hard-linked source file';Remove-Item $hard -Force}else{Write-Host 'CAPABILITY-SKIP hard-link: New-Item -ItemType HardLink setup unavailable.'}
 }

 $doc=New-Input $source $planning $input;$raw=$doc|ConvertTo-Json -Depth 20;$rawBytes=[Text.Encoding]::UTF8.GetByteCount($raw);$exact=$raw+(' '*(1MB-$rawBytes));[IO.File]::WriteAllText($input,$exact,[Text.UTF8Encoding]::new($false));$null=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning;[IO.File]::AppendAllText($input,' ',[Text.UTF8Encoding]::new($false));Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'input byte over-bound'
 $doc=New-Input $source $planning $input;$schemaDoc=Clone $doc;while($schemaDoc.source.inventory.Count-lt512){$i=$schemaDoc.source.inventory.Count;$schemaDoc.source.inventory+= [pscustomobject]@{ordinal=$i;path="f$i.json";type='file';size=0;sha256='0'*64}};$schemaRaw=$schemaDoc|ConvertTo-Json -Depth 20;Assert-True($schemaRaw|Test-Json -SchemaFile $inputSchema)'Exact 512-item schema boundary rejected.';$schemaDoc.source.inventory+=[pscustomobject]@{ordinal=512;path='over.json';type='file';size=0;sha256='0'*64};Reject {($schemaDoc|ConvertTo-Json -Depth 20)|Test-Json -SchemaFile $inputSchema} '513-item schema over-bound'

 $payload=Join-Path $workspace payload.bin;[IO.File]::WriteAllBytes($payload,[byte[]]::new(4MB));$doc=New-Input $source $planning $input;$null=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning;[IO.File]::WriteAllBytes($payload,[byte[]]::new(4MB+1));$doc=New-Input $source $planning $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'per-file byte over-bound';Remove-Item $payload
 $ledger=Join-Path $workspace 'iteration-events.jsonl';[IO.File]::WriteAllLines($ledger,@(1..4096|ForEach-Object{'{}'}),[Text.UTF8Encoding]::new($false));$doc=New-Input $source $planning $input;$null=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning;[IO.File]::AppendAllText($ledger,"{}`n",[Text.UTF8Encoding]::new($false));$doc=New-Input $source $planning $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'JSONL record over-bound'
 $line='{"v":"'+('x'*(256KB-8))+'"}';Assert-True([Text.Encoding]::UTF8.GetByteCount($line)-eq256KB)'Line boundary fixture length is wrong.';[IO.File]::WriteAllText($ledger,$line+"`n",[Text.UTF8Encoding]::new($false));$doc=New-Input $source $planning $input;$null=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning;[IO.File]::WriteAllText($ledger,$line+' '+"`n",[Text.UTF8Encoding]::new($false));$doc=New-Input $source $planning $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'JSONL line over-bound';[IO.File]::WriteAllText($ledger,'{"schema":"rusty.morphospace.workflow.iteration_event.v1"}'+"`n",[Text.UTF8Encoding]::new($false))

 $currentTotal=[int64]0;foreach($row in @(Inventory $workspace)){$currentTotal+=[int64]$row.size};$remaining=32MB-$currentTotal;$index=0;while($remaining-gt0){$take=[Math]::Min(4MB,$remaining);[IO.File]::WriteAllBytes((Join-Path $workspace "aggregate-$index.bin"),[byte[]]::new($take));$remaining-=$take;$index++};$doc=New-Input $source $planning $input;$exactTotal=[int64]0;foreach($row in @($doc.source.inventory)){$exactTotal+=[int64]$row.size};Assert-True($exactTotal-eq32MB)"Aggregate boundary fixture totals $exactTotal rather than 33554432.";$null=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning;[IO.File]::WriteAllBytes((Join-Path $workspace 'aggregate-over.bin'),[byte[]]::new(1));$doc=New-Input $source $planning $input;Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning} 'aggregate byte over-bound';Get-ChildItem $workspace -Filter 'aggregate-*.bin'|Remove-Item

 $doc=New-Input $source $planning $input 'new-parent/deeper/morphospace';$driftJob=Start-Job -ArgumentList $planning,$workspace -ScriptBlock{param($p,$w);$limit=[DateTime]::UtcNow.AddSeconds(15);while([DateTime]::UtcNow-lt$limit){if(Get-ChildItem $p -Directory -Recurse -Filter '*.materializing-*' -ErrorAction SilentlyContinue){[IO.File]::AppendAllText((Join-Path $w 'workspace.state.json'),' ',[Text.UTF8Encoding]::new($false));return};Start-Sleep -Milliseconds 20}};Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning -ObservationDelayMilliseconds 300 -Execute} 'source drift during staging/final observation';Wait-JobDone $driftJob;Assert-True(-not(Test-Path(Join-Path $planning 'new-parent')))'Attempt-created empty destination parents were not cleaned.';Write-State $workspace
 [IO.Directory]::CreateDirectory((Join-Path $planning 'preexisting'))|Out-Null;$doc=New-Input $source $planning $input 'preexisting/deeper/morphospace';$stageJob=Start-Job -ArgumentList $planning -ScriptBlock{param($p);$limit=[DateTime]::UtcNow.AddSeconds(15);while([DateTime]::UtcNow-lt$limit){$s=Get-ChildItem $p -Directory -Recurse -Filter '*.materializing-*' -ErrorAction SilentlyContinue|Select-Object -First 1;if($s){$f=Get-ChildItem $s.FullName -File -Recurse|Select-Object -First 1;if($f){[IO.File]::AppendAllText($f.FullName,'tamper',[Text.UTF8Encoding]::new($false));return}};Start-Sleep -Milliseconds 20}};Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning -ObservationDelayMilliseconds 300 -Execute} 'staged-copy tamper';Wait-JobDone $stageJob;Assert-True(Test-Path(Join-Path $planning 'preexisting'))'Pre-existing parent was removed.';Assert-True(-not(Test-Path(Join-Path $planning 'preexisting/deeper')))'Created child parent survived failure.'

 $doc=New-Input $source $planning $input 'rollback/after-move/morphospace';$destination=Join-Path $planning 'rollback/after-move/morphospace';$receiptPath=Join-Path $destination 'receipts/unpublished-authority.json';$moveJob=Start-Job -ArgumentList $receiptPath -ScriptBlock{param($r);$limit=[DateTime]::UtcNow.AddSeconds(15);while([DateTime]::UtcNow-lt$limit){if(Test-Path $r){[IO.File]::WriteAllText($r,'{}',[Text.UTF8Encoding]::new($false));return};Start-Sleep -Milliseconds 10}};Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning -ObservationDelayMilliseconds 300 -Execute} 'post-move receipt tamper/readback failure';Wait-JobDone $moveJob;Assert-True(-not(Test-Path(Join-Path $planning 'rollback')))'Post-move failure did not exactly roll back destination and owned parents.'

 $doc=New-Input $source $planning $input;$sourceBefore=@(Inventory $workspace)|ConvertTo-Json -Depth 10 -Compress;$receipt=&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning -Timestamp '2026-08-07T12:00:00Z' -Execute|ConvertFrom-Json -Depth 40;$destination=Join-Path $planning 'projects/fixture/morphospace';Assert-True(Test-Path(Join-Path $destination 'receipts/unpublished-authority.json'))'Success did not install receipt.';Assert-True(-not$receipt.PSObject.Properties['claims'])'Receipt retained caller claims.';Assert-True($receipt.route_eligibility.workspace_scope-ceq'repository-root-morphospace')'Receipt route facts are not tool-generated constants.';Assert-True((@(Inventory $workspace)|ConvertTo-Json -Depth 10 -Compress)-ceq$sourceBefore)'Source bytes changed.';Assert-True(([string]@(Git $source @('rev-parse','HEAD'))[0]).Trim()-ceq$sourceHead)'Source ref changed.';Assert-True(([string]@(Git $planning @('rev-parse','HEAD'))[0]).Trim()-ceq$planningHead)'Planning ref changed.';Reject {&$script -InputPath $input -SourceRepository $source -PlanningRepository $planning -Execute} 'second execution'
 Write-Host 'Unpublished planning-authority security self-test passed.'
}finally{Get-Job -ErrorAction SilentlyContinue|Remove-Job -Force -ErrorAction SilentlyContinue;if(Test-Path $root){Remove-Item -LiteralPath $root -Recurse -Force}}
