param([string]$Path="",[string]$WorkspaceRoot="",[switch]$SelfTest)
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospacePlannedPublication.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospacePublishedPrerequisiteSuffix.psm1') -Force
function Write-Json($Path,$Value){$parent=Split-Path -Parent $Path;if($parent-and-not(Test-Path $parent)){New-Item -ItemType Directory $parent|Out-Null};[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 32)+"`n",[Text.UTF8Encoding]::new($false))}
function Hash($Path){(Get-FileHash $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Invoke-FixtureGit($Repo,[string[]]$GitArgs){$o=@(& (Get-Command git -CommandType Application).Source -C $Repo @GitArgs 2>&1);if($LASTEXITCODE){throw "git $($GitArgs-join' ') failed: $($o-join' ')"};if($o.Count){([string]($o|Select-Object -Last 1)).Trim()}else{''}}
function Clone($Value){$Value|ConvertTo-Json -Depth 32|ConvertFrom-Json}
function Reject([scriptblock]$Action,[string]$Name){try{&$Action|Out-Null}catch{return};throw "Damaged published-prerequisite case '$Name' was accepted."}

if($SelfTest){
 $root=Join-Path ([IO.Path]::GetTempPath()) ('published-prerequisite-'+[guid]::NewGuid().ToString('N'));$ws=Join-Path $root 'planning\project\morphospace';$src=Join-Path $root 'source';$planning=Split-Path (Split-Path $ws -Parent) -Parent
 try{
 foreach($repo in @($src,$planning)){New-Item -ItemType Directory $repo -Force|Out-Null;Invoke-FixtureGit $repo @('init','-q');Invoke-FixtureGit $repo @('config','user.email','fixture@example.invalid');Invoke-FixtureGit $repo @('config','user.name','Fixture');Invoke-FixtureGit $repo @('config','core.autocrlf','false');Invoke-FixtureGit $repo @('checkout','-q','-b','main');[IO.File]::WriteAllText((Join-Path $repo 'base.txt'),"base`n");Invoke-FixtureGit $repo @('add','.');Invoke-FixtureGit $repo @('commit','-q','-m','base')}
  New-Item -ItemType Directory $ws -Force|Out-Null
  Write-Json (Join-Path $ws 'project.spec.json') ([ordered]@{'$schema'='../../schemas/project-spec-v2.schema.json';schema='rusty.morphospace.workflow.project_spec.v2';project_id='test-project';revision=1;owner='fixture';purpose='Published prerequisite reconciliation fixture.';activation_model=[ordered]@{default='disabled';unlisted_modules='inert';runtime_rule='selected-lock-and-runtime-input'};composition=[ordered]@{selected_features=@();denied_features=@();selected_modules=@();denied_modules=@();allowed_permissions=@();denied_permissions=@();data_classes=@()};authority_map=@();repositories=@([ordered]@{repo_id='source-repo';role='source';path=$src;allowed_paths=@('accepted.txt')},[ordered]@{repo_id='planning-repo';role='planning';path=$planning;allowed_paths=@('project/morphospace/')});modules=@();non_scope=@('Real repositories.');validation_profiles=@();acceptance_profiles=@();release_policy=[ordered]@{versioning='semver';commit_policy='Fixture only.';push_checkpoint='integration-batch';source_first=$true;planning_last=$true;force_push_allowed=$false};public_boundary=[ordered]@{mode='mixed';private_overlay='local/';prohibited_evidence=@()}})
  Write-Json (Join-Path $ws 'feature.lock.json') ([ordered]@{'$schema'='../../schemas/feature-lock-v2.schema.json';schema='rusty.morphospace.workflow.feature_lock.v2';project_id='test-project';project_revision=1;revision=1;generated_at='1970-01-01T00:00:00Z';resolver_version='rusty-morphospace-feature-resolver/2';lock_fingerprint='4142867dc0e3e62f910761aa5a24a75fc74400c34a33af1e38dee2fb9ab7f7be';default_activation='disabled';activation_rule='selected-lock-and-runtime-input';selected_features=@();denied_features=@();features=@();effect_union=[ordered]@{permissions=@();services=@();activities=@();queries=@();tools=@();assets=@();shaders=@();native_libraries=@();commands=@();routes=@();streams=@();inputs=@();scenes=@();markers=@()}})
  Write-Json (Join-Path $ws 'workspace.state.json') ([ordered]@{'$schema'='../../schemas/workspace-state-v2.schema.json';schema='rusty.morphospace.workflow.workspace_state.v2';project_id='test-project';plan_revision=1;current_unit=$null;next_ready_unit=$null;last_event_id=$null;last_accepted_receipt=$null;repository_heads=@();repository_checkpoints=@();module_registry=[ordered]@{lock_revision=1;lock_fingerprint='4142867dc0e3e62f910761aa5a24a75fc74400c34a33af1e38dee2fb9ab7f7be';modules=@()};capability_registry=@();dirty_repositories=@();blockers=@();validation_checkpoint=$null;pending_push_bundle=$null})
  [IO.File]::WriteAllText((Join-Path $ws 'iteration-events.jsonl'),'')
  $fixtureUnit=[ordered]@{'$schema'='../schemas/iteration-unit.schema.json';schema='rusty.morphospace.workflow.iteration_unit.v1';unit_id='trigger-unit';project_id='test-project';status='accepted';objective='Exercise exact published prerequisite reconciliation.';change_categories=@('workflow');instruction_impact='none';instruction_surfaces=@();instruction_none_justification='Temporary owner self-test.';prerequisites=@();allowed_repositories=@([ordered]@{repo_id='source-repo';allowed_paths=@('accepted.txt')});non_scope=@('Real repositories.');acceptance=@([ordered]@{acceptance_id='self-test';proof='The exact transition passes.';command='Test-PublishedPrerequisiteSuffixReconciliation.ps1 -SelfTest'});risk_tier='standard';device_requirement='none';validation=@([ordered]@{profile_id='workflow';command='temporary validation command'});outputs=@('reconciliation event');commit_policy='Temporary repository only.';push_checkpoint='integration-batch'}
  Write-Json (Join-Path $ws 'iteration-units\trigger-unit.json') $fixtureUnit
  $fixtureState=Get-Content -Raw (Join-Path $ws 'workspace.state.json')|ConvertFrom-Json;$fixtureState.current_unit=$null;$fixtureState.next_ready_unit=$null;$fixtureState.pending_push_bundle=[pscustomobject]@{bundle_id='trigger-unit-push-bundle';unit_ids=@('trigger-unit');repo_ids=@('source-repo','planning-repo');ready=$true};$fixtureState.validation_checkpoint=[pscustomobject]@{receipt='receipts/prior-pass.json';result='pass';tier='standard'};Write-Json (Join-Path $ws 'workspace.state.json') $fixtureState
  Write-Json (Join-Path $ws 'receipts\prior-pass.json') ([ordered]@{schema='rusty.morphospace.workflow.validation_receipt.v1';unit_id='prior-unit';result='pass'})
  Invoke-FixtureGit $planning @('add','.');Invoke-FixtureGit $planning @('commit','-q','-m','workspace fixture')
  $srcOld=Invoke-FixtureGit $src @('rev-parse','HEAD');[IO.File]::WriteAllText((Join-Path $src 'accepted.txt'),"accepted`n");Invoke-FixtureGit $src @('add','.');Invoke-FixtureGit $src @('commit','-q','-m','accepted source');$srcFinal=Invoke-FixtureGit $src @('rev-parse','HEAD');$srcTree=Invoke-FixtureGit $src @('rev-parse','HEAD^{tree}')
  $planOld=Invoke-FixtureGit $planning @('rev-parse','HEAD');New-Item -ItemType Directory $ws -Force|Out-Null;[IO.File]::WriteAllText((Join-Path $ws 'prepared.txt'),"prepared`n");Invoke-FixtureGit $planning @('add','.');Invoke-FixtureGit $planning @('commit','-q','-m','prepare');$prepared=Invoke-FixtureGit $planning @('rev-parse','HEAD')
  New-Item -ItemType Directory (Join-Path $ws 'receipts') -Force|Out-Null;Write-Json (Join-Path $ws 'unit-status.json') ([ordered]@{unit_id='trigger-unit';status='accepted'});Write-Json (Join-Path $ws 'prepared-event.json') ([ordered]@{event_id='trigger-unit-push-prepared-0001';event_type='commit'})
  $plan=[ordered]@{schema='rusty.morphospace.workflow.push_bundle_plan.v1';bundle_id='trigger-unit-push-bundle';project_id='test-project';unit_ids=@('trigger-unit');prepared_at='2026-07-20T10:00:00Z';dependency_order=@('source-repo','planning-repo');repositories=@([ordered]@{repo_id='source-repo';role='source';branch='main';commit=$srcFinal;upstream='origin/main';ahead=0;behind=0},[ordered]@{repo_id='planning-repo';role='planning';branch='main';commit=$prepared;upstream='origin/main';ahead=0;behind=0});source_first=$true;planning_last=$true;execution='not-performed';force_push_allowed=$false};Write-Json (Join-Path $ws 'receipts\plan.json') $plan
  $executed=[ordered]@{schema='rusty.morphospace.workflow.executed_push_receipt.v1';receipt_id='executed-receipt';bundle_id=$plan.bundle_id;project_id=$plan.project_id;unit_ids=@('trigger-unit');prepared_plan_id=$plan.bundle_id;started_at='2026-07-20T10:01:00Z';finished_at='2026-07-20T10:02:00Z';status='validated-pushed';execution='externally-performed';dependency_order=@('source-repo','planning-repo');execution_order=@('source-repo','planning-repo');repositories=@([ordered]@{repo_id='source-repo';old_revision=$srcOld;new_revision=$srcFinal;observed_remote_revision=$srcFinal},[ordered]@{repo_id='planning-repo';old_revision=$planOld;new_revision=$prepared;observed_remote_revision=$prepared});force_push_used=$false;remote_readback_complete=$true;failure=$null};$executedPath=Join-Path $ws 'receipts\executed.json';Write-Json $executedPath $executed
  $account=[ordered]@{schema='rusty.morphospace.workflow.planned_publication_accounting.v1';accounting_id='publication-accounting';project_id='test-project';bundle_id=$plan.bundle_id;trigger_unit_id='trigger-unit';prepared_plan=[ordered]@{path='receipts/plan.json';sha256=Hash (Join-Path $ws 'receipts\plan.json')};prepared_event=[ordered]@{event_id='trigger-unit-push-prepared-0001';path='prepared-event.json';sha256=Hash (Join-Path $ws 'prepared-event.json')};executed_push_receipt=[ordered]@{path='receipts/executed.json';sha256=Hash $executedPath};chronology=[ordered]@{prepared_at='2026-07-20T10:00:00Z';push_started_at='2026-07-20T10:01:00Z';push_finished_at='2026-07-20T10:02:00Z';accounted_at='2026-07-20T10:03:00Z'};dependency_order=@('source-repo','planning-repo');execution_order=@('source-repo','planning-repo');repositories=@([ordered]@{repo_id='source-repo';role='source';branch='main';upstream='origin/main';old_revision=$srcOld;prepared_revision=$srcFinal;final_revision=$srcFinal;remote_readback_revision=$srcFinal;source_first=$true;planning_last=$false;fast_forward_verified=$true;force_push_used=$false;worktree_clean=$true;units=@([ordered]@{unit_id='trigger-unit';role='triggering-unit';status_at_publication='accepted';status_evidence=[ordered]@{path='unit-status.json';sha256=Hash (Join-Path $ws 'unit-status.json')};no_acceptance_claim=$false});commits=@([ordered]@{revision=$srcFinal;role='triggering-unit';unit_id='trigger-unit';changed_paths=@('accepted.txt')});allowed_finalization_paths=@()},[ordered]@{repo_id='planning-repo';role='planning-transport';branch='main';upstream='origin/main';old_revision=$planOld;prepared_revision=$prepared;final_revision=$prepared;remote_readback_revision=$prepared;source_first=$false;planning_last=$true;fast_forward_verified=$true;force_push_used=$false;worktree_clean=$true;units=@([ordered]@{unit_id='trigger-unit';role='triggering-unit';status_at_publication='accepted';status_evidence=[ordered]@{path='unit-status.json';sha256=Hash (Join-Path $ws 'unit-status.json')};no_acceptance_claim=$false});commits=@([ordered]@{revision=$prepared;role='triggering-unit';unit_id='trigger-unit';changed_paths=@('project/morphospace/prepared.txt')});allowed_finalization_paths=@()});workspace_transition=[ordered]@{pending_push_bundle_before=$plan.bundle_id;pending_push_bundle_after=$null};force_push_used=$false;remote_readback_complete=$true;failure=$null};$accountPath=Join-Path $ws 'receipts\accounting.json';Write-Json $accountPath $account;Test-MorphospacePlannedPublicationDocument $accountPath $ws|Out-Null
  $executedRel='project/morphospace/receipts/executed.json';$accountRel='project/morphospace/receipts/accounting.json';$account.chronology.accounted_at='2026-07-20T10:03:30Z';Write-Json $accountPath $account;Invoke-FixtureGit $planning @('add',$executedRel,$accountRel);Invoke-FixtureGit $planning @('commit','-q','-m','publish exact prerequisites');$suffixFirst=Invoke-FixtureGit $planning @('rev-parse','HEAD');$account.chronology.accounted_at='2026-07-20T10:03:00Z';Write-Json $accountPath $account;Invoke-FixtureGit $planning @('add',$accountRel);Invoke-FixtureGit $planning @('commit','-q','-m','correct full accounting binding');$suffix=Invoke-FixtureGit $planning @('rev-parse','HEAD');$suffixTree=Invoke-FixtureGit $planning @('rev-parse','HEAD^{tree}');$preparedTree=Invoke-FixtureGit $planning @('rev-parse',"$prepared^{tree}")
  foreach($repo in @($src,$planning)){Invoke-FixtureGit $repo @('remote','add','origin',$repo)};Invoke-FixtureGit $src @('update-ref','refs/remotes/origin/main',$srcFinal);Invoke-FixtureGit $planning @('update-ref','refs/remotes/origin/main',$suffix);foreach($repo in @($src,$planning)){Invoke-FixtureGit $repo @('branch','--set-upstream-to','origin/main','main')}
  $doc=[ordered]@{schema='rusty.morphospace.workflow.published_prerequisite_suffix_reconciliation.v2';reconciliation_id='published-prerequisite-reconciliation';project_id='test-project';bundle_id=$plan.bundle_id;trigger_unit_id='trigger-unit';planned_publication_accounting=[ordered]@{path='receipts/accounting.json';sha256=Hash $accountPath};planning_repository=[ordered]@{repo_id='planning-repo';branch='main';upstream='origin/main';execution_final_revision=$prepared;execution_final_tree=$preparedTree;published_suffix_commits=@($suffixFirst,$suffix);published_suffix_revision=$suffix;published_suffix_tree=$suffixTree;published_suffix_parent=$prepared;current_remote_readback_revision=$suffix;executed_push_receipt=[ordered]@{path=$executedRel;sha256=Hash $executedPath};publication_accounting_receipt=[ordered]@{path=$accountRel;sha256=Hash $accountPath};worktree_clean=$true};source_repositories=@([ordered]@{repo_id='source-repo';branch='main';upstream='origin/main';execution_final_revision=$srcFinal;execution_final_tree=$srcTree;current_remote_readback_revision=$srcFinal;history_unchanged=$true;worktree_clean=$true});publication=[ordered]@{scope='planning-published-prerequisite-suffix';commit_count=2;changed_paths=@($accountRel,$executedRel);fast_forward_verified=$true;force_push_used=$false;force_with_lease_used=$false;rewrite_used=$false;observed_at='2026-07-20T10:04:00Z'};workspace_transition=[ordered]@{pending_push_bundle_before=$plan.bundle_id;pending_push_bundle_after=$null;validation_unchanged=$true;acceptance_unchanged=$true};failure=$null};$docPath=Join-Path $ws 'receipts\reconciliation.json';Write-Json $docPath $doc;Add-Content -LiteralPath (Join-Path $planning '.git\info\exclude') -Value "`nproject/morphospace/receipts/reconciliation.json`nproject/morphospace/receipts/bad-*.json`nproject/morphospace/receipts/plan.json`nproject/morphospace/prepared-event.json`nproject/morphospace/unit-status.json"
  $spec=[pscustomobject]@{project_id='test-project'};$state=[pscustomobject]@{current_unit=$null;pending_push_bundle=[pscustomobject]@{bundle_id=$plan.bundle_id;unit_ids=@('trigger-unit');repo_ids=@('source-repo','planning-repo')}};$map=@{'source-repo'=[pscustomobject]@{path=$src};'planning-repo'=[pscustomobject]@{path=$planning}};$sourceState=[pscustomobject]@{repo_id='source-repo';dirty=$false;diverged=$false;ahead=0;behind=0;head=$srcFinal;branch='main';upstream='origin/main'};$planningState=[pscustomobject]@{repo_id='planning-repo';dirty=$false;diverged=$false;ahead=0;behind=0;head=$suffix;branch='main';upstream='origin/main'}
  Test-MorphospacePublishedPrerequisiteSuffixLive $docPath $ws $spec $state $map @($sourceState,$planningState)|Out-Null
  $cases=@('extra-path','wrong-count','duplicate-commit','abbreviated-commit','reversed-commits','bad-accounting-hash','bad-executed-hash','dirty','ahead','behind','diverged','nonancestor','alternate-history','source-drift','force','rewrite','wrong-unit','wrong-bundle','missing-receipt','missing-object','repeated-consumption')
  foreach($case in $cases){$bad=Clone $doc;$badState=Clone $state;$badSource=Clone $sourceState;$badPlanning=Clone $planningState;switch($case){'extra-path'{$bad.publication.changed_paths[0]='extra.json'}'wrong-count'{$bad.publication.commit_count=1}'duplicate-commit'{$bad.planning_repository.published_suffix_commits[1]=$bad.planning_repository.published_suffix_commits[0]}'abbreviated-commit'{$bad.planning_repository.published_suffix_commits[0]=$bad.planning_repository.published_suffix_commits[0].Substring(0,7)}'reversed-commits'{$x=$bad.planning_repository.published_suffix_commits[0];$bad.planning_repository.published_suffix_commits[0]=$bad.planning_repository.published_suffix_commits[1];$bad.planning_repository.published_suffix_commits[1]=$x}'bad-accounting-hash'{$bad.planned_publication_accounting.sha256=('0'*64)}'bad-executed-hash'{$bad.planning_repository.executed_push_receipt.sha256=('0'*64)}'dirty'{$badPlanning.dirty=$true}'ahead'{$badPlanning.ahead=1}'behind'{$badPlanning.behind=1}'diverged'{$badPlanning.diverged=$true}'nonancestor'{$bad.planning_repository.published_suffix_parent=$srcOld}'alternate-history'{$bad.planning_repository.execution_final_revision=$srcOld;$bad.planning_repository.published_suffix_parent=$srcOld}'source-drift'{$bad.source_repositories[0].current_remote_readback_revision=$srcOld}'force'{$bad.publication.force_push_used=$true}'rewrite'{$bad.publication.rewrite_used=$true}'wrong-unit'{$bad.trigger_unit_id='wrong-unit'}'wrong-bundle'{$bad.bundle_id='wrong-bundle'}'missing-receipt'{$bad.planned_publication_accounting.path='receipts/missing.json'}'missing-object'{$bad.planning_repository.published_suffix_revision=('f'*40);$bad.planning_repository.current_remote_readback_revision=('f'*40)}'repeated-consumption'{$badState.pending_push_bundle=$null}};$badPath=Join-Path $ws "receipts\bad-$case.json";Write-Json $badPath $bad;Reject {Test-MorphospacePublishedPrerequisiteSuffixLive $badPath $ws $spec $badState $map @($badSource,$badPlanning)} $case}
  $repoMapPath=Join-Path $root 'repository-map.json';Write-Json $repoMapPath ([ordered]@{schema='rusty.morphospace.workflow.repository_map.v1';repositories=@([ordered]@{repo_id='source-repo';role='source';path=$src},[ordered]@{repo_id='planning-repo';role='planning';path=$planning})})
  $planningPorcelain=@(& git -C $planning status --porcelain=v1);if($planningPorcelain.Count){throw "Fixture planning repository is unexpectedly dirty: $($planningPorcelain-join'; ')"}
  $beforeUnitHash=Hash (Join-Path $ws 'iteration-units\trigger-unit.json');$beforeValidation=(Get-Content -Raw (Join-Path $ws 'workspace.state.json')|ConvertFrom-Json).validation_checkpoint|ConvertTo-Json -Compress
  $runner=Join-Path $root 'fresh-process-runner.ps1';$transitionPath=Join-Path $root 'transition.json';[IO.File]::WriteAllText($runner,@'
param($Module,$Workspace,$RepositoryMap,$Output,$Timestamp)
$ErrorActionPreference='Stop'
Import-Module $Module -Force
$result=Invoke-MorphospaceWorkUnitAutomation -Action ReconcilePublishedPrerequisiteSuffix -WorkspaceRoot $Workspace -UnitId 'trigger-unit' -RepoMapPath $RepositoryMap -PublishedPrerequisiteSuffixReconciliation 'receipts/reconciliation.json' -Timestamp $Timestamp -Execute
[IO.File]::WriteAllText($Output,($result|ConvertTo-Json -Depth 16)+"`n",[Text.UTF8Encoding]::new($false))
'@,[Text.UTF8Encoding]::new($false));$automationModule=Join-Path $PSScriptRoot 'WorkUnitAutomation.psm1'
  $pwshPath=(Get-Process -Id $PID).Path;& $pwshPath -NoProfile -ExecutionPolicy Bypass -File $runner -Module $automationModule -Workspace $ws -RepositoryMap $repoMapPath -Output $transitionPath -Timestamp '2026-07-20T10:05:00Z';if($LASTEXITCODE-ne0){throw "Fresh-process reconciliation failed with exit $LASTEXITCODE."};$transition=Get-Content -Raw $transitionPath|ConvertFrom-Json
  $afterState=Get-Content -Raw (Join-Path $ws 'workspace.state.json')|ConvertFrom-Json;$afterUnit=Get-Content -Raw (Join-Path $ws 'iteration-units\trigger-unit.json')|ConvertFrom-Json;$lastEvent=Get-Content (Join-Path $ws 'iteration-events.jsonl')|Select-Object -Last 1|ConvertFrom-Json
  if($transition.transition-ne'published-prerequisite-suffix-reconciled'-or$null-ne$afterState.pending_push_bundle-or$afterUnit.status-ne'accepted'-or(Hash (Join-Path $ws 'iteration-units\trigger-unit.json'))-ne$beforeUnitHash-or($afterState.validation_checkpoint|ConvertTo-Json -Compress)-cne$beforeValidation-or$lastEvent.event_id-notlike '*published-prerequisite-suffix-reconciled*'){throw 'Automation-level reconciliation did not preserve acceptance/validation, clear only the bundle, and append the distinct event.'}
  & $pwshPath -NoProfile -ExecutionPolicy Bypass -File $runner -Module $automationModule -Workspace $ws -RepositoryMap $repoMapPath -Output $transitionPath -Timestamp '2026-07-20T10:06:00Z' 2>$null;if($LASTEXITCODE-eq0){throw "Damaged published-prerequisite case 'automation-repeated-consumption' was accepted."}
  "Published-prerequisite suffix reconciliation self-test passed (1 positive, $($cases.Count) damaged cases)."
 }finally{if(Test-Path $root){Remove-Item -Recurse -Force $root}}
 exit 0
}
if(-not$Path-or-not$WorkspaceRoot){throw 'Path and WorkspaceRoot are required unless -SelfTest is used.'}
Test-MorphospacePublishedPrerequisiteSuffixDocument -Path $Path -WorkspaceRoot $WorkspaceRoot|ConvertTo-Json -Depth 16
