param()

$ErrorActionPreference='Stop'
$RepoRoot=Split-Path -Parent $PSScriptRoot
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceOwnership.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceProtocolCommon.psm1') -Force
Import-Module (Join-Path $PSScriptRoot 'lib\MorphospaceContentObservation.psm1') -Force
$script:OwnershipModule=Get-Module MorphospaceOwnership

function Assert-Owner {param([bool]$Condition,[string]$Message)if(-not$Condition){throw "Ownership authority self-test failed: $Message"}}
function Assert-Rejected {param([scriptblock]$Action,[string]$Message)$rejected=$false;try{&$Action}catch{$rejected=$true};Assert-Owner $rejected $Message}
function Write-Utf8 {param([string]$Path,[string]$Text)[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
function Invoke-Git {param([string]$Git,[string]$Root,[string[]]$Arguments)$output=&$Git -C $Root @Arguments 2>&1;if($LASTEXITCODE-ne0){throw "Fixture Git failed: $($Arguments-join' ') $output"};return $output}
function Get-EntryDocuments {
    param([object]$Observation,[switch]$Baseline)
    $rows=&$script:OwnershipModule {param($value,$isBaseline)$list=[Collections.Generic.List[object]]::new();foreach($entry in @($value.entries)){$normalized=New-MorphospaceObservedEntry $value $entry;$core=$normalized.core;if($isBaseline){$list.Add([pscustomobject][ordered]@{path=[string]$core.path;entry_fingerprint_sha256=[string]$normalized.fingerprint_sha256;state=[string]$core.state;sha256=$core.sha256;length=$core.length;mode=$core.mode;patch_sha256=$core.patch_sha256;hunks=@($core.hunks)})}else{$list.Add($normalized)}};$array=@($list.ToArray());[Array]::Sort($array,[Comparison[object]]{param($left,$right)$leftPath=if($isBaseline){[string]$left.path}else{[string]$left.core.path};$rightPath=if($isBaseline){[string]$right.path}else{[string]$right.core.path};[StringComparer]::Ordinal.Compare($leftPath,$rightPath)});return $array} $Observation $Baseline
    return @($rows)
}
function Get-ValueFingerprint {param([object]$Value)return Get-MorphospaceCanonicalJsonSha256 ([pscustomobject]@{value=$Value})}
function New-BaselineRow {
    param([object]$Observation,[object[]]$Instructions=@())
    $entries=@(Get-EntryDocuments $Observation -Baseline);$instructionFingerprint=Get-MorphospaceCanonicalJsonSha256 ([pscustomobject]@{entries=@($Instructions)})
    return [pscustomobject][ordered]@{repo_id=[string]$Observation.repo_id;kind=[string]$Observation.kind;head_revision=if([string]$Observation.kind-ceq'git'){[string]$Observation.head_revision}else{$null};head_tree_oid=if([string]$Observation.kind-ceq'git'){[string]$Observation.head_tree}else{$null};branch=if([string]$Observation.kind-ceq'git'){[string]$Observation.branch}else{$null};allowed_paths=if([string]$Observation.kind-ceq'git'){@('src')}else{@('inputs')};content_observation_sha256=(Get-MorphospaceCanonicalJsonSha256 $Observation);status_sha256=if([string]$Observation.kind-ceq'git'){[string]$Observation.status_sha256}else{$null};overlay_fingerprint_sha256=if([string]$Observation.kind-ceq'git'){[string]$Observation.overlay_fingerprint_sha256}else{[string]$Observation.tree_fingerprint_sha256};commit_manifest_fingerprint_sha256=if([string]$Observation.kind-ceq'git'){[string]$Observation.commit_fingerprint_sha256}else{$null};instruction_observation_sha256=$instructionFingerprint;entries_fingerprint_sha256=(Get-ValueFingerprint $entries);entries=$entries;instructions_fingerprint_sha256=$instructionFingerprint;instructions=@($Instructions)}
}
function New-OwnershipRow {
    param([object]$BaselineRow,[object]$Observation)
    $baselineMap=@{};foreach($entry in @($BaselineRow.entries)){$baselineMap[[string]$entry.path]=$entry};$preserved=[Collections.Generic.List[string]]::new();$entries=[Collections.Generic.List[object]]::new()
    foreach($normalized in @(Get-EntryDocuments $Observation)){$core=$normalized.core;$path=[string]$core.path;$baseline=$null;if($baselineMap.ContainsKey($path)){$baseline=$baselineMap[$path]};if($null-ne$baseline-and[string]$baseline.entry_fingerprint_sha256-ceq[string]$normalized.fingerprint_sha256){$preserved.Add([string]$baseline.entry_fingerprint_sha256);continue};$entries.Add([pscustomobject][ordered]@{path=$path;final_entry_fingerprint_sha256=[string]$normalized.fingerprint_sha256;baseline_entry_fingerprint_sha256=if($null-eq$baseline){$null}else{[string]$baseline.entry_fingerprint_sha256};state=[string]$core.state;sha256=$core.sha256;length=$core.length;mode=$core.mode;patch_sha256=$core.patch_sha256;hunks=@($core.hunks);attribution=if($null-eq$baseline){'unit'}else{'shared'}})}
    $entryArray=@($entries.ToArray());[Array]::Sort($entryArray,[Comparison[object]]{param($left,$right)[StringComparer]::Ordinal.Compare([string]$left.path,[string]$right.path)});$preservedArray=@($preserved.ToArray());[Array]::Sort($preservedArray,[StringComparer]::Ordinal);$instructionHash=Get-MorphospaceCanonicalJsonSha256 ([pscustomobject]@{entries=@()})
    return [pscustomobject][ordered]@{repo_id=[string]$Observation.repo_id;kind=[string]$Observation.kind;base_revision=if([string]$Observation.kind-ceq'git'){[string]$BaselineRow.head_revision}else{$null};head_revision=if([string]$Observation.kind-ceq'git'){[string]$Observation.head_revision}else{$null};head_tree_oid=if([string]$Observation.kind-ceq'git'){[string]$Observation.head_tree}else{$null};branch=if([string]$Observation.kind-ceq'git'){[string]$Observation.branch}else{$null};allowed_paths=@($BaselineRow.allowed_paths);live_content_observation_sha256=(Get-MorphospaceCanonicalJsonSha256 $Observation);live_status_sha256=if([string]$Observation.kind-ceq'git'){[string]$Observation.status_sha256}else{$null};live_overlay_fingerprint_sha256=if([string]$Observation.kind-ceq'git'){[string]$Observation.overlay_fingerprint_sha256}else{[string]$Observation.tree_fingerprint_sha256};live_commit_manifest_fingerprint_sha256=if([string]$Observation.kind-ceq'git'){[string]$Observation.commit_fingerprint_sha256}else{$null};baseline_entries_sha256=[string]$BaselineRow.entries_fingerprint_sha256;preserved_baseline_entries_sha256=(Get-ValueFingerprint $preservedArray);preserved_baseline_count=$preservedArray.Count;instruction_observation_sha256=$instructionHash;entries=$entryArray}
}
function Copy-JsonObject {param([object]$Value)$text=$Value|ConvertTo-Json -Depth 100 -Compress;return $text|ConvertFrom-Json}
function ConvertTo-ProcessArgument {param([string]$Value)if($Value-notmatch'[\s"]'){return $Value};return '"'+$Value.Replace('"','\"')+'"'}
function Get-TestHost { $property=[Environment].GetProperty('ProcessPath');if($null-ne$property){$candidate=[string]$property.GetValue($null,$null);if($candidate){return $candidate}};return [Diagnostics.Process]::GetCurrentProcess().MainModule.FileName }
function Start-TestProcess {param([string[]]$Arguments)$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=Get-TestHost;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;if($psi.PSObject.Properties.Name-contains'ArgumentList'){foreach($argument in $Arguments){[void]$psi.ArgumentList.Add($argument)}}else{$parts=[Collections.Generic.List[string]]::new();foreach($argument in $Arguments){$parts.Add((ConvertTo-ProcessArgument $argument))};$psi.Arguments=$parts.ToArray()-join' '};return [Diagnostics.Process]::Start($psi)}

$tempRoot=[IO.Path]::GetFullPath([IO.Path]::GetTempPath());$root=Join-Path $tempRoot ('morphospace-ownership-test-'+[guid]::NewGuid().ToString('N'));$junction=$null;$cleanRoom=$null
try{
    [IO.Directory]::CreateDirectory($root)|Out-Null;$git=(Get-MorphospaceBoundExecutable git).path;$repo=Join-Path $root 'git-owner';$nonGit=Join-Path $root 'non-git-owner';[IO.Directory]::CreateDirectory((Join-Path $repo 'src'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $nonGit 'inputs'))|Out-Null
    $directoryScope=&$script:OwnershipModule {ConvertTo-MorphospaceSortedCanonicalPaths @('src/','inputs\')};Assert-Owner ((@($directoryScope)-join'|')-ceq'inputs|src') 'trailing directory separators did not normalize before scope validation'
    Write-Utf8 (Join-Path $repo '.gitattributes') "*.flt filter=ownership-trap`n";foreach($name in @('preexisting.txt','predelete.txt','unit.txt','unit-delete.txt','contamination.txt','copy.bin','trap.flt')){Write-Utf8 (Join-Path $repo "src\$name") "base-$name`n"};$batchFixture=Join-Path $repo 'src\batch';[IO.Directory]::CreateDirectory($batchFixture)|Out-Null;for($batchIndex=0;$batchIndex-lt256;$batchIndex++){Write-Utf8 (Join-Path $batchFixture ('entry-{0:D4}.txt'-f$batchIndex)) ("batch-$batchIndex`n")};Invoke-Git $git $repo @('init')|Out-Null;Invoke-Git $git $repo @('config','user.name','Ownership Test')|Out-Null;Invoke-Git $git $repo @('config','user.email','ownership@example.invalid')|Out-Null;Invoke-Git $git $repo @('config','core.autocrlf','false')|Out-Null;Invoke-Git $git $repo @('add','--','.gitattributes','src')|Out-Null;Invoke-Git $git $repo @('commit','-m','claim head')|Out-Null;$head=(Invoke-Git $git $repo @('rev-parse','HEAD')).Trim()
    $marker=Join-Path $root 'filter-marker.txt';$driver=Join-Path $root 'filter-driver.ps1';Write-Utf8 $driver "[IO.File]::WriteAllText('$($marker.Replace("'","''"))','executed')`nexit 1`n";$hostExe=Get-TestHost;$driverCommand='"'+$hostExe+'" -NoProfile -NonInteractive -File "'+$driver+'"';foreach($key in @('clean','process','smudge')){Invoke-Git $git $repo @('config',"filter.ownership-trap.$key",$driverCommand)|Out-Null};Invoke-Git $git $repo @('config','filter.ownership-trap.required','true')|Out-Null
    Write-Utf8 (Join-Path $repo 'src\preexisting.txt') "user-wip`n";[IO.File]::Delete((Join-Path $repo 'src\predelete.txt'));Write-Utf8 (Join-Path $repo 'src\pre-untracked.txt') "user-untracked`n";Write-Utf8 (Join-Path $repo 'src\trap.flt') "user-filter-wip`n";Write-Utf8 (Join-Path $nonGit 'inputs\baseline.json') '{"baseline":true}'
    $baselineGit=Get-MorphospaceGitRepositoryObservation git-owner $repo $head @('src') $git;$baselineNonGit=Get-MorphospaceNonGitTreeObservation non-git-owner $nonGit @('inputs');Assert-Owner (-not[IO.File]::Exists($marker)) 'Git clean/process/smudge filter executed during baseline observation'
    $mapReference=[pscustomobject][ordered]@{role='repository-map';path='repository-map.json';schema='rusty.morphospace.workflow.repository_map.v1';sha256=('1'*64)};$claimReference=[pscustomobject][ordered]@{role='claim-baseline';path='receipts/unit-test-claim-baseline.json';schema='rusty.morphospace.workflow.claim_baseline.v1';sha256=('2'*64)};$map=@{'git-owner'=[pscustomobject]@{path=$repo;aliases=@()};'non-git-owner'=[pscustomobject]@{path=$nonGit;aliases=@()}}
    $unit=[pscustomobject]@{project_id='test-project';unit_id='unit-test';allowed_repositories=@([pscustomobject]@{repo_id='git-owner';allowed_paths=@('src')},[pscustomobject]@{repo_id='non-git-owner';allowed_paths=@('inputs')});instruction_impact='none';instruction_surfaces=@()}
    $baselineGitRow=New-BaselineRow $baselineGit;$baselineNonGitRow=New-BaselineRow $baselineNonGit;$claim=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.claim_baseline.v1';baseline_id='unit-test-baseline';created_at='2026-07-11T19:30:00.0000000Z';project_id='test-project';unit_id='unit-test';repository_map=$mapReference;repositories=@($baselineGitRow,$baselineNonGitRow);status='frozen'}
    Write-Utf8 (Join-Path $repo 'src\unit.txt') "unit-change`n";[IO.File]::Delete((Join-Path $repo 'src\unit-delete.txt'));Write-Utf8 (Join-Path $repo 'src\new.txt') "unit-new`n";$copyBytes=[byte[]]::new(8388608);for($i=0;$i-lt$copyBytes.Length;$i+=4096){$copyBytes[$i]=[byte]($i%251)};[IO.File]::WriteAllBytes((Join-Path $repo 'src\copy.bin'),$copyBytes);Write-Utf8 (Join-Path $nonGit 'inputs\unit.json') '{"unit":true}'
    $currentGit=Get-MorphospaceGitRepositoryObservation git-owner $repo $head @('src') $git;$currentNonGit=Get-MorphospaceNonGitTreeObservation non-git-owner $nonGit @('inputs');$ownershipGitRow=New-OwnershipRow $baselineGitRow $currentGit;$ownershipNonGitRow=New-OwnershipRow $baselineNonGitRow $currentNonGit
    $ownership=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.unit_ownership.v1';ownership_id='unit-test-ownership';created_at='2026-07-11T19:31:00.0000000Z';project_id='test-project';unit_id='unit-test';claim_baseline=$claimReference;repositories=@($ownershipGitRow,$ownershipNonGitRow);shared_overlaps=@();status='assigned'}
    [void](Test-MorphospaceUnitOwnership $ownership $claim $claimReference $unit $mapReference $map);Assert-Owner (-not[IO.File]::Exists($marker)) 'Git filter executed during ownership validation';Assert-Owner (@($ownershipGitRow.entries|Where-Object{[string]$_.path-ceq'src/preexisting.txt'}).Count-eq0) 'preserved baseline dirty file was claimed by the unit'
    $automationOwnership=[pscustomobject][ordered]@{schema=$ownership.schema;ownership_id=$ownership.ownership_id;created_at=$ownership.created_at;project_id=$ownership.project_id;unit_id=$ownership.unit_id;claim_baseline=$ownership.claim_baseline;repositories=@($ownership.repositories);shared_overlaps=@($ownership.shared_overlaps);automation_outputs=@();status=$ownership.status}
    $automationOutput=[pscustomobject][ordered]@{repo_id='git-owner';path='src/automation-evidence.json';phase='validation';role='validation-evidence';schema='rusty.morphospace.workflow.validation_evidence.v2';validator_id=$null}
    $automationNonGitOutput=[pscustomobject][ordered]@{repo_id='non-git-owner';path='inputs/automation-owner.json';phase='validation';role='owner-validation';schema='rusty.morphospace.workflow.owner_validation.v1';validator_id='non-git-owner-validator'}
    $automationOwnership.automation_outputs=@($automationOutput,$automationNonGitOutput)
    $automationComparable=ConvertTo-MorphospaceComparableRepositoryObservation $currentGit @($automationOutput)
    $automationNonGitComparable=ConvertTo-MorphospaceComparableRepositoryObservation $currentNonGit @($automationNonGitOutput)
    $automationOwnership.repositories[0]=New-OwnershipRow $baselineGitRow $automationComparable
    $automationOwnership.repositories[1]=New-OwnershipRow $baselineNonGitRow $automationNonGitComparable
    $automationContract=@(Get-MorphospaceAutomationOutputContract $automationOwnership $unit @{'git-owner'=$unit.allowed_repositories[0];'non-git-owner'=$unit.allowed_repositories[1]})
    $transitionOwnership=Copy-JsonObject $automationOwnership
    $transitionOwnership.automation_outputs=@([pscustomobject][ordered]@{repo_id='git-owner';path='src/transition-intent.json';phase='transition';role='transition-ledger-intent';schema='rusty.morphospace.workflow.transition_ledger_intent.v3';validator_id=$null})
    $transitionContract=@(Get-MorphospaceAutomationOutputContract $transitionOwnership $unit @{'git-owner'=$unit.allowed_repositories[0];'non-git-owner'=$unit.allowed_repositories[1]})
    Assert-Owner ($transitionContract.Count-eq1-and[string]$transitionContract[0].schema-ceq'rusty.morphospace.workflow.transition_ledger_intent.v3') 'transition-ledger intent v3 was not admitted as a typed automation output'
    $projectedRawTransition=Copy-JsonObject $transitionOwnership;$projectedRawTransition.automation_outputs[0].schema='rusty.morphospace.workflow.transition_ledger_intent.v4';$projectedRawContract=@(Get-MorphospaceAutomationOutputContract $projectedRawTransition $unit @{'git-owner'=$unit.allowed_repositories[0];'non-git-owner'=$unit.allowed_repositories[1]});Assert-Owner ($projectedRawContract.Count-eq1-and[string]$projectedRawContract[0].schema-ceq'rusty.morphospace.workflow.transition_ledger_intent.v4') 'transition-ledger intent v4 was not admitted as a typed automation output'
    $unsupportedTransition=Copy-JsonObject $projectedRawTransition;$unsupportedTransition.automation_outputs[0].schema='rusty.morphospace.workflow.transition_ledger_intent.v5';Assert-Rejected {Get-MorphospaceAutomationOutputContract $unsupportedTransition $unit @{'git-owner'=$unit.allowed_repositories[0];'non-git-owner'=$unit.allowed_repositories[1]}|Out-Null} 'unsupported transition-ledger intent schema was accepted'
    Test-MorphospaceAutomationOutputSet $automationContract $map 'absent';[void](Test-MorphospaceUnitOwnership $automationOwnership $claim $claimReference $unit $mapReference $map)
    Write-Utf8 (Join-Path $repo 'src\automation-evidence.json') '{"evidence":true}';Write-Utf8 (Join-Path $nonGit 'inputs\automation-owner.json') '{"owner":true}'
    Test-MorphospaceAutomationOutputSet $automationContract $map 'present';[void](Test-MorphospaceUnitOwnership $automationOwnership $claim $claimReference $unit $mapReference $map)
    Write-Utf8 (Join-Path $repo 'src\automation-shadow.json') '{"shadow":true}';Assert-Rejected {Test-MorphospaceUnitOwnership $automationOwnership $claim $claimReference $unit $mapReference $map|Out-Null} 'undeclared adjacent automation output was accepted'
    [IO.File]::Delete((Join-Path $repo 'src\automation-shadow.json'));[IO.File]::Delete((Join-Path $repo 'src\automation-evidence.json'));[IO.File]::Delete((Join-Path $nonGit 'inputs\automation-owner.json'))
    $badBase=Copy-JsonObject $ownership;$badBase.repositories[0].base_revision=('0'*40);Assert-Rejected {Test-MorphospaceUnitOwnership $badBase $claim $claimReference $unit $mapReference $map|Out-Null} 'cumulative/pre-claim base reuse was accepted'
    $badBaselineOrder=Copy-JsonObject $claim;[Array]::Reverse($badBaselineOrder.repositories[0].entries);Assert-Rejected {Test-MorphospaceClaimBaseline $badBaselineOrder $unit $mapReference $map|Out-Null} 'non-canonical baseline entry order was accepted'
    $orphan=Copy-JsonObject $ownership;$unitEntry=@($orphan.repositories[0].entries|Where-Object{[string]$_.path-ceq'src/unit.txt'})[0];$orphan.shared_overlaps=@([pscustomobject]@{integration_id='integration-orphan';repo_id='git-owner';bindings=@([pscustomobject]@{path='src/unit.txt';baseline_entry_fingerprint_sha256=('3'*64);final_entry_fingerprint_sha256=[string]$unitEntry.final_entry_fingerprint_sha256;patch_sha256=[string]$unitEntry.patch_sha256;hunks=@($unitEntry.hunks)});contributing_units=@('unit-test','other-unit');integration_owner='integration-owner';decision='accepted'});Assert-Rejected {Test-MorphospaceUnitOwnership $orphan $claim $claimReference $unit $mapReference $map|Out-Null} 'orphan shared binding was accepted'
    Write-Utf8 (Join-Path $repo 'src\preexisting.txt') "unit-over-user-wip`n";$overlapGit=Get-MorphospaceGitRepositoryObservation git-owner $repo $head @('src') $git;$overlapOwnership=Copy-JsonObject $ownership;$overlapOwnership.repositories[0]=New-OwnershipRow $baselineGitRow $overlapGit
    Assert-Rejected {Test-MorphospaceUnitOwnership $overlapOwnership $claim $claimReference $unit $mapReference $map|Out-Null} 'same-path baseline WIP was accepted as unit ownership without shared binding';Write-Utf8 (Join-Path $repo 'src\preexisting.txt') "user-wip`n"
    $closure=@([pscustomobject]@{repo_id='git-owner';kind='git-tree';paths=@('src/unit.txt','src/new.txt')},[pscustomobject]@{repo_id='non-git-owner';kind='non-git-tree';paths=@('inputs/baseline.json','inputs/unit.json')});$cleanRoom=New-MorphospaceCleanRoom $ownership $claim $map $closure 'unit-test-cleanroom1' $git;Assert-Owner ([IO.File]::Exists((Join-Path $cleanRoom.repositories['git-owner'] 'src\unit.txt'))) 'owned Git file missing from clean room';Assert-Owner (-not[IO.File]::Exists((Join-Path $cleanRoom.repositories['git-owner'] 'src\preexisting.txt'))-and-not[IO.File]::Exists((Join-Path $cleanRoom.repositories['git-owner'] 'src\contamination.txt'))) 'clean room included preserved/unclosed contamination';Assert-Owner ([IO.File]::Exists((Join-Path $cleanRoom.repositories['non-git-owner'] 'inputs\unit.json'))) 'owned non-Git input missing from clean room';Assert-Owner ((Get-MorphospaceFileSha256 (Join-Path $cleanRoom.repositories['non-git-owner'] 'inputs\baseline.json'))-ceq[string]$baselineNonGitRow.entries[1].sha256-or[IO.File]::Exists((Join-Path $cleanRoom.repositories['non-git-owner'] 'inputs\baseline.json'))) 'unchanged baseline non-Git input was not deliberately materialized';$cleanFingerprint=Get-MorphospaceCleanRoomFingerprint $cleanRoom;Assert-Owner ($cleanFingerprint-ceq[string]$cleanRoom.fingerprint_sha256) 'clean-room initial fingerprint drifted'
    $batchRoom=$null;$batchWatch=[Diagnostics.Stopwatch]::StartNew();try{$batchClosure=@([pscustomobject]@{repo_id='git-owner';kind='git-tree';paths=@('src/batch/')});$batchRoom=New-MorphospaceCleanRoom $ownership $claim $map $batchClosure 'unit-test-batch-cleanroom' $git;$batchWatch.Stop();Assert-Owner (@(Get-ChildItem -LiteralPath (Join-Path $batchRoom.repositories['git-owner'] 'src\batch') -File).Count-eq256) 'batched clean room omitted committed files';Assert-Owner ($batchWatch.Elapsed.TotalSeconds-lt30) "batched clean-room materialization exceeded 30 seconds: $($batchWatch.Elapsed.TotalSeconds)"}finally{if($null-ne$batchRoom){Remove-MorphospaceCleanRoom $batchRoom}}
    $baselineClosure=@([pscustomobject]@{repo_id='git-owner';kind='git-tree';paths=@('src/preexisting.txt')});$baselineRoom=New-MorphospaceCleanRoom $ownership $claim $map $baselineClosure 'unit-test-baseline-cleanroom' $git;try{Assert-Owner (([IO.File]::ReadAllText((Join-Path $baselineRoom.repositories['git-owner'] 'src\preexisting.txt')))-ceq"user-wip`n") 'clean room did not materialize a preserved dirty Git baseline input'}finally{Remove-MorphospaceCleanRoom $baselineRoom}
    $historyObject=(Invoke-Git $git $repo @('rev-parse',"$head`:src/unit.txt")).Trim();$historyBytes=[Text.UTF8Encoding]::new($false).GetBytes("base-unit.txt`n");$historySha=([BitConverter]::ToString([Security.Cryptography.SHA256]::Create().ComputeHash($historyBytes))).Replace('-','').ToLowerInvariant();$historyBlobs=@([pscustomobject]@{repo_id='git-owner';object_id=$historyObject;sha256=$historySha});$historyRoom=$null;try{$historyRoom=New-MorphospaceCleanRoom $ownership $claim $map $closure 'unit-test-history-cleanroom' $git $historyBlobs;$historyProbe=&$git -C $historyRoom.repositories['git-owner'] cat-file -e "$historyObject^{blob}" 2>&1;Assert-Owner ($LASTEXITCODE-eq0) "sealed clean-room history object was unavailable: $historyProbe";Assert-Owner ((Get-MorphospaceCleanRoomFingerprint $historyRoom)-ceq[string]$historyRoom.fingerprint_sha256) 'clean-room history object changed the sealed fingerprint'}finally{if($null-ne$historyRoom){Remove-MorphospaceCleanRoom $historyRoom}};$badHistory=@([pscustomobject]@{repo_id='git-owner';object_id=$historyObject;sha256=('0'*64)});Assert-Rejected {New-MorphospaceCleanRoom $ownership $claim $map $closure 'unit-test-history-damage' $git $badHistory|Out-Null} 'clean room accepted a forged historical blob hash'
    $outside=Join-Path $root 'outside-sentinel';[IO.Directory]::CreateDirectory($outside)|Out-Null;$sentinel=Join-Path $outside 'keep.txt';Write-Utf8 $sentinel 'keep';$junction=Join-Path $cleanRoom.root 'outside-link';[void](Microsoft.PowerShell.Management\New-Item -ItemType Junction -Path $junction -Target $outside);Remove-MorphospaceCleanRoom $cleanRoom;$cleanRoom=$null;$junction=$null;Assert-Owner ([IO.File]::Exists($sentinel)) 'no-follow cleanup traversed an outside junction'
    $forgedParent=Join-Path $tempRoot 'rusty-morphospace-cleanrooms';$sibling=Join-Path ($tempRoot+'-sibling') 'unit-test-cleanroom-forged';[IO.Directory]::CreateDirectory($sibling)|Out-Null;$siblingSentinel=Join-Path $sibling 'keep.txt';Write-Utf8 $siblingSentinel 'keep';Assert-Rejected {Remove-MorphospaceCleanRoom ([pscustomobject]@{root=$sibling;parent=$forgedParent;guard='forged'})} 'forged sibling-temp cleanup authority was accepted';Assert-Owner ([IO.File]::Exists($siblingSentinel)) 'forged cleanup changed sibling-temp content';[IO.Directory]::Delete((Split-Path -Parent $sibling),$true)
    $copyEntry=@($ownershipGitRow.entries|Where-Object{[string]$_.path-ceq'src/copy.bin'})[0];$raceWorker=Join-Path $root 'copy-race.ps1';$raceReady=Join-Path $root 'copy-race-ready';$raceStop=Join-Path $root 'copy-race-stop';Write-Utf8 $raceWorker "param(`$Path,`$Ready,`$Stop)`n[IO.File]::WriteAllText(`$Ready,'ready')`nwhile(-not[IO.File]::Exists(`$Stop)){try{`$s=[IO.FileStream]::new(`$Path,[IO.FileMode]::Open,[IO.FileAccess]::Write,[IO.FileShare]::ReadWrite);`$s.Position=0;`$s.WriteByte(255);`$s.Flush();`$s.Dispose()}catch{};[Threading.Thread]::Sleep(1)}`n";$race=Start-TestProcess @('-NoProfile','-NonInteractive','-File',$raceWorker,'-Path',(Join-Path $repo 'src\copy.bin'),'-Ready',$raceReady,'-Stop',$raceStop);$deadline=[DateTime]::UtcNow.AddSeconds(5);while(-not[IO.File]::Exists($raceReady)-and[DateTime]::UtcNow-lt$deadline){[Threading.Thread]::Sleep(10)};Assert-Owner ([IO.File]::Exists($raceReady)) 'copy race worker did not start';$raceTarget=Join-Path $root 'race-copy.bin';$raceRejected=$false;$lease=$null;try{$lease=&$script:OwnershipModule {param($source,$target,$entry)Copy-MorphospaceLeasedOverlay $source $target $entry} (Join-Path $repo 'src\copy.bin') $raceTarget $copyEntry}catch{$raceRejected=$true};if($null-ne$lease){try{Assert-Owner ((Get-MorphospaceFileSha256 $raceTarget)-ceq[string]$copyEntry.sha256) 'leased race copy returned unauthorized bytes'}finally{$lease.stream.Dispose()}};[IO.File]::WriteAllText($raceStop,'stop');$race.WaitForExit();$race.Dispose();Assert-Owner ($raceRejected-or[IO.File]::Exists($raceTarget)) 'copy race produced neither rejection nor exact leased copy'
    $shadow=Join-Path $root 'shadow.ps1';Write-Utf8 $shadow @'
param($Module)
function global:Where-Object {throw 'shadow'};function global:ForEach-Object {throw 'shadow'};function global:Sort-Object {throw 'shadow'};function global:Out-Null {throw 'shadow'};function global:Test-Path {throw 'shadow'};function global:Remove-Item {throw 'shadow'}
try{Import-Module $Module -Force;$m=Get-Module MorphospaceOwnership;$result=&$m {ConvertTo-MorphospaceSortedCanonicalPaths @('b','a')};if($result.Count-ne2-or$result[0]-cne'a'-or$result[1]-cne'b'){exit 7};exit 0}catch{exit 9}
'@;$shadowProcess=Start-TestProcess @('-NoProfile','-NonInteractive','-File',$shadow,'-Module',(Join-Path $PSScriptRoot 'lib\MorphospaceOwnership.psm1'));$shadowProcess.WaitForExit();$shadowCode=$shadowProcess.ExitCode;$shadowProcess.Dispose();Assert-Owner ($shadowCode-eq0) "caller command-shadow test failed with exit $shadowCode"
    Write-Host 'Ownership authority self-test passed.'
}finally{
    if($null-ne$cleanRoom){try{Remove-MorphospaceCleanRoom $cleanRoom}catch{}}
    if($null-ne$junction-and[IO.Directory]::Exists($junction)){[IO.Directory]::Delete($junction)}
    if([IO.Directory]::Exists($root)){foreach($file in [IO.Directory]::EnumerateFiles($root,'*',[IO.SearchOption]::AllDirectories)){try{[IO.File]::SetAttributes($file,[IO.FileAttributes]::Normal)}catch{}};[IO.Directory]::Delete($root,$true)}
}
