Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'lib/MorphospaceProtocolCommon.psm1')
Import-Module (Join-Path $PSScriptRoot 'lib/MorphospaceTransitionLedger.psm1')
Import-Module (Join-Path $PSScriptRoot 'ToolingContextProvenance.psm1')
Import-Module (Join-Path $PSScriptRoot 'DevelopmentEnvelopeProvenance.psm1')

function Copy-ToolingUpgradeValue { param([object]$Value) $Value|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String }
function Get-ToolingUpgradeSchema { param([string]$Name) Join-Path (Split-Path $PSScriptRoot -Parent) "schemas/$Name" }
function Test-ToolingUpgradeJson { param([object]$Document,[string]$Schema,[string]$Message) if(-not(Test-Json -Json ($Document|ConvertTo-Json -Depth 100 -Compress) -SchemaFile (Get-ToolingUpgradeSchema $Schema))){throw $Message} }
function Get-ToolingUpgradeEvents {
 param([string]$Path);$items=[Collections.Generic.List[object]]::new();foreach($line in @(Get-Content -LiteralPath $Path)){if(-not[string]::IsNullOrWhiteSpace($line)){$items.Add((ConvertFrom-MorphospaceProtocolJsonBytes ([Text.UTF8Encoding]::new($false).GetBytes([string]$line)) 'tooling upgrade event'))|Out-Null}};if($items.Count-eq0){throw 'Tooling-context upgrade requires a non-empty event ledger.'};@($items.ToArray())
}
function Get-ToolingUpgradeArtifactDocument {
 param([object]$Intent,[string]$Schema);$matches=@();foreach($artifact in @($Intent.artifacts)){try{$bytes=[Convert]::FromBase64String([string]$artifact.bytes_base64)}catch{throw 'Tooling-context upgrade intent contains invalid artifact base64.'};if((Get-MorphospaceSha256Bytes $bytes)-cne[string]$artifact.sha256){throw 'Tooling-context upgrade intent artifact hash is detached.'};$document=ConvertFrom-MorphospaceProtocolJsonBytes $bytes 'tooling-context upgrade intent artifact';if([string]$document.schema-ceq$Schema){$matches+=,[pscustomobject]@{binding=$artifact;bytes=$bytes;document=$document}}};if($matches.Count-ne1){throw "Tooling-context upgrade intent must contain exactly one '$Schema' artifact."};$matches[0]
}
function Assert-ToolingUpgradePointer {
 param([object]$Pointer,[object]$Context,[byte[]]$Bytes,[string]$Name)
 if([string]$Pointer.protocol_id-cne(Get-MorphospaceToolingContextProtocolId)-or[string]$Pointer.sha256-cne(Get-MorphospaceSha256Bytes $Bytes)-or[string]$Pointer.canonical_sha256-cne(Get-MorphospaceCanonicalJsonSha256 $Context)){throw "Tooling-context upgrade $Name pointer is detached."}
}
function Assert-ToolingUpgradeProductProjectionFiles {
 param([string]$Workspace,[object]$Projection)
 foreach($name in @('source_composition','repository_map','feature_lock')){$binding=$Projection.$name;$path=Resolve-MorphospaceWorkspacePath $Workspace ([string]$binding.path) -RequireLeaf;if((Get-MorphospaceFileSha256 $path)-cne[string]$binding.sha256){throw "Tooling-context upgrade current product $name bytes drifted."};[void](Read-MorphospaceProtocolJson $path)}
}
function Test-ToolingUpgradeProjectionEqual { param([object]$A,[object]$B) (Get-MorphospaceCanonicalJsonSha256 $A)-ceq(Get-MorphospaceCanonicalJsonSha256 $B) }
function Get-ToolingUpgradeFeatureBinding { param([object]$Document) [pscustomobject][ordered]@{path='feature.lock.json';sha256=Get-MorphospaceSha256Bytes (ConvertTo-MorphospaceProtocolJsonBytes $Document)} }
function Test-ToolingUpgradeOriginProjection {
 param([object]$Projection,[object]$Provenance)
 $candidates=@([pscustomobject][ordered]@{source_composition=[pscustomobject]@{path=[string]$Provenance.original.source_composition_binding.path;sha256=[string]$Provenance.original.source_composition_binding.raw_sha256};repository_map=[pscustomobject]@{path=[string]$Provenance.original.repository_map.path;sha256=[string]$Provenance.original.repository_map.raw_sha256};feature_lock=Get-ToolingUpgradeFeatureBinding $Provenance.original.preparation_intent.target.feature_lock.document})
 foreach($extension in @($Provenance.extensions)){$intent=$extension.intent;$sourceArtifact=$null;foreach($artifact in @($intent.artifacts)){$bytes=[Convert]::FromBase64String([string]$artifact.bytes_base64);$doc=ConvertFrom-MorphospaceProtocolJsonBytes $bytes;if([string]$doc.schema-ceq'rusty.morphospace.workflow.active_development_envelope_source_composition.v1'){$sourceArtifact=[pscustomobject]@{binding=$artifact;document=$doc}}};if($null-eq$sourceArtifact){continue};$lock=@($intent.additional_projections|Where-Object{[string]$_.path-ceq'feature.lock.json'});if($lock.Count-ne1){continue};$candidates+=,[pscustomobject][ordered]@{source_composition=[pscustomobject]@{path=[string]$sourceArtifact.binding.path;sha256=[string]$sourceArtifact.binding.sha256};repository_map=[pscustomobject]@{path=[string]$sourceArtifact.document.repository_map.path;sha256=[string]$sourceArtifact.document.repository_map.raw_sha256};feature_lock=Get-ToolingUpgradeFeatureBinding $lock[0].document}}
 @($candidates|Where-Object{Test-ToolingUpgradeProjectionEqual $_ $Projection}).Count-eq1
}
function Assert-ToolingUpgradeEffectiveEnvelope {
 param([string]$Workspace,[string]$UnitId,[object]$Request,[object]$OldContext,[object]$NewContext)
 $map=Resolve-MorphospaceWorkspacePath $Workspace ([string]$Request.product_projection.repository_map.path) -RequireLeaf
 $effective=Test-MorphospaceEffectiveDevelopmentEnvelope -WorkspaceRoot $Workspace -UnitId $UnitId -RepositoryMapPath $map
 $current=[pscustomobject][ordered]@{source_composition=[pscustomobject]@{path=[string]$effective.effective.source_composition_binding.path;sha256=[string]$effective.effective.source_composition_binding.raw_sha256};repository_map=[pscustomobject]@{path=[string]$effective.effective.repository_map.path;sha256=[string]$effective.effective.repository_map.raw_sha256};feature_lock=[pscustomobject]@{path='feature.lock.json';sha256=Get-MorphospaceFileSha256 (Resolve-MorphospaceWorkspacePath $Workspace 'feature.lock.json' -RequireLeaf)}}
 if(-not(Test-ToolingUpgradeProjectionEqual $Request.product_projection $current)-or-not(Test-ToolingUpgradeProjectionEqual $NewContext.product_projection $current)){throw 'Tooling-context upgrade new context does not bind the authenticated current effective envelope.'}
 if(-not(Test-ToolingUpgradeOriginProjection $OldContext.product_projection $effective)){throw 'Tooling-context upgrade old context is outside the authenticated envelope lineage.'}
 $effective
}
function Assert-ToolingUpgradeCompatibilityReceipt {
 param([string]$Workspace,[object]$Request,[object]$OldContext,[object]$NewContext)
 $path=Resolve-MorphospaceWorkspacePath $Workspace ([string]$Request.compatibility_receipt.path) -RequireLeaf;if((Get-MorphospaceFileSha256 $path)-cne[string]$Request.compatibility_receipt.sha256){throw 'Tooling-context compatibility receipt bytes drifted.'};$proof=Read-MorphospaceProtocolJson $path;Test-ToolingUpgradeJson $proof 'tooling-context-compatibility-receipt-v1.schema.json' 'Tooling-context compatibility receipt violates its owner schema.'
 foreach($pair in @(@('old_context',$OldContext),@('new_context',$NewContext))){$binding=$proof.($pair[0]);$context=$pair[1];if([string]$binding.context_id-cne[string]$context.context_id-or[string]$binding.fingerprint-cne[string]$context.fingerprint-or[string]$binding.commit-cne[string]$context.executor.commit-or[string]$binding.tree-cne[string]$context.executor.tree){throw "Tooling-context compatibility receipt $($pair[0]) binding is detached."}}
 if([string]$proof.project_id-cne[string]$Request.project_id-or[string]$proof.consumer.protocol_id-cne(Get-MorphospaceToolingContextProtocolId)-or-not(Test-ToolingUpgradeProjectionEqual $proof.consumer.product_projection $Request.product_projection)-or-not(Test-ToolingUpgradeProjectionEqual $proof.consumer.allowed_actions $NewContext.compatibility.allowed_actions)){throw 'Tooling-context compatibility receipt consumer binding is detached.'}
 Assert-MorphospaceToolingContextOwnerValidationEvidence -WorkspaceRoot $Workspace -Binding $proof.validation.evidence -Executor $NewContext.executor -Name 'compatibility'|Out-Null;$proof
}
function Assert-ToolingUpgradeExecutingBoundTool {
 param([string]$Workspace,[object]$Context)
 $resolver=Read-MorphospaceToolingContextResolver $Workspace $Context;$declared=[IO.Path]::GetFullPath([string]$resolver.executor_root).TrimEnd('\','/');$actual=[IO.Path]::GetFullPath((Split-Path $PSScriptRoot -Parent)).TrimEnd('\','/');$comparison=if([OperatingSystem]::IsWindows()){[StringComparison]::OrdinalIgnoreCase}else{[StringComparison]::Ordinal};if(-not$actual.Equals($declared,$comparison)){throw 'UpgradeToolingContext must execute from the new context executor root.'};if(@($Context.executor.closure|Where-Object{[string]$_.path-ceq'scripts/ToolingContextUpgrade.psm1'}).Count-ne1-or[string]$Context.executor.entrypoint-cne'scripts/ToolingContextUpgrade.psm1'){throw 'UpgradeToolingContext new executor closure does not bind its owner module entrypoint.'}
 [void](Assert-MorphospaceToolingContextLoadedOwnerModule -Context $Context -ExecutorRoot $declared -OwnerModule $MyInvocation.MyCommand.Module)
}
function New-ToolingUpgradeAutomationReceipt {
 param([object]$Request,[string]$Timestamp,[string]$OutRelative,[string]$RequestHash,[bool]$Executed,[string]$EventId)
 $result=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.work_unit_automation_receipt.v2';project_id=[string]$Request.project_id;unit_id=[string]$Request.unit_id;action='UpgradeToolingContext';timestamp=$Timestamp;executed=$Executed;transition='tooling-context-upgraded';status_before='active';status_after='active';current_unit_before=[string]$Request.unit_id;current_unit_after=[string]$Request.unit_id;preservation=[pscustomobject][ordered]@{git_mutation_performed=$false;device_mutation_performed=$false;remote_mutation_performed=$false};audit_receipt=[pscustomobject][ordered]@{path=$OutRelative;sha256=$RequestHash};event_id=$(if($Executed){$EventId}else{$null})}
 Test-ToolingUpgradeJson $result 'work-unit-automation-receipt-v2.schema.json' 'Tooling-context upgrade emitted an invalid automation receipt.';$result
}

function Assert-MorphospaceToolingContextUpgradeRecoveryBindings {
 [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][object]$Intent)
 $workspace=[IO.Path]::GetFullPath($WorkspaceRoot);if([string]$Intent.schema-cne'rusty.morphospace.workflow.transition_ledger_intent.v6'){throw 'Tooling-context upgrade recovery requires transition-ledger v6.'}
 $requestArtifact=Get-ToolingUpgradeArtifactDocument $Intent 'rusty.morphospace.workflow.tooling_context_upgrade.v1';$newArtifact=Get-ToolingUpgradeArtifactDocument $Intent 'rusty.morphospace.workflow.tooling_context.v1';$request=$requestArtifact.document;$new=$newArtifact.document
 Test-ToolingUpgradeJson $request 'tooling-context-upgrade-v1.schema.json' 'Tooling-context recovery request violates its owner schema.';$new=Assert-MorphospaceToolingContext $new
 $expectedReceipts=@([string]$request.new_context.path,[string]$requestArtifact.binding.path)|Sort-Object -CaseSensitive
 $artifactPaths=@($Intent.artifacts|ForEach-Object{[string]$_.path});$eventReceipts=@($Intent.event.receipts)
 if(@($Intent.artifacts).Count-ne2-or[string]$requestArtifact.binding.path-cnotmatch'^receipts/.+-tooling-context-upgrade-request\.json$'-or[string]$newArtifact.binding.path-cne[string]$request.new_context.path-or($artifactPaths-join[char]0)-cne($expectedReceipts-join[char]0)-or($eventReceipts-join[char]0)-cne($expectedReceipts-join[char]0)-or[string]$Intent.event.event_type-cne'state-transition'-or[string]$Intent.event.summary-cne'Upgraded the current pre-freeze tooling context while preserving the authenticated product envelope.'){throw 'Tooling-context recovery artifact or event bindings are detached.'};Assert-ToolingUpgradePointer $request.new_context $new $newArtifact.bytes 'new-context'
 if(@($Intent.additional_projections).Count-ne2-or[string]$Intent.additional_projections[0].path-cne'feature.lock.json'-or[string]$Intent.additional_projections[1].path-cne'project.spec.json'){throw 'Tooling-context recovery product fences are absent or reordered.'};foreach($projection in @($Intent.additional_projections)){if([string]$projection.pre_sha256-cne[string]$projection.target_sha256-or(Get-MorphospaceCanonicalJsonSha256 $projection.document)-cne[string]$projection.pre_sha256){throw "Tooling-context recovery product fence '$($projection.path)' changes its projection."}};if([string]$Intent.additional_projections[0].pre_raw_sha256-cne[string]$request.product_projection.feature_lock.sha256){throw 'Tooling-context recovery feature-lock raw fence detaches from the request.'}
 $oldPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$request.old_context.path) -RequireLeaf;$oldBytes=[IO.File]::ReadAllBytes($oldPath);$old=Read-MorphospaceProtocolJson $oldPath;Assert-ToolingUpgradePointer $request.old_context $old $oldBytes 'old-context';$old=Assert-MorphospaceToolingContext $old
 Test-MorphospaceToolingContextCompatibility $old $new $request.product_projection|Out-Null;Assert-ToolingUpgradeCompatibilityReceipt $workspace $request $old $new|Out-Null;Assert-ToolingUpgradeProductProjectionFiles $workspace $request.product_projection
 Assert-MorphospaceToolingContextHistoricalObservation $old $workspace|Out-Null;Assert-MorphospaceToolingContextLocalObservation $new $workspace|Out-Null;Assert-ToolingUpgradeExecutingBoundTool $workspace $new
 $unitPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$Intent.unit.path) -RequireLeaf;$statePath=Resolve-MorphospaceWorkspacePath $workspace ([string]$Intent.state.path) -RequireLeaf;$liveUnit=Read-MorphospaceProtocolJson $unitPath;$liveState=Read-MorphospaceProtocolJson $statePath
 $targetPointer=[pscustomobject][ordered]@{path=[string]$request.new_context.path;sha256=[string]$request.new_context.sha256;canonical_sha256=[string]$request.new_context.canonical_sha256;protocol_id=[string]$request.new_context.protocol_id};if([string]$Intent.transaction_id-cne"$([string]$request.upgrade_id)-tooling-context-upgraded-transition"-or[string]$Intent.event.event_id-cne"$([string]$request.upgrade_id)-tooling-context-upgraded"-or[string]$Intent.event.project_id-cne[string]$request.project_id-or[string]$Intent.event.unit_id-cne[string]$request.unit_id-or[string]$Intent.target.state.document.project_id-cne[string]$request.project_id-or[string]$Intent.target.state.document.current_unit-cne[string]$request.unit_id-or[string]$Intent.target.unit.document.project_id-cne[string]$request.project_id-or[string]$Intent.target.unit.document.unit_id-cne[string]$request.unit_id-or[string]$Intent.target.unit.document.status-cne'active'-or$Intent.target.unit.document.PSObject.Properties.Name-ccontains'candidate_freeze'-or-not(Test-ToolingUpgradeProjectionEqual $Intent.target.unit.document.tooling_context $targetPointer)){throw 'Tooling-context recovery target unit or event identity is detached.'}
 $preUnit=Copy-ToolingUpgradeValue $Intent.target.unit.document;$preUnit.tooling_context=Copy-ToolingUpgradeValue $request.old_context;$preState=Copy-ToolingUpgradeValue $Intent.target.state.document;$preState.last_event_id=[string]$request.expected.event_tail_id
 if((Get-MorphospaceCanonicalJsonSha256 $preUnit)-cne[string]$request.expected.unit_sha256-or(Get-MorphospaceCanonicalJsonSha256 $preState)-cne[string]$request.expected.state_sha256-or(Get-MorphospaceCanonicalJsonSha256 $Intent.target.unit.document)-cne[string]$Intent.target.unit.sha256-or(Get-MorphospaceCanonicalJsonSha256 $Intent.target.state.document)-cne[string]$Intent.target.state.sha256){throw 'Tooling-context recovery projection semantics are detached.'}
 $unitHash=Get-MorphospaceCanonicalJsonSha256 $liveUnit;$stateHash=Get-MorphospaceCanonicalJsonSha256 $liveState;if(@([string]$request.expected.unit_sha256,[string]$Intent.target.unit.sha256)-cnotcontains$unitHash-or@([string]$request.expected.state_sha256,[string]$Intent.target.state.sha256)-cnotcontains$stateHash){throw 'Tooling-context recovery live projection is outside its exact preimage and target.'}
 $expectedUnitRaw=if($unitHash-ceq[string]$request.expected.unit_sha256){[string]$request.expected.unit_raw_sha256}else{Get-MorphospaceSha256Bytes (ConvertTo-MorphospaceProtocolJsonBytes $Intent.target.unit.document)};$expectedStateRaw=if($stateHash-ceq[string]$request.expected.state_sha256){[string]$request.expected.state_raw_sha256}else{Get-MorphospaceSha256Bytes (ConvertTo-MorphospaceProtocolJsonBytes $Intent.target.state.document)}
 if((Get-MorphospaceFileSha256 $unitPath)-cne$expectedUnitRaw-or(Get-MorphospaceFileSha256 $statePath)-cne$expectedStateRaw){throw 'Tooling-context recovery live raw projection is detached.'};$true
}

function Assert-ToolingContextHistoricalTransition {
 [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][object]$ExpectedEvent,[Parameter(Mandatory)][object]$Transition,[object]$ExpectedProductProjection=$null)
 $workspace=[IO.Path]::GetFullPath($WorkspaceRoot);$intent=$Transition.intent;if([string]$intent.schema-cne'rusty.morphospace.workflow.transition_ledger_intent.v6'-or(Get-MorphospaceCanonicalJsonSha256 $intent.event)-cne(Get-MorphospaceCanonicalJsonSha256 $ExpectedEvent)){throw 'Historical tooling-context upgrade transition is detached.'}
 $requestArtifact=Get-ToolingUpgradeArtifactDocument $intent 'rusty.morphospace.workflow.tooling_context_upgrade.v1';$newArtifact=Get-ToolingUpgradeArtifactDocument $intent 'rusty.morphospace.workflow.tooling_context.v1';$request=$requestArtifact.document;$new=Assert-MorphospaceToolingContext $newArtifact.document;Test-ToolingUpgradeJson $request 'tooling-context-upgrade-v1.schema.json' 'Historical tooling-context request is invalid.'
 $expectedReceipts=@([string]$request.new_context.path,[string]$requestArtifact.binding.path)|Sort-Object -CaseSensitive
 $eventReceipts=@($ExpectedEvent.receipts);$artifactPaths=@($intent.artifacts|ForEach-Object{[string]$_.path})
 if(@($intent.artifacts).Count-ne2-or[string]$ExpectedEvent.event_id-cne"$([string]$request.upgrade_id)-tooling-context-upgraded"-or[string]$ExpectedEvent.project_id-cne[string]$request.project_id-or[string]$ExpectedEvent.unit_id-cne[string]$request.unit_id-or[string]$ExpectedEvent.event_type-cne'state-transition'-or[string]$ExpectedEvent.summary-cne'Upgraded the current pre-freeze tooling context while preserving the authenticated product envelope.'-or($eventReceipts-join[char]0)-cne($expectedReceipts-join[char]0)-or($artifactPaths-join[char]0)-cne($expectedReceipts-join[char]0)-or[string]$intent.transaction_id-cne"$([string]$ExpectedEvent.event_id)-transition"){throw 'Historical tooling-context event identity is detached.'}
 $oldPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$request.old_context.path) -RequireLeaf;$oldBytes=[IO.File]::ReadAllBytes($oldPath);$old=Read-MorphospaceProtocolJson $oldPath;Assert-ToolingUpgradePointer $request.old_context $old $oldBytes old-context;Assert-ToolingUpgradePointer $request.new_context $new $newArtifact.bytes new-context;$old=Assert-MorphospaceToolingContext $old
 if($null-ne$ExpectedProductProjection-and(-not(Test-ToolingUpgradeProjectionEqual $request.product_projection $ExpectedProductProjection)-or-not(Test-ToolingUpgradeProjectionEqual $new.product_projection $ExpectedProductProjection))){throw 'Historical tooling-context upgrade product projection detaches from its authenticated continuation input.'}
 $targetPointer=[pscustomobject][ordered]@{path=[string]$request.new_context.path;sha256=[string]$request.new_context.sha256;canonical_sha256=[string]$request.new_context.canonical_sha256;protocol_id=[string]$request.new_context.protocol_id};if([string]$intent.target.state.document.project_id-cne[string]$request.project_id-or[string]$intent.target.state.document.current_unit-cne[string]$request.unit_id-or[string]$intent.target.unit.document.project_id-cne[string]$request.project_id-or[string]$intent.target.unit.document.unit_id-cne[string]$request.unit_id-or[string]$intent.target.unit.document.status-cne'active'-or$intent.target.unit.document.PSObject.Properties.Name-ccontains'candidate_freeze'-or-not(Test-ToolingUpgradeProjectionEqual $intent.target.unit.document.tooling_context $targetPointer)){throw 'Historical tooling-context target unit identity is detached.'}
 Test-MorphospaceToolingContextCompatibility $old $new $request.product_projection|Out-Null;Assert-ToolingUpgradeCompatibilityReceipt $workspace $request $old $new|Out-Null;Assert-MorphospaceToolingContextHistoricalObservation $old $workspace|Out-Null;Assert-MorphospaceToolingContextHistoricalObservation $new $workspace|Out-Null
 if(@($intent.additional_projections).Count-ne2-or[string]$intent.additional_projections[0].path-cne'feature.lock.json'-or[string]$intent.additional_projections[1].path-cne'project.spec.json'){throw 'Historical tooling-context product fences are absent or reordered.'};foreach($projection in @($intent.additional_projections)){if([string]$projection.pre_sha256-cne[string]$projection.target_sha256-or(Get-MorphospaceCanonicalJsonSha256 $projection.document)-cne[string]$projection.pre_sha256){throw "Historical tooling-context product fence '$($projection.path)' changes its projection."}};Test-ToolingUpgradeJson $intent.additional_projections[0].document 'feature-lock-v2.schema.json' 'Historical tooling-context feature-lock fence is invalid.';Test-ToolingUpgradeJson $intent.additional_projections[1].document 'project-spec-v2.schema.json' 'Historical tooling-context project fence is invalid.';if([string]$intent.additional_projections[0].pre_raw_sha256-cne[string]$request.product_projection.feature_lock.sha256){throw 'Historical tooling-context feature-lock raw fence detaches from the request.'}
 $preUnit=Copy-ToolingUpgradeValue $intent.target.unit.document;$preUnit.tooling_context=Copy-ToolingUpgradeValue $request.old_context;$preState=Copy-ToolingUpgradeValue $intent.target.state.document;$preState.last_event_id=[string]$request.expected.event_tail_id
 if((Get-MorphospaceCanonicalJsonSha256 $preUnit)-cne[string]$intent.pre.unit.sha256-or(Get-MorphospaceCanonicalJsonSha256 $preState)-cne[string]$intent.pre.state.sha256-or[string]$intent.pre_unit_raw.sha256-cne[string]$request.expected.unit_raw_sha256-or[string]$intent.pre_state_raw.sha256-cne[string]$request.expected.state_raw_sha256-or[string]$intent.expected.events_sha256-cne[string]$request.expected.events_sha256-or[int64]$intent.expected.events_length-ne[int64]$request.expected.events_length){throw 'Historical tooling-context transition preimage is detached.'};$Transition
}
function Test-MorphospaceHistoricalToolingContextUpgrade {
 [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][object]$ExpectedEvent)
 $proof=Test-MorphospaceCommittedTransitionLedger -WorkspaceRoot $WorkspaceRoot -TransactionId "$([string]$ExpectedEvent.event_id)-transition" -ExpectedStatePath 'workspace.state.json' -ExpectedUnitPath "iteration-units/$([string]$ExpectedEvent.unit_id).json" -ExpectedEventsPath 'iteration-events.jsonl';Assert-ToolingContextHistoricalTransition -WorkspaceRoot $WorkspaceRoot -ExpectedEvent $ExpectedEvent -Transition $proof
}

function Invoke-MorphospaceUpgradeToolingContext {
 [CmdletBinding()]param([Parameter(Mandatory)][string]$WorkspaceRoot,[Parameter(Mandatory)][string]$UnitId,[Parameter(Mandatory)][string]$ToolingContextUpgrade,[Parameter(Mandatory)][string]$OutPath,[string]$ExpectedToolingContextUpgradeSha256='',[string]$Timestamp='',[ValidateSet('none','after-intent','after-artifact','after-projection','after-event')][string]$FaultAfter='none',[switch]$Execute)
 $workspace=[IO.Path]::GetFullPath((Resolve-Path -LiteralPath $WorkspaceRoot -ErrorAction Stop).Path);$input=[IO.Path]::GetFullPath((Resolve-Path -LiteralPath $ToolingContextUpgrade -ErrorAction Stop).Path);$request=Read-MorphospaceProtocolJson $input;Test-ToolingUpgradeJson $request 'tooling-context-upgrade-v1.schema.json' 'Tooling-context upgrade request violates its owner schema.';$requestHash=Get-MorphospaceFileSha256 $input
 if([string]$request.unit_id-cne$UnitId){throw 'Tooling-context upgrade request unit differs from UnitId.'};if($ExpectedToolingContextUpgradeSha256-and$ExpectedToolingContextUpgradeSha256-cne$requestHash){throw 'ExpectedToolingContextUpgradeSha256 differs from the request bytes.'};if($Execute-and-not$ExpectedToolingContextUpgradeSha256){throw 'Executed UpgradeToolingContext requires its reviewed request SHA-256.'}
 $out=[IO.Path]::GetFullPath($OutPath);$prefix=$workspace+[IO.Path]::DirectorySeparatorChar;if(-not$out.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){throw 'Tooling-context upgrade output must stay inside the workspace.'};$outRelative=$out.Substring($prefix.Length).Replace('\','/');$expectedOut="receipts/$([string]$request.upgrade_id)-tooling-context-upgrade-request.json";if($outRelative-cne$expectedOut-or$out-ceq$input){throw "Tooling-context upgrade output must be '$expectedOut'."}
 $eventId="$([string]$request.upgrade_id)-tooling-context-upgraded";$transactionId="$eventId-transition";$intentPath=Resolve-MorphospaceWorkspacePath $workspace "receipts/transactions/$transactionId.intent.json";$completionPath=Resolve-MorphospaceWorkspacePath $workspace "receipts/transactions/$transactionId.completion.json"
 if([IO.File]::Exists($completionPath)-and-not[IO.File]::Exists($intentPath)){throw 'Tooling-context upgrade completion exists without intent.'}
 if([IO.File]::Exists($intentPath)){$intent=Read-MorphospaceProtocolJson $intentPath;Assert-MorphospaceToolingContextUpgradeRecoveryBindings $workspace $intent|Out-Null;$artifact=Get-ToolingUpgradeArtifactDocument $intent 'rusty.morphospace.workflow.tooling_context_upgrade.v1';if((Get-MorphospaceSha256Bytes $artifact.bytes)-cne$requestHash){throw 'Tooling-context upgrade replay request differs from its durable intent.'};$replayTimestamp=[string]$intent.event.timestamp;if([IO.File]::Exists($completionPath)){Test-MorphospaceHistoricalToolingContextUpgrade $workspace $intent.event|Out-Null;return New-ToolingUpgradeAutomationReceipt $request $replayTimestamp $outRelative $requestHash $true $eventId};if(-not$Execute){throw 'Interrupted tooling-context upgrade requires -Execute recovery.'};Complete-MorphospaceTransitionLedger -WorkspaceRoot $workspace -TransactionId $transactionId -Repair -FaultAfter $FaultAfter|Out-Null;Test-MorphospaceHistoricalToolingContextUpgrade $workspace $intent.event|Out-Null;return New-ToolingUpgradeAutomationReceipt $request $replayTimestamp $outRelative $requestHash $true $eventId}
 $statePath=Resolve-MorphospaceWorkspacePath $workspace 'workspace.state.json' -RequireLeaf;$unitRelative="iteration-units/$UnitId.json";$unitPath=Resolve-MorphospaceWorkspacePath $workspace $unitRelative -RequireLeaf;$eventsPath=Resolve-MorphospaceWorkspacePath $workspace 'iteration-events.jsonl' -RequireLeaf;$projectPath=Resolve-MorphospaceWorkspacePath $workspace 'project.spec.json' -RequireLeaf;$featurePath=Resolve-MorphospaceWorkspacePath $workspace 'feature.lock.json' -RequireLeaf
 $state=Read-MorphospaceProtocolJson $statePath;$unit=Read-MorphospaceProtocolJson $unitPath;$project=Read-MorphospaceProtocolJson $projectPath;$feature=Read-MorphospaceProtocolJson $featurePath;$events=@(Get-ToolingUpgradeEvents $eventsPath)
 foreach($pair in @(@($state,'workspace-state-v2.schema.json'),@($unit,'iteration-unit.schema.json'),@($project,'project-spec-v2.schema.json'))){Test-ToolingUpgradeJson $pair[0] $pair[1] 'Tooling-context upgrade live workflow document violates its owner schema.'}
 if([string]$state.project_id-cne[string]$request.project_id-or[string]$state.current_unit-cne$UnitId-or[string]$unit.project_id-cne[string]$request.project_id-or[string]$unit.status-cne'active'-or$unit.PSObject.Properties.Name-contains'candidate_freeze'-or-not($unit.PSObject.Properties.Name-contains'tooling_context')){throw 'UpgradeToolingContext requires the exact current active pre-freeze unit with a tooling context.'}
 $oldPath=Resolve-MorphospaceWorkspacePath $workspace ([string]$request.old_context.path) -RequireLeaf;$oldBytes=[IO.File]::ReadAllBytes($oldPath);$old=Read-MorphospaceProtocolJson $oldPath;Assert-ToolingUpgradePointer $request.old_context $old $oldBytes old-context;$old=Assert-MorphospaceToolingContext $old;if(-not(Test-ToolingUpgradeProjectionEqual $unit.tooling_context $request.old_context)){throw 'Tooling-context upgrade old pointer differs from the current unit.'}
 $newBytes=ConvertTo-MorphospaceProtocolJsonBytes $request.new_context.document;$new=Assert-MorphospaceToolingContext $request.new_context.document;Assert-ToolingUpgradePointer $request.new_context $new $newBytes new-context;Test-MorphospaceToolingContextCompatibility $old $new $request.product_projection|Out-Null;Assert-ToolingUpgradeExecutingBoundTool $workspace $new
 Assert-ToolingUpgradeProductProjectionFiles $workspace $request.product_projection;Assert-ToolingUpgradeEffectiveEnvelope $workspace $UnitId $request $old $new|Out-Null;Assert-ToolingUpgradeCompatibilityReceipt $workspace $request $old $new|Out-Null;Assert-MorphospaceToolingContextHistoricalObservation $old $workspace|Out-Null;Assert-MorphospaceToolingContextLocalObservation $new $workspace|Out-Null
 $tail=$events[-1];foreach($binding in @(@('state canonical',[string]$request.expected.state_sha256,(Get-MorphospaceCanonicalJsonSha256 $state)),@('state raw',[string]$request.expected.state_raw_sha256,(Get-MorphospaceFileSha256 $statePath)),@('unit canonical',[string]$request.expected.unit_sha256,(Get-MorphospaceCanonicalJsonSha256 $unit)),@('unit raw',[string]$request.expected.unit_raw_sha256,(Get-MorphospaceFileSha256 $unitPath)),@('events raw',[string]$request.expected.events_sha256,(Get-MorphospaceFileSha256 $eventsPath)),@('event tail',[string]$request.expected.event_tail_id,[string]$tail.event_id))){if([string]$binding[1]-cne[string]$binding[2]){throw "Tooling-context upgrade expected $($binding[0]) is stale."}};if([int64]$request.expected.events_length-ne[IO.FileInfo]::new($eventsPath).Length-or[string]$state.last_event_id-cne[string]$tail.event_id){throw 'Tooling-context upgrade event prefix is stale.'}
 $newTarget=Resolve-MorphospaceWorkspacePath $workspace ([string]$request.new_context.path);if([IO.File]::Exists($newTarget)-or[IO.Directory]::Exists($newTarget)-or[IO.File]::Exists($out)-or[IO.Directory]::Exists($out)){throw 'Tooling-context upgrade immutable output is already occupied.'}
 if(-not$Timestamp){$Timestamp=[DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffffffZ')};if(-not(Test-MorphospaceStrictUtcTimestamp $Timestamp)){throw 'Timestamp must be strict UTC.'}
 $targetUnit=Copy-ToolingUpgradeValue $unit;$targetUnit.tooling_context=[pscustomobject][ordered]@{path=[string]$request.new_context.path;sha256=[string]$request.new_context.sha256;canonical_sha256=[string]$request.new_context.canonical_sha256;protocol_id=[string]$request.new_context.protocol_id};$targetState=Copy-ToolingUpgradeValue $state;$targetState.last_event_id=$eventId;$artifactPaths=@([string]$request.new_context.path,$outRelative)|Sort-Object -CaseSensitive
 $event=[pscustomobject][ordered]@{schema='rusty.morphospace.workflow.iteration_event.v1';event_id=$eventId;sequence=[int]$tail.sequence+1;timestamp=$Timestamp;project_id=[string]$request.project_id;unit_id=$UnitId;event_type='state-transition';summary='Upgraded the current pre-freeze tooling context while preserving the authenticated product envelope.';receipts=@($artifactPaths)};Test-ToolingUpgradeJson $targetUnit 'iteration-unit.schema.json' 'Tooling-context upgrade target unit violates its owner schema.';Test-ToolingUpgradeJson $event 'iteration-event.schema.json' 'Tooling-context upgrade event violates its owner schema.'
 if($Execute){Assert-ToolingUpgradeProductProjectionFiles $workspace $request.product_projection;Assert-MorphospaceToolingContextLocalObservation $new $workspace|Out-Null;$artifacts=@();foreach($path in $artifactPaths){if($path-ceq$outRelative){$artifacts+=,[pscustomobject]@{source_path=$input;path=$path;sha256=$requestHash}}else{$artifacts+=,[pscustomobject]@{bytes_base64=[Convert]::ToBase64String($newBytes);path=$path;sha256=[string]$request.new_context.sha256}}};$projections=@([pscustomobject]@{path='feature.lock.json';expected_sha256=Get-MorphospaceCanonicalJsonSha256 $feature;expected_raw_sha256=Get-MorphospaceFileSha256 $featurePath;document=$feature},[pscustomobject]@{path='project.spec.json';expected_sha256=Get-MorphospaceCanonicalJsonSha256 $project;expected_raw_sha256=Get-MorphospaceFileSha256 $projectPath;document=$project});Start-MorphospaceTransitionLedger -WorkspaceRoot $workspace -TransactionId $transactionId -StatePath 'workspace.state.json' -UnitPath $unitRelative -EventsPath 'iteration-events.jsonl' -TargetState $targetState -TargetUnit $targetUnit -Event $event -ExpectedPreStateSha256 ([string]$request.expected.state_sha256) -ExpectedPreStateRawSha256 ([string]$request.expected.state_raw_sha256) -ExpectedPreUnitSha256 ([string]$request.expected.unit_sha256) -ExpectedPreUnitRawSha256 ([string]$request.expected.unit_raw_sha256) -ExpectedEventTailId ([string]$request.expected.event_tail_id) -ExpectedEventsSha256 ([string]$request.expected.events_sha256) -ExpectedEventsLength ([int64]$request.expected.events_length) -AdditionalProjections $projections -Artifacts $artifacts -FaultAfter $FaultAfter|Out-Null}
 New-ToolingUpgradeAutomationReceipt $request $Timestamp $outRelative $requestHash $Execute.IsPresent $eventId
}

Export-ModuleMember -Function Invoke-MorphospaceUpgradeToolingContext,Assert-MorphospaceToolingContextUpgradeRecoveryBindings,Test-MorphospaceHistoricalToolingContextUpgrade
